### ISSUE TITLE
DeploymentItem should be implemented via Fx extensibility

### ISSUE THREAD

**Issue by AbhitejJohn** [microsoft/testfx#100]
## Description
Deployment Item currently is hard-coded into the adapter's core platform service leading to a bunch of dependency issues with discovery in projects targeting UWP. This should truly be separated out as a separate module so that:
1. Deployment as a pillar is extensible to anyone wanting to have their own custom deployment.
2. The design as such is clean, since this is specific only to certain platforms.

**Comment by Evangelink** [comment]
I will close this issue because it's not really clear what we want to do and also I believe this deployment functionality should be removed as it can be provided by msbuild or initialize methods.
