### ISSUE TITLE
Additional Nullable Reference Type-aware support

### ISSUE THREAD

**Issue by dferretti** [microsoft/testfx#1004]
## Description
Following https://github.com/microsoft/testfx/issues/714
and borrowing from https://devblogs.microsoft.com/dotnet/try-out-nullable-reference-types/#flow-attributes-doesnotreturn-and-doesnotreturnifbool
Can `DoesNotReturnIf` be added to `Assert.IsTrue` / `Assert.IsFalse` ? And `DoesNotReturn` be added to `Assert.Fail()` ? There are some other null checks should be able to be skipped, such as:

## Steps to reproduce
```c#
Dictionary<string, string> dictionary = ...
Assert.IsTrue(dictionary.TryGetValue(key, out var value));
Assert.AreEqual(5, value.Length); // should know that value is not null, but still warns currently
```
similarly:
```c#
Dictionary<string, string> dictionary = ...
var found = dictionary.TryGetValue(key, out var value);
if (!found) Assert.Fail();
Assert.AreEqual(5, value.Length); // should know that value is not null, but still warns currently
```

## Expected behavior
No compiler warnings.

## Actual behavior
Compiler warnings issued on `value.Length`.

## Environment
Using version `2.2.7` of MSTest.TestAdapater and MSTest.TestFramework

## Workaround

Similar shims can be written such as
```c#
[DoesNotReturn]
public static void AssertFail() => Assert.Fail();

public static void AssertIsTrue([DoesNotReturnIf(false)] bool condition) => Assert.IsTrue(condition);

public static void AssertIsFalse([DoesNotReturnIf(true)] bool condition) => Assert.IsFalse(condition);
```

**Comment by dferretti** [comment]
The work is already done to add the conditionally included compiler attributes in `NullableAttributes.cs`, so there shouldn't be too much to add here. So if this looks like an acceptable proposal I can put in a PR for it!

**Comment by Haplois** [comment]
Thank you @dferretti for the proposal, it looks good. Please go ahead and create the PR if you wish.
