### ISSUE TITLE
Value of Internal properties gets overridden by default when using ITestDataSource and Attribute

### ISSUE THREAD

**Issue by Hejle** [microsoft/testfx#1010]
## Description
When using a attribute implementing ITestDataSource the value of internals members is always default when passed to the unittest. This makes it impossible to test internal properties and members using ITestDataSource and Attributes.

As far as I can see, the problem is that MsTest serialises the data to text using DataContractJsonSerializer, which doesn't serialize Internal Properties.
https://github.com/microsoft/testfx/blob/e977b82f30a4ae9ca800398691b6643a4f94d7a2/src/Adapter/MSTest.CoreAdapter/Helpers/DataSerializationHelper.cs#L28

## Steps to reproduce
Example project with the unexpected behaviour
https://github.com/Hejle/InternalUnittestTest
* Create a class with an internal property
* Add [assembly: InternalsVisibleTo(<Your Testproject>)]
* Add a DataTestMethod which gets its inputdata from a Custom Attribute implementing ITestDataSource.
* Assign value to internal property in ITestDataSourceAttribute
* Assert value of internal property in DataTestMethod

## Expected behavior
Value of internal property is equal to the value assigned in the ITestDataSource attribute

## Actual behavior
Value of internal property is equal to default

## Environment
> Please share additional details about the test environment.
- Operating system: Windows 10
- Package version of MSTest framework and adapter: 2.2.7

**Comment by Haplois** [comment]
This behavior is by-design, there are two workarounds:

   1. You can opt-out of this behavior as described [here](https://github.com/microsoft/testfx/issues/905#issuecomment-907775327).
   2. You can use [System.Runtime.Serialization.ISerializable](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.serialization.iserializable) interface to facilitate serialization of internal members.
