### ISSUE TITLE
Data driven tests are incompatible with Azure Test Plans after moving to MSTest.TestAdapter 2.2.4+

### ISSUE THREAD

**Issue by TroyWalshProf** [microsoft/testfx#1023]
## Description
MSTest.TestAdapter 2.2.4 (and above) break the [Visual Studio Test](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/vstest?view=azure-devops) task integration when it comes to data driven tests  

## Steps to reproduce
1. Open or create a Azure DevOps project
2. Create a test case work item 
![image](https://user-images.githubusercontent.com/2066107/145886114-05d770f6-9e6e-461f-b75b-2f2e236f2a56.png)
3. Create a new MSTest based test project, make sure you are referencing MSTest.TestAdapter version 2.2.3
4. Create a data driven test 
![image](https://user-images.githubusercontent.com/2066107/145886692-dd8b444c-1752-4396-a8f3-a441803486bd.png)
5. Associate the the data driven test with a test case 
![image](https://user-images.githubusercontent.com/2066107/145887063-707e845c-438d-45e2-921e-d5394b9c6483.png)
6. Create a test plan and add the test case
![image](https://user-images.githubusercontent.com/2066107/145887250-7039c098-3207-4f7b-9b29-252f467ef087.png)
7. Create a pipeline to build and run the test
8. Add  the [Visual Studio Testing Task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/vstest?view=azure-devops) to the pipeline.  Use the testPlan testSelector link up the test plan, test suite, end test configuration from step 6.
9. Run the pipeline and note that the tests results appear in your build and test plan
![image](https://user-images.githubusercontent.com/2066107/145888236-b7e18ff7-8736-4d32-9a63-e3b935220e24.png)
![image](https://user-images.githubusercontent.com/2066107/145888614-1df5a441-9f3c-4174-b39c-595d7ccfe0cb.png)
10. Go back into your test code and upgrade MSTest.TestAdapter to 2.2.8, check in the change and try rerunning the tests
11. **Note*** The tests look like they run correctly, but on the first iteration of the data driven test is executed
![image](https://user-images.githubusercontent.com/2066107/145898041-dd3afbba-a1e8-4972-8077-f0738d3b420b.png)
![image](https://user-images.githubusercontent.com/2066107/145901427-3a4679c1-a35a-4a6e-8662-4a45a63411f8.png)
12. Got back into your test code and add "[assembly: TestDataSourceDiscovery(TestDataSourceDiscoveryOption.DuringExecution)]" just below the using statements in your test class file.
![image](https://user-images.githubusercontent.com/2066107/145889546-226c8d3f-bd19-410d-81ab-165a3bd47e7f.png)
13. **Note*** The build now shows the data driven test as other and Azure Test plans show the tests as In Progress.
![image](https://user-images.githubusercontent.com/2066107/145889748-9a2d1799-0dbf-42b2-abcd-30791b06c795.png) 
![image](https://user-images.githubusercontent.com/2066107/145889793-34f64c6a-55bc-4232-a073-d2b10c4d32b0.png)

## Expected behavior
Data driven tests would work with Azure Test Plans

## Actual behavior
If you don't use [assembly: TestDataSourceDiscovery(TestDataSourceDiscoveryOption.DuringExecution)] the data driven tests are not run.
If you use [assembly: TestDataSourceDiscovery(TestDataSourceDiscoveryOption.DuringExecution)] only the first iteration of the data driven tests is run.

## Environment
Azure DevOps
MSTest.TestAdapter 2.2.4 and above
Sample project and code: https://dev.azure.com/MagenicOpen/

**Comment by TroyWalshProf** [comment]
@nohwnd  - Any idea if this is something that will get fixed?

**Comment by TroyWalshProf** [comment]
@Haplois - do you know if this is issue is on the teams radar?

**Comment by TroyWalshProf** [comment]
@AbhitejJohn
@jayaranigarg
 - Any idea if this is something that will get fixed?

**Comment by Evangelink** [comment]
Hi @TroyWalshProf. I will move forward by closing this issue as it overlaps with #1026 and there are more discussions on the other ticket. Please comment on the other ticket.
