### ISSUE TITLE
Unable to load native dll after migrating to MSTest V2

### ISSUE THREAD

**Issue by Tohnmeister** [microsoft/testfx#1027]
## Description

We're migrating all our test projects from MSTest V1 to MSTest V2. Some of our tested projects depend on native dlls. In the past we could just add a an ItemGroup as below to the test project:

```
<ItemGroup>
  <None Include="some_path\some_native.dll">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </None>
</ItemGroup>
```

But after we'move moved to MSTest V2, we're getting the following error while running tests.

```
System.DllNotFoundException: Unable to load DLL 'some_native.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
```

Adding a `DeploymentItem` attribute above the test class or test method has no effect.

## Steps to reproduce

1. Create a C# project that depends on a native dll
2. Create a SDK-style test project that tests the code in the C# project that depends on the native dll
3. Run the test
3. Note that you'll get a DllNotFoundException
4. Add an ItemGroup as stated above
5. Run the test
5. Note that you'll still get a DllNotFoundException
6. Add a DeploymentItem attribute above the test class that deploys the native dll
7. Run the test
7. Note that you'll still get a DllNotFoundException

## Expected behavior

V2 MSTest tests should still be capable of testing managed code that depends on native code.

## Actual behavior

See reproduction steps.

## Environment

Windows 10 x64
.NET Framework 4.8
```xml
<PackageReference Update="Microsoft.NET.Test.Sdk"                                   Version="17.0.0" />
<PackageReference Update="MSTest.TestFramework"                                     Version="2.2.8" />
<PackageReference Update="MSTest.TestAdapter"                                       Version="2.2.8" />
```

**Comment by Evangelink** [comment]
Hi @Tohnmeister, sorry for the huge delay in looking into this issue. Could you please upload some repro because I am not sure if I have the right setup or not and I cannot reproduce the issue. I expect it's a problem of configuration on my side.
