### ISSUE TITLE
Provide an easy way to see the public version of MSTest

### ISSUE THREAD

**Issue by nohwnd** [microsoft/testfx#1051]
MSTest dlls do not contain the version under which it is published, which makes it really hard to see what is being used. Here I am using 2.2.9-preview-20220210-07.  I would like to be able to easily see the version in ilspy, and hopefully in file properties as well: 

![image](https://user-images.githubusercontent.com/5735905/157821294-773faa64-45e7-498c-afcf-004cb41628e1.png)

![image](https://user-images.githubusercontent.com/5735905/157821228-d20cf529-22c1-4506-ae07-b06e4f622365.png)

Ideally this would also be accompanied by docs page that lists versions from all the available nugets on nuget.org and their publish version, **until we started embedding that data**. I can help automating that if you'd like.

**Comment by Haplois** [comment]
I think we started including branch name and commit id in assemblies. Let me verify.

**Comment by Haplois** [comment]
Binaries in the latest preview now contain commit hash as assembly metadata. 

![image](https://user-images.githubusercontent.com/433724/184221321-b635e2b7-b253-4e10-8760-1f7feb783c07.png)

**Comment by nohwnd** [comment]
Please add the public version, I don’t want to be hunting commit ids to know what version the dll is.

**Comment by nohwnd** [comment]
@Evangelink thanks!
