### ISSUE TITLE
When data source provides no data, it is impossible to see why tests does not run

### ISSUE THREAD

**Issue by nohwnd** [microsoft/testfx#1052]
## Description
When data source provides no data it is very hard to understand why test does not run. There is no warning that can be easily seen. And debugger breakpoint in the data source class is not hit (because it only attaches in run). 

## Steps to reproduce
```cs
using FluentAssertions;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;

namespace mstest44
{
    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        [MyDataSource(1)]

        public void TestMethod1(int i)
        {
            
        }

        [TestMethod]
        [MyDataSource(0)]

        public void TestMethod2(int i)
        {

        }
    }

    public class MyDataSource : Attribute, ITestDataSource
    {
        private readonly int _count;

        public MyDataSource(int count)
        {
            _count = count;
        }

        public IEnumerable<object[]> GetData(MethodInfo methodInfo)
        {
            var items = new List<object[]>();
            foreach (var i in Enumerable.Range(100, _count))
            {
                items.Add(new object[] { i });
            }

            return items;
        }

        public string GetDisplayName(MethodInfo methodInfo, object[] data)
        {
            return null;
        }
    }
}
```

## Expected behavior
I expect to see some warning, but have the ability to force not generating any data. Probably as an additional property on the data source interface?

## Actual behavior

One of my data sources are is not running any tests, because I did not add the data to the collection, and the test stays blue in TE, and I can't figure it out. 

![image](https://user-images.githubusercontent.com/5735905/158191323-47d296c2-acfe-4131-b758-6c8f07d2ec5c.png)

## Environment
Latest TP, with latest mstest.

AB#2051847

**Comment by Grauenwolf** [comment]
Has there been any progress in this? I ask because I have data-driven tests that used to work, but now fail and I don't see way to debug them.

**Comment by Evangelink** [comment]
There is some inconsistency in this API. 

When using `DynamicData`, providing an empty result is today considered as an error and there is a suggestion in #1748 to make it a warning via configuation.

To test it, we can add the following to code provided by @nohwnd

```cs
[TestMethod]
[DynamicData(nameof(GetData), DynamicDataSourceType.Method)]
public void TestMethod3(int i)
{
}

public static IEnumerable<object[]> GetData() => new MyDataSource(0).GetData(null!)
```

This thread shows that with custom data source, the default behavior is that nothing happens (no warning nor error). I think we should reconciliate both behavior toward the same. By default, we would have an empty source considered as an inconclusive and we would have some option to make it error.

**Comment by nohwnd** [comment]
> By default, we would have an empty source considered as an inconclusive and we would have some option to make it error.

The other way around please. Error by default, and warning by option.

**Comment by Evangelink** [comment]
I was thinking that the other way around would allow to not have breaking change as the warning is not causing test failure. But safest might be to wait v4 and have error by defaul.t

**Comment by fhnaseer** [comment]
Latest VS does not show node if no data is available. 

![image](https://github.com/microsoft/testfx/assets/1503766/0f064591-4ae5-4a6f-b26d-26e25e5fb472)
![image](https://github.com/microsoft/testfx/assets/1503766/802f2541-49ec-4fa7-a5cd-c4c0181a5c77)

@nohwnd @Evangelink Is there any change at MSTest side and it does not send data to VS? Or VS hides node by itself?
