### ISSUE TITLE
DynamicData is not working properly when classes have empty constructor and private setters. version 2.2.6 onwards

### ISSUE THREAD

**Issue by eliranShema** [microsoft/testfx#1058]
## Description
When you use dynamic data of a class with an empty constructor and a private setter, the value is of the property is reset to default value (null,0,mindate,etc)

## Steps to reproduce
Create a class with an empty constructor and a private setter property, and use it in dynamic data:
```       
        public static IEnumerable<object[]> TestCasesClass2()
        {           
                 yield return new object[] { new Class2("1", 1, new DateTime(1, 1, 1)) }; 
        }

        [DynamicData(nameof(TestCasesClass2), typeof(DynamicDataTest), DynamicDataSourceType.Method)]
        [DataTestMethod]
        public void TestDynamicDataClass2(Class2 item)
        {
            Assert.AreEqual(new DateTime(1, 1, 1), item.Date);
            Assert.AreEqual(1, item.Num);
            Assert.AreEqual("1", item.Str); // **this line fails because Class2.Str has a private setter and an empty constructor**
        }
```

## Expected behavior
it should work as it does in version 2.2.5 and lower - values should be as they were created in the testCaseMethod

## Actual behavior
values are reset to default value (null,0,mindatetime,etc)

## Environment
**Tests code is exactly the same except for the version of the nugets**

![image](https://user-images.githubusercontent.com/38204708/160593873-ab21af5a-c64a-4d38-a14b-c145e3e29720.png)
repo with sample code can be seen at: 
https://github.com/eliranShema/mstestDynamicDataIssue

**Comment by Haplois** [comment]
Hi,

This is expected since since the data you provide must be serializable. You can opt-out of this behavior as described https://github.com/microsoft/testfx/issues/905#issuecomment-907775327 by adding following to your solution:

```csharp
[assembly: TestDataSourceDiscovery(TestDataSourceDiscoveryOption.DuringExecution)]
```
