### ISSUE TITLE
Code coverage should respect assembly level ExcludeFromCodeCoverage attribute

### ISSUE THREAD

**Issue by devlie** [microsoft/testfx#1060]
## Description
We would like to exclude our test binaries from code coverage, and the only options we have today are either decorating each and every class with `[ExcludeFromCodeCoverage]` or have crazy regexes in our `runsettings.json`. `testfx` should respect **assembly level** `ExcludeFromCodeCoverage` instead. This is related to https://github.com/microsoft/vstest/issues/1050.

## Steps to reproduce
1. Create a simple Hello World project.
2. Create a unit test project that calls Hello World and specify this in csproj:

```xml
  <ItemGroup>
        <AssemblyAttribute Include="System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute" />
    </ItemGroup>
```
3. Run unit test with code coverage enabled.

## Expected behavior
The test binary is **not** included in coverage results.

## Actual behavior
The test binary is included in coverage results.

## Environment
>  - OS: Windows 11
>  - Build version of vstest.console: VS2022.
>  - Package version of MSTest framework and adapter: 2.2.3

**Comment by abatishchev** [comment]
+1, please.

**Comment by gioce90** [comment]
+1

**Comment by Evangelink** [comment]
Thank you for reporting this incorrect behavior!

I will close this issue and reopen the one on vstest (this needs to be handled on vstest side).
