### ISSUE TITLE
Data disappears when using DynamicData.

### ISSUE THREAD

**Issue by guyemup** [microsoft/testfx#1075]
## Description
Data disappears when using DynamicData.

## Steps to reproduce
Using the included code, put a breakpoint on both Assert statements and debug HasExpectedItems1(). You may also debug HasExpectedItems2() for comparative purposes.

## Expected behavior
Both tests should run 3 times given the following values for the method argument in each:

HasExpectedItems1() should produce:
null
empty List
List with 3 items

HasExpectedItems2() should produce:
0
1
2

## Actual behavior
HasExpectedItems1() only runs 2 times and is skipping the empty List as an argument. HasExpectedItems2() runs correctly and is here only to show all 3 items are certainly there.

HasExpectedItems1() produces:
null
List with 3 items

HasExpectedItems2() produces:
0
1
2

## Environment
Using MSTest 2.2.9, VS2022, multitargeting 4.5 - .net 6. 

Code sample to reproduce:

`
    using System.Collections.Generic;
    using System.Diagnostics.CodeAnalysis;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    #if NET45_OR_GREATER
    using System.Web.Mvc;
    #elif NETCOREAPP3_0_OR_GREATER
    using Microsoft.AspNetCore.Mvc.Rendering;
    #endif

    [TestClass]
    [ExcludeFromCodeCoverage]
    public class StaticTestingUnitTests
    {
        protected static readonly IEnumerable<SelectListItem>[] DumbItems = new IEnumerable<SelectListItem>[]
        {
            null,
            new List<SelectListItem>(),
            new List<SelectListItem>
            {
                new SelectListItem { Text = "One", Value = "1" },
                new SelectListItem { Text = "Two", Value = "2" },
                new SelectListItem { Text = "Three", Value = "3" },
            },
        };

        protected static IEnumerable<object[]> GetDumbTest1()
        {
            foreach (object item in DumbItems)
            {
                yield return new object[] { item };
            }
        }

        protected static IEnumerable<object[]> GetDumbTest2()
        {
            for (int i = 0; i < DumbItems.Length; i++)
            {
                yield return new object[] { i };
            }
        }

        [DataTestMethod]
        [DynamicData(nameof(GetDumbTest1), DynamicDataSourceType.Method)]
        public void HasExpectedItems1(IEnumerable<SelectListItem> items)
        {
            Assert.AreEqual(5, 5);
        }

        [DataTestMethod]
        [DynamicData(nameof(GetDumbTest2), DynamicDataSourceType.Method)]
        public void HasExpectedItems2(int index)
        {
            Assert.AreEqual(5, 5);
        }
    }
`

**Comment by SnarkOrBoojum2** [comment]
It is the same bug as I described. (roots are the same). Class SelectListItem must have attribute [Serializable] for you to see the results. This all because of serialization the parameters from DynamicData into json.

**Comment by Haplois** [comment]
Hi,

This is expected since we differentiate between tests using their fully-qualifed member and display names. You data source creates to indistinguishable items, so one is ignored. To avoid this behavior, you need to make sure that data you provide ends up with different `ToString` result.

You can opt-out of this behavior as described [here](https://github.com/microsoft/testfx/issues/905#issuecomment-907775327) by adding following to your solution:

```csharp
[assembly: TestDataSourceDiscovery(TestDataSourceDiscoveryOption.DuringExecution)]
```
