### ISSUE TITLE
ClassCleanup declared on a base type not correctly triggered

### ISSUE THREAD

**Issue by 3s-ap** [microsoft/testfx#1093]
## Description

When the ClassCleanup attribute is declared on a base type with ClassCleanupBehavior.EndOfClass, it still triggered at end of assembly.

## Steps to reproduce

Run this code:

```
[TestClass]
public class TestClassBase
{
	[ClassInitialize(InheritanceBehavior.BeforeEachDerivedClass)]
	public static void BeforeClsBase(TestContext testContext)
	{
		Log.Message("ClassInitialize - TestClassBase");
	}

	[ClassCleanup(InheritanceBehavior.BeforeEachDerivedClass, ClassCleanupBehavior.EndOfClass)]
	public static void AfterClsBase()
	{
		Log.Message("ClassCleanup - TestClassBase");
	}
}

[TestClass]
public class TestClassDerivedA : TestClassBase
{
	[TestMethod]
	public void TestMethod()
	{
		Log.Message("Test Method A");
	}
}

[TestClass]
public class TestClassDerivedB : TestClassBase
{
	[TestMethod]
	public void TestMethod()
	{
		Log.Message("Test Method B");
	}
}
```

## Expected behavior
ClassCleanup is triggered at the end of class, according to 'ClassCleanupBehavior.EndOfClass'

## Actual behavior
Log output:

```
ClassInitialize - TestClassBase
Test Method A
ClassInitialize - TestClassBase
Test Method B
ClassCleanup - TestClassBase
ClassCleanup - TestClassBase
```

## Environment
VS 2019
MSTest.TestAdapter: 2.2.10
MSTest.TestFramework: 2.2.10

[AB#1677601](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1677601)

**Comment by Evangelink** [comment]
Hi @3s-ap! Thank you for reporting this issue! I have managed to reproduce the behavior.

**Comment by Evangelink** [comment]
@engyebrahim This issue is somehow related to the various fixes you are doing on init and cleanup methods. Could you please investigate it after you are done with your refactoring?

**Comment by engyebrahim** [comment]
Hi @3s-ap! I tried to reproduce the issue using V2.2.10 using testContext and console.write
but the messages' order was different than the ones you had.

using testcontext the cleanuplogs don't appear.
using console.write the cleanup appear at the beginning.

so please can you upload the whole repo to use the log.message() you used in my investigation, or you try to use one of the ways I used?

**Comment by Evangelink** [comment]
@3s-ap v3.0.1 is now released, feel free to give it a go and get back to us if you find anything wrong.
