### ISSUE TITLE
MSTest 2.2.4 - 2.2.10: `DataRowAttribute` does not preserve the sign of `-0.0`

### ISSUE THREAD

**Issue by notcake** [microsoft/testfx#1096]
## Description
Usage of `DataRowAttribute` does not preserve the sign of doubles when they are zero.

## Steps to reproduce
The following passes on 2.2.3 and fails on 2.2.4 to 2.2.10:

```cs
        [DataTestMethod]
        [DataRow(0.0, "0")]
        [DataRow(-0.0, "-0")]
        public void TestFloat(double value, string expectedString)
        {
            Assert.AreEqual(expectedString, value.ToString());
        }
```

## Expected behavior
The negative sign of the double is preserved.

## Actual behavior
The negative sign is lost.

## Environment
- Windows 10 21H2
- Visual Studio 2022
- MSTest 2.2.10

**Comment by Haplois** [comment]
MSTest discovers data source tests during discovery phase, and stores the discovered data serialized. In this case during serialization sign data is lost, you can opt-out of this behaviour by adding following to your test assembly.

```csharp
[assembly: TestDataSourceDiscovery(TestDataSourceDiscoveryOption.DuringExecution)]
```
