### ISSUE TITLE
DeploymentDirectory is 'Out' folder using .NET Framework, but build folder using .NET 6

### ISSUE THREAD

**Issue by craigbrown** [microsoft/testfx#1097]
## Description
When running a unit test with MSTest under .NET Framework, the `TestContext.DeploymentDirectory` path is the 'Out' folder inside the test run directory, e.g:
```
C:\Repositories\MySolution\TestResults\Deploy_User yyyy-MM-dd HH_mm_ss\Out
```
When running the same test under .NET 6, the `TestContext.DeploymentDirectory` path is the build directory, e.g:
```
C:\Repositories\MySolution\MyUnitTestProject\bin\Debug\net6.0
```
I've looked around but this change in behavior between Framework & Core doesn't seem to be documented anywhere. In fact, [the documentation for the DeploymentDirectory property](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.testtools.unittesting.testcontext.deploymentdirectory?view=visualstudiosdk-2022) says it's "typically a subdirectory of TestRunDirectory" - which isn't the case under .NET 6.

I've looked at existing issues; #653 seems similar at first but I think that's actually related to `DeploymentItem` rather than `DeploymentDirectory` despite the title - whereas the issue I'm describing is present whether or not `DeploymentItem` is used.

Is this a bug or intended behavior?

The reason I'm asking is that I have existing tests which are dependent on this directory being isolated for each run.

## Steps to reproduce
Create a new unit test project in .NET 6. Add the following unit test and run it.
```csharp
[TestMethod]
public void TestDeploymentDirectory()
{
    Assert.IsTrue(TestContext.DeploymentDirectory.StartsWith(TestContext.TestRunDirectory));
}
```

## Expected behavior
The test passes, since the `DeploymentDirectory` is inside the `TestRunDirectory`. This is the current behavior if you change the target framework to `net480`.

## Actual behavior
The test fails.

## Environment
Windows 10, Visual Studio 2022 v17.1.1
MSTest.TestAdapter v2.2.7
MSTest.TestFramework v2.2.7
Microsoft.NET.Test.Sdk 16.11.0
coverlet.collector 3.1.0

**Comment by persn** [comment]
> Is this a bug or intended behavior?

Does anyone know this? It seems like it should be a simple question to answer.

**Comment by craigbrown** [comment]
Hi @Evangelink sorry to tag you in this but not sure how else I can get a response! I'm not sure if my issue was missed.

**Comment by Evangelink** [comment]
Hey @craigbrown, no worries for the direct ping. I saw this issue but couldn't look into it yet. It seems that there are a bunch of related issues for `DeploymentDirectory`. Looking quickly at the code, it seems that we expect some parts to be set by the Test Platform. There is not much information, design or test that would help me with having the right behavior for this.

I will look more deeply into this during the week and I will keep you posted.

Do you know if it ever worked properly with MSTest v2?

**Comment by craigbrown** [comment]
@Evangelink thank you! I haven't checked previous versions but I don't remember it ever working the same way between .NET Framework and Core.

**Comment by Evangelink** [comment]
Yep it's broken since the start and wasn't available for MSTest v1. PR adding the implementation is #565. This looks like this in new code: https://github.com/microsoft/testfx/blob/main/src/Adapter/MSTestAdapter.PlatformServices/Deployment/TestRunDirectories.cs#L63-L73

I don't see any good design or argument motivating this change of directory. I will try to update this and see what's the impact, if it's minimal, I will ship it in v3 otherwise I will have to postpone to v4.

**Comment by Evangelink** [comment]
@craigbrown Thanks for the ping, fix will be part of the MSTest v3 release :)

**Comment by craigbrown** [comment]
@Evangelink awesome, thanks!
