### ISSUE TITLE
Can we implement CustomTestMethod(TestCategory,TestName,TestID) like that 

### ISSUE THREAD

**Issue by vigneshbabuv** [microsoft/testfx#1101]
Need info , 
Can we create the custom Test method as CustomTestMethod(Category,TestName,TestID) like that . Pls help me . If it is possible

**Comment by Evangelink** [comment]
Hi @vigneshbabuv! Sorry for the late answer, could you give us a little more details about your request?

**Comment by Evangelink** [comment]
I will move forward by closing this issue. Please feel free to ping back here or to open a new issue.
