### ISSUE TITLE
tests fail to run after updating to v 2.2.10

### ISSUE THREAD

**Issue by krb-vci** [microsoft/testfx#1134]
Description

I currently run unit tests using MSTest.TestFramework v 2.2.8.

I also used MSTest.TestAdapter which I've upgraded from 2.2.8 to 2.2.10, and
Microsoft.NET.Test.Sdk which i've upgraded from 17.0.0 to 17.2.0.

Everything runs fine. But when i tried upgrading MSTest.TestFramework v 2.2.8 to 2.2.10, the tests would not run.  They are discovered, but don't run.

I work in VS 2022 on a windows 10 machine.

Is this a bug in the package, or is there a command required by the new version?

**Comment by Evangelink** [comment]
Hi @krb-vci, could you share some repro or some verbose logs? Sadly, there isn't much we are able to do with the information you are providing.

**Comment by krb-vci** [comment]
Hi @Evangelink - Do you mean verbose build logs?  (I am still a newbie - still learning VS - and could use some guidance of what to send you.

**Comment by krb-vci** [comment]
A little more info...
After updating the MSTest.TestFramework package to 2.2.10 I tried to debug a test, with a breakpoint at the first line of the assembly init.  The breakpoint was never reached.  The Test output log shows this:

Building Test Projects
========== Starting test run ==========
========== Test run finished: 0 Tests (0 Passed, 0 Failed, 0 Skipped) run in < 1 ms ==========

When i try to Run the test I get the same test output.

**Comment by krb-vci** [comment]
As stated already - I am still learning Visual Studio. I did verbose Test output, and am providing 2 files of the logs.  One is before the update, and the other is after.  Again - before the update the tests rtun.  After the update they don't even get to the first line of the Assembly Init.  And again I redacted some of the proprietary references that won't matter to you
[TestOutputAfterUpgrade.txt](https://github.com/microsoft/testfx/files/9067728/TestOutputAfterUpgrade.txt)
[TestOutputBeforeUpgrade.txt](https://github.com/microsoft/testfx/files/9067729/TestOutputBeforeUpgrade.txt)
.

**Comment by Evangelink** [comment]
@krb-vci  I will investigate today.

**Comment by Evangelink** [comment]
@krb-vci I will need the diagnostic logs (there is nothing relevant in the simple logs you have sent). Please follow this guide https://github.com/microsoft/vstest-docs/blob/main/docs/troubleshooting.md#visual-studio

**Comment by krb-vci** [comment]
Have been away from my desk all day.  Will do this tomorrow morning California time.

Can I send the zip file directly, without posting the world?

Thanks,

Ken Blaker
***@***.******@***.***> or ***@***.***

**Comment by krb-vci** [comment]
I was too curious to wait until tomorrow.  I’ve attached 2 zip files.  One is three files generated before upgrading to the latest version.  The after zip only has 2 files generated after upgrading the package.

**Comment by krb-vci** [comment]
@Evangelink -
[AfterLogs.zip](https://github.com/microsoft/testfx/files/9120713/AfterLogs.zip)
[Before-logs.zip](https://github.com/microsoft/testfx/files/9120714/Before-logs.zip)

**Comment by krb-vci** [comment]
I was able to solve this by simply creating a new project and copying in all my classes and tests.  
Still have no idea why I had this problem.
