### ISSUE TITLE
Build on VS 2019

### ISSUE THREAD

**Issue by Ishu0045** [microsoft/testfx#1139]
I am trying to build the project downloaded from https://github.com/microsoft/testfx but it is unable to build. Could anyone please provide a stepwise guide on how to succeed in this. I want to run it in .net framework 4.5

**Comment by Ishu0045** [comment]
Yes, I am following the complete guide. Please have a look at the attached shot describing the missing references from the projects. 
![image](https://user-images.githubusercontent.com/108327108/176134211-ec238686-ed82-487f-97ae-da1c89bfa5e1.png)

**Comment by Ishu0045** [comment]
Also, I am getting these errors while building as well 

![image](https://user-images.githubusercontent.com/108327108/176136953-fec7df3a-a942-44f4-bacb-db5cf0bafe2a.png)

**Comment by Ishu0045** [comment]
it is missing these references 
![image](https://user-images.githubusercontent.com/108327108/176141480-79604770-8b95-45b0-9023-c83ab0f1cbbe.png)

**Comment by Evangelink** [comment]
@Ishu0045 Have you run `build.cmd` from command line before building in VS?

**Comment by Evangelink** [comment]
Ping @Ishu0045

**Comment by Evangelink** [comment]
Closing this issue. Feel free to ping if you are still facing some issues.
