### ISSUE TITLE
Improper Handling of Exceptional Conditions in Newtonsoft.Json before 13.0.1

### ISSUE THREAD

**Issue by SymbioticKilla** [microsoft/testfx#1143]
https://github.com/advisories/GHSA-5crp-9r3c-p9vr
Hi,
any chance to get this updated? Actual version is 10.0.3+: https://github.com/microsoft/testfx/pull/827/commits/db514b0779fd00f664cecb36276af40b7ec30c12

Thanks!

[AB#1575802](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1575802)

**Comment by majastrz** [comment]
Will this be fixed in 17.4? Any ETA?

**Comment by Evangelink** [comment]
We are currently working on it. We yet have to decide if we will do a separate release with only "this" feature or include that into MSTest v3 bucket.

**Comment by Haplois** [comment]
This is fixed in our [nightly builds][fixed-build] now, and will be included in our first public preview of version `2.3.0`.

   [fixed-build]: https://dev.azure.com/dnceng/public/_artifacts/feed/test-tools/NuGet/MSTest/versions/2.3.0-preview-20220805-01
