### ISSUE TITLE
MSTest.TestAdapter > 2.2.8 "MSTestAdapter failed to discover tests in class" in Net 6.0 test project

### ISSUE THREAD

**Issue by wangyuan8421** [microsoft/testfx#1256]
The most useful log message "Method 'get_Properties' in type 'Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.TestContextImplementation' 
 from assembly 'Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' does not have an implementation"

## Description
We have a MSTest project target to Net 6.0 (windows 11, most updated Visual Studio 2022). Use VS project wizard create the MSTest project, it will install "MSTest.TestAdapter 2.2.8" by default. And everything works fine.

If we upgrade "MSTest.TestAdapter > 2.2.8", the VS test explorer will throw warning "**MSTestAdapter failed to discover tests in class**"

## Steps to reproduce
- Windows 11, most updated Visual Studio 2022, create a MSTEST project in Net 6.0
- It will install ["MSTest.TestAdapter", "MSTest.TestFramework"] version 2.2.8 by default
- The unit test will run and test without problem
![image](https://user-images.githubusercontent.com/74802417/190436699-73064f07-bcf8-498f-8840-6b2cd123050a.png)

- Then, I upgrade the ["MSTest.TestAdapter", "MSTest.TestFramework"] >= 2.2.10
- The Visual Studio test explorer will not find any unit test from dll
![image](https://user-images.githubusercontent.com/74802417/190436773-1f198aca-db3d-4a41-bbb7-e8e0fb15e422.png)

- Test explorer warning
[<img width="1609" alt="image" src="https://user-images.githubusercontent.com/74802417/190429803-ceb8b433-c0c7-451d-9d59-cab028387534.png">](https://user-images.githubusercontent.com/74802417/190429803-ceb8b433-c0c7-451d-9d59-cab028387534.png)

- Warning message detail (hide some directory / class name)
<img width="1463" alt="image" src="https://user-images.githubusercontent.com/74802417/190436990-82426769-46c3-4501-ad03-b91c133abd3e.png">

## Expected behavior
Nuget > 2.2.8 should find test case in dll.

## Actual behavior
Nuget > 2.2.8 (v2.3.0-preview-20220810-02 has same issue) cannot find test case in dll.

## Environment
> Please share additional details about the test environment.
>  - Operating system: Windows 11
>  - Build version of vstest.console: Microsoft (R) Test Execution Command Line Tool Version 17.3.0-preview-20220626-01 (x64)
>  - Package version of MSTest framework and adapter: 2.2.8 is working, 2.2.10 and 2.3.0-preview-20220810-02 does not working. Didn't test before 2.2.8
>  - Other installed packages and their versions on the test project: <PackageReference Include="Microsoft.VisualStudio.TestPlatform" Version="14.0.0.1" />

**Comment by Evangelink** [comment]
Thanks for reporting this issue! Would you have any demo/repro case we could use to debug?

**Comment by Evangelink** [comment]
Hi @wangyuan8421, sorry for the delay in answering your request! I have created a PR (https://github.com/wangyuan8421/MsTestAdapterBugDemo/pull/1/files) against your demo repository where I simply removed the references to `Microsoft.VisualStudio.TestPlatform` and now the tests are correctly discovered/executed:

![image](https://user-images.githubusercontent.com/11340282/192468818-0b3ac847-495d-4cd7-96ef-da46351adfac.png)

I will move forward by closing this issue but please feel free to let us know if you are still facing the issue.
