### ISSUE TITLE
VB unit test project templates that ship in VS 2017 do not reference MSTest V2 nuget packages

### ISSUE THREAD

**Issue by AbhitejJohn** [Microsoft/testfx#132]
> From @shyamnamboodiripad, Microsoft/vstest#673

## Description
Live Unit testing does not work out of the box for VB unit test projects created using VS 2017

## Steps to reproduce
1. Create a new VB Unit Test Project in VS 2017 -
![image](https://cloud.githubusercontent.com/assets/10579684/24526659/bf3032d2-1553-11e7-8349-0cc1b0d979c3.png)
2. Build the project
3. Turn on LUT (Test -> Live Unit Testing -> Start)

## Expected behavior
LUT is turned on

## Actual behavior
```
[14:16:35.202 Error] No test adapters are referenced by this solution. If you have a test project, add a NuGet reference to a test adapter corresponding to the test framework used in order to run the tests. If you already have the required NuGet reference in your test project, performing a NuGet restore may resolve the issue.
[14:16:35.202 Info] Start failed.
[14:16:35.264 Info] Live Unit Testing stopped.
```
Looks like VB project template for Unit Test Project is still adding a reference to the old 'MS.VS.QualityTools.UnitTestFramework.dll' instead of 'MS.VS.TestPlatform.TestFramework' nuget packages. Corresponding C# project template references the correct version.

![image](https://cloud.githubusercontent.com/assets/10579684/24526934/dc8f27ba-1554-11e7-8224-691fb18fa4a8.png)

Referencing the same nuget packages in the created VB project fixes the issue.

## Environment
VS 2017 Enterprise
![image](https://cloud.githubusercontent.com/assets/10579684/24527281/47fc4306-1556-11e7-872e-65aa9528c69c.png)

**Comment by jayaranigarg** [comment]
This has been fixed in 15.3 latest Preview.
