### ISSUE TITLE
Allow IEnumerable of Tuples for DynamicData

### ISSUE THREAD

**Issue by johanneshoehn** [microsoft/testfx#1335]
## Summary

Allow code like this:
```csharp
public (int a, int b int sum)[] TestData => new []
{
    (a: 1, b: 2, sum: 3),
};

[TestMethod]
[DynamicData(nameof(TestData))]
public void SumIsCalculatedCorrectly(int a, int b, int sum)
{
   ...
}
```

## Background and Motivation

Commonly when using `DynamicDataAttribute` the test data is relatively complex.
The input for it needs to be passed as an `IEnumerable<object[]>`.
It's easy to mix up some elements, so they don't match the signature of the test function. 
With big data rows it can also sometimes be difficult to read which element matches which parameter of the test function.

## Proposed Feature

Allow `IEnumerable<ITuple>` for the data of `DynamicDataAttribute`. This could be solved very easily in `DynamicDataAttribute.GetData()`: If `obj is IEnumerable<ITuple>` then convert it to an `IEnumerable<ITuple>`.
For each `ITuple` create a new array and copy the elements of the tuple over.

A further step could be an analyzer that warns if types or names don't match up.

## Alternative Designs

Offer an API to run tests with given parameters in a type-safe way.

**Comment by Evangelink** [comment]
Hi @johanneshoehn, thanks for the suggestion! We will look into how we can improve the experience of `DynamicData` as-soon-as we are done with the Milestone v3.

**Comment by jnyrup** [comment]
For inspiration, xUnit has `TheoryData` which provides type-safe dynamic data.
See e.g. https://andrewlock.net/creating-strongly-typed-xunit-theory-test-data-with-theorydata/.
Especially the last code-snippet shows how how concise it can be used.

**Comment by Evangelink** [comment]
Thanks @jnyrup! I wasn't aware of this part on xUnit.
