### ISSUE TITLE
Allow to override GetDisplayName method from DataRowAttribute

### ISSUE THREAD

**Issue by Evangelink** [microsoft/testfx#1336]
> As far as I can see, there is a [DisplayName](https://github.com/microsoft/testfx/blob/main/src/TestFramework/TestFramework/Attributes/DataSource/DataRowAttribute.cs?rgh-link-date=2022-10-12T14%3A17%3A06Z#L59) property that is settable so you should be able to manually override the name.

DisplayName is settable, but that does not solve the problem imho. To generate DisplayName I need to get the input data (method and params) and I get those in GetDisplayName. 

I also most likely want to rely on the `base` implementation of GetDisplayName, and only add some additional info, not re-implement the whole method from scratch or hide it. So imho GetDisplayName should be virtual.

_Originally posted by @nohwnd in https://github.com/microsoft/testfx/issues/1180#issuecomment-1277155353_
      

[AB#1642313](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1642313)

**Comment by inikulshin** [comment]
@Evangelink thanks for this improvement.

But did you managed to make overridden `GetDisplayName() `to be used by Visual Studio? I thought it was the main reason for making it `virtual`, but with latest (**17.7.4**) Visual Studio I still see all the lines the same:

![image](https://github.com/microsoft/testfx/assets/17042537/4e2af11b-1203-47f6-b4ab-2e2af898d835)

MSTest packages are **3.0.2**, custom DataRow implementation is the following:
```
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    public class DataRowAttribute : Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute
    {
        public DataRowAttribute() : base() { }
        public DataRowAttribute(object data1) : base(data1) { }
        public DataRowAttribute(object data1, params object[] moreData) : base(data1, moreData) { }

        public override string? GetDisplayName(MethodInfo methodInfo, object?[]? data)
        {
            return base.GetDisplayName(methodInfo,
                Array.ConvertAll(data, obj => (obj is Array ? "[" + string.Join(",", obj as Array) + "]" : obj)));
        }
    }
```
