### ISSUE TITLE
MSTest.TestAdapter and MSTest.TestFramework package should be transitive (buildtransitive instead of build)

### ISSUE THREAD

**Issue by Ildrial** [microsoft/testfx#1343]
## Summary

I would like to have the .props and .targets of MSTest.TestAdapter and MSTest.TestFramework transitive - similar as it was [suggested and implemented for Microsoft.Net.Test.Sdk](https://github.com/microsoft/vstest/issues/32270).

## Background and Motivation

I have the same test hierarchy scenario as described in the above issue and would like to distribute requirements via NuGets.
I am using these 3 libraries (Microsoft.Net.Test.Sdk, MSTest.TestAdapter, MSTest.TestFramework) together and hence depend on the transitivity of all three libraries to avoid repetitive package references.

## Proposed Feature

The following .nuspecs should change like depicted below (for all build folders).

### https://github.com/microsoft/testfx/blob/main/src/Package/MSTest.TestFramework.nuspec
```
...
<!-- net6.0 -->
<file src="Build\Net6\MSTest.TestFramework.targets" target="buildtransitive\net6.0\" />
<file src="TestFramework.Extensions\net6.0\Microsoft.VisualStudio.TestPlatform.TestFramework.dll" target="lib\net6.0\" />
<file src="TestFramework.Extensions\net6.0\Microsoft.VisualStudio.TestPlatform.TestFramework.xml" target="lib\net6.0\" />
<file src="TestFramework.Extensions\net6.0\Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions.dll" target="buildtransitive\net6.0\" />
<file src="TestFramework.Extensions\net6.0\Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions.xml" target="buildtransitive\net6.0\" />
<file src="TestFramework.Extensions\net6.0-windows10.0.18362.0\Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions.dll" target="buildtransitive\net6.0\winui\" />
<file src="TestFramework.Extensions\net6.0-windows10.0.18362.0\Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions.xml" target="buildtransitive\net6.0\winui\" />
...
```

### https://github.com/microsoft/testfx/blob/main/src/Package/MSTest.TestAdapter.nuspec
```
...
<!-- net6.0 -->
<file src="Build\Net6\MSTest.TestAdapter.props" target="buildtransitive\net6.0\MSTest.TestAdapter.props" />
<file src="Build\Net6\MSTest.TestAdapter.targets" target="buildtransitive\net6.0\MSTest.TestAdapter.targets" />
<file src="TestFramework\net6.0\Microsoft.VisualStudio.TestPlatform.TestFramework.dll" target="buildtransitive\net6.0\" />
<file src="MSTestAdapter.PlatformServices\net6.0\Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.dll" target="buildtransitive\net6.0\" />
<file src="MSTestAdapter.PlatformServices\net6.0-windows10.0.18362.0\Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.dll" target="buildtransitive\net6.0\winui\" />
<file src="Microsoft.TestPlatform.AdapterUtilities\netstandard2.0\" target="buildtransitive\net6.0\" />
<file src="MSTest.TestAdapter\net6.0\Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.dll" target="buildtransitive\net6.0\" />
...
```

**Comment by Evangelink** [comment]
Hi @Ildrial, thanks for the suggestion. We will review it and make sure it doesn't have any unwanted side effect but that does sound like a good idea.

**Comment by Evangelink** [comment]
Hi @Ildrial, I will move forward by marking this issue as won't fix. We did a rollback on vstest side as there were unexpected consequences.

Besides, it seems that NUnit and xUnit are also both avoid the build transitive configuration.

Please do keep suggesting improvement here!
