### ISSUE TITLE
MSTest v3 Assert.ThrowsExceptionAsync is marked as returns nullable

### ISSUE THREAD

**Issue by Mertsch** [microsoft/testfx#1375]
## Describe the bug
MSTest 3.0.0-preview-20221110-04
`Assert.ThrowsExceptionAsync<T>` now returns `Task<T?>` which causes null ref warnings/errors everywhere.

## Expected behavior
`Assert.ThrowsExceptionAsync<T>` should return `Task<T>` (`where T : Exception`)

## Actual behavior
`Assert.ThrowsExceptionAsync<T>` returns `Task<T?>`

[AB#1675470](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1675470)

**Comment by Evangelink** [comment]
Hi @Mertsch,

You are also right here. I got confused by the fact that the method does return `null` in some path but that path was indicated as unreachable in some method. I will fix the API and the code comments.
