### ISSUE TITLE
Extensibility: Custom assertions

### ISSUE THREAD

**Issue by pvlakshm** [Microsoft/testfx#138]
## Description
Enable users to define custom assertions that plug-in to the test framework’s assertion infrastructure.
RFC: [Framework Extensibility for Custom Assertions](https://github.com/Microsoft/testfx-docs/blob/master/RFCs/002-Framework-Extensibility-Custom-Assertions.md)

**Comment by AbhitejJohn** [comment]
Dupe of #116.
