### ISSUE TITLE
Extensibility: Action attributes

### ISSUE THREAD

**Issue by pvlakshm** [microsoft/testfx#140]
## Description
Allow all test lifecycle attributes to be extensible:
- TestInitializeAttribute
- ClassInitializeAttribute
- AssemblyInitializeAttribute
- TestCleanupAttribute
- ClassCleanupAttribute
- AssemblyCleanupAttribute

Also allow multiple action attributes on a test method.

**Comment by parrainc** [comment]
I'm just wondering, you guys still are interested in this enhancement?
I have a local branch with changes related to this issue that might be ready for PR, so you can review and merge them, so this one get closed. And, of course, mark one more item from the extensibility list on the roadmap for MSTest V2 (not sure if it's updated)

Let me know, and I'll be pushing my changes later this week.
@AbhitejJohn @pvlakshm

**Comment by Evangelink** [comment]
Given there is no upvotes here I will move forward by closing this ticket.
