### ISSUE TITLE
MSTest v4 Assert.ThrowsException should allow Func<nullable> as parameter

### ISSUE THREAD

**Issue by Mertsch** [microsoft/testfx#1402]
## Describe the bug
MSTest 3.0.0-preview-20221122-01
`Assert.ThrowsException` expects a `Func<object>` which causes null ref warnings/errors when specifying a `Func<object?>`

## Expected behavior
`Func<object?>`

## Actual behavior
`Func<object>`

https://github.com/microsoft/testfx/blob/fc1be70c740fb0e527364b3058ae9739ccda5fa9/src/TestFramework/TestFramework/Assertions/Assert.ThrowsException.cs#L82
3 times

**Comment by Evangelink** [comment]
Yep this one is probably still an error on my side so I will make it straight for the MSTest v3 directly. Adding nullable on MSTest wasn't super easy given the current coverage.
