### ISSUE TITLE
Extensibility: data driven testing

### ISSUE THREAD

**Issue by pvlakshm** [Microsoft/testfx#141]
## Description
Provide the ability to extend the data source to your favorite store, generate data, use combinatorics or pairwise testing.

**Comment by AbhitejJohn** [comment]
The RFC for this support is under PR here: https://github.com/Microsoft/testfx-docs/pull/12.

**Comment by harshjain2** [comment]
@JVimes @ipjohnson Thanks for your valuable feedback. 
We have implemented this feature and latest dogfooding bits are available here :
https://dotnet.myget.org/F/mstestv2/api/v3/index.json

Do let us know your feedback.
