### ISSUE TITLE
Changed TRX file 'InnerResults' structure for datarows

### ISSUE THREAD

**Issue by PSchmidde** [microsoft/testfx#1424]
Hi,

since I updated my IDE enviroment, to VisualStudio 2019  V16.10.2 my test trx result file is no longer structured as expected.
I use vstest.console.exe in version 16.0.3136.167. All my test classes are started with this option to performe more datarows are defined in the TestFiles_prepared.xml:

`      
[DataSource("Microsoft.VisualStudio.TestTools.DataSource.XML", "|DataDirectory|\\TestFiles_prepared.xml", "TestFile", DataAccessMethod.Sequential)]
`

The problem now is, that all UnitTestResults are stored flat in the 'TestResult\Results\ node'. In the past it was structured on the child node 'InnerResults'

<img width="801" alt="Unbenannt" src="https://user-images.githubusercontent.com/86401380/123225798-5a1d7500-d4d3-11eb-808f-f57ce5186e7e.PNG">

<img width="742" alt="Unbenannt2" src="https://user-images.githubusercontent.com/86401380/123226729-33ac0980-d4d4-11eb-956a-3e161049e8e1.PNG">

Any ideas, how I get the old structure?
Thanks

**Comment by Evangelink** [comment]
Hi @PSchmidde,

This issue duplicates #1149 but to give you some details, there was a breaking change introduced in MSTest (sadly not following semantic versioning) to align behavior with other test frameworks (NUnit and xUnit).

With v3 of MSTest, you will be able to revert to legacy behavior. But please note that this is also going to lead to some issue with unfolding of the data tests in VS.

**Comment by dobsa** [comment]
Dear all. Are you aware that this breaking change breaks also running of the tests via Microsoft AZDS task `VSTest@2` (see [here](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/vstest-v2?view=azure-pipelines))? That is when `testSuite` and `testPlan` are used to define the tests to run. In case of `DataRow` it runs only one data point and reports it (ignoring the rest). In case of `DynamicData` it runs all and reports nothing. Is there a plan to fix that? We do rely heavily on this functionality.

**Comment by Evangelink** [comment]
Hi @dobsa,

For AzDO related issues, please open an issue on https://developercommunity.visualstudio.com/AzureDevOps/report.

This repository is not linked to AzDO

**Comment by dobsa** [comment]
Hi @Evangelink thanks for quick reply.

> 
> For AzDO related issues, please open an issue on https://developercommunity.visualstudio.com/AzureDevOps/report.
> 

They clearly need to be linked at least somehow since the change in one breaks the other. But I will try to search also there. I hope the breaking change has been at least communicated.

Thanks again and regards.
Martin
