### ISSUE TITLE
TestContext is not CLS-compliant in MSTest v3.0.0

### ISSUE THREAD

**Issue by vaLP2eh** [microsoft/testfx#1449]
## Describe the bug

Microsoft.VisualStudio.TestTools.UnitTesting.TestContext is not CLS-compliant.
MSTest v3.0.0

## Steps To Reproduce

Add the System.CLSCompliant(true) to your test class and use TestContext somewhere.

Example:
```
[TestClass]
[CLSCompliant(true)]
public sealed class DummyUnitTest
{
    [AssemblyInitialize]
    public static void AssemblyInit(TestContext testContext)
    {
        Trace.WriteLine(nameof(AssemblyInit));
    }

    [AssemblyCleanup]
    public static void AssemblblyCleanup()
    {
        Trace.WriteLine(nameof(AssemblblyCleanup));
    }

    [TestMethod]
    public void DummyTest()
    {
        Trace.WriteLine(nameof(this.DummyTest));
    }
}
```

## Expected behavior

No compiler warning.

## Actual behavior

Compiler warning: CS3001, Argument type 'TestContext' is not CLS-compliant

## Comment

MSTest 2.2.10 was CLS-Compliant.

**Comment by Evangelink** [comment]
Hi @valP2eh, thanks for raising this issue. I looked back and found that I dropped it when introducing some `MemberNotNullAttribute` that is using some non-compliant syntax. As this is only used in a non-user facing method, I will work on a revert and fix this issue in `3.0.1`.

Sorry for the inconvenience.
