### ISSUE TITLE
System.InvalidOperationException and System.Collections.Generic.KeyNotFoundException errors when running tests

### ISSUE THREAD

**Issue by liamfl** [microsoft/testfx#1474]
## Describe the bug

I am running unit tests on a 2 c# test projects using the lates version of Visual Studio Community 2022

The 2 test project are named EngineTests and ServerCodeTests.

While the test projects compile correctly, I regularly get a series of error messages in the Output / Tests window when running unit tests:

System.InvalidOperationException: TestsForOrigin: Unknown TestCaseRecord.Origin value Unknown
System.Collections.Generic.KeyNotFoundException: The given key 'C:\Users\liamf\Source\Repos\TradingReplay\ServerCodeTests\bin\Debug\net6.0\ServerCodeTests.dll' was not present in the dictionary.
An exception occurred while test discoverer 'MSTestDiscoverer' was loading tests. Exception: Could not load type 'Microsoft.VisualStudio.TestTools.UnitTesting.StringEx' from assembly 'Microsoft.VisualStudio.TestPlatform.TestFramework, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
No test is available in C:\Users\liamf\Source\Repos\TradingReplay\ServerCodeTests\bin\Debug\net6.0\ServerCodeTests.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.

I have posted this in the vstest issues log as well, where @Evangelink identified that this issue has been raised before (https://developercommunity.visualstudio.com/t/Unit-test-startup-fails-with-an-exceptio/10226576) where @ocallesp suggested that this was an issue with MsTest.Framework and TestAdapter v3.0.0. 

Downgrading to the previous versions of MsTest.TestFramework and MsTest.TestAdapter doesn't solve the issue.

## Steps To Reproduce

Running any test from Test Explorer.

Reloading Visual Studio allows you to do 2-3 test runs before the issue arises again.

## Additional context

Added output log showing error messages

## Environment
Windows 11 10.0.22621 Build 22621
Visual Studiio Community v17.4.3

Nuget packages:
MSTest.TesAdapter v3
MSTest.TestFramework v3
Microsoft.NET.Test.SDK v17.4
[ErrorLog.txt](https://github.com/microsoft/testfx/files/10246979/ErrorLog.txt)

**Comment by Evangelink** [comment]
Thanks for raising the issue @liamfl. I will close this one and keep track from the vstest repository as it seems to not be linked to a change in vstest done for Test Window.
