### ISSUE TITLE
MSTest.TestAdapter v3.0.0 does not copy to Output directory

### ISSUE THREAD

**Issue by HeikoWr** [microsoft/testfx#1484]
With **MSTest.TestAdapter** NuGet package v3.0.0 project files marked as 'Copy to Output Directory: Copy always' are not not copied to TestContext.TestDeploymentDir while v2.2.10 does.

(using VS 2022 with Live Unit Testing und <TargetFramework>net7.0</TargetFramework>)

In csproj:
```xml
<ItemGroup>
    <None Update="TestFiles\MyFile.zip">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
</ItemGroup>
```

Having a TestMethod:
```csharp
[TestClass]
public class MyTests
{
        public TestContext TestContext { get; set; } = null!;

        [TestMethod]
        public void Test1()
        {
            string filename = Path.Combine(TestContext.TestDeploymentDir, "Testfiles", "MyFile.zip");
            Assert.IsTrue(File.Exists(filename)); 
            //...
        }
}
```
This Assert fails with v3.0.0 while running with v2.2.10 and several versions earlier (we use this pattern a lot and it worked for years).

Packages Test.Sdk and TestFramework are working with the latest NuGet version. So we currently use this to get our existing Tests working:
```xml
<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.4.1" />
<PackageReference Include="MSTest.TestAdapter" Version="2.2.10" />
<PackageReference Include="MSTest.TestFramework" Version="3.0.0" />
```

**Comment by Evangelink** [comment]
Hi @HeikoWr, thanks for the report. This is part of a breaking change that happened with v3 where we unified the behaviour to what was done for netfx (the netcore version was buggy for years). You will need to use `DeploymentItemAttribute` on top of either your method or class to have the bin content copied over to the MSTest working dir.

**Comment by fstugren** [comment]
This breaking change in how test files are handled is causing significant work for teams like mine, with lots of test code written for the 2.x versions. I tried to update to 3.x, but given the sheer number of test projects and how after one hour of trying to upgrade I realized that making this work requires refactoring more test code than I'd like - the conclusion is that it's not worth the effort unless you decide to go through a big code cleanup push.
