### ISSUE TITLE
Migrated from MSTest v1: AssemblyInitialize method has wrong signature

### ISSUE THREAD

**Issue by ivonin** [Microsoft/testfx#149]
## Description
We are trying to migrate our tests to MSTest v2. Our test assemblies use `[AssemblyInitialize]` and after migration all our test are failing with the following message:

> Method ...InitializeAssembly has wrong signature.  Parameter 1 should be of type Microsoft.VisualStudio.TestTools.UnitTesting.TestContext.

Our `InitializeAssembly` method looks like this:

```
[AssemblyInitialize]
public static void InitializeAssembly(TestContext context)
{
	// code
}
```

First of all, it does meet the requirements. Also, I noticed that the actual message in the current version of code looks slightly different. 

This makes me think that Visual Studio somehow uses the old MSTest tooling despite the fact that our projects no longer reference `Microsoft.VisualStudio.QualityTools.UnitTestFramework` and reference `MSTest.TestFramework` and `MSTest.TestAdapter` instead.

## Environment
We are referencing MSTest packages version 1.1.14. The problem is present both in VS 2017 test runner and ReSharper test runner. 

We are also using the old .csproj format. Is it possible that we need to make some additional migration changes in our csproj files?

**Comment by AbhitejJohn** [comment]
@ivonin : It looks like you have the legacy .testsettings specified. If there isn't anything specific that you need in a testsettings, do remove it or move over to .runsettings.

**Comment by ivonin** [comment]
@AbhitejJohn we don't have .testsettings files anywhere in our solution.

**Comment by AbhitejJohn** [comment]
That's interesting. Ok I'm assuming you are trying this out from Visual Studio for now and that you do not have a testsettings or vsmdi selected under "Test -> Test Settings" menu. Can you turn on [diagnostic logs](https://blogs.msdn.microsoft.com/aseemb/2012/03/01/how-to-enable-ute-logs/) for vstest.executionengine*.exe and send that over please?

**Comment by ivonin** [comment]
@AbhitejJohn we do use .testrunconfig file for our tests. Can it be a problem? If so, how do I migrate it?

**Comment by AbhitejJohn** [comment]
What is it used for? Can you share the contents please?
[.runsettings](https://msdn.microsoft.com/en-us/library/jj635153.aspx) is the single source of all test configuration that we work with.

**Comment by ivonin** [comment]
Here is a our [Default.testrunconfig](https://github.com/Microsoft/testfx/files/914023/Default.txt)
We use it to deploy some additional configuration into test folders. We don't use it for anything but `Deployment` section, all the other stuff came from some template a long time ago, I presume.

**Comment by AbhitejJohn** [comment]
ah, this is the legacy testsettings. As a replacement to the `Deployment` section you can set the `CopyToOutputDirectory` property to `Always` for the config file in the csproj which includes it. That should be available for the test in the output directory.

**Comment by ivonin** [comment]
Cool, when I don't use `.testrunconfig` settings it does seem to work, thanks a lot!

We do have some more complex deployment items though, like folders that are not included in solution. It seems to me that .runsettings doesn't support deployment items in any way. Is there a workaround for that?

While I consider my issue fixed, is it possible to make things more clear when there is such misconfiguration? It isn't really obvious what's going on when you get an error that we got.

**Comment by AbhitejJohn** [comment]
That's great news @ivonin .

>It seems to me that .runsettings doesn't support deployment items in any way. Is there a workaround for that?

you can use the [`DeploymentItemAttribute`](https://github.com/Microsoft/testfx/blob/master/src/TestFramework/Extension.Desktop/Attributes/DeploymentItemAttribute.cs#L20) for that. Adorn this on a `TestClass` or `TestMethod` that needs the folder\file deploymed.

> is it possible to make things more clear when there is such misconfiguration?

We do throw out the following warning in the Output -> Tests pane when these settings are used.
`Warning : A testsettings file or a runsettings with a ForcedLegacyMode set to true is not supported with the MSTest V2 Adapter.`

**Comment by AbhitejJohn** [comment]
Feel free to file a new issue if you run into other problems with the migration effort.
