### ISSUE TITLE
DataRowAttribute enhancement

### ISSUE THREAD

**Issue by ipjohnson** [Microsoft/testfx#151]
## Description
Currently the DataRowAttribute has no understanding of what method it's being executed on.

It would be really nice to change it to have the following method

```
public virtual Tuple<object[],string> GetDataForMethod(ITestMethod) 
{
  return new Tuple<object[],string>(Data, DisplayName);
} 
```

This would allow for providing data that's specific to the method without having to write our own attribute that inherits from TestCaseAttribute.

Not sure if this is on the list for [issue 141](https://github.com/Microsoft/testfx/issues/141) but it would be really helpful.

**Comment by AbhitejJohn** [comment]
Thanks for filing this issue @ipjohnson . Yes #141 should cover this scenario. This would especially be of much use when data is being pulled in dynamically from other methods or properties. Please do vote for #141 - that would greatly help in prioritization.

**Comment by AbhitejJohn** [comment]
Closing this since this has been taken care of as part of #141.
