### ISSUE TITLE
Add setting for test discovery issues to be logged as errors

### ISSUE THREAD

**Issue by johnthcall** [microsoft/testfx#1544]
## Summary
There are certain errors like "CouldNotInspectTypeDuringDiscovery" which indicate that a TestClass is misconfigured in some way and will be skipped during unit test runs for the assembly. Because these appear as warnings instead of errors it may be hard to convince the team operating the testing infrastructure to fail a build due to these issues.

## Background and Motivation
I recently found out that 40 of my teams test files were being skipped due to this issue and have found no way to cause a build to fail because of it.

## Proposed Feature
Add a setting similar to MapNotRunnableToFailed such as TreatDiscoveryWarningsAsErrors and hook it in at https://github.com/microsoft/testfx/blob/0bd9f31419b9c21a536b8aeb1e5d5ad268a8c5e1/src/Adapter/MSTest.TestAdapter/Discovery/UnitTestDiscoverer.cs#L64-L72

**Comment by Evangelink** [comment]
Hi @johnthcall, thanks for the suggestion.

We are planning to add some code analyzers that should help prevent most of the issues at compile time but I still think something along the lines of your suggestion could be useful.

**Comment by johnthcall** [comment]
@Evangelink I have made the mentioned PR, let me know if it makes sense. I'm happy to abandon if it doesn't makes sense as it adds new configuration which you may want to avoid.

**Comment by Evangelink** [comment]
Hey @johnthcall, sorry it's a busy week. I will try to have a look either today or on Monday. Thanks for the contribution :)

**Comment by Evangelink** [comment]
Fixed by #1547

**Comment by cremor** [comment]
Is there a reason why this has to wait until 4.0.0 to be released? Is there a breaking change in it?

**Comment by Evangelink** [comment]
It's a new feature and we are currently working on v4 so we don't feel like there is a need to cherry-pick only this as part of a `3.1.0` release.

**Comment by johnthcall** [comment]
Is there a timeline for 4.0.0? It would be great to use this to avoid regressions in unit test discovery.
