### ISSUE TITLE
Documentation on Test discovery/Run flow

### ISSUE THREAD

**Issue by AbhitejJohn** [Microsoft/testfx#155]
## Description
There is no documentation currently on how the flow of control is during discovery and execution in testfx-docs. Filing this issue to track the following:
1. The design of the platform service model.
2. An overall architecture of discovery and execution flows.
3. Order of execution of setup and tear down methods - test class object creation etc.

**Comment by pvlakshm** [comment]
Unfortunately, we cannot accommodate this currently.
