### ISSUE TITLE
looking for appsettings.json

### ISSUE THREAD

**Issue by MCFHTAGENTS** [microsoft/testfx#1559]
With a recent upgrade (and I can't tell you whether we are talking Moq. MSTest, .NET Core or Visual Studio)

I am seeing a lot of my tests fail with:
````
Test method MyTestMethod threw exception: 
System.IO.FileNotFoundException: The configuration file 'appsettings.json' was not found and is not optional. The expected physical path was 'D:\....\my project\TestResults\Deploy_MarkHeaton 20230114T084906\Out\appsettings.json'.

  Stack Trace: 
FileConfigurationProvider.Load(Boolean reload)
ConfigurationRoot.ctor(IList`1 providers)
ConfigurationBuilder.Build()
ActionFilterAttributeTest.ExecuteOnActionExecutingTest(String testName, IHeaderDictionary headerDictionary, IRequestCookieCollection cookieCollection, Type resultType) line 127
BasicAuthenticationAttributeTest.TestBasicAuthenticationAttributeNoUser() line 27
````
Obviously it is expecting an appsettings.json file in the OUT directory and that is not there. Google suggests issues with active project context with this sort of error.

Any thoughts?

**Comment by Evangelink** [comment]
I just did investigate your reproducer and this is a breaking change behaviour documented (https://github.com/microsoft/testfx/blob/main/docs/Changelog.md#300---2022-12-06), in particular the entry `[breaking change] Unify DeploymentDirectory location across target frameworks https://github.com/microsoft/testfx/pull/1414`. There was a long standing bug where the `DeploymentDirectory` was not pointing to the correct directory. But because of the time it took to fix the issue, a lot of people got time to rely on this behaviour.

There is nothing better but updating your code that we could recommend.

**Comment by AlphaCreative-Mike** [comment]
Will do.  Using "AppDomain.CurrentDomain.SetupInformation.ApplicationBase" does the trick.

**Comment by MCFHTAGENTS** [comment]
Hi - am looking at my two problems and note AlphaCreative's comment above but not sure where you are setting this and what you are setting that to!

My other issue I have data files (e.g. an image to load) that were being copied into a deep path that is now being flattened so my test expects something in TestResults\Deploy\Out\Folder A\FolderB\image.jpg but the build process is copying the file to TestResults\Deploy\Out\image.jpg

**Comment by AlphaCreative-Mike** [comment]
@MCFHTAGENTS - If you clone my repo, you will see that in my scenario, I had code in my ClassInitialize function that was loading the appSettings.json.  If you can provide your own repo of the issue, I'd be glad to help you.

**Comment by MCFHTAGENTS** [comment]
ok - the issue here is my application, which is a .NET Core website, expects the current directory to be the directory the app is installed into (as do some of the MS libraries I use) and the test framework is setting it to the 'out' directory and so all the relative paths break and it also can't find appsettings.json.

**Comment by Evangelink** [comment]
Glad to see it's working for you folks!
