### ISSUE TITLE
Bug with ClassInitialize

### ISSUE THREAD

**Issue by Evangelink** [microsoft/testfx#1560]
> Latest version (not preview) and we were using debug. Had to switch to testcleanup instead.

Same here :(

_Originally posted by @enisak in https://github.com/microsoft/testfx/issues/143#issuecomment-1033470772_

**Comment by Evangelink** [comment]
I am confused as there seems to be two different "things" (one feature request and one bug) being discussed here.

As far as I can see, the inheritance of the class initialize is implemented and is working properly (we recently added a bunch of integration tests for this: https://github.com/microsoft/testfx/blob/2d2ab810a78fa98855a9e56cb5a18d7f963c45f2/test/IntegrationTests/MSTest.VstestConsoleWrapper.IntegrationTests/SuiteLifeCycleTests.cs).

@enisak Could you please let us know which version of MSTest you are using? Also, would you mind providing a small repro of what's not working so we can investigate (cc @engyebrahim)?

**Comment by enisak** [comment]
> I am confused as there seems to be two different "things" (one feature request and one bug) being discussed here.
> 
> As far as I can see, the inheritance of the class initialize is implemented and is working properly (we recently added a bunch of integration tests for this: https://github.com/microsoft/testfx/blob/2d2ab810a78fa98855a9e56cb5a18d7f963c45f2/test/IntegrationTests/MSTest.VstestConsoleWrapper.IntegrationTests/SuiteLifeCycleTests.cs).
> 
> @enisak Could you please let us know which version of MSTest you are using? Also, would you mind providing a small repro of what's not working so we can investigate (cc @engyebrahim)?

Hi there, 
I am not currently working on the same thing, but I do remember that Class Initialize was working as expected: being triggered once per class (which inherits base class containing class initialize method). However, the issue was that class cleanup did not follow the pattern. So, at the end, I have actually created Assembly cleanup method in a way that it becomes a workaround to overcome the issue (business logic could fit somehow into that). 
I do not remember which version of MSTest was, but surely the latest version that was available on Feb 9, 2022

**Comment by enisak** [comment]
If still not clear, please let me know to provide some code to help you to reproduce the issue.

**Comment by Evangelink** [comment]
It seems to me that what you are asking for is available (not sure since which version) but we have a test for derived class cleanup that seems to be working well: https://github.com/microsoft/testfx/blob/main/test/IntegrationTests/TestAssets/SuiteLifeCycleTestProject/LifeCycleClassInitializeAndCleanupBeforeEachDerivedClass.cs#L90

I will move forward by closing as cannot reproduce. If you see some problem please reopen or create a new issue with a reproducer so we can investigate.
