### ISSUE TITLE
We need Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface.dll

### ISSUE THREAD

**Issue by Jixinwen-Microsoft** [microsoft/testfx#1579]
## Summary
I am a MSFT employee and request for your help. I am wondering Why there is no **Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface.dll** in MSTest.TestAdapter 3.0.X package. https://www.nuget.org/packages/MSTest.TestAdapter/3.0.2. We need it to upgrade our product unit-test framework to MSTest V3.

**Comment by Evangelink** [comment]
Hi @Jixinwen-Microsoft,

The dll no longer exists as the code was merged in the platform services dll `Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.dll`.

You can update your code to use this dll while migrating to MSTest v3.
