### ISSUE TITLE
Inherited tests from base class are ignored

### ISSUE THREAD

**Issue by MikeChristensen** [Microsoft/testfx#158]
## Description
> It would be fantastic if MSTest2 would allow you to derive from another class and inherit tests from that base class.  This actually works if both classes are within the same assembly, but breaks across assemblies.  This is detailed on [this StackOverflow post](http://stackoverflow.com/questions/6002424/inherited-test-class-from-generic-base-is-ignored-in-mstest/6008179).

## Steps to reproduce
Base class in Assembly 1:

    [TestClass]
    public abstract class TestingBase
    {
        [TestMethod]
        public void TestBase()
        {
            Assert.IsTrue(true);
        }
    }

Derived class in Assembly 2:

    [TestClass]
    public class Testing : TestingBase
    {
        [TestMethod]
        public void TestTwo()
        {
            Assert.IsTrue(true);
        }
    }

## Expected behavior
> When running the "Testing" test class, both TestBase and TestTwo should be run.

## Actual behavior
> Only TestTwo is run.

## Environment
> Running the latest MSTest2 NuGet package and adapter with Visual Studio 2015.

**Comment by MikeChristensen** [comment]
Would love to see this fixed, and am willing to submit a pull request if someone wants to point me in the right direction in regards to what code I'd want to start looking at.

**Comment by MikeChristensen** [comment]
Just found [this pull request](https://github.com/Microsoft/testfx/pull/147/files) that looks like it might fix this bug!  Let's get that thing merged!!!

**Comment by AbhitejJohn** [comment]
@MikeChristensen : This is #23 and @ajryan helped with fixing this already. This should be part of the nuget release this week. However, this is currently under a setting `EnableBaseClassTestMethodsFromOtherAssemblies` as #144 describes. We plan to make this the default as soon as we fix an issue that popped up post this change that is being discussed in #23.
Thanks for willing to fix this however 👍 . Will close this issue.
