### ISSUE TITLE
[AssemblyInitialize] attribute prevents unit-tests from running

### ISSUE THREAD

**Issue by asfarley** [microsoft/testfx#1589]
## Describe the bug

With the following versions:

- Visual Studio 2022 4.8.09032
- Microsoft.NET.Test.Sdk (17.1.0)
- MSTest.TestAdapter (2.2.8)
- MSTest.TestFramework (2.2.8)

I have added functions to my unit-test class intended to run before and after the unit-tests execute. Adding these functions appears to prevent any unit-tests from executing as described here:
https://stackoverflow.com/questions/74862048/assemblyinitialize-seems-break-unit-test-project-in-net-6-visual-studio-2022

Note that my unit-tests class **is** marked with [TestClass], and I have several (working) unit-tests marked with [TestMethod], and I have ensured that my [AssemblyInitialize] function takes a TestContext object as a parameter.

## Steps To Reproduce

Create a unit-test class, marked with [TestClass] attribute. Create several unit-tests. Verify that unit-tests pass. Add an initialization function:

        private static credentials credential;
        
        [AssemblyInitialize]
        public static void TestInit(TestContext context)
        {
            // Initalization code goes here
            credential = new credentials();
            credential.CheckoutLicense();
        }

Now observe that unit-tests do not run, when triggered via the Test Explorer.

**Comment by engyebrahim** [comment]
Hi @asfarley, I tried to reproduce the problem with this sample project but I didn't get it can you please add a sample project?
[TestProject.zip](https://github.com/microsoft/testfx/files/10704818/TestProject.zip)
![Untitled](https://user-images.githubusercontent.com/24208132/218031599-5ab01bab-c999-4c02-9756-99c11ddc4b24.png)

**Comment by asfarley** [comment]
Ah, I think I've figured it out. I did the same thing you did and it worked. Then I added a function tagged with [AssemblyCleanup] and it stopped working. The issue was my assumption that the [AssemblyCleanup] method should have the same signature as [AssemblyInitialize]. Apparently it should take no arguments. After making this change, my tests are running again. 

Thank you.
