### ISSUE TITLE
Assert.AreEqual() type conversion issues 

### ISSUE THREAD

**Issue by Jixinwen-Microsoft** [microsoft/testfx#1613]
# Bug
Please see the files. 
For the test method TestEnum(), the build passes in lower versions of MSTest packages (like 2.2.10) while I turned to 3.0.x ones, there were issues below:
Error CS1503:Argument 2: cannot convert from 'EnumComparison.FruitKind' to 'float'
Error CS1503:Argument 3: cannot convert from 'string' to 'float'

[TestEnumCompareInMSTestV3.zip](https://github.com/microsoft/testfx/files/10878962/TestEnumCompareInMSTestV3.zip)

**Comment by engyebrahim** [comment]
Hi @Jixinwen-Microsoft ,
for the new visions `Assert.AreEqual(object, object)` no longer supported based on this PR
https://github.com/microsoft/testfx/pull/1429
so to fix your problem you need to use this overload `AreEqual<T>(T? expected, T? actual, string? message)`  then your line of code will be like this `Assert.AreEqual<FruitKind>(0, ((Fruit)(2)).GetFruit(),"comment of assertion");`

Thank you! I'll close the issue based on that!
