### ISSUE TITLE
[3.0 regression] Unable to run a test with timeout in STA ApartmentState

### ISSUE THREAD

**Issue by cremor** [microsoft/testfx#1616]
## Describe the bug

MSTest v2 ran all tests in STA ApartmentState when executed in a .NET Framework runtime. v3 runs "normal" tests still in STA, but tests that have a `TimeoutAttribute` applied now run in MTA.

## Steps To Reproduce

Run these tests with various versions of MSTest and runtimes:

```cs
[TestMethod]
public void TestMethod1()
{
    // Outputs:
    // MSTest   net7.0   net48
    // 2.2.10   MTA      STA
    // 3.0.2    MTA      STA
    Console.WriteLine(Thread.CurrentThread.GetApartmentState());
}

[TestMethod, Timeout(1000)]
public void TestMethod2()
{
    // Outputs:
    // MSTest   net7.0   net48
    // 2.2.10   MTA      STA
    // 3.0.2    MTA      MTA    <-- Problem
    Console.WriteLine(Thread.CurrentThread.GetApartmentState());
}
```

## Expected behavior
Either MSTest v2 behavior should be retained, or I should have a way to force STA on an unit test.

## Actual behavior
Tests with timeout always run in MTA.

## Additional context
I need STA to run UI (WPF) tests. Those tests try to execute WPF commands which now fail with `InvalidOperationException: The calling thread must be STA, because many UI components require this.`

This is most likely a side effect of #1296
The package "MSTest.STAExtensions" which is mentioned in #21 does not help/work, see saikrishnav/testfxSTAext#5
Related: #320

[AB#1822144](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1822144)

**Comment by engyebrahim** [comment]
Hi @cremor, thanks for your feedback!
I confirm I can reproduce the issue with mstest v.3.0.2.

**Comment by cremor** [comment]
@engyebrahim Thanks for confirming. But why did you tag this issue as a feature? I'd say that this is a bug.

**Comment by engyebrahim** [comment]
@cremor because it's related to this one https://github.com/microsoft/testfx/issues/320 and also to making something like this [MSTest.STAExtensions](https://www.nuget.org/packages/MSTest.STAExtensions/1.0.3-beta) inside mstest.

by making default behaviour and a decorator to use the other behaviour.

**Comment by cremor** [comment]
But the default behavior worked in 2.2.10.
So it was an intentional change in v3 to have different ApartmentStates when running with or without a TimeoutAttribute?

**Comment by cremor** [comment]
@engyebrahim Thanks for reclassifying this as a bug.

Is there a chance that this will be fixed in a 3.0.x release?
If not, is there any kind of workaround?

**Comment by engyebrahim** [comment]
Hi @cremor we will discuss it and let you as soon as possible

**Comment by fforjan** [comment]
@engyebrahim  any update on this ? I'm doing some porting between .net framework and .net 6.0 on my unit test with WPF and i'm getting 
```System.InvalidOperationException: The calling thread must be STA, because many UI components require this.```

It seems there is a different of behavior between .net framework and .net 6.0 and would like to know what is the expectation.

Seems you were having some discussion. Let me know if you need a different issue

**Comment by Evangelink** [comment]
Hey @cremor, @fforjan,

We are still investigating the issue (more precisely the fix). 

I confirm @cremor investigation that the change is a side-effect of merging the timeout behaviors hence using `Task.Run` instead of a `Thread` which helped with cancellation token but cause a change in the current apartment.

We will get back to you asap.

**Comment by fforjan** [comment]
Salut @Evangelink !
Any update on the issue ? 

This is blocking us we are trying to have the same WPF unit test compiled and running with 2 different framework - .NET Fwk/.NET 6.0 with the differene MTA/STA between both framework.

**Comment by Evangelink** [comment]
Hi @fforjan,

Sorry it's taking some time but we are exploring the solution to fix this issue. If we don't find something reasonable quickly we will probably revert the linked change in a bug fix version and plan to reapply the change in a later update when we have a proper upgrade path for users.

**Comment by Evangelink** [comment]
Might be related to https://github.com/microsoft/vstest/issues/1865

**Comment by fforjan** [comment]
@Evangelink in my case, yes  !

**Comment by Evangelink** [comment]
I haven't been able to make lots of progress on that today but I noticed that depending on target framework the testhost was using different mode and I found the linked issue.

**Comment by dotMorten** [comment]
I'm still seeing async tests that timeout will deadlock the test process on .NET Framework using 3.0.4. No issue on 2.2.10
![image](https://github.com/microsoft/testfx/assets/1378165/82281b08-86e3-4a45-b5d1-22fecb2c5710)
