### ISSUE TITLE
Allow not only object[] but also Tuple and ValueTuple for DynamicData

### ISSUE THREAD

**Issue by hrumhurum** [microsoft/testfx#1624]
## Summary

The existing `Microsoft.VisualStudio.TestTools.UnitTesting.DynamicDataAttribute` allows us to supply the data to a test method. Currently it only understands the data sources that return `IEnumerable<object[]>`. 

## Background and Motivation

The existing loosely-typed approach based on `object[]` works, but sometimes a strongly-typed approach is more desirable.

The problem with the loosely-typed `object[]` approach is that a compiler does not validate the types returned from a particular data source. This may lead to surprise errors in run time.

## Proposed Feature

I propose to add the support for more strongly-typed approaches in addition to the existing `object[]`.

Before we start, let's take a look at the existing loosely-typed code snippet that unfortunately will blow up in run time:

```c#
[TestClass]
public class FooSemanticsTests
{
    static IEnumerable<object[]> TestData
    {
        get
        {
            yield return new object[] { new FooName("123"), true };
            yield return new object[] { new FooName("10"), 10 };
        }
    }

    [TestMethod]
    [DynamicData(nameof(TestData))]
    public void Test(FooName fooName, bool isSimpleName)
    {
    }
}
```

The snipped above uses existing loosely-typed `object[]` approach which does not provide the benefits of compile-time type validations. The lack of compile-time validation leads to wasted time and requires additional development resources.

However, `DynamicData` attribute could, in theory, allow the consumption of strongly-typed tuples.

Let's take a look at the corresponding code snippet. It uses a strongly-typed approach based on `System.ValueType`. This time, the existing error will be caught in compile time:

```c#
[TestClass]
public class FooSemanticsTests
{
    static IEnumerable<(FooName, bool)> TestData
    {
        get
        {
            yield return (new FooName("123"), true);
            yield return (new FooName("10"), 10);  // <-- C# compiler will generate a type cast error at this line 
        }
    }

    [TestMethod]
    [DynamicData(nameof(TestData))]
    public void Test(FooName fooName, bool isSimpleName)
    {
    }
}
```

Currently, the above code snippet cannot be understood by `MSTest.TestFramework` (v3.0.2) in run time: 
```
Parameter 'Property or method TestData on FooSemanticsTests does not return IEnumerable<object[]>.'
```

The same limitation applies to `System.Tuple`: it is not understood either.

## Alternative Designs

As an alternative, I considered using adapter properties to convert from `IEnumerable<System.ValueTuple>` to `IEnumerable<object[]>`. However, that approach is hardly practical due to boilerplate distractions nobody wants to invest in.

[AB#1950023](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1950023)

**Comment by Evangelink** [comment]
To avoid breaking changes for now, I will add the support for `IEnumerable<Tuple<...>>` and `IEnumerable<ValueTuple<...>>` on dynamic data but without breaking the `ITestDataSource` interface so I will need to do transformation from tuple to object[] that will have a small overhead impact.

This is still overall beneficial for users.
