### ISSUE TITLE
Test stays "not run" if TestContext property is readonly, no error

### ISSUE THREAD

**Issue by pasisavolainen** [microsoft/testfx#1630]
## Describe the bug

It was hard to locate the issue here because the error was hidden deep in the logs and additionally marked `[Warning]`.

If test class has readonly `TestContext` the tests in that class will not get run. Setting this property in constructor does not affect the issue.

Additionally just changing the property from `get` to `get;set` doesn't change situation immediately, elaborate "clean;rebuild" dance is further required.

## Steps To Reproduce

```csharp
namespace TestProject1;

[TestClass]
public class UnitTest1 {
    // bork
    public TestContext TestContext { get; }

    // works
    //public TestContext TestContext { get; set; }

    public UnitTest1(TestContext context) => TestContext = context;

    [TestMethod]
    public void TestMethod1()
        => Assert.Fail();
}
```

## Expected behavior

Either the test should be allowed to run even if injection of `TestContext` failed (it's trusted to be set in constructor) or the test should get failed with clear error message.

## Actual behavior

Test stays "not run". No errors are shown:

![image](https://user-images.githubusercontent.com/6162135/231146589-709d6c48-e5d9-4d12-a6cb-f997e12b12e6.png)

## Additional context

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.1.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="2.2.8" />
    <PackageReference Include="MSTest.TestFramework" Version="2.2.8" />
    <PackageReference Include="coverlet.collector" Version="3.1.2" />
  </ItemGroup>

</Project>
```

**Comment by Evangelink** [comment]
Hi @pasisavolainen,

Thanks for the feedback. This is something that needs to be improved.

I think we can add an analyzer for this and also add a safety by emiting a warning in the logs when we detect that there is no setter.

**Comment by Evangelink** [comment]
Analyzer is brought by #2019

**Comment by Evangelink** [comment]
I did a few more tests and there is actually an error printed:

* In Visual Studio, you have to go to `Output > Tests`:
 
	![image](https://github.com/microsoft/testfx/assets/11340282/fd2fefda-cc98-4489-95e6-9658410c1b5b)

* With `dotnet test`:

	![image](https://github.com/microsoft/testfx/assets/11340282/c09c0be5-0333-40ac-ad00-ac152ff84197)

Another problem that exists with your solution is that (for now), MSTest doesn't support injecting the `TestContext` object through the ctor (and more widely doesnt' support non-parameterized ctors.

The analyzer was added as described on my previous comment so I will move ahead and close this issue.
