### ISSUE TITLE
TestAdapter: Wrongly grouped DataTestMethod

### ISSUE THREAD

**Issue by HightowerCZ** [microsoft/testfx#1634]
## Describe the bug

DataTestMethods are wrongly grouped with MSTest.TestAdapter in version 3.0.x
(Grouping in VS is by Traits)

Wrong grouping:
![image](https://user-images.githubusercontent.com/22144797/232417126-dfad8209-df9e-4972-87c8-94cce83c8435.png)

Expected grouping (achieved with MSTest.TestAdapter 2.2.x):
![image](https://user-images.githubusercontent.com/22144797/232417595-86831a5f-cae1-41b6-8cb6-98f442c15a65.png)

## Steps To Reproduce

Explore tests in this class:

```
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace TestProject
{
    [TestClass]
    [TestCategory("L3")]
    public class BasicUnitTest : UnitTestBase
    {
        public override int TypeCount => 3;
    }
    
    [TestClass]
    [TestCategory("L3")]
    public class ExtendedUnitTest : UnitTestBase
    {
        public override int TypeCount => 8;
    }

    [TestClass]
    [TestCategory("L3")]
    public class UnitTestBase
    {
        public virtual int TypeCount => 5;

        [DataRow(1)]
        [DataRow(2)]
        [DataTestMethod]
        public void DocumentCostCurrentDataFunctions(int count)
        {
            Assert.IsTrue(count < TypeCount);
        }
    }
}

```
## Expected behavior

Expected grouping (achieved with MSTest.TestAdapter 2.2.x):
![image](https://user-images.githubusercontent.com/22144797/232417595-86831a5f-cae1-41b6-8cb6-98f442c15a65.png)

## Actual behavior

Wrong grouping:
![image](https://user-images.githubusercontent.com/22144797/232417126-dfad8209-df9e-4972-87c8-94cce83c8435.png)

## Additional context

We also run tests in Azure DevOps wth `vstest.console.exe  "C:\abc.dll" /TestCaseFilter:"TestCategory=L3" "/logger:trx;LogFileName=C:\abc.trx" /TestAdapterPath:"C:\UnitTests\Tests"` command. The test report file has changed after the libraries update.

[AB#1813781](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1813781)

**Comment by Evangelink** [comment]
Hi @HightowerCZ,

Thanks for reporting this bug. I can also reproduce the issue, we will need to investigate to understand what changed.

As for the report file being changed, are you talking about the change of ID or are you referring to something else?

**Comment by HightowerCZ** [comment]
Hi @Evangelink,

We have two issues. One is showing in Visual Studio; the second is with trx reporting file. I am including the correct report and the incorrect report. It is difficult to find which test failed since the name of the test is the same for all runs.
[TestResults.zip](https://github.com/microsoft/testfx/files/11248716/TestResults.zip)

We noticed the issue because we are upgrading our solution from .Net Framework 4.8 to .NET 7.0.

Newest findings:
- vstest.console.exe produce grouped results only for MSTest.Adapter 2.2.3, but this version shows tests in VisualStudio incorrectly
- vstest.console.exe in different versions of MSTest.Adapter than 2.2.3 shows mostly correctly in VisualStudio, but produce the ungrouped report

Is this what you asked for?

**Comment by Evangelink** [comment]
Hi @HightowerCZ,

I am waiting for a little more info about the change of behaviour in VS because it's not yet fully clear if this is coming from a change caused by MSTest or VS Test Explorer. I will let you know more when I have some news.

Regarding the change in the trx, this is not linked to traits grouping but linked to a change of behavior (breaking change) that was introduced in 2.2.4. This is unfortunate but sadly we cannot easily change this on our side because we need to synchronize with Azure DevOps team to ensure the UI will reflect the change. To get more information about this change, I encourage you to refer to https://github.com/microsoft/testfx/issues/1024.

**Comment by Evangelink** [comment]
In MSTest v3+ we have started using some new features from newer versions of Test Platform and one of them is causing this change of display in VS. The Test Explorer team (cc @peterwald) told me that if you update your grouping to be "Traits" + "Class" you will have an output similar to the previous one:

![image](https://user-images.githubusercontent.com/11340282/235626120-6e7b1c18-1fe4-4bf2-851a-5ada64133004.png)

I will update the release notes to specify that change of behaviour and this "workaround".

I hope this new display is convenient enough for you?!
