### ISSUE TITLE
Make discovering test methods from base classes defined in another assembly the default.

### ISSUE THREAD

**Issue by AbhitejJohn** [Microsoft/testfx#164]
> Pulled out from #23.

## Description
We plugged in this support in the `1.1.17` version of the packages as part of #23. This should however be the default workflow even though this is a difference in behavior from MSTest V1. This should however be documented though.

**Comment by AbhitejJohn** [comment]
From @AbhitejJohn
> Here are the top level discovery numbers I got from VS for a solution with 9 projects each having 10 test classes each with 100 tests:

>With the config enabled: 4.67 s. (average of 5 runs)
Without the config enabled: 4.76 s. (average of 5 runs)

>This is on a 16 Gb, 2 core machine.

>Although the numbers should ideally be reversed based on our theory above, the point is that this does not affect performance and can be turned on by default.

**Comment by AbhitejJohn** [comment]
This is currently blocked by #163.

**Comment by MikeChristensen** [comment]
Just checking on this one - We'd really love to see this get done!  Any estimate on when this will be fixed?

**Comment by AbhitejJohn** [comment]
@MikeChristensen : This feature is already available in version 1.1.18 of the Framework/Adapter tuple. Its just not the default. You can turn it on by passing in the following runsettings:
```
<RunSettings>    
  <MSTest> 
    <EnableBaseClassTestMethodsFromOtherAssemblies>true</EnableBaseClassTestMethodsFromOtherAssemblies> 
  </MSTest> 
</RunSettings>
```

**Comment by MikeChristensen** [comment]
I'm aware of this.  I'm asking when it will be turned on by default, without needing a runsettings file.

**Comment by AbhitejJohn** [comment]
That is scheduled for the next release - End of next week is when we are hoping to get this through.
