### ISSUE TITLE
DataRow: Nulls and empty string are displayed as no data in display name

### ISSUE THREAD

**Issue by Evangelink** [microsoft/testfx#1647]
## Describe the bug

The display name of MSTest DataRow elements doesn't display well nulls.

## Steps To Reproduce

```csharp
[DataRow("", "", false)]
[DataRow(null, null, false)]
public void M1(string s1, string s2, bool b)
{
}
```

## Expected behavior

Should be displayed as

```
M1 ("","",false)
M1 (null,null,false)
```

## Actual behavior

Will be displayed as

```
M1 (,,false)
M1 (,,false)
```

## Additional context

The empty string should also probably be improved to display `""` instead of empty.

**Comment by Evangelink** [comment]
This can be a breaking change for people using the ID generation with display mode (although it is deprecated it's still in place so we will do th breaking change in v4).

**Comment by nohwnd** [comment]
If we are breaking this, I would like to something along the type serialization providers.

```
namespace mstest2;

[TestClass]
public class UnitTest1
{
    [TestMethod]
    [DataRow("a", 'b', "null", null, "", new string[0], new string []{"a","b" })]
    public void TestMethod1(object a, object b, object c, object d, object e)
    {
    }
}
```

Will output `TestMethod1 (a,b,null,,,System.String[],System.String[])`. 

I would much rather see something like `TestMethod1 ("a", 'b', "null", null, "", System.String[], System.String["a", "b"])`. This would also help IDataSource, where you have to serialize the data "from scratch" in every new provider, and you cannot easily leave the parameter serialization up to the framework and only provide your own new name for the test.

**Comment by Kissaki** [comment]
The change was mentioned to be a breaking change, so I assume this ticket should be linked to from #1285?

**Comment by Evangelink** [comment]
With the change done in #3053 we can avoid the breaking change and easily fix this ticket. @Kissaki would you like to give it a go? Or maybe @MichelZ?

**Comment by Evangelink** [comment]
I have merged your other PR so you can rebase! If you want to also handle `string` (by surrounding with `"`) and `char` (by surround with `'`) that's awesome. Otherwise we can do another ticket/PR.
