### ISSUE TITLE
LogMessage System.FormatException

### ISSUE THREAD

**Issue by DisparueStrix** [microsoft/testfx#1687]
## Describe the bug

Logger.LogMessage throws a System.FormatException for strings with curly braces, this is problematic for records that have curly braces. While one could use Console.WriteLine, if one if making use of other Logger features such as Logger.OnLogMessage or code is heavy with Logger.LogMessage, it may not be as simple to use Console.WriteLine.

## Steps To Reproduce

```
    public record StringRecord(int A, int B);

    [TestClass]
    public class StringRecordTests
    {
        [TestMethod]
        public void StringRecordTestMethod()
        {
            var obj = new StringRecord(10, 11);

            Logger.LogMessage(obj.ToString()); // Causes System.FormatException

            Console.WriteLine(obj); // This will work but code heavy with Logger use cant just change
            Logger.LogMessage("{0}", obj.ToString()); // This will work but is ugly
        }
    }
```

## Expected behavior

Test Passed!
Output: _StringRecord { A = 10, B = 11 }_

## Actual behavior

Test Failed!
Output: _Test method Scrutiny.StringRecordTests.StringRecordTestMethod threw exception: 
System.FormatException: Input string was not in a correct format._

## Additional context

net6.0
"Microsoft.NET.Test.Sdk" Version="17.4.1"
"Microsoft.Windows.Compatibility" Version="7.0.0"
"MSTest.TestAdapter" Version="3.0.2"
"MSTest.TestFramework" Version="3.0.2"

Regards

**Comment by engyebrahim** [comment]
Hi @DisparueStrix !

thanks for taking the time to add the issue.

I confirm the issue and I think we add skipping for the curly braces inside `LogMessage` function.

**Comment by Evangelink** [comment]
@engyebrahim I believe that the right fix here is to add an overload without params where we would not consider the string to be a format string. We should not start parsing/escaping the string ourselves.
