### ISSUE TITLE
Pass/fail icons get big

### ISSUE THREAD

**Issue by JVimes** [Microsoft/testfx#170]
## Description
Icons get big when strings contain newlines:

![image](https://cloud.githubusercontent.com/assets/6148201/25540093/12568816-2c07-11e7-9429-46fc813ee06c.png)

## Steps to reproduce

```c#
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Tests
{
    [TestClass]
    public class MainTests
    {
        [TestMethod]
        [DataRow("\r\n")]
        [DataRow("\r\n\r\n")]
        [DataRow("\r\n\r\n\r\n")]
        public void Test1(string token)
        {
            StringAssert.Contains("\r\n\r\n\r\n", token);
        }
    }
}
```

## Expected behavior
Icons remain the same size:

![image](https://cloud.githubusercontent.com/assets/6148201/25540244/9f2a2176-2c07-11e7-9df4-f675f272499a.png)

## Actual behavior
(Screenshot, top, above).

## Environment
Visual Studio 2017
MSTest.TestAdapter v1.1.17
MSTest.TestFramework v1.1.17

**Comment by AbhitejJohn** [comment]
Great catch. It looks like this has been the behavior for a while now. Since this is a Test Explorer accessibility issue, I'm moving this over to the vstest repo to track it better. https://github.com/Microsoft/vstest/issues/773
