### ISSUE TITLE
Release notes has duplicates

### ISSUE THREAD

**Issue by jnyrup** [microsoft/testfx#1722]
The release notes for 3.1.0 includes #1475 and #1477 both of which are also listed for v3.0.1
The two PRs are also listed in https://github.com/Microsoft/testfx/compare/v3.0.4...v3.1.0
I inspected all 3.y.z nugets and all 3.0.1+ packages contain the changes from #1477.

Not a bug report, but something in the release notes generation doesn't add up.

**Comment by Evangelink** [comment]
Thanks for the report @jnyrup! We will cleanup the release notes.

**Comment by Evangelink** [comment]
It seems that how we merged or cherry-picked fixes between v3.0.X and 3.1 confused git and our script. I have manually checked the entries.
