### ISSUE TITLE
Undocumented runsetting TreatDiscoveryWarningsAsErrors

### ISSUE THREAD

**Issue by BBreiden** [microsoft/testfx#1736]
The MSTestSettings class has a property TreatDiscoveryWarningsAsErrors which can be set using the MSTest node of the Runsettings file. However, this setting is not documented. Should the documentation be extended or is the setting not intended for public use?

**Comment by Evangelink** [comment]
Hi @BBreiden,

Thanks for raising this point! I forgot to update the documentation following the merge of [#1547](https://github.com/microsoft/testfx/pull/1547). Here is the link to the documentation page https://learn.microsoft.com/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-filemstest-element, would you be willing to update the doc?

**Comment by BBreiden** [comment]
I've opened a PR https://github.com/MicrosoftDocs/visualstudio-docs/pull/9607

**Comment by Evangelink** [comment]
Thank you for your contribution!
