### ISSUE TITLE
Using 3.1.1 and UWP

### ISSUE THREAD

**Issue by jnyrup** [microsoft/testfx#1741]
## Describe the bug

In FluentAssertions we have a test project [UWP.Specs](https://github.com/fluentassertions/fluentassertions/tree/develop/Tests/UWP.Specs) exercising running FluentAssertions with UWP with `<UseDotNetNativeToolchain>true</UseDotNetNativeToolchain>` enabled.

With 3.0.4 I can I can run the test `Determining_caller_identity_should_not_throw_for_native_programs` from the Visual Studio Test Explorer.
With 3.1.1 I get build time and runtime diagnostics:

Build time warning
```
1>C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages\microsoft.net.native.compiler\2.2.12-rel-31116-00\tools\Microsoft.NetNative.targets(809,5): warning : ILTransform : warning ILT0003: Method 'MSTestSettings.ValidateSettings(IMessageLogger)' will always throw an exception due to the missing method 'MSTestSettingsProvider.get_Settings()' in assembly 'Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices'. There may have been a missing assembly, or a dependency on a more recent Windows SDK release.
```

Runtime error
```
[Error] An exception occurred while test discoverer 'MSTestDiscoverer' was loading tests. Exception: Method 'MSTestSettingsProvider.get_Settings()' from assembly 'Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices' was not included in compilation, but was referenced in MSTestSettings.ValidateSettings(IMessageLogger). There may have been a missing assembly, or a dependency on a more recent Windows SDK release.
```

## Steps To Reproduce

1. Checkout https://github.com/fluentassertions/fluentassertions
2. Change to release mode
2. Right click on `UWP.Specs` and select build (it's excluded from the configuration manager)
2. See that `Determining_caller_identity_should_not_throw_for_native_programs` succeeds
2. Edit `Tests\UWP.Specs\UWP.Specs.csproj` to use 3.1.1
3. Build `UWP.Specs` again
4. See that `Determining_caller_identity_should_not_throw_for_native_programs` no longer runs.

## Expected behavior
`Determining_caller_identity_should_not_throw_for_native_programs` should be executable

## Actual behavior
Cannot execute `Determining_caller_identity_should_not_throw_for_native_programs`

## Additional context

I tried to dig into this and it looks like this addition to `MSTest.TestAdapter` from #1669
https://github.com/microsoft/testfx/blob/1223683d9b4ee9e2dd784f8315b45a50698281a0/src/Adapter/MSTest.TestAdapter/MSTestSettings.cs#L466-L469

tries to reference code from `MSTestAdapter.PlatformServices` which is excluded for the UWP target.
https://github.com/microsoft/testfx/blob/1223683d9b4ee9e2dd784f8315b45a50698281a0/src/Adapter/MSTestAdapter.PlatformServices/Services/SettingsProvider.cs#L17-L43

**Comment by Evangelink** [comment]
Please @engyebrahim have a look at this issue.

**Comment by juanmalm** [comment]
Same issue here

**Comment by Evangelink** [comment]
Hi @jnyrup! Sorry for the delay, I will be investigating the issue.
