### ISSUE TITLE
What causes multiple tests with the same testId

### ISSUE THREAD

**Issue by samholder** [microsoft/testfx#1744]
Hi.

I am trying to merge multiple trx files from multiple test runs into a single run, by replacing the tests that fail on a first run with the successful test result in a second run. I have been using another project for this, https://github.com/ricardofslp/dotnet-trx-merge. However on some projects when I run the tests I get multiple tests which have the same id. The project uses testId to manage the replacement during the merge, and this causes my trx merges to fail. I am trying to fix this issue and was trying to create an MVP to reproduce the issue so I would have example trx files to use for the tests I wanted to write.

In my 'real' project I am using `DataTestMethod` on my tests and attributes which implement `ITestDataSource` and provide the test data. Each attribute returns a unique name. When I run the tests I get the same test id for all the tests that execute because of that method. 

![image](https://github.com/microsoft/testfx/assets/2073290/07e1e22d-91de-428d-b827-5dec33014ce5)

In my MVP I cannot get the same id unless I return the same name from the `ITestDataSource`.

What determines if a test can get the same id? Is this valid, or is there something wrong in my 'real' project? How can I find out what that is? if it is valid, how can I reproduce it consistently?

Thanks!

**Comment by Evangelink** [comment]
I am not sure exactly about the TRX, I will double check tomorrow. For the ID used within MSTest (assuming it's being reused), it depends on the version of MSTest you are using (and if on v3 the strategy you are using https://github.com/microsoft/testfx/issues/1286).
