### ISSUE TITLE
Possibility to treat missing dynamic data as warning?

### ISSUE THREAD

**Issue by fx999dev** [microsoft/testfx#1748]
Hello,

we dynamically get our data for our unit test from different databases. Sometimes there is no data for specific cases on specific databases. This is not a bug and intended. However these tests do not run because of missing data. This is expected.
The following message is displayed:

> Property or method TestData on XyViewModelTests returns empty  IEnumerable<object[]>

 But these tests are then marked as failed --- is there a possibility to treat such cases (when there is not data) as warning?

Thank you!

[AB#2046260](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/2046260)

**Comment by engyebrahim** [comment]
Hi @fx999dev,
thanks for the suggestion!
is it gonna be okay if marked as failed and attached a warning with the output?
or you suggested to mark it as ignored with the output with the reason of no driven data received?

**Comment by Evangelink** [comment]
We will add a runsettings MSTest entry that will allow to consider this case as a single test returning "inconclusive" result.
