### ISSUE TITLE
Records with default constructor not shown as single tests

### ISSUE THREAD

**Issue by wondering639** [microsoft/testfx#1767]
## Describe the bug

I would expect this to create three single entries in the Test Explorer, but it does not (-> you can not repeat a single test, only all three):
```
public record CustomRecord(
    decimal Number, 
    string Comment
);

public static IEnumerable<object[]> RecordTestData
{
    get
    {
        yield return new object[] {
            new CustomRecord(1m, "first")
        };

        yield return new object[] {
            new CustomRecord(2m, "second")

        };

        yield return new object[] {
            new CustomRecord(3m, "third")
        };
    }
}

[TestMethod]
[DynamicData(nameof(RecordTestData))]
public void TestWithRecordTestData(CustomRecord item)
{
    Console.WriteLine($"item number is {item.Number} entries");
}
```
In this case, no "subentries" are created in the Test Explorer (you can see that as the triangle on the left side is not there):
![image](https://github.com/microsoft/testfx/assets/25722498/21787526-8c88-4dfe-b538-7c56f6373ce3)

However it works when using 
```
public record CustomRecord
{
    public decimal Number;
    public string Comment = "";
}
```
instead of
```
// I call this record constructor variant
public record CustomRecord(
    decimal Number, 
    string Comment
);
```
See how we suddenly have three single entries in the Test Explorer:
![image](https://github.com/microsoft/testfx/assets/25722498/72e3fe92-b1fe-43e7-9d41-2868157d2443)

## Steps To Reproduce
see bug description

## Expected behavior
- all tests shown as single entries
- both record "variants" (constructor and property "variant") should yield the same output in Test Explorer

## Actual behavior
all tests shown as one entry when using record constructor variant

**Comment by Evangelink** [comment]
Hi @wondering639,

This issue is related to #1462. MSTest is currently relying on datacontract serializer as a way to discriminate entries. Because of that some data types are not "supported". We know how painful this is but we are really limited by the design of vstest in fixing this issue.
