### ISSUE TITLE
Assert.IsInstanceOf passes on value null

### ISSUE THREAD

**Issue by LarsCelie** [Microsoft/testfx#178]
## Description
> Assert.IsInstanceOfType succeeds when value is null, while the MSDN specifies it should throw an error.
> AssertFailedException : 'value is null or expectedType is not found in the inheritance hierarchy of value.'
> https://msdn.microsoft.com/en-us/library/ms243733.aspx

## Steps to reproduce
> Create a standard .net core test project from visual studio 2017, and create a dummy class. then use the following method:
> `public void TestMethod1()
        {
            Assert.IsInstanceOfType(null, typeof(Dummy));
        }`

## Expected behavior
> The test should throw AssertFailedException and fail

## Actual behavior
> The test passes

## Environment
> Windows Server 2016,
> MSTest.Framework version 1.1.11 and 1.1.17
> MSTest.TestAdapter version 1.1.11 and 1.1.17

**Comment by LarsCelie** [comment]
When i checked out testfx, i was able to reproduce this as well.
`        [TestMethod]
        public void InstanceOfTypeShouldFailWhenValueIsNull()
        {
            // Assert.IsInstanceOfType(null, typeof(AssertTests));
            FrameworkV2::Microsoft.VisualStudio.TestTools.UnitTesting.Assert.IsInstanceOfType(null, typeof(AssertTests));
        }`

the commented out line would fail if ran, and the frameworkv2 version will succeed.

**Comment by AbhitejJohn** [comment]
Thanks @LarsCelie for filing this. It looks like we are missing a check [here](https://github.com/Microsoft/testfx/blob/master/src/TestFramework/MSTest.Core/Assertions/Assert.cs#L1659). Marked this as an up-for-grabs issue - its a small change.

**Comment by LarsCelie** [comment]
You can assign me as well, trying to fix it.

**Comment by AbhitejJohn** [comment]
Great. Thanks @LarsCelie .

**Comment by LarsCelie** [comment]
@AbhitejJohn Pull Request is up.

**Comment by AbhitejJohn** [comment]
Thanks a bunch @LarsCelie . Had a few small comments. Will merge it soon after.

**Comment by AbhitejJohn** [comment]
Merged. Thanks.
