### ISSUE TITLE
Console.Writeline in a TestMethod are not available in test output for .net core

### ISSUE THREAD

**Issue by codito** [Microsoft/testfx#18]
## Description

Console.WriteLine in a test method should be available in output.
## Steps to reproduce
1. Create a new test project
2. Add a test method
3. Add `Console.WriteLine("foo")` in test method
## Expected behavior

A output link should appear in test explorer summary
## Actual behavior

Output link is not shown.
## Environment

VS: WPT/25810.00
VSTest: as of ce0eac2

Copied from https://github.com/Microsoft/vstest/issues/132

**Comment by AbhitejJohn** [comment]
This is active work in progress.
