### ISSUE TITLE
dotnet test --logger "trx" missing categories

### ISSUE THREAD

**Issue by antferreira** [Microsoft/testfx#181]
## Description
.trx file generated by dotnet test don't have test categories information

## Steps to reproduce
Create a test project with test methods annotated with [TestCategory("foo")].
Run dotnet test --logger "trx"

## Expected behavior
.trx file with test categories information 

## Actual behavior
.trx file without test categories information

## Environment
Windows 10 Pro 1607
MSTest.TestAdapter 1.1.17
MSTest.TestFramework 1.1.17
dotnet version 1.0.4

**Comment by AbhitejJohn** [comment]
Thanks for filing this @antferreira . Copied this over to https://github.com/Microsoft/vstest/issues/805.
