### ISSUE TITLE
Enable MSTest framework based tests targeting .NET Core to be run and debugged from within VSCode

### ISSUE THREAD

**Issue by pvlakshm** [Microsoft/testfx#182]
As of C# for Visual Studio Code extension: 1.9.0, only xUnit and NUnit based tests targeting .NET Core can be run and debugged from within VSCode.
This issue tracks the addition of MSTest support.

linked: [omnisharp-vscode #1482](https://github.com/OmniSharp/omnisharp-vscode/issues/1482)

**Comment by pvlakshm** [comment]
[omnisharp-vscode #1482](https://github.com/OmniSharp/omnisharp-vscode/issues/1482)

**Comment by AbhitejJohn** [comment]
This has been fixed in https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.10.0-beta3.
