### ISSUE TITLE
Running multiple .net core VS2017 unit tests in TFS2015 build

### ISSUE THREAD

**Issue by mailbala** [Microsoft/testfx#185]
## Description
I need a suggestion. 

I have an asp.net core web api targeting net462 and  2 netstandard class libraries targeting netstandard1.4. There are corresponding .net core unit test projects for those class libraries targeting netcoreapp1.1. 

I have build definition in TFS2015. I want to run those unit tests and publish those test results as a build task.

Please suggest how can i achieve this?. 

Currently I am just running dotnet test using multiple command tasks for each test projects. creating .trx logger for each test projects.

VS2017 is not installed in the build agents.
I am using .NET core SDK 1.0.4.

**Comment by AbhitejJohn** [comment]
unfortunately there isn't a better way of doing this today AFAIK. I believe there would be a dotnet task to achieve a test and publish in the near future.

Tagging @acesiddhu on this.

**Comment by AbhitejJohn** [comment]
Here is an interesting thread though: https://github.com/Microsoft/vsts-tasks/issues/2126

**Comment by AbhitejJohn** [comment]
This experience isn't the best in the CI scenarios as of now. This is however in the backlog is what I'm hearing. 
Closing this issue here. Please either file a new one at https://github.com/Microsoft/vsts-tasks/issues or report on the thread I referred above to understand the timeline.

**Comment by mailbala** [comment]
Thanks @AbhitejJohn. The suggestion in that thread was really helpful.
