### ISSUE TITLE
Test methods with UITestMethod attribute are not discovered.

### ISSUE THREAD

**Issue by bmourat** [Microsoft/testfx#186]
## Description
Issue is the same as described [here](https://github.com/Microsoft/testfx/issues/76), but it appears with current version too (1.1.17)

## Steps to reproduce
1. Create a new UWP test project.
2. Build. Notice that TestMethod1 shows up in the Test Explorer.
3. Change [TestMethod] to [UITestMethod] on TestMethod1.
4. Build.

## Expected behavior
TestMethod1 still appears in Test Explorer.

## Actual behavior
It disappears.

## Environment
VS Enterprise 2017
MSTest.TestAdapter - 1.1.17
MSTest.TestFramework - 1.1.17

**Comment by AbhitejJohn** [comment]
@bmourat : I cannot repro this. Can you turn on the following diagnostic logs and share them here please: 
1. Assuming you aren't on the latest preview, set a system wide environment variable `VS_UTE_Diagnostics` to '1'. Logs would show up in Output -> Tests pane in VS.
2. Set `TPTrace` to `4` in %ProgramFilesx86%\Microsoft Visual Studio\2017\Enterprise\Comon7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.discoveryengine*.exe.config. Logs for this would go to %temp%.

**Comment by bmourat** [comment]
Sorry for this one, seems like it was some visual studio related behaviour.
