### ISSUE TITLE
Adapter is not sending TestCategory traits in testcase object to testhost.

### ISSUE THREAD

**Issue by Faizan2304** [Microsoft/testfx#189]
> From @antferreira 

## Description
.trx file generated by dotnet test don't have test categories information

## Steps to reproduce
Create a test project with test methods annotated with [TestCategory("foo")].
Run dotnet test --logger "trx"

## Expected behavior
.trx file with test categories information 

## Actual behavior
.trx file without test categories information

## Environment
Windows 10 Pro 1607
MSTest.TestAdapter 1.1.17
MSTest.TestFramework 1.1.17
dotnet version 1.0.4

**Comment by AbhitejJohn** [comment]
This is working in VS IDE. Strange it isn't in trx. The adapter does not differentiate these two scenarios. Need to investigate this one.

**Comment by jayaranigarg** [comment]
Platform searches for TestProperty in list of properties by Id. This Id has changed for MSTestV2. That is the reason neither TPV1 nor TPV2 are able to find TestCategory properties.
Changes need to be made in [this](https://github.com/Microsoft/vstest/blob/05027bdfa0f09914b42b3555285458e882071a9f/src/Microsoft.TestPlatform.Extensions.TrxLogger/Utility/Converter.cs#L112) part of code s.t. it does not check for any hard-coded  category ID.

**Comment by codito** [comment]
@jayaranigarg any idea why the id was changed for MSTestv2? Just curious..

**Comment by AbhitejJohn** [comment]
@codito: Ah that was just to be consistent with the executor uri which has the v2 in it.
