### ISSUE TITLE
The test adapter nuget should have a dependency on the framework

### ISSUE THREAD

**Issue by AbhitejJohn** [Microsoft/testfx#192]
## Description
MSTest.TestAdapter depends on MSTest.TestFramework internally but does not call out an explicit dependency in the nuspec. This is causing version mismatch issues and confusion as to which version goes with which. This issue tracks linking these two nugets together.

Should reduce number of instances of #177 happening.

**Comment by pvlakshm** [comment]
Closing this as it is already being tracked here: #193.
