### ISSUE TITLE
MSTest meta package

### ISSUE THREAD

**Issue by codito** [Microsoft/testfx#193]
## Description
Should both framework and adapter be part of a meta package? Say `mstest`.

It will reduce number of dependencies a developer has to manage. Plus, we can introduce newer functionality by including additional packages in the metapackage. E.g. `AssertExtensions` or may be an analyzer in future to catch [authoring](https://github.com/Microsoft/testfx/search?utf8=%E2%9C%93&q=UTA007&type=) issues at build time.

**Comment by codito** [comment]
Possibly related #192.

**Comment by jayaranigarg** [comment]
Closing this issue. Will be picked up as part of CPS work. Please follow/upvote https://github.com/Microsoft/testfx/issues/606 for tracking progress on this issue.
