### ISSUE TITLE
Tests fail sometimes when multiple in-compatible test adapter versions are used in a solution

### ISSUE THREAD

**Issue by AbhitejJohn** [Microsoft/testfx#194]
## Description
The way test adapters are picked up in VS IDE today is at a solution level. So if there is a project P1 referring to 1.1.11 version of MSTest.TestAdapter and another project P2 referring to 1.1.18 version in the same solution - it picks up one of them randomly and uses that to run tests for both P1 and P2. This ends up causing tests in one of them to not run.

Here is the problem: Lets say 1.1.11 is picked up and we are running tests for P2. We create an app domain to host the test dll output from P2 and set the AppBase for it to the out directory(bin/debug). Now we also copy the adapter assemblies to the out directory for multiple reasons. So when the adapter is loaded in the new app domain, it loads the one in the out directory(because AppBase is set here and this is loaded in the Default Context) which is of version 1.1.18. So, If there is change in internal types b/w these two versions and if we use these types for communication across the app domains - (say) we add a new ctor or remove the default one then this would result in a mismatch and we bail out and don't run the tests. 

Workaround:
The obvious workaround for this is to move all test projects in a solution to refer the same version of the adapter.

Possible fixes:
1. The Test Explorer logic could change to start picking up adapters from the out directory of each project - thereby making each adapter isolated to a single project.

Even if we do not fix this holistically we should at least add a warning to let folks know that only one of the adapters is being picked up.

Thoughts/Suggestions?
/cc @codito @jayaranigarg @harshjain2

**Comment by singhsarab** [comment]
With the fix in the Test Platform to pick up the highest versioned adapter, we don't have the problem of random pick of the dll, it is 
The logic to pick up the adapter loaded inside the new app domain, lies with the adapter, and that should be handled by the adapter. 

Just a note on the current behavior: If the adapter is not present in the output directory, the same adapter selected by testplatform gets loaded in the new app domain.

**Comment by jayaranigarg** [comment]
Closing this as duplicate issue. Please follow https://github.com/Microsoft/testfx/issues/384 for updates on this issue.
