### ISSUE TITLE
Can't get EnableMSTestRunner to work

### ISSUE THREAD

**Issue by jpribele** [microsoft/testfx#1949]
Trying to follow these instructions but not having any luck
https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-mstest-runner-intro?tabs=dotnetcli

That documentation appears to reference nuget package that does not exist.

Searching through the codebase I see EnableMSTestRunner  but nothing I have tried works in practice. Launching a MSTest project from VisualStudio always runs dotnet.exe

**Comment by Evangelink** [comment]
Hey @jpribele,

We were supposed to released the preview version on NuGet on Friday but we found some issues and delayed releasing. I didn't wanted to rollback doc as I wasn't expecting people to read it.

I hope we have it all sorted today, I'll keep you posted.

We would be more than happy to get your feedback when you try out the new feature.

**Comment by Evangelink** [comment]
Just a simple message to let you know we are still working on having the preview release available. We noticed some flows in User Experience and in some advanced scenario that we are fixing now.

**Comment by Evangelink** [comment]
Tests are good but we are still waiting for the prefix reservation validation from NuGet team!

**Comment by Evangelink** [comment]
Hi @jpribele, the packages are now available on nuget.org, please see https://github.com/microsoft/testfx/blob/main/docs/Changelog.md#320-preview236221---2023-12-22

**Comment by jpribele** [comment]
Fantastic. F5 worked on a simple test project. 
The documentation though need to be updated with correct version numbers

**Comment by Evangelink** [comment]
I'll take care of updating the doc during the weekend but I'm not sure if doc team will have some bandwidth to approve and merge it.
