### ISSUE TITLE
Not all annotations on a test method show up in the trx file.

### ISSUE THREAD

**Issue by pvlakshm** [Microsoft/testfx#202]
Not all annotations on a test method show up in the trx file.
For example the ```SmokeTest``` annotation from here ([#201](https://github.com/Microsoft/testfx/issues/201)) does not show up in the trx file.

Can all annotations be emitted to the trx file without it being a breaking change (note that the trx is consumed downstream in VSTS for test reporting)?
If not we will want to write our own logger (using logger extensibility) and emit the annotations as appropriate.

**Comment by AbhitejJohn** [comment]
Moved this to https://github.com/Microsoft/vstest/issues/914.
