### ISSUE TITLE
Add support for injecting `TestContext` in ctor

### ISSUE THREAD

**Issue by Evangelink** [microsoft/testfx#2039]
## Summary

Allow to inject `TestContext` object in ctor of the test class as alternate design.

## Background and Motivation

To be able to access the `TestContext` object, we currently need to declare a property of type `TestContext` which gets injected by MSTest. When enabling `nullable` on the project, we start getting many warnings about the fact this property could be null because it's not assigned any non-null value in all path. Although this is a FP, there is no way for the compiler to know that this will be injected at runtime. 

A better pattern for this would be to be able to retrieve the `TestContext` object from the ctor and have the property readonly (or have a field) which would eliminate this nullability issue. 

This is also preventing to change the `TestContext` value as it should not be set by user.

## Proposed Feature

The user should be able to have a single parameter of type `TestContext` in the ctor of his/her test class.

## Alternative Designs

Keep current design and either:

- assign `null!` (e.g. `public TestContext TestContext { get; set; } = null!`)

- disable nullable for the tests

**Comment by avivanoff** [comment]
This would be a welcome addition.

**Comment by Duranom** [comment]
Really want this, it is very annoying you either have to use ClassInitialize or the property to have it added.
The constructor to test and then dispose(async) is really a nicer preference as it keeps also in line of how the rest of the code base is, instead of strange hooks.

Would even be a prelude for dependency injection for unit tests, where you at the class level you define a class/container through generic attribute which will register services and those are then used for injection to ctor/method, but that is getting ahead of a desire to reduce common stub/fakes/mocks retrieval.

**Comment by Evangelink** [comment]
> Really want this, it is very annoying you either have to use ClassInitialize or the property to have it added.

Please don't store the `TestContext` object from the `ClassInitialize` as it's not updated with instance test info. We have added an analyzer for that.

**Comment by Duranom** [comment]
> > Really want this, it is very annoying you either have to use ClassInitialize or the property to have it added.
> 
> Please don't store the `TestContext` object from the `ClassInitialize` as it's not updated with instance test info. We have added an analyzer for that.

Apologies on that part then of my statement, but the out of place feeling remains cause when need for the TestContext you will need initialization code in a TestInitializeAttributed method and the constructor, or go with a TestInitializeAttributed method only and none of the fields decorated with readonly or NRT defined (or rather heavily = null! polluted).

**Comment by avivanoff** [comment]
@Evangelink, is there a beta NuGet package to try it out?

**Comment by Evangelink** [comment]
> @Evangelink, is there a beta NuGet package to try it out?

You can test it out using our [AzDO feed](see https://github.com/microsoft/testfx/blob/main/docs/preview.md) and use any version greater or equal to `3.6.0-preview.24366.13`

**Comment by avivanoff** [comment]
> You can test it out using our [AzDO feed](https://github.com/microsoft/testfx/blob/main/docs/preview.md) and use any version greater or equal to `3.6.0-preview.24366.13`

Tested in a few of our internal projects, no issues found.

**Comment by Evangelink** [comment]
Thanks for letting us know @avivanoff
