### ISSUE TITLE
Warnings are not shown in console in runner mode

### ISSUE THREAD

**Issue by MarcoRossignoli** [microsoft/testfx#2062]
During the discovery we collect warnings to explain to the users if something is not good. 
Warning can lead to a test session failure for instance for zero tests ran, but without the console output is hard to understand what's wrong.

Here looks like we send the warning to the logger inside the bridge but we don't send it to the display output https://github.com/microsoft/testfx/blob/main/src/Adapter/MSTest.TestAdapter/Discovery/UnitTestDiscoverer.cs#L73

cc: @Evangelink

**Comment by Evangelink** [comment]
This should be fixed on next insertion. I'll try to add an integration test when it gets inserted.

**Comment by Evangelink** [comment]
Closed by #2070
