### ISSUE TITLE
MSTEST0002 and AssemblyInitialize/AssemblyCleanup

### ISSUE THREAD

**Issue by avivanoff** [microsoft/testfx#2161]
There is one case where [MSTEST0002: Test classes should have valid layout](https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-mstest-analyzers-MSTEST0002):
```
[TestClass]
public static class TestSetup
{
    [AssemblyInitialize]
    public static void Initialize(TestContext testContext)
    {
        ...
    }
}
```
MSTEST0002 is fired because TestSetup class is static.

[AB#1948288](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1948288)

**Comment by Evangelink** [comment]
Oh! Thanks! That's indeed some false-positive.

Could you confirm that in your setup you don't have any test in the same class?

**Comment by avivanoff** [comment]
No. This is our actual code with implementation of Initilize method stripped out.

**Comment by avivanoff** [comment]
@Evangelink, any ETA on 3.2.1?

**Comment by Evangelink** [comment]
@avivanoff we just released 3.2.1!

**Comment by avivanoff** [comment]
Verified, the issue is fixed. Thank you.

**Comment by Evangelink** [comment]
Awesome! Looking forward for your feedback on V3.3
