### ISSUE TITLE
Add mapping for TestOutcome.None to the UnitTestOutcome enum to achieve NotExecuted behaviour in VSTS. 

### ISSUE THREAD

**Issue by irguzhav** [Microsoft/testfx#217]
## Description
> There is no way to create a custom TestMethodAttribute which will return the Not Executed state for the test. With what is available today one can only get Passed/Failed/Skipped. We want to closely monitor amount of Ignored tests as they “pollute” the codebase. So if we use the Skipped(Inconclusive) outcome we won’t be able to distinguish the Ignored tests from the tests which were not supposed to run based on the custom attribute.

**Comment by AbhitejJohn** [comment]
More details from an offline conversation:
To achieve a Not Executed  state however we would need to update the mapping [here](https://github.com/Microsoft/testfx/blob/a0cfbcffe9f292064bf57d784eae9e2bc3ea2103/src/Adapter/MSTest.CoreAdapter/Extensions/TestResultExtensions.cs#L49) and [here](https://github.com/Microsoft/testfx/blob/abd5ea3585657914490c83d5d2b4c9e732640a89/src/Adapter/MSTest.CoreAdapter/Helpers/UnitTestOutcomeHelper.cs#L26) to get it to eventually return TestOutcome.None which would map to Not Executed in VSTS.
