### ISSUE TITLE
Simplify `PerRequestServerDataConsumer`

### ISSUE THREAD

**Issue by MarcoRossignoli** [microsoft/testfx#2170]
Today in server mode we're trying to batch payloads per-call, we could do better and move the complexity close to the network channel and have a queue there where we can queue "all the in-progress" per call and move this class to a simply proxy.

https://github.com/microsoft/testfx/blob/main/src/Platform/Microsoft.Testing.Platform/ServerMode/PerRequestServerDataConsumerService.cs 

[AB#1950773](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1950773)

**Comment by Evangelink** [comment]
Pushed back to 3.4

**Comment by Evangelink** [comment]
Clearing milestone as there is no plan on improving server mode for now.
