### ISSUE TITLE
MSTest runner doesn't work with VS Code

### ISSUE THREAD

**Issue by Evangelink** [microsoft/testfx#2171]
## Describe the bug

According to some user, MSTest runner is not working with VS Code Test explorer. See https://devblogs.microsoft.com/dotnet/introducing-ms-test-runner/#comment-20327

**Comment by drognanar** [comment]
The latest prerelease v1.3.6, enables the new MSTestRunner protocol by default and it's then likely related to the https://github.com/microsoft/testfx/pull/2167 fix that was recently made.

The current workaround is to disable the new protocol, by creating a `.vscode/settings.json` file, with the following setting:

```json
{
    "dotnet.testWindow.useTestingPlatformProtocol": false
}
```

**Comment by drognanar** [comment]
MSTest 3.2.1 no longer has this issue
