### ISSUE TITLE
control output when using EnableMSTestRunner

### ISSUE THREAD

**Issue by jpribele** [microsoft/testfx#2172]
is there a way to change the output when using EnableMSTestRunner in your project? 
trx output or console logging that show the tests ran. 

one thing that would be nice it to log messages in the output. 
I often use a test for a quick way to test code but the Console.WriteLine don't show up or TestContext.WriteLines

**Comment by Evangelink** [comment]
There is an extension to generate TRX report.

For the other part of your question, it partially relates to #2162. This is the same reasoning behind why we don't display these messages in the console. As far the console.writeline messages, I'm not a big fan of current implementation. I believe that we should not capture Console.Write messages but instead rely only on TestContext writes.

All these being said, and as we said in the linked ticket, I think that it makes sense to provide an option to allow displaying that.
