### ISSUE TITLE
MSTest Runner not working with F5 in VS

### ISSUE THREAD

**Issue by WestDiscGolf** [microsoft/testfx#2214]
## Describe the bug

Just been reading about the new MSTest Runner - https://devblogs.microsoft.com/dotnet/introducing-ms-test-runner/ - and wanted to check it out. I cloned this repository and opened the sample project - https://github.com/microsoft/testfx/tree/main/samples/mstest-runner/Simple1

On making sure it was set as the startup project and pressing F5 I am presented with the following error:

![image](https://github.com/microsoft/testfx/assets/374343/9bb34f87-a831-4f52-8fac-35a9428ab424)

On looking at the project properties there is a warning about a dependency version warning:

![image](https://github.com/microsoft/testfx/assets/374343/738d313d-59cb-4e05-abde-32232d9589c6)

## Steps To Reproduce

1. Clone repo
2. Open Simple1 project
3. Run

## Expected behavior

Tests run as blog describes

## Actual behavior

Error message (see above) about AppInsights telemetry

## Additional context

Using Visual Studio 2022 Preview

![image](https://github.com/microsoft/testfx/assets/374343/3589e14c-8d69-476b-a489-b35ed90998f4)

**Comment by WestDiscGolf** [comment]
Tried upgrading to stable packages and that didn't work.

Tried removing the package reference to Microsoft.Testing.Extensions.CodeCoverage and it appears to now run.

**Comment by Evangelink** [comment]
@WestDiscGold, please use the stable version. I just checked and it's working fine.

**Comment by Evangelink** [comment]
I'll update the samples.

**Comment by WestDiscGolf** [comment]
Thanks @Evangelink :-)

**Comment by Evangelink** [comment]
Thanks for reporting the issue :) Samples are sometimes a curse, I forgot to ensure everything was still working!

**Comment by WestDiscGolf** [comment]
Just tried it and I get the following errors when pressing f5:

![image](https://github.com/microsoft/testfx/assets/374343/103f6580-148a-4697-987c-3ace1bfa4cc7)

Even though I have updated to the stable versions:

![image](https://github.com/microsoft/testfx/assets/374343/e4e935d7-55b5-478f-9486-c747f87592cf)

**Comment by Evangelink** [comment]
Ohhh! Could you try to clean and rebuild?

**Comment by Evangelink** [comment]
Can you build and execute from command line? I just tried to git clean and run from command line or VS and it's fine for me.

Command line:
![image](https://github.com/microsoft/testfx/assets/11340282/aef9775c-a0f1-4b8b-b291-e53d432d16fd)

VS F5:
![F5](https://github.com/microsoft/testfx/assets/11340282/300b68d2-f347-4771-824f-7c527fc33943)

**Comment by WestDiscGolf** [comment]
Hi, thanks for the feedback. I tried the way you did it and it got confused around .NET 9 (as only have it installed in my local .net repo clone, not globally). I then tried doing it specifically in the folder of the Simple1 sample and it still errored. Going a `git clean` as suggested and trying again does appear to have resolved it.

Closing issue. Thanks for the help 👍
