### ISSUE TITLE
Assert class has public constructor

### ISSUE THREAD

**Issue by MikeChristensen** [Microsoft/testfx#223]
## Description
It's very cool that Assert is no longer a static class, which allows us to add extension methods and access the singleton "Assert" instance using Assert.That.  However, is there a reason why the Assert constructor is public?  I'd expect private, or at least Internal.

## Steps to reproduce
var a = new Assert();

## Expected behavior
I'd expect this not to work.

## Actual behavior
Works.  But is there a reason why you would ever need/want to do this?

## Environment
Latest MSTestV2 on VS2015.

**Comment by AbhitejJohn** [comment]
Thanks for filing this @MikeChristensen . This should be private and sealed.

**Comment by AbhitejJohn** [comment]
Fixed.
