### ISSUE TITLE
Analyzer: TestCleanup should be valid

### ISSUE THREAD

**Issue by Evangelink** [microsoft/testfx#2234]
## Summary

Title: Test cleanup method should have valid layout
Category: Usage
Description: <to be defined based on all constraints>
Default severity: Warning

Please refer to `MSTEST0003: Test methods should have valid layout`.

[AB#1950779](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1950779)

**Comment by cvpoienaru** [comment]
Closed by this PR: https://github.com/microsoft/testfx/pull/2312
