### ISSUE TITLE
Analyzer: DynamicData should be valid

### ISSUE THREAD

**Issue by Evangelink** [microsoft/testfx#2237]
## Summary

Title: DynamicData should be valid
Category: Usage
Description: <to be defined based on all constraints>
Default severity: Warning

Please refer to `MSTEST0003: Test methods should have valid layout`.

Non exhaustive list of constraints:
- public (except if discover internals)
- static
- member should match kind declared on the attribute (property or method)
- member should exist
- member return type should be valid (`IEnumerable<object[]>` or `IEnumerable<(Value)Tuple<...>>`)
- if member is property it should be gettable
- if member is method, it should not have parameters

[AB#1950780](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1950780)

**Comment by nohwnd** [comment]
Would be perfect if this could compare the count and type of parameters when IEnumerable<Tuple> is used.

**Comment by Evangelink** [comment]
Thanks! I definitely missed these cases here but I described them in the global analyzers ticket.

**Comment by Evangelink** [comment]
@engyebrahim As discussed, postponing to milestone 3.4

**Comment by xcaptain** [comment]
I also have a issue with `DynamicData` in vscode test explorer. same cause here?

![image](https://github.com/microsoft/testfx/assets/4054836/5b50290b-ba16-49de-88a4-ec238a423285)

@Evangelink

**Comment by nohwnd** [comment]
Moved the above issue to a separate one. This is a work item to create the analyzer, not an issue report.
