### ISSUE TITLE
Custom Report Generator

### ISSUE THREAD

**Issue by ray440** [microsoft/testfx#2242]
Hi, I'm just looking for advice.

Excited to here about the new MSTest runner and I saw that it allows for custom report generators.  
What is the best way to do this?  Are there events for test discovery (suites, methods) and runtime checks (pass, fail, etc..)?

[AB#1950757](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1950757)

**Comment by Evangelink** [comment]
Hi @ray440,

> Excited to here about the new MSTest runner

Glad to hear :)

> I saw that it allows for custom report generators.

Out of curiosity, may I ask what kind of report you are trying to build? Just to see if it could be worth for us to provide it.

> What is the best way to do this? Are there events for test discovery (suites, methods) and runtime checks (pass, fail, etc..)?

Let me craft a few simple examples as it can be useful! We will iterate over it until there is something good enough for you to build something custom.

**Comment by Evangelink** [comment]
@ray440 please see #2246 and let me know if that's providing enough context and information.

**Comment by ray440** [comment]
That sounds great!

**Comment by Evangelink** [comment]
@ray440 if that's ok with you, I'll move the issue as fixed and close it.

**Comment by ray440** [comment]
> @ray440 if that's ok with you, I'll move the issue as fixed and close it.

Sure.

I'm struggling to get access to `VSTestProperty`.  They seem to be inaccessible or `internal`.

**Comment by Evangelink** [comment]
> I'm struggling to get access to VSTestProperty. They seem to be inaccessible or internal.

They are internal for now (I don't recall what was the reasoning but I will look it up tomorrow).

**Comment by ray440** [comment]
> They are internal for now (I don't recall what was the reasoning but I will look it up tomorrow).

I suspect there are reasons. In the meantime I think I can hack around it to get the info need.

**Comment by ray440** [comment]
> I would be really interested to get some details about what you are trying to achieve.

Oh it's a horrific hack!  😬 😨 

**_Temporarily_**... I'll just `ToString()` all the relevant properties and parse out the info.

**Comment by Evangelink** [comment]
> It might be helpful if MSTest had a way to emit custom TestNodeStateProperty messages..?

When you are talking about "emit custom `TestNodeStateProperty` messages, do you mean if MSTest was exposing an API (e.g. `TestContext` or something else) for users to send some states or do you talk only about the internal of MSTest? On the latter, that's already possible.

**Comment by Evangelink** [comment]
@ray440 I am moving this ticket as closed. Feel free to add more comments or open a new one if you have some other problem,
