### ISSUE TITLE
DataTestMethod display name is not applied

### ISSUE THREAD

**Issue by Evangelink** [microsoft/testfx#2245]
Hi @Evangelink Today I tested the new 3.2.0 package. The new constructor with displayname overload is there now, but unfortunately the display name seems to be ignored when the test is actually displayed.. 
Do I create a new issue for this or do you reopen this one? 

`````[TestClass]
public class MyTestClass
{
    [DataTestMethod("This is a data test method")]
    [DataRow("This_is_a_datarow1", DisplayName = "Row 1")]
    [DataRow("This_is_a_datarow2", DisplayName = "Row 2")]
    public void MyDataTestMethod(string input)
    {
        // test code
    }

    [TestMethod("This is a regular test method")]
    public void MyTestMethod()
    {
        // test code
    }
}
`````
![image](https://github.com/microsoft/testfx/assets/29945379/7f8d73b2-d095-43a5-96c7-bca9785bae5b)

_Originally posted by @HannoZ in https://github.com/microsoft/testfx/issues/2121#issuecomment-1923497818_
            

[AB#1950755](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1950755)

**Comment by Evangelink** [comment]
Closing this ticket as it actually duplicates #1635. This is a known issue that needs some breaking change to be fixed.

**Comment by HannoZ** [comment]
So today I learned that you don't actually need the DataTestMethod attribute for unit tests with DataRows because they also work with the regular TestMethod attribute!

**Comment by Evangelink** [comment]
Yeah I don't really know what's the history there. `[DataTestMethod]` doesn't seem to have any particular value :(
