### ISSUE TITLE
Appdomain.Unload occasionally ends up hanging the test run 

### ISSUE THREAD

**Issue by AbhitejJohn** [Microsoft/testfx#225]
## Description
We've seen instances where test code that isn't properly cleaned up, ends up hanging the finalizer thread when AppDomain.Unload gets called. From [msdn](https://msdn.microsoft.com/en-us/library/system.appdomain.unload(v=vs.110).aspx) an AD.Unload could take an indeterminate amount of time to return in cases like these. We should have some kind of a timeout for this operation so we do not hang forever which especially impacts CI runs.

## Environment
Latest version of the adapter.

**Comment by codito** [comment]
This issue needs to be fixed in MSTest v1 and v2.

**Comment by AbhitejJohn** [comment]
We've seen this happen for users having an app.config file. Here is a workaround for such users:
Add the following startup section to the config
```
<configuration>
…
              <startup useLegacyV2RuntimeActivationPolicy="true">
                            <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.0" />
              </startup>
…
</configuration>
```

**Comment by acesiddhu** [comment]
RFC for the change we did https://github.com/Microsoft/vstest-docs/blob/master/RFCs/0019-Disable-Appdomain-While-Running-Tests.md

Closing this issue
