### ISSUE TITLE
does this repo really require a alpha sdk?

### ISSUE THREAD

**Issue by SimonCropp** [microsoft/testfx#2253]
does this repo require an alpha sdk? currently 9.0.100-alpha.1.23615.4

it is a non starter for many people who would consider contributing

**Comment by SimonCropp** [comment]
@Evangelink thanks so much

**Comment by nohwnd** [comment]
@SimonCropp  would it help if we made it easier to use the locally installed dotnet? On my environment I am always installing just stable dotnet to global installation, and then using a script like this to pick up the local dotnet SDK that build.cmd installs. 

Would adding something like this help? e.g. a script open.cmd, open.ps1 or a windows shortcut that sets this up and opens vs.

```powershell
function sln ($path = $PWD.Path) {
    # open the solution with the shortest name in the current folder or in src
    function get ($path) {
        Get-ChildItem $path *.sln |
        Sort-Object -Property { $_.Name.Length } |
        Select-Object -First 1
    }

    if ((Test-Path $pwd/.dotnet)) {
        $dotnetPath = Resolve-Path $pwd/.dotnet
        $env:DOTNET_MULTILEVEL_LOOKUP=0
        $env:DOTNET_ROOT=$dotnetPath
        $env:DOTNET_MSBUILD_SDK_RESOLVER_CLI_DIR=$dotnetPath
        $env:PATH="$dotnetPath;$env:PATH"
    }

    $env:VSDebugger_ValidateDotnetDebugLibSignatures=0


    $sln = if ($path -like "*.sln?") { $path } else { get $path }
    if ($null -eq $sln -or 0 -eq $sln.Count) {
        $path = Join-Path $PWD.Path "src"
        $sln = get $path
    }

    if ($null -ne $sln -and 1 -eq $sln.Count) {
        & "C:\Program Files\Microsoft Visual Studio\2022\IntPreview\Common7\IDE\devenv.exe" $sln
    }
}
```

**Comment by SimonCropp** [comment]
@nohwnd i am not a fan of open.cmd, open.ps1, runmefirst.ps1 requirements. too often i have seen them abuse the local machine by installing at the machine or user level. then suddenly other things stop working or u get weird side effect.

so if i encounter a solution that doesnt build by opening the sln file, i may review the runme, or more likely just raise a bug instead of trying to fix the issue myself in a PR

i IMO i am one the "more likely to deal with some friction to submit a pr" end of the spectrum. most would be less will to be amenable to debug a build

**Comment by nohwnd** [comment]
Fair enough. There is still a script to install the required (and old) windows sdk to be able to build uwp (via build.cmd). But maybe that can be solved by solution filter. So then the only requirement is to have net8.0.100 installed on your machine.

**Comment by SimonCropp** [comment]
net 8.0.101. since 8.0.100  has a cve

**Comment by Evangelink** [comment]
I'll update the readme + still create the batch file for opening VS but the main part of the change is merged. I'll link follow-up PR to this issue for completness.
