### ISSUE TITLE
MSTest command line is not working when used Owner or Priority attribute. Not able to associate test cases to tfs also.

### ISSUE THREAD

**Issue by mailing2pankaj** [Microsoft/testfx#227]
_##_ Description
> When executing the test cases using MSTest.exe command line, it is throwing error: "Index was outside the bounds of the array." This is happening only when we use the Owner or Priority attribute in the Test Methods.

## Steps to reproduce
> Create a unit test project in VS 2017.
> MsTest.TestFramework and MsTest.TestAdapter is automatically added.
> Create a basic test case to add two numbers and Assert the result.
> Add Priority and Owner attributes and give some values for them.
>Build solution and execute the test cases. It should execute successfully.
> Execute the same test cases in the dlls using MsTest.exe command line.

## Expected behavior
> It should work fine and display the execution result

## Actual behavior
> It is throwing error: "Index was outside the bounds of the array." 
> Not able to associate test cases to tfs test cases after creating a build definition. The "Choose Tests "window is not displaying any test methods if these attributes are added.

## Environment
> Operating system - Win 10
> MSTest package version - latest (1.1.18)
> Build version of vstest.console-  Visual Studio 2017 Developer Command Prompt v15.0.26430.15
> Framework - Unit test project (.Net framework, not core)

**Comment by AbhitejJohn** [comment]
@mailing2pankaj : Thanks for filing this. MSTest V2 is not supported via the legacy mstest.exe runner. Please use vstest.console instead.
Leaving this issue open to fix up the warning message to indicate to users the same.

**Comment by pvlakshm** [comment]
Validate and close.

**Comment by mayankbansal018** [comment]
This is not a supported scenario. Closing this issue.
