### ISSUE TITLE
Error thrown when framework is not registered is outdated

### ISSUE THREAD

**Issue by nohwnd** [microsoft/testfx#2279]
## Describe the bug

When test framework is not registered, error `The test framework adapter has not been registered. Use 'RegisterTestFrameworkAdapter' to register it` is thrown. It mentions non-existing method, and should instead mention `ITestApplicationBuilder.RegisterTestFramework`.

https://grep.app/search?q=RegisterTestFrameworkAdapter

**Comment by Evangelink** [comment]
Can you please provide a PR?
