### ISSUE TITLE
Unit Test templates for .NET Core not referencing latest stable version of MSTest

### ISSUE THREAD

**Issue by morrisjoe** [Microsoft/testfx#229]
## Description
Unit test templates for .NET Core 2.0 do not use MSTest.Adapter and MSTest.TestFramework 1.1.18 (latest stable) and uses 1.1.17 instead. This is inconsistent with what is used with test templates for .NET, which correctly uses 1.1.18. Also we know that when latest stable is not present, features that are built on top of this (e.g LUT) could run into issues depending on the bug fixes that went into 1.1.18

## Steps to reproduce
Install VS 2017 version 15.3 and .NET Core 2.0 SDK. 
File->New->Test and pick a .NET Core Unit Test template

## Expected behavior
Should reference MSTest.TestFramework & MSTest.TestAdapter version 1.1.18 (latest stable) and manage NuGet packages UI should not show updates available immediately after File->New

## Actual behavior
Shows references to MSTest.TestFramework MSTest.TestAdapter version 1.1.17 and manage NuGet packages UI shows updates available for version 1.1.18

**Comment by morrisjoe** [comment]
https://github.com/dotnet/templating/pull/1155

**Comment by AbhitejJohn** [comment]
> Also we know that when latest stable is not present, features that are built on top of this (e.g LUT) could run into issues depending on the bug fixes that went into 1.1.18

@morrisjoe : Can you please help us with such a scenario? This is not expected to break. Customers running LUT on earlier stable VS builds would run into issues then and that is a concern.

**Comment by AbhitejJohn** [comment]
@morrisjoe: gently pinging back.

**Comment by pvlakshm** [comment]
This is fixed since VS 15.4.
