### ISSUE TITLE
Change the name of the MSTest.Runner

### ISSUE THREAD

**Issue by OsirisTerje** [microsoft/testfx#2298]
## Summary

Change the name of the MSTest.Runner to Microsoft.Testing.Runner  (or something else that is test framework agnostic.

## Background and Motivation

The new MSTest.Runner is intended to also support the other frameworks, XUnit and NUnit, ref https://github.com/microsoft/testfx/issues/2164

It is then very confusing and unfortunate to have this being named MSTest.Runner, as it is more of a Microsoft.Testing.Runner.

It also makes comments like this

> We just need to provide enough new nice features for you to want to migrate to MSTest

in https://github.com/microsoft/testfx/issues/2164#issuecomment-1910743166

confusing.  Does the [commenter](https://github.com/Evangelink)  mean that this is an attempt to convert all XUnit and NUnit users to move to use the MSTest framework or does he mean that he want users to use the misnamed MSTest.Runner instead of the current runners ?   I prefer to believe it is the latter.  If it is the former, well, the runner is not that important, the framework is.

## Proposed Feature

Change the name of the MSTest.Runner to Microsoft.Testing.Runner  (or something else that is test framework agnostic.

**Comment by Evangelink** [comment]
Thanks @OsirisTerje, we will review this name change request soon.

**Comment by Evangelink** [comment]
Docs website has been updated, this will take some time to flow to public but I will move forward by closing this task.
