### ISSUE TITLE
mstest trx bug in className when using nunit tests with parameters

### ISSUE THREAD

**Issue by arielcloud** [Microsoft/testfx#230]
## Description
I have nunit test like this:

`protected static TimeRange[] TestCaseX = new TimeRange[] 
        {
            new TimeRange(new DateTime(2016, 2, 3), new DateTime(2016, 2, 4)),
            new TimeRange(new DateTime(2016, 2, 3), new DateTime(2016, 3, 3))
        };`

`[Test, TestCaseSource(nameof(TestCaseX))]
        public void testFoo(TimeRange time)`

TimeRange exists in Infra.Services

when runnig tests with "dotnet test --logger:trx" it output the trx file with:
"className="BL.Tests.services.OneTimeTests.testFoo(infra.Services" 

probably because it see the test as 
"BL.Tests.services.OneTimeTests.testFoo(infra.Services.TimeRange)"

and it is trying to take the className by splice(".") and taking the first part till the dot, which is not correct in this case when we have dots also in the test name.

is exists any fix for that?

10x!

**Comment by AbhitejJohn** [comment]
Thanks for filing this. Moved this over to https://github.com/Microsoft/vstest/issues/972 to get the right folks involved.
