### ISSUE TITLE
Using just `--hangdump-timeout 3s` reports no error, and does not work

### ISSUE THREAD

**Issue by nohwnd** [microsoft/testfx#2308]
## Describe the bug

`ProjectWithExtensions.exe --filter HangingTest --hangdump-timeout 3s` should either throw an error, or imply that `--hangdump` is used, but it does neither. 

I think the parser sees that --hangdump-timeout is a valid option, but it does not consider it to be an option that enables the hangdump extension. So in effect I get no error on screen, and my tests are allowed to run for 10s.

## Steps To Reproduce

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>

    <EnableMSTestRunner>true</EnableMSTestRunner>
    <OutputType>Exe</OutputType>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" Version="3.2.0" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" Version="17.10.1" />
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" Version="1.0.0" />
    <PackageReference Include="Microsoft.Testing.Extensions.HangDump" Version="1.0.0" />
    <PackageReference Include="Microsoft.Testing.Extensions.HotReload" Version="1.0.0" />
  </ItemGroup>
</Project>
```
```cs
namespace ProjectWithExtensions;

[TestClass]
public class UnitTest1
{
    [TestMethod]
    public void TestMethod1()
    {
    }

    [TestMethod]
    public void HangingTest()
    {
        System.Threading.Thread.Sleep(10_000);
    }
}
```

## Expected behavior

~~--hangdump-timeout implies that --hangdump extension is used and will configure it.~~

We won't make it implicit for now. We can do it in future if we won't add any new parameters like in-proc/out-of-proc with the default timeout, or if command line length will be an issue.

## Actual behavior

It (probably) configures the extension, but does not enable it.

## Additional context

[AB#1955261](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1955261)

**Comment by MarcoRossignoli** [comment]
Now we have space for this kind of check, I'll add the validation.
