### ISSUE TITLE
Deployment pulls in symbols from configured symbol servers

### ISSUE THREAD

**Issue by AbhitejJohn** [Microsoft/testfx#231]
## Description
Tests with `[DeploymentItem]s` when run pull in symbols for dependent assemblies from configured symbols servers(if they aren't on disk). We do this to get the line number information in the stack trace for failed tests. This however is a very costly operation.

The proposal here is to just deploy symbols that are on disk and nothing else.

**Comment by AbhitejJohn** [comment]
We would have to fix this in MSTest V1 as well.

**Comment by codito** [comment]
Impact: this leads to hangs (and potential timeouts) test execution in CI servers.
