### ISSUE TITLE
Document the new `MSTest.Sdk`

### ISSUE THREAD

**Issue by MarcoRossignoli** [microsoft/testfx#2331]
We should document the usage of the new MSTest.Sdk taking inspiration by ASP.NET for instance https://learn.microsoft.com/en-us/aspnet/core/razor-pages/web-sdk?view=aspnetcore-8.0

[AB#1956005](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1956005)

**Comment by Evangelink** [comment]
This is now done.
