### ISSUE TITLE
Request to Support Create Unit Tests for VB.NET in VS 2017

### ISSUE THREAD

**Issue by elynch100** [Microsoft/testfx#235]
Per my issue reported in https://developercommunity.visualstudio.com/content/problem/70314/vbnet-create-unit-tests.html VS 2017 does not support Create Unit Tests. Requesting an enhancement to include functionality in later release of software.

**Comment by jayaranigarg** [comment]
Closing as duplicate of https://github.com/Microsoft/testfx/issues/376
