### ISSUE TITLE
Warning from adapters when containers doesnt have any test cases

### ISSUE THREAD

**Issue by acesiddhu** [Microsoft/testfx#236]
[foo.txt](https://github.com/Microsoft/testfx/files/1207378/foo.txt)
## Description
> Warnings from adapter when a test containers doesn't have any tests

## Steps to reproduce
> What steps can reproduce the defect?
> vstest.console.exe "F:\AgentDTAtestingint\_work\15\s\TIAdogfood\TIAdogfoodTests1\bin\Release\Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.dll" "F:\AgentDTAtestingint\_work\15\s\TIAdogfood\TIAdogfoodTests1\bin\Release\Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface.dll" "F:\AgentDTAtestingint\_work\15\s\TIAdogfood\TIAdogfoodTests1\bin\Release\Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.dll" "F:\AgentDTAtestingint\_work\15\s\TIAdogfood\TIAdogfoodTests1\bin\Release\Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions.dll" "F:\AgentDTAtestingint\_work\15\s\TIAdogfood\TIAdogfoodTests1\bin\Release\Microsoft.VisualStudio.TestPlatform.TestFramework.dll" "F:\AgentDTAtestingint\_work\15\s\TIAdogfood\TIAdogfoodTests\bin\Release\Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.dll" "F:\AgentDTAtestingint\_work\15\s\TIAdogfood\TIAdogfoodTests\bin\Release\Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface.dll" "F:\AgentDTAtestingint\_work\15\s\TIAdogfood\TIAdogfoodTests\bin\Release\Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.dll" "F:\AgentDTAtestingint\_work\15\s\TIAdogfood\TIAdogfoodTests\bin\Release\Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions.dll" "F:\AgentDTAtestingint\_work\15\s\TIAdogfood\TIAdogfoodTests\bin\Release\Microsoft.VisualStudio.TestPlatform.TestFramework.dll" /logger:trx /TestAdapterPath:F:\AgentDTAtestingint\_work\15\s

## Expected behavior
> It should just run test if discovered. 

## Actual behavior
> What is the behavior observed?
Warning: Input string was not in a correct format.

Warning: Input string was not in a correct format.

Warning: Input string was not in a correct format.

Warning: Input string was not in a correct format.

## Environment
Logs are attached
[foo.txt](https://github.com/Microsoft/testfx/files/1207380/foo.txt)

**Comment by alex-tomin** [comment]
+1, Quite annoying.

**Comment by jayaranigarg** [comment]
We are unable to repro this issue with latest adapter i.e. MSTest 1.2.0.
Please feel free to re-open this thread if you are blocked on this.
