### ISSUE TITLE
Test classes should have test methods

### ISSUE THREAD

**Issue by Evangelink** [microsoft/testfx#2374]
## Summary

Enabled by default: true
Default severity: Info
Title: Test classes should have test methods

When a non-abstract or static type is marked with `[TestClass]` (or any descendant), it should contain at least one test method.

**Comment by AliveDevil** [comment]
The analyzer should consider Assembly Initializers:
```
[TestClass]
class GlobalState {
  [AssemblyInitializer]
  static void Init(TestContext context) { … }
  [AssemblyCleanup]
  static void Cleanup() { … }
}
```

**Comment by AliveDevil** [comment]
Ah, so
```
[TestClass]
static class GlobalState {
 [AssemblyInitializer] …
```
would work?
If this is the case, the wording "non-abstract or static type […] should contain at least one test method" should not include "static" (or rephrase that it applies to non-abstract and non-static / non (abstract or static)), then the analyzer can be stricter for these types.

**Comment by Evangelink** [comment]
Just realizing that I already created a ticket for this one here #2236. Will close this one as duplicate and copy your comments.
