### ISSUE TITLE
C# Unit Test Template is still the old template

### ISSUE THREAD

**Issue by CoolDadTx** [Microsoft/testfx#239]
The readme for the project says that VS 2017 Preview 4 and above are using the new unit test template. But I have the 17 Preview 7.1 update and attempting to create a new C# unit test project is still using the old template. Is there something additional that needs to be installed before the new templates show up?

**Comment by AbhitejJohn** [comment]
@CoolDadTx : That's strange, this should be part of the ".Net Desktop Development" workload. Can you share the build version please? Also, I'm assuming you are creating a Desktop based UT project from `Test -> Unit Test Project` in the New project dialog which is putting out a project which does not have nuget packages auto-referenced. Do correct me if that is incorrect.

**Comment by CoolDadTx** [comment]
15.3.0 Preview 7.1 which was just released.

I started VS and created a new project via File\New Project -> Visual C#\Test -> Unit Test Project (.NET Framework). The generated project still contains the import of Microsoft.TestTools.targets but doesn't include any references to the unit test assemblies like it used to. 

I don't know that I've updated to the newer .NET core SDK yet. Is that required? The project itself I targeted at .NET 4.6.1.

**Comment by michaeltccd** [comment]
Maybe I'm doing something wrong because I see this behavior on 2 different machines with the same updates. The templates appear to be the old template but they don't have any Nuget or assembly references to the testing framework. Creating a new project and clicking build complains about the types defined in the test assemblies not being found. This behavior is identical on another machine that is configured the same way.

**Comment by AbhitejJohn** [comment]
@CoolDadTx , @michaeltccd: Thanks. Can you share the project that got created with us please?

**Comment by michaeltccd** [comment]
[UnitTestProject1.zip](https://github.com/Microsoft/testfx/files/1219953/UnitTestProject1.zip)
Attaching the generated project.

I also went and looked at the base template being used by VS. It still has the install date of the original VS 2017 instance. It doesn't appear to have been updated in any recent updates to VS 2017.

**Comment by CoolDadTx** [comment]
FYI, this the same user, I have 2 different GitHub accounts I bounce between.

There is no category for NuGet when the project is created. There also isn't any when I try to do a build but I have my system configured to not save solutions by default so if I create a "temp" project and then try to build it fails. If I try to go to Manage Nuget then it errors saying the project has to be saved first. Saving the solution doesn't change anything.  There is also no packages.config nor does the project file contain any PackageReference elements to refer to NuGet. It looks just like the template that is stored in the VS install folder.

**Comment by AbhitejJohn** [comment]
Thanks @CoolDadTx. This looks like an issue with the installation of nuget. Can you move to the 15.3 RTM version and try this out? It doesn't repro for me there.

**Comment by CoolDadTx** [comment]
Yes I confirmed it seems to be working with RTM version. It doesn't honor the nuget settings properly but I'll report that as a separate issue if it hasn't been reported yet.
