### ISSUE TITLE
MSTestv2 does not support testSettings. Are there features that need to be brought fwd to runSettings?

### ISSUE THREAD

**Issue by sbaid** [Microsoft/testfx#24]
## Description
TestSettings are not supported in MSTestv2. Are there features that need to brought forward in runsettings?

**Comment by AbhitejJohn** [comment]
Here is the list of gaps:
1. Session level test timeout. Tracked by #26.
2. Test settings supports remote execution - This is more of a request on the test platform. 
3. Setup and cleanup scripts aren't available in runsettings.
4. Testsettings supported Host types, the defaults being (VS IDE/ ASP.Net) enabling users to run tests against these hosts. There is no way of achieving this today with MSTest V2 and the new test platform without the legacy engine.
5. There are a list of Legacy system based data collectors(Event Log, Screen and Video Capture etc) that we currently cannot specify via runsettings. Hence these cannot be run with MSTest V2.

**Comment by pvlakshm** [comment]
MSTest V2 will not support .testsettings.
Getting .runsettings to parity will be taken up as a separate item.
