### ISSUE TITLE
 [DataTestMethod] is not allowed to be a Generic method

### ISSUE THREAD

**Issue by mlsomers** [microsoft/testfx#2402]
## Describe the bug

A test marked with the [DataTestMethod] attribute cannot have a generic parameter. It will not be recognized by the test runner.

## Steps To Reproduce

```
[TestClass]
public class GTest
{
  [DataTestMethod]
  [DataRow((byte)10)]
  [DataRow((short)11)]
  [DataRow((long)12)]
  [DataRow((ulong)13)]
  public void GenericTest<T>(T value)
  {
    List<T> list = new List<T>(new[] {value});
    Assert.AreEqual<T>(value, list[0]);
  }
}
```
## Expected behavior

The test framework should invoke the method of type T with the correct type of the given argument in DataRow.

## Actual behavior

The test framework ignores the whole test.

## Additional context

Ran into this limitation while migrating my [LsMsgPack project](https://github.com/mlsomers/LsMsgPack/tree/master) from NUnit to MsTest. The last 100 or so tests in [MpIntTest.cs](https://github.com/mlsomers/LsMsgPack/blob/master/LsMsgPackNetStandardUnitTests/MpIntTest.cs) are ignored. The [old tests](https://github.com/mlsomers/LsMsgPack/blob/master/LsMsgPackUnitTests/MpIntTest.cs) in Nunit are working.

**Comment by Evangelink** [comment]
Hi @mlsomers,

Generics are indeed not supported at the moment. Marking this as a feature request.

In the meantime, you will have to work with `object`.

**Comment by Youssef1313** [comment]
Assigning myself so that I don't forget. I'll validate how much work is needed here.
