### ISSUE TITLE
MSTEST0012: Flag cases where assemblyinit is set on generic test class

### ISSUE THREAD

**Issue by Evangelink** [microsoft/testfx#2420]
## Summary

With the change that will be introduced through the fix of #2419, assembly init should be improved to also raise an issue when it is defined on a generic test class.

[AB#1976483](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1976483)

**Comment by engyebrahim** [comment]
`AssemblyInit` does't have an inheritance param 
<img width="845" alt="image" src="https://github.com/microsoft/testfx/assets/24208132/114e6000-3eeb-4d1b-8084-87c9f3827768">

**Comment by engyebrahim** [comment]
`AssemblyInit` does't have an inheritance param 
<img width="845" alt="image" src="https://github.com/microsoft/testfx/assets/24208132/114e6000-3eeb-4d1b-8084-87c9f3827768">
