### ISSUE TITLE
Visual Studio Right-Click Run Tests not working for multiple selected test projects

### ISSUE THREAD

**Issue by james1301** [microsoft/testfx#2424]
## Describe the bug

In Visual Studio when you select multiple test projectsm right-click and choose run tests, it only runs the project you are right-clicking on and not all of the selected projects. This seems a recent breakage in VS/MS Test package.

## Steps To Reproduce

1. Make sure you have a solution with multiple test projects
2. Hold ctrl and select multiple test projects
3. Right-Click and hit Run Tests

## Expected behavior

Tests run for all selected test projects

## Actual behavior

Tests only run for the project you have right-clicked

## Additional context

MS Test 3.2.1
Visual Studio 17.9.1

Broken in a recent MSTest/Visual Studio version.

**Comment by Evangelink** [comment]
@drognanar I strongly suspect this is linked to Test Explorer. Coud you please confirm and if that's the case, create a public ticket and link it here as it's pretty unlikely to be MSTest related.

**Comment by drognanar** [comment]
It is Test Explorer related. TE has logic specific to handle file support and dedupes selected entries based on source location file path, but this causes it to dedupe all projects since projects do not have a mapped source location file path.

I created a ticket https://developercommunity.visualstudio.com/t/Clicking-run-tests-for-multiple-test-pro/10618293?port=1025&fsid=5a9c451c-be79-4891-b081-9419f606771d and will forward it accordingly

**Comment by james1301** [comment]
Thanks @drognanar, I think the ticket might be private? I can't seem to see it.

**Comment by Evangelink** [comment]
@drognanar I confirm that you created an internal ticket.

**Comment by drognanar** [comment]
oh no, let me change it to public

**Comment by drognanar** [comment]
is it visible now? it says it might take a couple of minutes to propagate it to a public ticket

**Comment by Evangelink** [comment]
It's good now (you can use private browser mode to check FYI)

**Comment by Evangelink** [comment]
@james1301 I will move forward by closing this ticket, please upvote and comment on the ticket created by Artur as it's onto a different team radar.
