### ISSUE TITLE
Are SSDT/SQL Unit tests in scope for this repo?

### ISSUE THREAD

**Issue by nschonni** [Microsoft/testfx#243]
It is part of the "Data Storage and Processing" workload in VS 2017

**Comment by AbhitejJohn** [comment]
@nschonni : I believe that workflow uses the same Framework from this repo in 15.3. Do you see a MSTest.TestFramework nuget package referred in the project? What version of VS are you on?

**Comment by pvlakshm** [comment]
@nschonni, are you referring to any test-related Visual Studio Project Templates that might come along with the workload you mention?

**Comment by nschonni** [comment]
Sorry for the delay in responding.
Currently most of our work stuff is in 2015 Enterprise, but we'll be moving to 2017 soon.
Right now the SSDT tests are created as an odd autogenerating format, but I was more interested in about whether this will enable test impact between the SSDT (.sqlproj) and the unit test project.

**Comment by pvlakshm** [comment]
@nschonni, as of VS 15.5 Preview 1, Live Unit Tests support MSTest V1 (the test framework used in the SSDT/SQL unit test project). if you still face issues, please report them on the Developer Community site.
