### ISSUE TITLE
Unit test template does not honor Nuget package reference setting

### ISSUE THREAD

**Issue by CoolDadTx** [microsoft/testfx#244]
In the NuGet package manager options you can select the option to either use PackageReferences or the older packages.config approach to using NuGet.  When creating a unit test template it always uses packages.config even if you have configured VS to use PackageReferences. Additionally the option to prompt on first package install is checked but I didn't get a prompt to decided either way.

Ideally the template should determine if it should prompt for the approach to use based upon the VS options. If not checked then it should honor the default approach that is configured. If that isn't possible then it seems like the PackageReferences approach should be preferred since that is the desired approach going forward.

**Comment by AbhitejJohn** [comment]
Thanks for filing this. I'm not sure if templates have this choice. Will figure this out and post back.

**Comment by Evangelink** [comment]
Looks like this is no longer relevant issue.
