### ISSUE TITLE
Code Coverage Analysis Engine threw exception(s)

### ISSUE THREAD

**Issue by tstephansen** [Microsoft/testfx#245]
## Description
> Running Code Coverage Analysis does not show code coverage.

## Steps to Reproduce
> I'm not able to give a good answer for this. I created a new console project and ran unit tests/coverage against it and it worked. I also recreated the solution that I have been trying to test but that didn't help. I'm not sure why the test runs will pass but code coverage will not work. This also wasn't an issue before updating to VS 2017 15.3.

## Expected behavior
> Code coverage should be displayed after analysis finishes.

## Actual behavior
> Tests take over 2 minutes to start running vs. ~30 seconds for just running the tests without coverage (may not really be an issue but didn't notice this before updating to 15.3). Also, as a reference the solution only contains ~17K lines of code.
> When coverage is finished an error is displayed (see screenshot below).
![error screenshot](https://preview.ibb.co/bCUezv/Screen_Shot_2017_08_16_at_7_40_45_PM.png)

## Environment
> Windows 7 x64 Professional and Windows 10 Pro (both systems on separate computers are having the issue)
> Visual Studio 2017 Enterprise 15.3
> vstest.console version 15.0.26720.2
> Adapter and framework packages are both v1.1.18

Any help or guidance would be greatly appreciated.

**Comment by AbhitejJohn** [comment]
Tagging @smadala and @mayankbansal018 .
@tstephansen : Can you share the coverage file please?

**Comment by tstephansen** [comment]
Sure. I deleted the ones from yesterday but I just ran a new one on the Windows 7 machine. Same error. The file is attached.

[30016976_300-2790-2 2017-08-17 09_33_49.zip](https://github.com/Microsoft/testfx/files/1231396/30016976_300-2790-2.2017-08-17.09_33_49.zip)

**Comment by smadala** [comment]
@tstephansen Can you please share sample repro project as well?

**Comment by tstephansen** [comment]
![Sample Repo](https://github.com/tstephansen/MSTest-Sample-Project)

**Comment by tstephansen** [comment]
I think I may have figured out a way around this problem and what's causing it. The DatesData.cs file holds all the entries from my dates table (really big file). Loading this data from JSON instead of pulling it from a class fixes the issue. 

Is it possible to add a warning when a file is too big for the code coverage analyzer to handle?

Thanks, Tim.

**Comment by AbhitejJohn** [comment]
Thanks a bunch for the repro @tstephansen . Glad you have a workaround. Logged a bug with Code Coverage internally to get this looked at.

**Comment by tstephansen** [comment]
The data size increased. I haven't had any more issues since I switched it to JSON.

**Comment by AbhitejJohn** [comment]
ah great. Thanks for the confirmation.

**Comment by jayaranigarg** [comment]
This issue is being tracked on Code Coverage viewer side. CLosing the thread.
