### ISSUE TITLE
[Help] Replacement for DiaSession? Getting Test File Location and Line Numbers

### ISSUE THREAD

**Issue by thomhurst** [microsoft/testfx#2452]
I'm looking at a non-bridged runner, and so I have removed all dependencies from the old VSTest packages (`Microsoft.TestPlatform.ObjectModel`).

I can see when constructing a `TestNode` we can pass a `TestFileLocationProperty` - Which takes the file path and line positions, like before.

In the old package, there was a `DiaSession` class that would help you get these details, the path and line number.

Is there something that does this within the new `Microsoft.Testing.Platform` package?

I also see that the new `LinePosition` takes a column position too, which the old `DiaSession` wouldn't give us anyway.

**Comment by MarcoRossignoli** [comment]
> Is there something that does this within the new Microsoft.Testing.Platform package?

`Microsoft.Testing.Platform` is the core of the platform that put together extensions and test frameworks and orchestrate the run and won't never take any dependency. Get the lines info is up to the test framework, I suggest to use the `System.Reflection.Metadata` classes to find out information about your "methods".

**Comment by thomhurst** [comment]
@MarcoRossignoli got you. Thanks for the info!
