### ISSUE TITLE
[Help] `System.InvalidOperationException: The test framework adapter has not been registered.`

### ISSUE THREAD

**Issue by thomhurst** [microsoft/testfx#2458]
I've been using code from the xUnit/NUnit PRs for the new test adapters as inspiration for my own code.

When using `dotnet test` I get failures due to missing dependencies, but I'm guessing that's because my .NET SDK isn't new enough (8.0.201).

So I tried `dotnet run` - And it starts trying to run, but then says my framework hasn't been registered.
From what I can tell, it's invoked dynamically? So any help as to why it isn't working would be greatly appreciated.

For the time being, I've created the main entry point myself and called these extensions manually, and it's working fine.

Error:
```
Unhandled exception. System.InvalidOperationException: The test framework adapter has not been registered. Use 'ITestApplicationBuilder.RegisterTestFramework' to register it
   at Microsoft.Testing.Platform.Builder.TestApplicationBuilder.BuildAsync() in /_/src/Platform/Microsoft.Testing.Platform/Builder/TestApplicationBuilder.cs:line 110
   at TestingPlatformEntryPoint.Main(String[] args) in C:\git\TUnit\TUnit.TestProject\obj\Debug\net7.0\TestPlatformEntryPoint.cs:line 14
   at TestingPlatformEntryPoint.<Main>(String[] args)
PS C:\git\TUnit\TUnit.TestProject>
```

Here's my code:

```csharp
using System.Reflection;
using Microsoft.Testing.Platform.Builder;

namespace TUnit.Engine;

public static class TestingPlatformBuilderHook
{
    public static void AddExtensions(
        ITestApplicationBuilder testApplicationBuilder,
        string[] _) =>
        testApplicationBuilder.AddTUnit(() => [Assembly.GetEntryAssembly()!]);
}
```

```csharp
using System.Reflection;
using Microsoft.Testing.Platform.Builder;
using Microsoft.Testing.Platform.Capabilities.TestFramework;
using Microsoft.Testing.Platform.MSBuild;

namespace TUnit.Engine;

public static class TestApplicationBuilderExtensions
{
    public static void AddTUnit(this ITestApplicationBuilder testApplicationBuilder, Func<IEnumerable<Assembly>> getTestAssemblies)
    {
        TUnitExtension extension = new();
        testApplicationBuilder.RegisterTestFramework(
            _ => new TestFrameworkCapabilities(),
            (capabilities, serviceProvider) => new TUnitTestFramework(extension, getTestAssemblies, serviceProvider, capabilities));
    }
}
```

The generated entry point looks like this:

```csharp
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Microsoft.Testing.Platform.MSBuild
// </auto-generated>
//------------------------------------------------------------------------------

[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
internal sealed class TestingPlatformEntryPoint
{
    public static async global::System.Threading.Tasks.Task<int> Main(string[] args)
    {
        global::Microsoft.Testing.Platform.Builder.ITestApplicationBuilder builder = await global::Microsoft.Testing.Platform.Builder.TestApplication.CreateBuilderAsync(args);
        Microsoft.Testing.Platform.MSBuild.TestingPlatformBuilderHook.AddExtensions(builder, args);
        using (global::Microsoft.Testing.Platform.Builder.ITestApplication app = await builder.BuildAsync())
        {
            return await app.RunAsync();
        }
    }
}
```

**Comment by thomhurst** [comment]
Ah I think I've figured out why it's not being invoked - I haven't added the 

`<ItemGroup><TestingPlatformBuilderHook ...`

However, both the xUnit and NUnit PRs have a different GUID on those elements. How is that generated? I don't suppose I can just use the same value?

**Comment by nohwnd** [comment]
The id is a guid that you should generate and keep using for this extension point. If in the future your extension will need to be registered in some order, of if we add some categories for extensions or something like that, this id will represent your extension to us so we can make it well-known.

So definitely use different guid than xunit, nunit or mstest :)

**Comment by MarcoRossignoli** [comment]
> Ah I think I've figured out why it's not being invoked - I haven't added the 

Sorry for the lack of documentation we didn't expect such an "immediate" interest 😄 and we're planning to write an extensive one.
The https://www.nuget.org/packages/Microsoft.Testing.Platform.MSBuild takes care of the MSBuild registration and insert the entry point, it's not mandatory and as you did you can do it manually but it's used to have smooth and transparent porting.
We collect all the items:

```xml
  <ItemGroup>
    <TestingPlatformBuilderHook Include="8E680F4D-E423-415A-9566-855439363BC0" >
      <DisplayName>MyBuilderHook</DisplayName>
      <TypeFullName>Contoso.BuilderHook</TypeFullName>
    </TestingPlatformBuilderHook>
  </ItemGroup>
```
And we "insert" a call expecting the shape of the method name like:
```cs
static Contoso.BuilderHook.AddExtensions(Microsoft.Testing.Platform.Builder.TestApplicationBuilder builder, string[] args)
```
So final users doesn't have to care about build-time registration.

**Comment by thomhurst** [comment]
Thanks! Got it working 😄
