### ISSUE TITLE
[Help] Custom Test Filtering

### ISSUE THREAD

**Issue by thomhurst** [microsoft/testfx#2462]
Hey again, sorry if these are becoming a nuisance!

Are you able to provide an example of implementing a basic filter?

I've looked at https://github.dev/microsoft/testfx/blob/main/src/Platform/Microsoft.Testing.Platform/CommandLine/TreeNodeFilterCommandLineOptionsProvider.cs

I've tried implementing my own `ICommandLineOptionsProvider` which is fine, but now I can't work out how I:
- New up my filter class which implements `ITestExecutionFilter` (because it expects the command switch string value)
- Register it as the `ITestExecutionFilter` which is passed to the `RunTestExecutionRequest` object

I can see in the code above there is a `ITestExecutionFilterFactory` but that's internal. So is this just not ready yet or is there another way to hook this up that I've missed?

Thanks!

**Comment by MarcoRossignoli** [comment]
> I can see in the code above there is a ITestExecutionFilterFactory but that's internal. So is this just not ready yet or is there another way to hook this up that I've missed?

The tree node filtering is not yet exposed and used internally. My first question is if you want to implement your custom filtering experience or you want to try to use our draft.

This is the registration code for it https://github.com/microsoft/testfx/blob/main/src/Platform/Microsoft.Testing.Platform/Helpers/TestApplicationBuilderExtensions.cs

**Comment by thomhurst** [comment]
Is creating your own one still internal as well?

I'm happy to use the tree node filter that you've built, as it looks like it'd handle most filters that users would need.

**Comment by MarcoRossignoli** [comment]
> Is creating your own one still internal as well?

We built it for native aot reason. We needed to test that scenario so we it's a limited adapter that will remain close for now only for new platform development.

> I'm happy to use the tree node filter that you've built, as it looks like it'd handle most filters that users would need.

If you want to try the "experimental internal" feature you have to accept that till the api will be public we could break, remove or never ship it.
If you accept this we can think to add a `ThirdPartyExperiment.cs` file where we put extensions that "wants" to experiment not yet and maybe never shipped features.

Also at the moment the filter system doesn't handle everything and it's partially implemented.

**Comment by thomhurst** [comment]
Sounds good. I'll happily try it if the team feels they can open it up..

**Comment by thomhurst** [comment]
Even if you don't want to open up your experimental filter yet, are you considering letting us write our own filters? Currently filters are new'd up inside the `ServerTestHost` so there's no way for us to plug in our own ones.

**Comment by MarcoRossignoli** [comment]
@Evangelink do you agree to add a `EarlyAdoptersFeatures.prop` where we add specific internal friends assemblies to let @thomhurst to experiment and help using features like server mode filters without public guarantee to maintain it?

**Comment by MarcoRossignoli** [comment]
@thomhurst is you project open source do you have an assembly name and public key we can use to let you experiment with the internals?

**Comment by nohwnd** [comment]
Most likely it is about TUnit as all the other issues by OP: https://github.com/thomhurst/TUnit

we ask the same question in each issue 😁

**Comment by thomhurst** [comment]
Haha yes you're right. TUnit.

My project/assembly that is referencing testing platform is actually TUnit.Engine.

Currently the testing platform work is on this branch:

https://github.com/thomhurst/TUnit/tree/feature/microsoft-testing-platform-with-source-generator3

**Comment by thomhurst** [comment]
What did this mean by the way guys? Are you considering some preview type of access?

**Comment by MarcoRossignoli** [comment]
> What did this mean by the way guys? Are you considering some preview type of access?

Yep we plan to add a prop where preview users can add their assembly name to access to the internals cc: @Evangelink

**Comment by Evangelink** [comment]
@thomhurst Please follow this [guide](https://github.com/microsoft/testfx/blob/main/docs/preview.md) to access our public previews and give us feedback on the filters (`NopFilter` and `TreeNodeFilter` are now public and experimental).

**Comment by MarcoRossignoli** [comment]
@thomhurst here you can find the usage of the `TreeNodeFilter` https://github.com/microsoft/testfx/blob/main/test/UnitTests/Microsoft.Testing.Platform.UnitTests/Requests/TreeNodeFilterTests.cs

**Comment by thomhurst** [comment]
Thanks both @MarcoRossignoli @Evangelink .

I've installed `1.3.0-preview.24280.1` from your test feed, which was only published 18 minutes ago, but things still look to be internal currently.

![image](https://github.com/microsoft/testfx/assets/30480171/9f0ad2c2-9c67-431e-988d-6def7792ebf2)

**Comment by Evangelink** [comment]
Hi @thomhurst, I see that our pipeline is broken so the new package wasn't yet produced.

**Comment by thomhurst** [comment]
> Hi @thomhurst, I see that our pipeline is broken so the new package wasn't yet produced.

Ah okay no worries. I'll keep checking when I have time 😃
