### ISSUE TITLE
Error running `dotnet test` using both .NET SDK 8 and 9

### ISSUE THREAD

**Issue by thomhurst** [microsoft/testfx#2467]
Using the `.MSBuild` package, I've tried invoking `dotnet test` - It fails for both the .NET 8 and .NET 9 SDK.

.NET 9:
```
  TUnit.TestProject failed with errors (0.0s)
    C:\Program Files\dotnet\sdk\9.0.100-preview.1.24101.2\Microsoft.TestPlatform.targets(41,5): error MSB6006: "dotnet.exe" exited with code 1. [C:\git\TUnit\TUnit.TestProject\TUnit.TestProject.csproj]
```
It doesn't give me any more information than that. If this is due to an issue with the SDK and because it's preview, feel free to remove.

.NET 8:
```
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
Testhost process for source(s) 'C:\git\TUnit\TUnit.TestProject\bin\Debug\net7.0\TUnit.TestProject.dll' exited with error: Error:
  An assembly specified in the application dependencies manifest (testhost.deps.json) was not found:
    package: 'Newtonsoft.Json', version: '13.0.1'
    path: 'lib/netstandard2.0/Newtonsoft.Json.dll'
. Please check the diagnostic logs for more information.

Test Run Aborted.
```

**Comment by MarcoRossignoli** [comment]
Have you added `<TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>` as explained here https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-mstest-runner-integrations#dotnet-test---mstest-runner-mode?

Looking at the error seems that you're running with VSTest engine.

**Comment by thomhurst** [comment]
Ah I missed that. Okay it works with that.

I've also added `<TestingPlatformShowTestsFailure>true</TestingPlatformShowTestsFailure>`

Is there a plan to improve/better format the output of using dotnet test? 

It's very hard to read currently. Running `dotnet run` is a much nicer experience.

**Comment by MarcoRossignoli** [comment]
> Is there a plan to improve/better format the output of using dotnet test?

Unfortunately that's the MSBuild way to show...we will improve using the new terminal logger(cc: @nohwnd) but I think will be done for net9.0. 

If you don't have to run multi-project my advice is "dotnet run" or directly the executable.

`dotnet test` at the moment is designed for CI(we forward output in files inside the test results for further investigation but we don't expect a lot of "interactivity", for that the F5 in VS and the direct run in console is the best) and so we reduced the output at minimum, when you run parallel project old ux anyway overlap the output and it not clear the same.

**Comment by thomhurst** [comment]
Got ya. Cheers for the info! Will close 😄

**Comment by Evangelink** [comment]
@thomhurstI am just curious but is the framework you are building OSS? I'd be happy to have a chat about what you are building, what do you think is missing from the current offer. Feel free to send me an email :)

**Comment by thomhurst** [comment]
@Evangelink what's your email?

**Comment by Evangelink** [comment]
amauryleve[at]microsoft[dot]com

**Comment by thomhurst** [comment]
@Evangelink I've just sent an email over. Sorry, it's a big brain dump of my thoughts!
