### ISSUE TITLE
Ship JSON extractor as Visual Studio Web Test plugin

### ISSUE THREAD

**Issue by abatishchev** [Microsoft/testfx#247]
Current set of the built-in plugins hadn't been update for a decade or do, since about VS2005. Currently it supports Plain Text starts/ends with, RegEx, HTML, XML. But not the language of modern Web - JSON.

Please ship one mor built-in extractor - for JSON. And make it compatible with Application Insights availability tests.

**Comment by AbhitejJohn** [comment]
@abatishchev :  I'm not really sure what you are referring to. Is this related to the MSTest framework?

**Comment by abatishchev** [comment]
I'm referring to Web Test Plugin, [Microsoft.VisualStudio.TestTools.WebTesting.WebTestPlugin](https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.testtools.webtesting.webtest.aspx). Who owns it, again Visual Studio?

**Comment by AbhitejJohn** [comment]
Yes, that would be VS. Developer community would be a good starting point for a discussion.
