### ISSUE TITLE
Allow [ExcludeFromCodeCoverageAttribute] to be used on assembly level

### ISSUE THREAD

**Issue by abatishchev** [Microsoft/testfx#248]
Since it has the following signature:

```csharp
[AttributeUsageAttribute
    (AttributeTargets.Class |
     AttributeTargets.Struct |
     AttributeTargets.Constructor |
     AttributeTargets.Method |
     AttributeTargets.Property |
     AttributeTargets.Event,
     Inherited = false, AllowMultiple = false)]
public sealed class ExcludeFromCodeCoverageAttribute : Attribute
```

you can't use it to annotate whole assembly, effectively making it inconvenient and rarely used. And instead you have to mess up with the XML hell within Run Settings.

**Comment by AbhitejJohn** [comment]
This attribute never did exist in the framework :) Thinking again Code Coverage isn't attributed directly to the framework as well. Its an offering of the test platform. I believe there is a `SuspendCodeCoverage` class in  [Microsoft.TestPlatform.ObjectModel](https://www.nuget.org/packages/Microsoft.TestPlatform.ObjectModel). If that doesn't work, you could submit an issue at https://github.com/Microsoft/vstest/issues.

**Comment by abatishchev** [comment]
Then who owns Code Coverage and ExcludeFromCodeCoverageAttribute? Visual Studio?

SuspendCodeCoverage won't work since I need to exclude from code coverage assembly level, that it, exclude just particular assemblies, not everything.

**Comment by AbhitejJohn** [comment]
Yes, Code Coverage is a component of the vstest repo I pointed you to but there isn't an `ExcludeFromCodeCoverageAttribute`. Possibly the assembly name where this is defined can give us a clue.
