### ISSUE TITLE
Implement codegen to insert the repo version from arcade

### ISSUE THREAD

**Issue by MarcoRossignoli** [microsoft/testfx#2481]
Here I added templating code at build time to have the correct repo version for telemetry https://github.com/microsoft/testfx/pull/2479

But as suggested we should add a simple codegen and so we should not have the Compile items issue

**Comment by nohwnd** [comment]
original comment: 
I've seen source generators being used for this. e.g. this: https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/SourceGenerators/PSVersionInfoGenerator/PSVersionInfoGenerator.cs

or the one that xunit uses: 

https://github.com/devlooped/ThisAssembly

**Comment by Evangelink** [comment]
See https://github.com/dotnet/sdk/issues/39555

**Comment by Evangelink** [comment]
Won't fix
