### ISSUE TITLE
TestCleanup should not be called if TestInitialize failed

### ISSUE THREAD

**Issue by arnonax** [Microsoft/testfx#250]
## Description
TestCleanup method is called even if TestInitialize failed. 
This is a wrong behavior for 2 reasons:
1. It breaks compatibility with MSTest V1 (see more details about my specific scenario below)
2. IMHO the V1 behavior is the correct one, because if you failed to initialize then you cannot guarantee that you need and can clean. This is similar to the "using(IDisposable) { ... }" behavior: if the code between the parenthesis of the using statement fails, IDisposable does not get called.

## Steps to reproduce

    [TestClass]
    public class ExceptionOnInitializeV2
    {
        [TestInitialize]
        public void Init()
        {
            throw new Exception("Boom!");
        }

        [TestCleanup]
        public void Cleanup()
        {
            MessageBox.Show("TestCleanup");  // THIS SHOULD NOT BE CALLED!!!
        }

        [TestMethod]
        public void Foo()
        {
        }
    }

## Expected behavior
The TestCleanup method should not be called (the message box in the example should not appear)

## Actual behavior
TestCleanup does get called (the message box do appear)

## Environment
OS: Windows 8.1
VS2015 Update 3
MSTest.Framework and MSTest.Adapter: 1.1.8. 

## Notes about the real problem I'm facing: 
I'm trying to port [TestAutomationEssentials](https://github.com/arnonax/TestEssentials).MSTest to MSTestV2. This project implement a generic TestBase class.
In this TestBase class I have some logic inside `TestInitialize` that in a certain condition calls `Assert.Inconclusive(...)`. I also have a `TestCleanup` method that does some stuff. 
In V1, if the mentioned condition is met, then the test fails on as Inconclusive and the `TestCleanup` is not called (which is what I expect), so the final outcome is "Inconclusive". 
In V2, the `TestCleanup` method does get called, but consequently throws an exception because it expects some field to be initialized and it doesn't... This causes the final test outcome to be "Failed" instead of "Inconclusive"...

**Comment by AbhitejJohn** [comment]
@arnonax : Thanks for making this explicit. This was a conscious compat break to give unit test writers a choice to cleanup partially initialized methods. However in order to make the transition from v1 extremely smooth, it does make sense to have some setting to preserve compat.

/cc: @harshjain2 , @pvlakshm

**Comment by arnonax** [comment]
I also want to share my thoughts about TestCleanup, in order to shed some more light on this:
It's usually pretty complicated to write good cleanup code that works in all cases. It's even harder to test that it works correctly in all cases, because cleanup should work both when the test passes and when it fails. And it can fail in many places inside the test... Moreover, TestCleanup is common to all tests in the class, which makes things even more complicated.
Therefore, I propose to use a pattern similar to AddCleanupAction which I described long ago [here](http://blogs.microsoft.co.il/arnona/2014/09/02/right-way-test-cleanup/), and implemented also in [TestAutomationEssentials](https://github.com/arnonax/TestEssentials).
I want to suggest implementing this pattern *inside* MsTestV2, and not as a separate library as I did.

Note: the pattern call also be implemented to use IDisposable instead of Action

**Comment by AbhitejJohn** [comment]
Thanks @arnonax. It does look like the new behavior fixes the `Avoid [TestInitialize]` issue you detail. If I try to draw parallels with what we already have and make things a bit more simpler - Lets assume we have the following class hierarchy `BC`, `DC:BC`, `DDC:DC` and an init-cleanup is a unit of class, we have the following execution in a non-error scenario:
```
BC initialization
DC initialization
DDC initialization
DDC cleanup
DC cleanup
BC cleanup
```
and if `DC initialization` errors out :
```
BC initialization
DC initialization
DDC cleanup
DC cleanup
BC cleanup
```

From the above it is very obvious that calling `DDC cleanup` does not make sense and should be fixed at our end smartly. Although this pattern does not go at a granular level that you put out in the blog, it does scope the problem down. Would you be able to help with fixing this issue?

Also, #140 should help with making this pattern more customizable. Although it wouldn't be in the framework by default, acquiring these extensions via nuget is way more simpler and what we already follow with `MSTest.Assert.Extensions` in the vstest repo.

**Comment by pvlakshm** [comment]
Please see here: https://github.com/Microsoft/testfx/issues/250#issuecomment-325274777 - this is a conscious compat break. we will not be adding a setting to fall back to the old semantics either. As for [this ](https://github.com/Microsoft/testfx/issues/250#issuecomment-328464115)pattern, we can live with it.
