### ISSUE TITLE
Rename MSBuild knob to enable aot engine to `TestEngineName`

### ISSUE THREAD

**Issue by MarcoRossignoli** [microsoft/testfx#2508]
https://github.com/microsoft/testfx/blob/main/src/Package/MSTest.Sdk/Sdk/Sdk.props.template#L9

thanks @baronfel for the suggestion

[AB#1986977](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1986977)

**Comment by Evangelink** [comment]
Different issue: MSTestEngineVersion is defined twice in the linked file (line 11 and 15)

**Comment by MarcoRossignoli** [comment]
> Different issue: MSTestEngineVersion is defined twice in the linked file (line 11 and 15)

I wanted to be sure to not forget it
