### ISSUE TITLE
Bug in UnitTest: UnitTestRunnerTests.RunSingleTestShouldSetTestsAsInProgressInTestContext

### ISSUE THREAD

**Issue by arnonax** [Microsoft/testfx#251]
* Note: this is not a bug in the product itself, but only one its unit tests.

## Description
The above unit test does not call ClassInitialize and AssemblyInitialize at all...

## Steps to reproduce
> What steps can reproduce the defect?
Set a breakpoint inside the lambda expression in the following line:
``DummyTestClassWithInitializeMethods.AssemblyInitializeMethodBody = () => { validator = validator << 2; };``
And run the test in debug. 

## Expected behavior
The breakpoint will be hit.

## Actual behavior
The breakpoint won't be hit.

## Environment
Master branch. Commit: 5665d786

**Comment by AbhitejJohn** [comment]
@arnonax : I'm guessing you are referring to `RunSingleTestShouldCallAssemblyInitializeAndClassInitializeMethodsInOrder`. That unit test does look quite precarious though. 
Tagging @jayaranigarg .
