### ISSUE TITLE
Fix guide `Show complete platform output`

### ISSUE THREAD

**Issue by MarcoRossignoli** [microsoft/testfx#2510]
https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-mstest-runner-integrations#show-complete-platform-output

the command line should report `net test -p:TestingPlatformCaptureOutput=false`

[AB#1986986](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1986986)

**Comment by Evangelink** [comment]
Related doc PR https://github.com/dotnet/docs/pull/39810
