### ISSUE TITLE
TestContext.TestName having a value in Class/Assembly Init is confusing.

### ISSUE THREAD

**Issue by alextolp** [Microsoft/testfx#255]
## Description
TestContext.TestName may report the wrong value during test execution. It appears to cache the value from the first test that runs and doesn't update the value for subsequent tests.

## Steps to reproduce
    [TestClass]
    public class Tests
    {
        private static TestContext testContext;

        private string testName;

        [TestMethod]
        public void Test1()
        {
            Assert.AreEqual(nameof(this.Test1), this.testName);
        }

        [TestMethod]
        public void Test2()
        {
            Assert.AreEqual(nameof(this.Test2), this.testName);
        }

        [TestInitialize]
        public void TestInit()
        {
            this.testName = testContext.TestName;
        }

        [ClassInitialize]
        public static void ClassInit(TestContext context)
        {
            testContext = context;
        }
    }

## Expected behavior
Tests should pass.

## Actual behavior
Test2 fails with: 

Message: Assert.AreEqual failed. Expected:Test2. Actual:Test1. 

note: this is a regression from earlier MSTest versions.

## Environment
VS version: 15.3.1
Framework version: net461
MSTest.TestAdapter version: 1.1.18
MSTest.TestFramework version: 1.1.18

**Comment by alextolp** [comment]
[MSTest.zip](https://github.com/Microsoft/testfx/files/1259032/MSTest.zip)

**Comment by AbhitejJohn** [comment]
Thanks for filing this @alextolp. The code does say we are re-setting the TestContext for every method. Need to re-check what's going wrong here.

**Comment by AbhitejJohn** [comment]
We expect test authors to declare a `public TestContext TestContext {get; set;}` for scenarios like this, so the framework resets the value of that property before running a test. A ClassInitialize on the other hand is called only once for all methods in that class, hence the TestContext passed in there would only end up being useful for session/class level data. Here is the test code that would work for your scenario:

```
[TestClass]
public class Tests
{
    public TestContext TestContext { get; set; }

    private string testName;

    [TestMethod]
    public void Test1()
    {
        Assert.AreEqual(nameof(this.Test1), this.testName);
    }

    [TestMethod]
    public void Test2()
    {
        Assert.AreEqual(nameof(this.Test2), this.testName);
    }

    [TestInitialize]
    public void TestInit()
    {
        this.testName = TestContext.TestName;
    }

    [ClassInitialize]
    public static void ClassInit(TestContext context)
    {
        // Use this TestContext instance within this method context itself for session/class level data.
    }
}

```
That said, I think we can avoid setting the method name in the instance being passed into the ClassInit – That is confusing. We also seem to have a strict criteria that the TestContext property should have the name TestContext(case sensitive) which catches people off-guard. #306 addresses the later. Changing the title of this bug to address the former.

**Comment by pvlakshm** [comment]
The recommendation is to use a public TestContext property.
Although it is confusing to have the test name in the TestContext instance in ClassInit, it is benign and we can live with it.
