### ISSUE TITLE
Get logs in even in success

### ISSUE THREAD

**Issue by AbhishekMarda** [microsoft/testfx#2552]
Currently I'm running MSTest through Azure Pipelines using a VSTest@3 task. I observe that the test output is only done in the case of a failure, but omitted completely in the case of a success. Is there a way to output the logs for a successful tests too?

**Comment by Evangelink** [comment]
I'll move forward by closing this issue. If you need further info, please open a new issue on either VSTest repository (https://github.com/microsoft/vstest) or on Azure Pipelines Tasks (https://github.com/microsoft/azure-pipelines-tasks).
