### ISSUE TITLE
Do implementations of IProperty require serializers?

### ISSUE THREAD

**Issue by bradwilson** [microsoft/testfx#2561]
When implementing [`IProperty`](https://github.com/microsoft/testfx/blob/c64571034ee71d2bd5dc60c99a2df50739e3f8ca/src/Platform/Microsoft.Testing.Platform/Messages/TestNodeProperties.cs#L11), is the implementer responsible for implementing a serializer? If not, what are the serialization rules? Is it using the standard in-box JSON serializer?

**Comment by Evangelink** [comment]
As of today, only the following properties are serializable: https://github.com/microsoft/testfx/blob/c64571034ee71d2bd5dc60c99a2df50739e3f8ca/src/Platform/Microsoft.Testing.Platform/Messages/TestNodeProperties.cs#L329-L333

We have been discussing how to handle serialization about extra properties but decided not to do anything for now as we only have VS/VS Code test explorers as client and we know they don't handle or support custom properties so there is no need to make any serialization.
