### ISSUE TITLE
MSTest SDK does not work with Central Package Management

### ISSUE THREAD

**Issue by plade** [microsoft/testfx#2568]
## Describe the bug

When using MSTest.SDK for a test project under [Central Package Management](https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management), [NU1008](https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1008) is encountered.

> Projects that use central package version management should not define the version on the PackageReference items but on the PackageVersion items: PackageId.

## Steps To Reproduce

- Start with an existing project that uses Central Package Management that has packages defined in a Directory.Packages.props file at root.
- Update the test csproj file to use MSTest.SDK (and optionally update the global.json file to specify version)

## Expected behavior
Project should build and test exe should be produced

## Actual behavior
Nuget Error NU1008 is encountered.

## Additional context
MSTest.SDK has a few PackageReference Includes that clash with Central Package Management. Correct behavior for a dotnet SDK is to either override or not include package versions.

[AB#1994877](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1994877)

**Comment by plade** [comment]
Attempting a fix with #2569

**Comment by MarcoRossignoli** [comment]
> Start with an existing project that uses Central Package Management that has packages defined in a Directory.Packages.props file at root.

Looking at the error I suppose you have some MSTest library inside the `Directory.Packages.props`. If so it will collide with the versions we "fixed" inside the SDK self.

To use the SDK you should remove all the `MSTest.*` packages you've referenced in your solution/projects and rely only on the version you specify inside the SDK. The SDK takes care about the correct set of dependencies. Finally you don't have anymore to know what dependencies are needed to run your tests, we take care of everything and you've only to decide if put the version inside the test project self or use the `global.json` at repository level and share same version (this is our suggested approach to keep everything aligned).
