### ISSUE TITLE
The MSTest runner fails to run when path contains spaces when invoked through `dotnet test`

### ISSUE THREAD

**Issue by gao-artur** [microsoft/testfx#2589]
1. Create a test project in the folder with a space, for example, `New Folder`. Configure it to use the new MSTest runner
```xml
<PropertyGroup>
  <OutputType>Exe</OutputType>
  <EnableMSTestRunner>true</EnableMSTestRunner>
  <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
</PropertyGroup>
```

2. Execute `dotnet test TestProject1.csproj` while in the project folder.
3. Observe the error
> C:\Users\xxx\\.nuget\packages\microsoft.testing.platform.msbuild\1.0.2\buildMultiTargeting\Microsoft.Testing.Platform.MSBuild.targets(228,5): error : Tests failed: The application to execute does not exist: 'C:\New' [C:\N
ew folder\TestProject1\TestProject1.csproj]

[AB#1998729](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1998729)

**Comment by MarcoRossignoli** [comment]
Thanks for reporting this I confirm the issue cc: @Evangelink
