### ISSUE TITLE
Ability to provide a test timeout for every test in a session.

### ISSUE THREAD

**Issue by AbhitejJohn** [Microsoft/testfx#26]
## Description
Currently the timeout for a test is only an attribute apply-able on a test method in code. This cannot be changed without a rebuild of the test code. This request is to add a configurable timeout for each test in a session. This can be achieved via an additional setting in the runsettings section for the adapter like below:
```
<Runsettings>
   <MSTest>
      <TestTimeout>2000</TestTimeout>
   </MSTest>
</Runsettings>
```
So when the above runsettings is provided in a session, every test in that session can run for a maximum of 2000 milliseconds.

**Comment by AbhitejJohn** [comment]
Few spec questions before implementing this:
1. What would happen if a test has its own timeout defined via the `Timeout` attribute? Which takes precedence?
2. All tests running in a session would now become time bound. Can/should a test opt-out?
/cc @pvlakshm

**Comment by pvlakshm** [comment]
1. the attribute closest to the method will win.
2. if a method wants to, it can set a custom time out for itself.

**Comment by mikefourie** [comment]
Any ETA on this?

**Comment by AdamDotNet** [comment]
It looks like this is just about done in #403. So look forward to NuGet 1.3.0 to have it?

**Comment by IanKemp** [comment]
@AdamDotNet Can confirm this is present in 1.3.2 at least, docs still don't reflect it though.

**Comment by smadala** [comment]
@IanKemp It was release in 1.3.0 version. Documented [here](https://github.com/Microsoft/testfx-docs/blob/master/docs/releases.md#130-may-2018).
