### ISSUE TITLE
Test runner does not work with DataSource attribute aplied

### ISSUE THREAD

**Issue by kant2002** [Microsoft/testfx#260]
## Description
Some tests does not run in the test explorer. When any of broken tests in the test run,entire test suite could not run.

## Steps to reproduce
Create test with [DataSource] attribute and [DeploymentItem]
I use CSV file as datasource to be specific.
Something like that.
```
        [TestMethod]
        [TestCategory("ACE")]
        [DeploymentItem(@"YYY\XXXX.Tests\File.csv")]
        [DataSource("Microsoft.VisualStudio.TestTools.DataSource.CSV", "|DataDirectory|\\File.csv", "File#csv", DataAccessMethod.Sequential)]

```

## Expected behavior
Test runner could run my tests

## Actual behavior

```
An exception occurred while invoking executor 'executor://mstestadapter/v2': Не удалось загрузить файл или сборку "System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" либо одну из их зависимостей. Не удается найти указанный файл.
```

or 
```
[8/30/2017 4:17:38 PM Error] An exception occurred while invoking executor 'executor://mstestadapter/v2': Не удалось загрузить файл или сборку "System.IO, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" либо одну из их зависимостей. Не удается найти указанный файл.
```

## Environment
Latest VS 15.3,

**Comment by AbhitejJohn** [comment]
@kant2002: This sounds similar to #216. Do you have an app.config file with redirections?

**Comment by kant2002** [comment]
It is indeed look similar, but 
a) tests always correctly discovered.
b) Issue only broke running
c) I do not have `bindingRedirects` in the App.config now and adding something like
```

  <runtime>
    <dependentAssembly>
      <assemblyIdentity name="System.IO" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
      <bindingRedirect oldVersion="0.0.0.0-4.1.1.0" newVersion="4.1.1.0" />
    </dependentAssembly>
    <dependentAssembly>
      <assemblyIdentity name="System.Runtime" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
      <bindingRedirect oldVersion="0.0.0.0-4.1.1.0" newVersion="4.1.1.0" />
    </dependentAssembly>
    <dependentAssembly>
      <assemblyIdentity name="System.Runtime.Extensions" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
      <bindingRedirect oldVersion="0.0.0.0-4.1.1.0" newVersion="4.1.1.0" />
    </dependentAssembly>
    <dependentAssembly>
      <assemblyIdentity name="System.Reflection" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
      <bindingRedirect oldVersion="0.0.0.0-4.1.1.0" newVersion="4.1.1.0" />
    </dependentAssembly>
  </runtime>
```
Don't change exception message for me. Still could not find `System.IO`

**Comment by kant2002** [comment]
I could not use 'Run all' even when I add `Ignore` attribute to offending tests, I have to remove `TestClass` from entire class, so these tests would not break running suite.

**Comment by kant2002** [comment]
I actually manage to make this run using following configuration
```

  <runtime>
    <dependentAssembly>
      <assemblyIdentity name="System.IO" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
      <bindingRedirect oldVersion="0.0.0.0-4.1.2.0" newVersion="4.1.2.0" />
    </dependentAssembly>
    <dependentAssembly>
      <assemblyIdentity name="System.Runtime" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
      <bindingRedirect oldVersion="0.0.0.0-4.1.2.0" newVersion="4.1.2.0" />
    </dependentAssembly>
    <dependentAssembly>
      <assemblyIdentity name="System.Runtime.Extensions" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
      <bindingRedirect oldVersion="0.0.0.0-4.1.2.0" newVersion="4.1.2.0" />
    </dependentAssembly>
    <dependentAssembly>
      <assemblyIdentity name="System.Reflection" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
      <bindingRedirect oldVersion="0.0.0.0-4.1.2.0" newVersion="4.1.2.0" />
    </dependentAssembly>
  </runtime>
```

In the build I did not see any suggestsion for binding redirects, when I add incorrect binding to version '4.1.1.0' build start correct me, that I should use right version. I miss that, since these suggestions was in the `Build` output, and not in 'Tests'.

**Comment by kant2002** [comment]
Still have a problem with 'Run all', it still does not work. When I run each test project individually using grouping by project, everything works fine, but when I hit 'Run all' I get exception from test runner that it could not find `System.IO`

**Comment by AbhitejJohn** [comment]
That's pretty odd. Should have asked this earlier - Is this a .Net Core test project? 
Depending on that you could add these redirections to the config of the process running the tests to ensure the redirection happens. It should ideally happen through the assembly config file as well though. 
Would you be able to share your project/repro? Do you have parallel enabled?
/cc: @harshjain2

**Comment by kant2002** [comment]
I think #299 will address how I could troubleshoot this. If I discover something odd and reproducible, then I reopen this issue.
