### ISSUE TITLE
--list-tests does not work with --filter

### ISSUE THREAD

**Issue by bmcclory** [microsoft/testfx#2604]
## Describe the bug

Cannot combine --list-tests and --filter options.  --list-tests always dumps all tests and ignores filters.

## Expected behavior

I'd like to be able to e.g. `--list-tests --filter TestCategory=Regression`

## Additional context

I'm trying to do this in order to achieve test parallelization across machines in Azure DevOps, using a technique like the one described here:

https://learn.microsoft.com/en-us/azure/devops/pipelines/test/parallel-testing-any-test-runner?view=azure-devops
https://github.com/idubnori/ParallelTestingSample-dotnet-core

It's a simple algorithm for slicing tests among N agent machines, using the test discovery (--list-tests) output.   If there's a better way to accomplish this with the new MSTest runner, please advise.

[AB#1999683](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1999683)

**Comment by Evangelink** [comment]
Hi @bmcclory,

I was convinced this wasn't working with VSTest but it does. Ok so that's a bug on the runner side.

We will work on providing a fix.

**Comment by bmcclory** [comment]
Thanks for looking into this. While I think it's generally useful for --list-tests to honor --filter, I'm also interested if there are other recommended ways of accomplish my ultimate goal here -- to slice a large test suite up for parallel execution across agents.

The [VSTest Azure DevOps task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/vstest-v3?view=azure-pipelines) offers sophisticated mechanisms for automatically detecting multi-agent parallelism and options slicing test suites by historical execution time.  

I'm not familiar with how much of those orchestration behaviors were provided by VSTest runner or the agent task, but ultimately I'm chasing a similar solution, but need it to be X-Plat (in addition to other benefits of MSTest runner)
