### ISSUE TITLE
MSTEST0014 Shows Incorrect Error Message

### ISSUE THREAD

**Issue by plade** [microsoft/testfx#2606]
## Describe the bug

MSTEST0014 is shown when last parameter of test method is `string[]` and last element of DataRow is also `string[]`
## Steps To Reproduce

For the following test method:
```
        [DataTestMethod]
        [DataRow(
            "123",
            new string[] { "something" },
            null)]
        [DataRow(
            "123",
            null,
            new string[] { "something" })]
        public void TestSomething(
            string x,
            string[] y,
            string[] z)
        {
            Assert.AreEqual("123", x);
            Assert.IsNotNull(y);
            Assert.IsNull(z);
        }
```

I get MSTEST0014 error for the third DataRow where the last element is a `string[]`

## Expected behavior
There should be no error
## Actual behavior
I get error
## Additional context
On first DataRow where the last element is a null I don't see the error.
Looks like this is due to the last parameter being an array, which conflicts with the handling of params.

![Image](https://github.com/microsoft/testfx/assets/2185301/9f8bfa60-68d0-4576-9222-217a59e7a377)

[AB#2000085](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/2000085)

**Comment by Evangelink** [comment]
Hi @plade,

Thanks for raising this issue. I confirm that there is an issue with this case. We will work on a fix and ship it as part of the 3.3 release.
