### ISSUE TITLE
MSTest extension version name is not correct

### ISSUE THREAD

**Issue by MarcoRossignoli** [microsoft/testfx#2626]
https://www.nuget.org/packages/MSTest.TestAdapter/3.3.0-preview.24164.4

<img width="601" alt="image" src="https://github.com/microsoft/testfx/assets/7894084/ba19984b-40d6-4bc2-a43a-6a132b72fb6a">

cc: @Evangelink 

[AB#2005165](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/2005165)

**Comment by Evangelink** [comment]
I confirm this is still buggy on latest built package from `rel/3.3` branch.

**Comment by MarcoRossignoli** [comment]
yeah that's a typo thanks!

**Comment by Evangelink** [comment]
Working on a fix.
