### ISSUE TITLE
Test duration not calculated correctly if tests are executed in parallel. 

### ISSUE THREAD

**Issue by HannoZ** [microsoft/testfx#2628]
## Describe the bug
After adding the Parallize atribute to a test project, I noticed that the test duration that is displayed in Test Explorer is not correct. It displays the sum of the duration of all executed test methods, instead of the actual duration. For example, three tests that take 3 seconds to execute, will display 9 seconds total test duration, even if the actual time is only 3 seconds if the tests are executed in parallel.

## Steps To Reproduce
The following code will demonstrate the behavior:
``` cs
[assembly: Parallelize(Workers = 0, Scope = ExecutionScope.MethodLevel)]

namespace TestProject1
{
    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void TestMethod1()
        {
            Thread.Sleep(3000);
        }

        [TestMethod]
        public void TestMethod2()
        {
            Thread.Sleep(3000);
        }

        [TestMethod]
        public void TestMethod3()
        {
            Thread.Sleep(3000);
        }
    }

    [TestClass]
    public class UnitTest2
    {
        [TestMethod]
        public void TestMethod1()
        {
            Thread.Sleep(2000);
        }

        [TestMethod]
        public void TestMethod2()
        {
            Thread.Sleep(2000);
        }
    }
}
```

## Expected behavior
For ExecutionScope.MethodLevel the expected duration should be 3 seconds.
For ExecutionScope.ClassLevel the expected duration should be 5 (3+2) seconds.
(assuming that the the target machine has suffcient cores to execute all tests in parallel) 

## Actual behavior
Test duration is 13 seconds, which is the total of all separate tests.

**Comment by Evangelink** [comment]
Hi @HannoZ,

Thanks for this bug report! There is indeed some problem with Test Explorer behaviors and sadly there is nothing we can do on MSTest side.

Could you please report the issue on https://developercommunity.visualstudio.com/VisualStudio/report for it to be picked up by Test Explorer team?
