### ISSUE TITLE
unused return value in TestableReflectHelper

### ISSUE THREAD

**Issue by jnyrup** [Microsoft/testfx#263]
In `TestableReflectHelper.SetCustomAttribute` the return value of `Concat` is not used.
```csharp
if (this.customAttributes.ContainsKey(hashcode))
{
	this.customAttributes[hashcode].Concat(values);
}
else
{
	this.customAttributes[hashcode] = values;
}
```

**Comment by harshjain2** [comment]
@jnyrup, Thanks for filing this.

Do you want to take a stab to fix this issue?

**Comment by jnyrup** [comment]
I have some difficulties building and the running the solution.
As I remember my problems are:
* some projects cannot find `UWP.Extensions`/`Extensions.UWP`
* every time I want to run unit tests, I have to open the Task Manager and kill instances of vstest/vstestconsole

So until i (might) get them sorted out, I won't be to try fixing these issues.
I tried the [Contribution Guide](https://github.com/Microsoft/testfx-docs/blob/master/docs/contribute.md#building-with-visual-studiovs) but it seemed a bit out of date?
At least I could find the matching workloads in the VS installer.

**Comment by AbhitejJohn** [comment]
@jnyrup: ah that's odd. I remember setting this up for someone recently and it worked great. What version of VS are you on?
/cc: @khilan2goel

**Comment by jnyrup** [comment]
@AbhitejJohn I'm on VS 15.3.3. 

Here's the list of installed modules from the VS installer (1.11.33287.817):
I had mixed up "workloads" and "individual components", but checked that `.Net desktop development`, `Universal Windows Platform development` and `.Net Core cross-platform development` is installed

<details>

IntelliTrace
Graphics debugger and GPU profiler for DirectX
Windows 10 SDK (10.0.14393.0)
.NET Framework 4 – 4.6 development tools
Blend for Visual Studio
Entity Framework 6 tools
.NET profiling tools
IntelliTrace
Live Unit Testing
Windows Communication Foundation
SQL Server Express 2016 LocalDB
VC++ 2017 v141 toolset (x86,x64)
C++ profiling tools
Windows 10 SDK (10.0.15063.0) for Desktop C++ x86 and x64
Visual C++ tools for CMake
Visual C++ ATL support
Windows 10 SDK (10.0.14393.0)
VC++ 2015.3 v140 toolset for desktop (x86,x64)
.NET Framework 4 – 4.6 development tools
Container development tools
Cloud Explorer
IntelliTrace
.NET profiling tools
Entity Framework 6 tools
Live Unit Testing
Windows Communication Foundation
Git for Windows
Connectivity and publishing tools
.NET profiling tools
Developer Analytics tools
Visual Studio C++ core features
VC++ 2017 v141 toolset (x86,x64)
NuGet package manager
.NET Framework 4.6.1 SDK
TypeScript 2.3 SDK
C# and Visual Basic Roslyn compilers
Static analysis tools
C# and Visual Basic
Razor Language Services
JavaScript and TypeScript language support
WebSocket4Net
JavaScript diagnostics
.NET Portable Library targeting pack
CLR data types for SQL Server
Data sources and service references
Developer Analytics tools
ClickOnce Publishing
.NET Framework 4.5 targeting pack
Windows 10 SDK (10.0.14393.0)
Code Clone
DGML editor
SQL Server Native Client
SQL Server Express 2016 LocalDB
Code Map
MSBuild
.NET Framework 4.6.1 targeting pack
Text Template Transformation
.NET Framework 4 targeting pack
.NET Framework 4.5.1 targeting pack
.NET Framework 4.5.2 targeting pack
.NET Framework 4.6 targeting pack
.NET Framework 4.6.2 SDK
.NET Framework 4.6.2 targeting pack
.NET Framework 4.7 SDK
.NET Framework 4.7 targeting pack
IIS Express
Web Deploy
Windows Universal CRT SDK
Windows 8.1 SDK
VC++ 2015.3 v140 toolset for desktop (x86,x64)
SQL ADAL runtime
Connectivity and publishing tools
SQL Server Command Line Utilities
SQL Server Data Tools
Data sources for SQL Server support
ASP.NET and web development tools
Azure Compute Emulator
Azure Storage Emulator
Azure libraries for .NET
Azure Authoring Tools
Azure Cloud Services core tools
Cloud Explorer
.NET Core runtime
Microsoft Azure WebJobs Tools
Azure development prerequisites
Git for Windows
Visual Studio SDK
GitHub Extension for Visual Studio
Testing tools core features
</details>

In `C:\Program Files\dotnet\sdk` I have
* 1.0.1
* 1.0.4
* 1.1.0
* 2.0.0

In `C:\Program Files (x86)\dotnet\sdk` I have
* 1.0.1
* 1.0.4
* 2.0.0

I tried opening the solution again, and double checked that my fork of the master branch was up to date.
From the Error List:
> Warning		Unable to add a reference to project 'Extension.UWP'.	PlatformServices.Universal.Unit.Tests
> Warning		Unable to add a reference to project 'PlatformServices.Universal'.	PlatformServices.Universal.Unit.Tests
