### ISSUE TITLE
(Regression from V1): When an exception occurs both in a test method and in TestCleanup, only the 2nd exception is reported

### ISSUE THREAD

**Issue by arnonax** [Microsoft/testfx#265]
## Description
> When an exception is thrown from a test method, and then another exception is thrown from TestCleanup, then only the exception from TestCleanup is reported, and the information about the original failure is lost.

## Steps to reproduce
> Run the following test:

```
[TestClass]
public class TestClass
{
    [TestMethod]
    public void TestMethod1()
    {
        throw new Exception("TestMethod");
    }

    [TestCleanup]
    public void Temp()
    {
        throw new Exception("Failure in cleanup");
    }
}
```
## Expected behavior
> The results should show the 2 exceptions as follows:
![expectedresult](https://user-images.githubusercontent.com/9963202/30129522-cec43fd0-934e-11e7-84ce-9f987ce9a6fc.PNG)

## Actual behavior
> Only the Cleanup exception is shown:
![actual](https://user-images.githubusercontent.com/9963202/30129655-4539907a-934f-11e7-93e3-bd602d34dcbe.PNG)

## Environment
> Windows 8.1. Visual Studio 2015 Update 3
> MSTest V2 and Adapter: 1.1.18

**Comment by AbhitejJohn** [comment]
This should be #58 which was fixed in the latest beta releases. Could you please give it a shot and resolve accordingly?

**Comment by arnonax** [comment]
This is indeed the same issue. Resolved.
