### ISSUE TITLE
Display MSTest banner in runner mode

### ISSUE THREAD

**Issue by Evangelink** [microsoft/testfx#2657]
We should display MSTest banner (version, parallelism mode...)

AB#2050327

**Comment by nohwnd** [comment]
Just be aware that people hate banners these days, so please keep it short.

**Comment by Evangelink** [comment]
I had a look and I think the best is to implement a feature on platform side that would allow the framework to either change the main banner or add a complementary info.

This is best handled on platform as we can reuse the logic of no banner, no telemetry (command line, env var...) instead of asking for duplication in multiple places.
