### ISSUE TITLE
Unit Tests Fail With Could not load file or assembly errors when using Entity Framework Core 2.0

### ISSUE THREAD

**Issue by bigswede74** [Microsoft/testfx#266]
## Description
After upgrading my projects to use Entity Framework Core 2.0 most of my unit tests are failing with various assembly errors. Some of the unit tests use the Entity Framework Core InMemory provider to mock database data.

System.IO.FileLoadException: Could not load file or assembly 'Microsoft.EntityFrameworkCore, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' 

System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' 

System.IO.FileLoadException: Could not load file or assembly 'System.ValueTuple, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' 

## Steps to reproduce
1. Create a project that uses Entity Framework Core 2.0 for data access
2. Create a test project that uses Entity Framework Core 2.0 InMemory provider to mock the data access for testing
3. Use the memory provider to verify data in a unit test
4. Unit test fails with below error

System.IO.FileLoadException: Could not load file or assembly 'System.ValueTuple, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' 

## Expected behavior
UnitTests should pass

## Actual behavior
Unit tests fail with below error

System.IO.FileLoadException: Could not load file or assembly 'System.ValueTuple, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' 

## Environment
Visual Studio 2017 15.3.3
Project Console Application targeting .net 4.7 framework
Test Project with NuGetPackages

![image](https://user-images.githubusercontent.com/23264080/30174579-689afe12-93b0-11e7-8382-52276b0a516b.png)

**Comment by AbhitejJohn** [comment]
@bigswede74: Could you help us with a project repro please?

**Comment by bigswede74** [comment]
Hello AbhitejJohn,
Attached is a sample project.
[HelloWorld.zip](https://github.com/Microsoft/testfx/files/1293230/HelloWorld.zip)

**Comment by AbhitejJohn** [comment]
Thanks Brad. Will get back on this.

**Comment by bigswede74** [comment]
Hello @AbhitejJohn 
Any movement on this issue?
Thanks

**Comment by AbhitejJohn** [comment]
@bigswede74: Looks like a .Net issue reported at https://github.com/dotnet/standard/issues/476 and https://github.com/aspnet/EntityFrameworkCore/issues/9046. The workaround with bindingredirects worked for me on the repro you shared.

**Comment by bigswede74** [comment]
@AbhitejJohn Where do the bindingredirects go, in the app.config for the test project?

**Comment by bigswede74** [comment]
@AbhitejJohn the problem with this fix is when you add the app.config file to a test project the tests disappear from the text explorer and are no longer discoverable.

see issue
https://developercommunity.visualstudio.com/content/problem/32282/test-explorer-doesnt-populate-with-tests.html

**Comment by AbhitejJohn** [comment]
@bigswede74: That's odd. That issue seems to be talking about a stale config file. This config file [Appconfig.zip](https://github.com/Microsoft/testfx/files/1321634/Appconfig.zip) works for me. Can you give it a shot please?

**Comment by bigswede74** [comment]
@AbhitejJohn when adding the app.config file you sent I now just get 2 errors for the same assembly.

System.IO.FileNotFoundException: Could not load file or assembly 'System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified. ---> 

System.IO.FileNotFoundException: Could not load file or assembly 'System.ValueTuple, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified..

**Comment by bigswede74** [comment]
@AbhitejJohn the assembly redirect worked.
