### ISSUE TITLE
Move runsettings documentation for the runner under the runner docs

### ISSUE THREAD

**Issue by MarcoRossignoli** [microsoft/testfx#2663]
Move https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-platform-runsettings into a section under https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-mstest-runner-intro

**Comment by Evangelink** [comment]
Why? These information are true for any test framework using VSTest bridge

**Comment by MarcoRossignoli** [comment]
> Microsoft.Testing.Platform allows you to provide a [VSTest .runsettings file](https://learn.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file)

This is a bit confusing to me....`Microsoft.Testing.Platform` doesn't know nothing about xml configuration and it's not using it, we ship a layer for `VSTest` but it's not part of the new platform, I wonder if at least we should explain better what it means "support runsettings".

**Comment by Evangelink** [comment]
I think the best would be to declare VSTEst bridge under the extensions and have a specialized page there that documents some of the features (including runsettings).

On MSTest side, we should clearly have a section mentioning runsettings that points to this doc, so that's easy to discover.

**Comment by Evangelink** [comment]
Closing as it will be addressed by https://github.com/dotnet/docs/pull/40380 and https://github.com/dotnet/docs/pull/40377
