### ISSUE TITLE
Simplify platform banner

### ISSUE THREAD

**Issue by Evangelink** [microsoft/testfx#2681]
## Summary

Simplify current platform banner

## Background and Motivation

Multiple dotnet projects are moving toward a simplified banner and there is a similar request on VSTest https://github.com/microsoft/vstest/issues/4869 so I think we should consider something similar here.

## Proposed Feature

Move from

```txt
Microsoft(R) Testing Platform Execution Command Line Tool
Version: 3.4.0-dev (UTC 2024/04/09)
RuntimeInformation: win-x64 - .NET 8.0.3
Copyright(c) Microsoft Corporation.  All rights reserved.
```

to

```txt
Microsoft Testing Platform version 3.4.0-dev (UTC 2024/04/09) [win-x64 - .NET 8.0.3]
```

[AB#2021757](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/2021757)

**Comment by MarcoRossignoli** [comment]
```
Microsoft Testing Platform v3.4.0-dev (UTC 2024/04/09) [win-x64 - .NET 8.0.3]
```

**Comment by Evangelink** [comment]
What about replacing `MS` with `.NET` so we would have `.NET Testing Platform v3.4.0-dev (24/04/09) [win-x64 - .NET 8.0.3]`

**Comment by MarcoRossignoli** [comment]
I agree!

**Comment by MarcoRossignoli** [comment]
wondering if somewhere we should add the module name `.NET Testing Platform v3.4.0-dev (24/04/09) [win-x64 - .NET 8.0.3] - Contoso.Tests.dll`

**Comment by Evangelink** [comment]
I am more afraid about confusions when we would have either multi-module cases or when you start to run with `dotnet test` but maybe this isn't a strong concern.

**Comment by nohwnd** [comment]
looks good, would keep 2024 in the date, it is not super easy to tell what it is without it. 

is 3.4.0 MStest version but not the testing.platform version? What should xunit / nunit show if they use the new platform?

**Comment by Evangelink** [comment]
> is 3.4.0 MStest version but not the testing.platform version?

Mistake from me, I have run from my local so we are showing MSTest version but the final product is shipped from the other repo where the version is aligned.

> What should xunit / nunit show if they use the new platform?

MSTest and other framework will have that display by default but #2657 will allow to either add extra line or replace current (depends on the design decisions we make there).

**Comment by nohwnd** [comment]
In that case: 

``` .NET Testing Platform v1.1.0-dev (2024/04/09) [win-x64 - .NET 8.0.3] ``` seems great..

What is the meaning of the date? Is that when the package was released or built?

**Comment by MarcoRossignoli** [comment]
> What is the meaning of the date? Is that when the package was released or built? Or is that todays date?

Build day
