### ISSUE TITLE
Add documentation for `--minimum-expected-tests` `--filter` and `--settings`

### ISSUE THREAD

**Issue by MarcoRossignoli** [microsoft/testfx#2684]
Add documentation for `--minimum-expected-tests` here https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-platform-intro?tabs=dotnetcli#options

 `--filter` and `--settings` here https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-mstest-runner-intro

**Comment by Evangelink** [comment]
Closing as doc update is merged.
