### ISSUE TITLE
Remove IsPackable from the DemoMSTestSdk

### ISSUE THREAD

**Issue by Varorbc** [microsoft/testfx#2695]
## Summary

https://github.com/microsoft/testfx/blob/0b7e9b53dd97c69da1b61b559867d0083ad2cc6c/samples/DemoMSTestSdk/ProjectUsingMSTestRunner/ProjectUsingMSTestRunner.csproj#L7

**Comment by Evangelink** [comment]
That's indeed defined into the SDK, thanks for catching that @Varorbc <3
