### ISSUE TITLE
[UWP] [loc] in release does not localize messages from TestPlatform Framework

### ISSUE THREAD

**Issue by mayankbansal018** [Microsoft/testfx#27]
## Description
> Messages from Framework are not localized

## Steps to reproduce
1. Install VS on a German machine, & create a UWP Test project
2. Add Assert.AreEqual(1,2)
3. Compile in release mode, & run tests.

## Expected behavior
> Failure message should be localized

## Actual behavior
> Failure message is not localized

## Environment
> Please share additional details about the test environment.
> Operating system, Build version of vstest.console, Package version of MSTest
> framework and adapter

**Comment by pvlakshm** [comment]
@mayankbansal018, please verify and close.

**Comment by jayaranigarg** [comment]
This is an issue with UWP in release mode and is not actionable on our end.
