### ISSUE TITLE
AssertInstanceOf overloads with out parameter

### ISSUE THREAD

**Issue by Mrxx99** [microsoft/testfx#2702]
## Summary

I would like new generic AssertInstanceOf overloads that have an additional out parameter with the casted instance.

## Background and Motivation

I always missed and out parameter for the casted instance that was validated with AssertInstanceOf.
Often I first checked with AssertInstanceOf and in following asserts I want to assert properites on that object as instance of that just validated type, so I always have to cast. But that always felt redundant, as a type check was done with AssertInstanceOf, it just didn't provide a casted instance back.

## Proposed Feature

New overloads of all (3) generic AssertInstanceOf overloads but with and additional out parameter which cast the value to the generic type parameter.

```csharp
public static void IsInstanceOfType<T>([NotNull] object? value, out T instance);
public static void IsInstanceOfType<T>([NotNull] object? value, out T instance, string? message);
public static void IsInstanceOfType<T>([NotNull] object? value, out T instance, string? message, params object?[]? parameters);
```

I have a branch ready for a PR.

## Alternative Designs

~~I don't know of any.~~
Returning T instead, see discussion below

**Comment by Evangelink** [comment]
Thanks @Mrxx99 ! I think that's a good addition, maybe we could have a return type instead of a out.

**Comment by Mrxx99** [comment]
Having a return type could work too, but you can't add new overloads with just a different return type, so the existing ones would need to change, which would be a breaking change. Not only a binary breaking change (at least I think it is) but also a source breaking change if one e.g. puts the method into an action variable (I guess unlikely but possible).
Also IMO that would be less discoverable because people are used to it not having a return value and I guess it would be the only Assert with a return value (except ThrowsException, but that is kind of special). While new APIs with a new out parameter would be easily discoverable with intellisense.

Would be ok for me though, if you say none of these concerns matter enough.

**Comment by Evangelink** [comment]
@Mrxx99 Would you be interested in contributing these additional APIs? I would start with the `out` to avoid any breaking change. We will do a breaking change in v4 and obsolete the out API there.

**Comment by gao-artur** [comment]
FYI, I sent a PR with a return value a while ago, but it was merged into the `dev/4.0.0` branch because of the breaking change.
- https://github.com/microsoft/testfx/pull/1715

**Comment by Evangelink** [comment]
@gao-artur I am really sorry! We did plan to be working on v4 and started to merge many things and then priorities were switched and it seems we forgot to move this change back... Again sorry.

**Comment by gao-artur** [comment]
No need to sorry 🙂

> We will do a breaking change in v4 and obsolete the out API there. 

Just wanted to remind you that this API is already implemented in v4.
