### ISSUE TITLE
Warning "TestClass attribute defined on generic non-abstract class" cannot be disabled/ignored

### ISSUE THREAD

**Issue by nietras** [microsoft/testfx#2723]
## Describe the bug
Running MSTest on attached project causes warning. This we have observed for a long time previously (e.g. 3.2.2) this was `UTA001`. Using MSTest 3.3.1 and now the below warning occurs.
```
[MSTest][Discovery][C:\git\issues\MSTestUTA001\Reproduction.Settings.Test\bin\Debug\net8.0\Reproduction.Settings.Test.dll] 
TestClass attribute defined on generic non-abstract class Reproduction.Settings.Test.ProjectSettingsTestBase`1
```
While this warning is fine, it is not possible to disable it, which we would like.

## Steps To Reproduce
1. Download [MSTestUTA001.zip](https://github.com/microsoft/testfx/files/15009883/MSTestUTA001.zip)
2. Extract somewhere
3. Run `dotnet test`
4. See warning

## Expected behavior
Possibility to disable the warning and hence avoid it.

## Actual behavior
Warning.

I understand the coding pattern is perhaps a bit unusual but it allows us to reuse tests across many different types, without having to rewrite TestMethod stuff, so unless this can be done similarly we would like to disable the warning. Preferable for the specific types.

AB#2050329

**Comment by Evangelink** [comment]
Hi @nietras! Thanks for the bug report and the cool repro!

I have done a quick investigation of the issue and I think there is a relatively big problem with the type cache on MSTest. Indeed, the cache is retrieving attributes using inheritance and although the validation method asks for non-inherited attributes, because of the cache, we retrieve inherited and so we end up reporting.

**Comment by nohwnd** [comment]
The new implementation for the cache is storing inherited and non-inherited attributes separately, fixing the issue that @Evangelink found out in his investigation. Using version 3.5.0-preview.24317.3 does not reproduce the problem anymore.

Repro: 
![image](https://github.com/microsoft/testfx/assets/5735905/1e79f8b3-1911-4a65-b499-4761456c3881)


upgraded to latest mstest: 
![image](https://github.com/microsoft/testfx/assets/5735905/049702b3-bd76-459f-99f9-a94163a432d8)

**Comment by Evangelink** [comment]
@nohwnd Could we still add this test case so we don't regress if we change/fix implementation later on.

**Comment by nohwnd** [comment]
Using the repro seemed difficult in our setup, because it relies on 2 assemblies. So I am testing the root cause rather than the symptom.
