### ISSUE TITLE
UnauthorizedAccessException thrown as MSTest.Sdk tries to create TestResults in .NET installation directory

### ISSUE THREAD

**Issue by martincostello** [microsoft/testfx#2733]
## Describe the bug

Running `dotnet test` in a folder containing a solution that has a project using the MSTest.Sdk SDK fails due to the SDK trying to create the `TestResults` folder in the .NET installation folder (e.g. `C:\Program Files\dotnet`).

## Steps To Reproduce

1. Clone https://github.com/martincostello/alexa-london-travel/commit/f8ab76f6a15535f0a33528147f9599984ab3c474
2. Run `dotnet test` in the root of the repository

## Expected behavior

The command succeeds, with `TestResults` being created in the project directory if it does not exist.

## Actual behavior

An error is logged to the console when `dotnet test` tries to run the `LondonTravel.Skill.NativeAotTests` project as it tries to create the directory in the wrong location, which is in a protected system folder:

```text
C:\Users\Martin.Costello\.nuget\packages\microsoft.testing.platform.msbuild\1.1.0\buildMultiTargeting\Microsoft.Testing.Platform.MSBuild.targets(228,5): error : Tests failed: Unhandled exception. System.UnauthorizedAccessException: Access to the path 'C:\Program Files\dotnet\TestResults' is denied. [C:\Coding\martincostello\alexa-london-travel\test\LondonTravel.Skill.NativeAotTests\LondonTravel.Skill.NativeAotTests.csproj]
C:\Users\Martin.Costello\.nuget\packages\microsoft.testing.platform.msbuild\1.1.0\buildMultiTargeting\Microsoft.Testing.Platform.MSBuild.targets(228,5): error :    at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor) [C:\Coding\martincostello\alexa-london-travel\test\LondonTravel.Skill.NativeAotTests\LondonTravel.Skill.NativeAotTests.csproj]
C:\Users\Martin.Costello\.nuget\packages\microsoft.testing.platform.msbuild\1.1.0\buildMultiTargeting\Microsoft.Testing.Platform.MSBuild.targets(228,5): error :    at System.IO.Directory.CreateDirectory(String path) [C:\Coding\martincostello\alexa-london-travel\test\LondonTravel.Skill.NativeAotTests\LondonTravel.Skill.NativeAotTests.csproj]
C:\Users\Martin.Costello\.nuget\packages\microsoft.testing.platform.msbuild\1.1.0\buildMultiTargeting\Microsoft.Testing.Platform.MSBuild.targets(228,5): error :    at Microsoft.Testing.Platform.Helpers.SystemFileSystem.CreateDirectory(String path) in /_/src/Platform/Microsoft.Testing.Platform/Helpers/System/SystemFileSystem.cs:line 10 [C:\Coding\martincostello\alexa-london-travel\test\LondonTravel.Skill.NativeAotTests\LondonTravel.Skill.NativeAotTests.csproj]
```

## Additional context

None.

[AB#2045304](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/2045304)

**Comment by nohwnd** [comment]
Thank you this is an interesting case. We check IsDynamicCodeSupported, which is False when you set PublishAot to true, no matter if you actually compiled as native (which is [by design](https://github.com/dotnet/runtime/issues/81803). The task calls the exe as dotnet test.dll, so we end up picking up location of dotnet.exe as the working directory.
