### ISSUE TITLE
vstest.console.exe does not discover 100k tests in a single project

### ISSUE THREAD

**Issue by preetsaimutneja** [Microsoft/testfx#275]
## Description
> vstest.console.exe does not discover 100k tests in a single project.

## Steps to reproduce
> Create a project with a .cs file containing 100k tests.
> After build, try to run tests using vstest.console.exe tests.dll

## Expected behavior
> Tests should run

## Actual behavior
> No tests are discovered. However, running 10k tests in a single project works fine.

## Environment
> Windows 10 version 10.0.15063, vstest.console 15.0.26720.2

**Comment by pvlakshm** [comment]
Not a real life case (at least from what we have seen till now).
