### ISSUE TITLE
Associate to Test Case in TFS broken

### ISSUE THREAD

**Issue by andresla** [Microsoft/testfx#278]
## Problem
1) Cannot associate test case to test in TFS, possible though workaround (see below) .
2) Description Attribute does not allow workaround

## Steps to reproduce

- Create new Test Project
- Check MSTest.TestAdapter 1.1.18 & MSTest.TestAdapter 1.1.18 are installed
- UnitTestClass1.cs looks like this:
`using System;`
`using Microsoft.VisualStudio.TestTools.UnitTesting;`
`namespace UnitTestProject1`
`{`
` [TestClass]`
`  public class UnitTest1`
`    {`
`        [TestMethod]`
`        public void TestMethod1()`
`        {`
`        }`
`    }`
`}`
- Build Test Project
- Verify you have access to a TFS having a Testcase
- TestMethod1 can be found in test explorer window
- Right click test

## Expected behavior
Associated automation should be available.
## Actual behavior
Associated automation is grayed out.

## Workaround for literal 1) in Problem:
**Precondition:** Do Steps to Reproduce

- Open **TFS** Test Case in Visual Studio
- Go to "Associated Automation Tab"
- Click on "Associate an automated test with this test case"
- Test is listed and can be added

**Note:** This workaround does not work with literal 2):
`        [TestMethod]`
`        [Description("MyDescription")]`
`        public void TestMethod1()`
`        {`

**Note 2:** Both cases work correctly using "Microsoft.VisualStudio.QualityTools.UnitTestFramework "

## Environment
OS: Windows 10
VS2017 Enterprise: 15.3.5
MSTest.TestAdapter 1.1.18
MSTest.TestFramework 1.1.18
TFS 2017 Update 1

**Comment by AbhitejJohn** [comment]
@abhishkk : Can you help please?

**Comment by AbhitejJohn** [comment]
@andresla : There is an active story tracking this support in our backlog. We do not have a clear timeline on this yet.
/cc: @pvlakshm, @PBoraMSFT

**Comment by andresla** [comment]
@AbhitejJohn Thank you for your answer

**Comment by jayaranigarg** [comment]
https://github.com/Microsoft/testfx/issues/353
