### ISSUE TITLE
Consider making `NopFilter` public

### ISSUE THREAD

**Issue by thomhurst** [microsoft/testfx#2787]
Currently NopFilter is internal. However it's the default filter being passed in if doing a basic `dotnet run` on your test suite.

If we `switch` on the Type of an `ITestExecutionFilter`, we're unable to see the NopFilter.

I think it should be public so we can see it when checking the type of filter we've been passed.

**Comment by MarcoRossignoli** [comment]
like explained in the guide the filter is in experimental internal mode https://github.com/microsoft/testfx/blob/main/docs/testingplatform/irequest.md#discovertestexecutionrequest but I'd like to find a way to let you use it and feedback us and help to shape it

cc: @Evangelink
