### ISSUE TITLE
Tests fail to run with error "Could not find part of path 'C:\'."

### ISSUE THREAD

**Issue by clementhervy** [Microsoft/testfx#279]
## Description
I created a solution with one library project, one console application project and a test project from the VS2017 template. After writing a few classes and tests, I tried running them but it stops after discovery. They appear in the test explorer window, but the following error message appears in the output:
`Une exception s'est produite lors de l'appel de l'exécuteur 'executor://mstestadapter/v2' : Impossible de trouver une partie du chemin d'accès 'C:\'.`

Which can be translated to:
`An exception occurred while invoking executor 'executor://mstestadapter/v2': Could not find part of path 'C:\'.`

As an addition: my Windows user account is named "---", without the quotes. The solution is in a subdirectory of the user folder, therefore "\---\" is part of its path.

## Steps to reproduce
- Create a console application from VS2017 template.
- Create a test project from VS2017 template.
- Write some tests that should fail.
- Run them.

## Expected behavior
Tests run.

## Actual behavior
Running tests stops after discovery and before running with message:
`An exception occurred while invoking executor 'executor://mstestadapter/v2': Could not find part of path 'C:\'.`

## Environment
Windows 10, Visual Studio 2017 v15.3.5, MSTest Adapter and Framework v1.1.18.
All projects target framework v4.6.1.

**Comment by pvlakshm** [comment]
I am unable to repro this on a similar setup.
In the issue description you mention " one library project, one console application project and a test project", whereas the repro steps only call out the creation of a console app and a test project. Are any steps missing? Can you provide more details, please.

**Comment by pvlakshm** [comment]
Please reactivate if this is still blocking you.

**Comment by clementhervy** [comment]
Finally had the time to look into this issue, at the time I had to go on with the project.

The problem described still happens, but only on my laptop, not on my other computer with a fresh VS2017 install.

I updated VS2017 and created a super, simple solution with just a class library and a test project. You can find it at [github.com/clementhervy/fixing-mstest](https://github.com/clementhervy/fixing-mstest).

I tried clearing the following folders before restarting VS and running the tests again: package, TestResults, bin and obj in both projects, VisualStudioTestExplorerExtensions in %Temp%, mstest.testadapter and mstest.testframework in Users\username\.nuget\packages
It did not solve the problem.

I set the VS_UTE_Diagnostics environment variable which does make the test discovery more verbose, but doesn't give any other info on the error.

Can you please explain the logging step better? In what console do I need to enter the line? Is that the full command?

**Comment by clementhervy** [comment]
@pvlakshm I added some info a while back, care to have a look? Thank you!

**Comment by jayaranigarg** [comment]
@clementhervy : Apologies for the delay. Since the issue was closed, we were not tracking it. Reactivating the issue will help us keep track of it :)

I tried running the repro solution shared by you but it works perfectly fine for me.

If you are on VS2017 15.5, then please collect traces like [this](https://github.com/Microsoft/vstest-docs/blob/master/docs/diagnose.md#collect-traces-using-command-line)
If you are on a  version prior to 15.5, please enable vstest.executionengine.*.exe logging. [Here ](https://blogs.msdn.microsoft.com/aseemb/2012/03/01/how-to-enable-ute-logs/)is how to do that.
