### ISSUE TITLE
Where can I find ITestDataSource?

### ISSUE THREAD

**Issue by hsinyij** [Microsoft/testfx#280]
May I know which nuget package and version I can use for the interface ITestDataSource? Thanks.

**Comment by AbhitejJohn** [comment]
@hsinyij : You can use this nuget package :
https://www.nuget.org/packages/MSTest.TestFramework/1.2.0-beta3. This is currently in beta.

**Comment by hsinyij** [comment]
I used the 1.2.0-beta3 but the ITestDataSource was not defined there and that is why I asked this question. Thanks.

**Comment by AbhitejJohn** [comment]
Here is the code: https://github.com/Microsoft/testfx/blob/master/src/TestFramework/MSTest.Core/Interfaces/ITestDataSource.cs . Are you looking at [MSTest.TestFramework](https://www.nuget.org/packages/MSTest.TestFramework/1.2.0-beta3)?

**Comment by hsinyij** [comment]
Yes. I checked MsTest.TestFramework 1.2.0-beta3, but the interface
ITestDataSource is not in the package. Please let me know. Thanks a lot.

**Comment by AbhitejJohn** [comment]
That's odd! Can you share the project you are trying this on?

**Comment by AbhitejJohn** [comment]
@hsinyij : pinging back on this and reopening this issue.
