### ISSUE TITLE
Where can I find ITestDataSource? It is not in 1.2.0-beta3!!!

### ISSUE THREAD

**Issue by hsinyij** [Microsoft/testfx#281]
Where can I find ITestDataSource? It is not in 1.2.0-beta3!!! Thanks.

**Comment by AbhitejJohn** [comment]
Closing this in favor of #280.

**Comment by hsinyij** [comment]
Hi Abhitej,

I found it in the latest version. Thanks a lot.

Sincerely,

Hsin-yi Jiang
