### ISSUE TITLE
Add CodeFixProvider for MSTEST0010

### ISSUE THREAD

**Issue by Youssef1313** [microsoft/testfx#2826]
## Summary

The analyzer MSTEST0010 could easily have an associated CodeFixProvider.

## Background and Motivation

I'm currently enabling MSTest.Analyzers in a codebase with quite good amount of violations for this analyzer. It makes the life easier to have an associated code fix.

**Comment by Evangelink** [comment]
Hi @Youssef1313,

We have received a few internal requests to add code fixes, I just didn't take time yet to create the issue and work on the infra.
