### ISSUE TITLE
[3.4 preview] Test parameter type check is very strict

### ISSUE THREAD

**Issue by cremor** [microsoft/testfx#2828]
## Describe the bug
After updating MSTest from 3.3.1 to 3.4.0-preview.24257.1 I noticed that one of my data driven tests now fails because of a method parameter type mismatch. But the test ran fine in all versions before 3.4.

## Steps To Reproduce
Example test:
```cs
      [TestMethod]
      [DataRow("Field", "Customer", 1, null)]
      public void TestMethod(string field, string entityType, long entityId, string richTextValue)
      {
      }
```

## Expected behavior
Test passes.

## Actual behavior
Test fails with this message:

```
Test data doesn't match method parameters. Either the count or types are different.
Test expected 4 parameter(s), with types 'String, String, Int64, String',
but received 4 argument(s), with types 'String, String, Int32, null'.
```

## Additional context
I assume the problem is only Int32 vs. Int64.
Is this type check so strict on purpose? Isn't the implicit conversion (which worked in older MSTest versions) enough?

I think this is caused by #2691

**Comment by nohwnd** [comment]
That is a good point. 

The new code seems to be too clever for its own good. We should probably give up on validating the types beforehand, and just use the logic to figure out if we are handing params parameters or not and then wait if the test fails with "Parameter count mismatch" exception, and throw our better exception.
