### ISSUE TITLE
Support for params in DataRow

### ISSUE THREAD

**Issue by jnyrup** [microsoft/testfx#283]
## Description
Currently, if you want to test a different number of arguments you have to wrap them.
```c#
[TestMethod]
[DataRow(new[] { 1 })]
[DataRow(new[] { 42, 43 })]
[DataRow(new[] { 100, 200, 300 })]
public void MyTestMethod(IEnumerable<int> integers)
{
    ...
}
```

In the test explorer this the following undesirable output.
![image](https://user-images.githubusercontent.com/919634/31320184-825aed7a-ac70-11e7-823e-ca6884b803fa.png)

It would be nice if `DataRow` supported methods with `params` argument like this:
```c#
[TestMethod]
[DataRow(1)]
[DataRow(42, 43)]
[DataRow(100, 200, 300)]
public void MyTestMethod(params int[] integers)
{
    ...
}
```

This is probably related to #252

**Comment by Haplois** [comment]
Support added for this with #604.
