### ISSUE TITLE
Overloaded test method is not recognized

### ISSUE THREAD

**Issue by schibu007** [microsoft/testfx#2859]
## Describe the bug
Overloaded test methods (attributed with `[TestMethod]`) are not recognized by MSTest and are therefor **silently ignored**.

## Steps To Reproduce
Consider following class:
```cs
[TestClass]
public sealed class Tests
{
    [TestMethod]
    public void Test() { }

    [TestMethod]
    [DataRow(123)]
    public void Test(int arg) { }
}
```
When you execute them in VS, you'll get this result:
![image](https://github.com/microsoft/testfx/assets/45459443/233924f2-5975-498d-a81c-9cce637aa7b9)

Note, that the result of the overloaded test method `Test(int arg)` is missing.

## Expected behavior
Either the overloaded test method should be recognized/executed, or an analyzer should prevent test method overloading.

## Actual behavior
The overloaded test method is not recognized by MSTest.

**Comment by Evangelink** [comment]
Overloads are currently not supported in MSTest. I was pretty sure we had a similar request but I cannot find it back.

I'll keep this ticket open as feature request to either add support for it or add an analyzer.

**Comment by schibu007** [comment]
@Evangelink thanks for the fast response. Based on your answer I searched again and found this issue [1235](https://github.com/microsoft/testfx/issues/1253). I guess you could close this issue then as a duplicate.
