### ISSUE TITLE
MSTESTXXXX: Type contaning `[TestMethod]` must be a `[TestClass]`

### ISSUE THREAD

**Issue by nohwnd** [microsoft/testfx#2862]
## Summary

Add **usage** analyzer that ensures that a non abstract class with `[TestMethod]` is marked with `[TestClass]`.

## Background and Motivation

Discoverer looks for classes that have attribute derived from `[TestClass]`, and does not look through inheritance chain (parent classes).

https://github.com/microsoft/testfx/blob/main/src/Adapter/MSTest.TestAdapter/Discovery/TypeEnumerator.cs#L55
https://github.com/microsoft/testfx/blob/main/src/Adapter/MSTest.TestAdapter/Discovery/TypeValidator.cs#L54

Not marking a class as `[TestClass]` is an easy way to lose tests, and currently there is no build time, or runtime warning. 

## Proposed Feature

Ensure that when a method has `[TestMethod]` attribute, it is defined by a class that is marked as `[TestClass]`. Skip this rule for abstract classes, because they are used to inherit tests to concrete classes.

q: do we see those inherited methods on a type? we should ensure that type is testClass as well (most likely, unless the user does some complex inheritance chain).

Examples: 

```
namespace TestProject97
{


namespace TestProject97
{
    // SCENARIO1
    // No test class, this loses tests. Would show WARNING.
    // User can either add [TestClass] or mark the class as abstract, if they only intend to inherit the tests.

    public class WithTestMethods_WithoutTestClass
    {
        [TestMethod]
        public void TestMethod1()
        {
        }

        [TestMethod]
        public void TestMethod2()
        {
        }
    }

    // SCENARIO2
    // This test class will inherit parent tests. 2 tests will run from here.
    [TestClass]
    public class WithoutTestMethods_WithTestClass : WithTestMethods_WithoutTestClass
    {

    }

    // This test class will inherit parent tests. Should it show WARNING? IMHO yes.
    public class WithoutTestMethods_WithoutTestClass : WithTestMethods_WithoutTestClass
    {

    }

    // This test class has no tests,
    // it is in examples only to prove that TestClass
    // is not looked up with inheritance (by checking parent class).
    [TestClass]
    public class ParentWithTestTestClass
    {

    }

    // SCENARIO3:
    // Those tests won't run, WARNING should show, the parent class [TestClass] won't be respected, because we don't search
    // inheritance.
    public class ChildWithoutTestClass : ParentWithTestTestClass
    {
        [TestMethod]
        public void TestMethod1()
        {
        }

        [TestMethod]
        public void TestMethod2()
        {
        }
    }

    // SCENARIO4
    // This a valid test class. 2 tests will run from here.
    [TestClass]
    public class UnitTest2
    {
        [TestMethod]
        public void TestMethod1()
        {
        }

        [TestMethod]
        public void TestMethod2()
        {
        }
    }
}

```

```
Microsoft(R) Testing Platform Execution Command Line Tool
Version: 1.1.0+8c0a8fd8e (UTC 2024/04/03)
RuntimeInformation: win-x64 - .NET 9.0.0-preview.4.24218.7
Copyright(c) Microsoft Corporation.  All rights reserved.
[MSTest][Discovery][C:\Users\jajares\source\repos\TestProject97\TestProject97\bin\Debug\net9.0\TestProject97.dll] MSTestAdapter failed to discover tests in class 'TestProject97.ChildWithoutTestClass' of assembly 'C:\Users\jajares\source\repos\TestProject97\TestProject97\bin\Debug\net9.0\TestProject97.dll' because Object reference not set to an instance of an object..
Passed! - Failed: 0, Passed: 4, Skipped: 0, Total: 4, Duration: 152ms - TestProject97.dll (win-x64 - .NET 9.0.0-preview.4.24218.7)
```

## Alternative Designs

None.

AB#2112216

**Comment by nohwnd** [comment]
The warning is also curious, but probably for a different issue.

**Comment by Evangelink** [comment]
Rule should be **enabled by default** but severity should be set to **Info** as it's still valid to not have the class `abstract` or marked with `[TestClass]` if it is only intended to be inherited.

I am wondering if the category should be `Design` more than `Usage` as we are not sure if that's a true problem. We are more trying to help people design their test suite to make it obvious if the test has to be run or inherited.

**Comment by nohwnd** [comment]
I was hoping for warning, and enabled by default, because this is a simple way to lose tests and there is no runtime error, we can add one but you would probably consider this a breaking change. 

While analyzer warnings and downgrading the severity is easy to do, for the case where you want a base class but it should not be abstract, which I don't know why you would need.

**Comment by Evangelink** [comment]
> you would probably consider that a breaking change

Yes, for most teams, they have warnings as errors. Bumping a minor version should not cause errors (by default) that are not linked to something that would not work at runtime.

I agree that it's more likely than not to be a case where the `[TestClass]` is missing and I do expect many teams to want to make this a warning by default. But that's tricky to expect "proper" design as default, for example, I personnaly expect any class to be created as `sealed` by default except if my design does want some potential inheritance but my experience shows that most devs won't make their classes sealed.

**Comment by nohwnd** [comment]
> we can add one but you would probably consider that a breaking change.

here I was talking about adding a runtime failure to the framework, (e.g. like UTAxxx test method is contained in non-test class). We don't have any advanced tooling around this. But we do this tooling around analyzers.

So the proposal was to add the warning, because it is super easy to downgrade (or upgrade) that, even if it causes additional warning being printed in the new version. 

Is the comparison with `sealed` fair? We are one of the teams that force warnings to be errors, and often when we update dotnet SDK we do get bunch of new errors coming from analyzers, and I don't think they only happen across major versions? or maybe that is just because we use preview net9 sdk, and there is a policy that analyzers should not produce new warnings in a stable version?

**Comment by Evangelink** [comment]
Analyzer part of the feature: 

I think it should be enabled by default as Info. 

It cannot be warning because the rule is not covering all scenarios. For example, it's valid to have a non-abstract class containing test methods, if it exists a class marked with `[TestClass]` that inherits from this type. For the same reason, we cannot simply extend [MSTEST0002: Test classes should have valid layout](https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0002) or [MSTEST0003: Test methods should have valid layout](https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0003).

Implementation details: callback on `INamedTypeSymbol`, check that it's a non-abstract class marked with `[TestClass]` (or derived attribute), report an issue if any available method (including inherited ones) is marked with `[TestMethod]` (or derived).
