### ISSUE TITLE
Cannot run ordered tests which have a class initialize method

### ISSUE THREAD

**Issue by Geetarman** [Microsoft/testfx#290]
## Description
Running an ordered test which has a class initialize method (even empty) will cause ordered tests to fail with error message
Method UnitTest.INVU.UserContext.UnitTest1.Initialize has wrong signature.  Parameter 1 should be of type Microsoft.VisualStudio.TestTools.UnitTesting.TestContext
Can reproduce on mulitple machines

## Steps to reproduce
Create a simple set of units test without a class initialize and create an ordered test for them. Run and check that the ordered tests run.  Then simply add an empty class initialize
[ClassInitialize]
public static void Initialize(TestContext context)
{
}

## Environment
Visual Studio 2017 15.4.0
MSTest.Adapter version 1.2.0
MSTest.TestFramework 1.2.0

**Comment by AbhitejJohn** [comment]
@Geetarman : Ordered tests is not supported with MSTest V2 yet. #25 tracks this.
