### ISSUE TITLE
How can I ignore an AssemblyInitialize method

### ISSUE THREAD

**Issue by mgolois** [Microsoft/testfx#292]
Hello,
I have a an AssemblyInitialize method, which I don't want to run on the build server; so I would like to put an [Ignore] attribute. How can I achieve that?
I'm using mstest

**Comment by AbhitejJohn** [comment]
Ignore only works on `TestMethod`. The framework does not provide a way to conditionally no-op an AssemblyInitialize code fragment. However I imagine you could do so in the AssemblyInit code itself via a [Test Run Parameter](https://blogs.msdn.microsoft.com/devops/2015/09/04/supplying-run-time-parameters-to-tests/) or a config section in the assembly config file or an environment variable amongst other options.
