### ISSUE TITLE
How to get exception from test in TestCleanup?

### ISSUE THREAD

**Issue by VanKrock** [microsoft/testfx#293]
We can get UnitTestOutcome.Error from TestContext.CurrentTestOutcome in TestCleanup. How to get additional information about error? May be Exception? It's can be important for cleanup.

**Comment by jayaranigarg** [comment]
@VanKrock : Currently there is no way to get additional information about the error. If we have enough asks for this feature, we will surely address this in our future releases.

**Comment by scyentyfyc** [comment]
I'll pile onto this one.  You seem to always have to give something up depending on which workaround you pursue.

There is a stackoverflow about this in which one answer suggests to [subscribe to FirstChanceException](https://stackoverflow.com/a/39208343/895010), but being static, you're risking things getting screwed up when using parallel test execution.

That same stackoverflow has a MSTest V2 suggestion to use a [TestMethodAttribute extension](https://stackoverflow.com/a/57165354/895010), which is better, but then as noted in another issue for V2, you [don't have access to TestContext](https://github.com/microsoft/testfx/issues/353).

Can we not have our cake and eat it too?  Please?

**Comment by gaurav137** [comment]
+1 on this ask. We want to capture the exception in TestCleanup via the logging infra that is being used to capture the rest of the tracing that the rest of the code is using. Currently our log files miss this last piece of information.
