### ISSUE TITLE
Fall Creators Update affects tests of code using System.DirectoryServices

### ISSUE THREAD

**Issue by DaveSlinn** [Microsoft/testfx#294]
## Description
Installation of Fall Creators Update has forced us to start running VS2017 as an administrator in order to complete tests that use System.DirectoryServices.  Without running VS as administrator, code attempting to query our AD throws "System.Runtime.InteropServices.COMException: Error accessing the OLE registry."  This worked fine until a few hours ago when the FCU got pushed onto my dev workstation. 

## Steps to reproduce
I created a simple solution with a [test class library here](https://github.com/DaveSlinn/DirectoryServicesErrorRepro).  This contains fairly standard usage of DirectoryEntry and DirectorySearcher.   

## Expected behavior
For the test to pass.

## Actual behavior
Tests fail due to error.  

![image](https://user-images.githubusercontent.com/18301427/31749122-2566a60a-b435-11e7-8643-ab0bcd5bf3dc.png)

Running VS as admin allows the tests to pass.

## Environment
Windows 10 Version 1709
Visual Studio 2017 15.4
Target framework: .NET Framework 4.7.0
Microsoft.NET.Test.Sdk version 15.3.0
MSTest.TestAdapter version 1.2.0
MSTest.TestFramework version 1.2.0

**Comment by DaveSlinn** [comment]
After further investigation, it appears this issue was caused by corrupt user profiles that occurred as a result of the Fall Creators Update.  Deleting the profile and recreating has solved the problem.  Closing the issue.

**Comment by tlecomte** [comment]
I'm running into the very same problem. Is there a way to fix the profile instead ?
