### ISSUE TITLE
Analyzer: Ensure to use Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute and not System.ComponentModel.DescriptionAttribute

### ISSUE THREAD

**Issue by fforjan** [microsoft/testfx#2949]
It is very easy to use  System.ComponentModel.Description instead of a Microsoft.VisualStudio.TestTools.UnitTesting attribute.
Having an analyzer which ensure that on a TestMethod we use the right attribute will be good.

AB#2079032

**Comment by Evangelink** [comment]
Yeah good idea!

**Comment by nohwnd** [comment]
This is great. I was hit by them same just this week.

**Comment by fforjan** [comment]
awesome, cannot wait for next release,
Thanks @engyebrahim  and @Evangelink  !
