### ISSUE TITLE
Should we do a double WaitForExit?

### ISSUE THREAD

**Issue by SimonCropp** [microsoft/testfx#2976]
https://github.com/dotnet/runtime/issues/27128

**Comment by Evangelink** [comment]
@MarcoRossignoli your expertise is summoned here :)

**Comment by MarcoRossignoli** [comment]
The new testing platform doesn't rely on output redirect for the out of process extensions https://github.com/microsoft/testfx/blob/main/docs/testingplatform/extensionintro.md
We simply wait the output here https://github.com/microsoft/testfx/blob/main/src/Platform/Microsoft.Testing.Platform/Hosts/TestHostControllersTestHost.cs#L258L-L262
We use named pipe and custom binary protocol if we need to pass info around. 
We should not suffer of the issue described in the runtime issue.

**Comment by SimonCropp** [comment]
thanks for the clarification
