### ISSUE TITLE
Build inside VS does not work

### ISSUE THREAD

**Issue by kant2002** [Microsoft/testfx#300]
## Description
Failed to build cleanly full solution checked out from latest source code. 

## Steps to reproduce
> Open solution in VS 2017 15.4
> Build solution

## Expected behavior
> Solution in the VS build cleanly

## Actual behavior
There 2 errors in the Error Window
1) *Message*: The type 'IRunSettings' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.VisualStudio.TestPlatform.ObjectModel, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.	
*Project*: PlatformServices.Universal.Unit.Test
*Location:* XXXX\GitHub\testfx\test\UnitTests\PlatformServices.Shared.Unit.Tests\netstandard1.0\ns10TestSourceHostTests.cs
2) *Message*: The type or namespace name 'IRunSettings' could not be found (are you missing a using directive or an assembly reference?)
*Project*: PlatformServices.Portable.Unit.Tests
*Location*: XXXX\GitHub\testfx\test\UnitTests\PlatformServices.Shared.Unit.Tests\netstandard1.0\ns10TestSourceHostTests.cs	

## Environment
> VS 2017 15.4.1
> Microsoft Windows [Version 10.0.16299.19]
> commit: 94997f12c9ca1bba11bb69e19e452bfd8513f6a6

My finding that project PlatformServices.Universal.Unit.Test has project.json file which contains Microsoft.Internal.TestPlatform.ObjectModel version 14.0.0 which looks like not published anywhere right now.
Another overvation is that Build.cmd produce only error from PlatformServices.Universal.Unit.Tests project.
This prevents me from finishing #299

**Comment by AbhitejJohn** [comment]
That nuget package is on an internal myget feed : https://dotnet.myget.org/feed/vstest/package/nuget/Microsoft.Internal.TestPlatform.ObjectModel . Are you running into access issues for some reason? The feed is public. Also what version of UWP tooling do you have installed? (Help->About)

**Comment by kant2002** [comment]
Here information about UWP tooling
![image](https://user-images.githubusercontent.com/4257079/32094673-49ebc7f0-bb09-11e7-9e60-22ddcff47c1c.png)

**Comment by AbhitejJohn** [comment]
Thanks @kant2002 . I'm not able to repro this on my end. Could you also share your verbose build logs? We generate an msbuild.log in the root directory of the repo on `build.cmd -verbose`.

**Comment by kant2002** [comment]
@AbhitejJohn I actually manage to error mentioned here, but I get another one now when run `Build.cmd -loc`
```
.... 
 PlatformServices.Universal -> D:\d\kant\GitHub\testfx\artifacts\Debug\PlatformServices.Universal\Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.dll
  ..\..\..\packages\MSTest.Internal.TestFx.Localized.Documentation.1.0.0-build-20170420-1\contentFiles\any\any\Extensions\Desktop\cs\Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions.xml
  ..\..\..\packages\MSTest.Internal.TestFx.Localized.Documentation.1.0.0-build-20170420-1\contentFiles\any\any\Extensions\Desktop\de\Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions.xml
  ..\..\..\packages\MSTest.Internal.TestFx.Localized.Documentation.1.0.0-build-20170420-1\contentFiles\any\any\Extensions\Desktop\es\Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions.xml
  ..\..\..\packages\MSTest.Internal.TestFx.Localized.Documentation.1.0.0-build-20170420-1\contentFiles\any\any\Extensions\Desktop\fr\Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions.xml
  ..\..\..\packages\MSTest.Internal.TestFx.Localized.Documentation.1.0.0-build-20170420-1\contentFiles\any\any\Extensions\Desktop\it\Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions.xml
  ..\..\..\packages\MSTest.Internal.TestFx.Localized.Documentation.1.0.0-build-20170420-1\contentFiles\any\any\Extensions\Desktop\ja\Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions.xml
  ..\..\..\packages\MSTest.Internal.TestFx.Localized.Documentation.1.0.0-build-20170420-1\contentFiles\any\any\Extensions\Desktop\ko\Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions.xml
  ..\..\..\packages\MSTest.Internal.TestFx.Localized.Documentation.1.0.0-build-20170420-1\contentFiles\any\any\Extensions\Desktop\pl\Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions.xml
  ..\..\..\packages\MSTest.Internal.TestFx.Localized.Documentation.1.0.0-build-20170420-1\contentFiles\any\any\Extensions\Desktop\pt-BR\Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions.xml
  ..\..\..\packages\MSTest.Internal.TestFx.Localized.Documentation.1.0.0-build-20170420-1\contentFiles\any\any\Extensions\Desktop\ru\Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions.xml
  ..\..\..\packages\MSTest.Internal.TestFx.Localized.Documentation.1.0.0-build-20170420-1\contentFiles\any\any\Extensions\Desktop\tr\Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions.xml
  ..\..\..\packages\MSTest.Internal.TestFx.Localized.Documentation.1.0.0-build-20170420-1\contentFiles\any\any\Extensions\Desktop\zh-Hans\Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions.xml
  Ошибка создания файла Системе не удается найти указанный путь.

D:\d\kant\GitHub\testfx\scripts\build\TestFx.Loc.targets(48,5): error MSB3073: выход из команды "xcopy /Y /I /S /E ..\..\..\packages\MSTest.Internal.TestFx.Localized.Documentation.1.0.0-build-20170420-1\contentFiles\any\any\Extensions\Desktop ..\..\..\artifacts\Debug\Ex
tension.Desktop\" с кодом 4. [D:\d\kant\GitHub\testfx\src\TestFramework\Extension.Desktop\Extension.Desktop.csproj]
  ..\..\..\packages\MSTest.Internal.TestFx.Localized.Documentation.1.0.0-build-20170420-1\contentFiles\any\any\Extensions\UWP\cs\Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions.xml
  ..\..\..\packages\MSTest.Internal.TestFx.Localized.Documentation.1.0.0-build-20170420-1\contentFiles\any\any\Extensions\UWP\de\Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions.xml
  ..\..\..\packages\MSTest.Internal.TestFx.Localized.Documentation.1.0.0-build-20170420-1\contentFiles\any\any\Extensions\UWP\es\Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions.xml
  ..\..\..\packages\MSTest.Internal.TestFx.Localized.Documentation.1.0.0-build-20170420-1\contentFiles\any\any\Extensions\UWP\fr\Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions.xml
  ..\..\..\packages\MSTest.Internal.TestFx.Localized.Documentation.1.0.0-build-20170420-1\contentFiles\any\any\Extensions\UWP\it\Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions.xml
  ..\..\..\packages\MSTest.Internal.TestFx.Localized.Documentation.1.0.0-build-20170420-1\contentFiles\any\any\Extensions\UWP\ja\Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions.xml
  ..\..\..\packages\MSTest.Internal.TestFx.Localized.Documentation.1.0.0-build-20170420-1\contentFiles\any\any\Extensions\UWP\ko\Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions.xml
  ..\..\..\packages\MSTest.Internal.TestFx.Localized.Documentation.1.0.0-build-20170420-1\contentFiles\any\any\Extensions\UWP\pl\Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions.xml
  ..\..\..\packages\MSTest.Internal.TestFx.Localized.Documentation.1.0.0-build-20170420-1\contentFiles\any\any\Extensions\UWP\pt-BR\Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions.xml
  ..\..\..\packages\MSTest.Internal.TestFx.Localized.Documentation.1.0.0-build-20170420-1\contentFiles\any\any\Extensions\UWP\ru\Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions.xml
  ..\..\..\packages\MSTest.Internal.TestFx.Localized.Documentation.1.0.0-build-20170420-1\contentFiles\any\any\Extensions\UWP\tr\Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions.xml
  ..\..\..\packages\MSTest.Internal.TestFx.Localized.Documentation.1.0.0-build-20170420-1\contentFiles\any\any\Extensions\UWP\zh-Hans\Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions.xml
  ..\..\..\packages\MSTest.Internal.TestFx.Localized.Documentation.1.0.0-build-20170420-1\contentFiles\any\any\Extensions\UWP\zh-Hant\Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions.xml
  Скопировано файлов: 13.
....
.....
```

It is appear that file "D:\d\user\GitHub\testfx\src\Adapter\PlatformServices.Universal\..\..\..\packages\MSTest.Internal.TestFx.Localized.Documentation.1.0.0-build-20170420-1\contentFiles\any\any\Extensions\Desktop\zh-Hans\Microsoft.VisualStudio.TestPlatform.TestFra
mework.Extensions.xml".Length
263

And I have "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem\LongPathsEnabled"
 set to 1.

**Comment by AbhitejJohn** [comment]
We usually just run `loc` on official builds where the enlistment root is short. You wouldn't be able to validate localization unless your changes are merged and someone from the loc team at our end checks in translated strings. Without that the strings would show up in English itself.

**Comment by kant2002** [comment]
I actually try that out of curiosity, and just since I already run that on clean PC I just want to report that, I not really care about translations, as you could imagine. So when #301 land, I would be able to build project. I think I'm done issue which prevent me build project. From my perspective I could close issue. Do you need some other information from me about this issue?

**Comment by AbhitejJohn** [comment]
Yes, Would be great if you could tell us how the original error got fixed.

**Comment by kant2002** [comment]
It is right there: https://github.com/kant2002/testfx/commit/f78d55c203f7a881948e8f4217166e1467f22c2f

**Comment by AbhitejJohn** [comment]
Thanks. It looks like nuget restores differently for Universal Library projects and a normal class library project. The former being `microsoft.internal.testplatform.objectmodel\14.0.0` and the later being `microsoft.internal.testplatform.objectmodel.14.0.0`. Looks good. 
Our build script also needs to move to the latest nuget.exe version [here](https://github.com/Microsoft/testfx/blob/master/scripts/common.lib.ps1#L10). You can go ahead and close this issue.
