### ISSUE TITLE
Wrong year in docs/Changelog.md for 3.4.x releases

### ISSUE THREAD

**Issue by TiltonJH** [microsoft/testfx#3000]
Hi,
there is an error in the year of the date of release `3.4.0` as well as release `3.4.1` within the change log file. It states 2023 while it should be 2024. :)

See [`docs/Changelog.md`.](https://github.com/microsoft/testfx/blob/main/docs/Changelog.md)

**Comment by Evangelink** [comment]
Hi @TiltonJH! Thanks for spotting that, I guess I don't want to get older ;)
