### ISSUE TITLE
Release notes for 3.4.0 are pointing to the main branch and some links are broken

### ISSUE THREAD

**Issue by fforjan** [microsoft/testfx#3017]
Some of links into the release note from https://github.com/microsoft/testfx/releases/tag/v3.4.0 like
![image](https://github.com/microsoft/testfx/assets/601810/ebb7b6ed-a21b-4045-838b-917a08189c10)
And
![image](https://github.com/microsoft/testfx/assets/601810/1ba55731-0147-47b1-ae63-b5d9d8e4cd96)
Are pointing to the main branch which may be subject to change .

note that the links are already broken, for example for the second screenshot:
![image](https://github.com/microsoft/testfx/assets/601810/39c5c7e7-3163-4f9f-be54-3424703fced8)

**Comment by Evangelink** [comment]
Hopefully I have now fixed the various references and ensured the samples in branch `rel/3.4` are up-to-date.
