### ISSUE TITLE
should settings parsing ignore invalid values?

### ISSUE THREAD

**Issue by SimonCropp** [microsoft/testfx#3020]
should settings parsing ignore invalid values?

![image](https://github.com/microsoft/testfx/assets/122666/28c6b354-57bc-47f9-bbb9-2e8f76ab46ac)

AB#2112231

**Comment by Evangelink** [comment]
It would definitely be better if we were printing a warning in case of invalid entries. 

We could also have another setting (disabled by default for now) to make it fail/stop test execution.

**Comment by nohwnd** [comment]
[like]  Jakub Jares reacted to your message:
________________________________
