### ISSUE TITLE
ClassCleanup is not skipped when ignored and ClassInitialize is not present

### ISSUE THREAD

**Issue by jbne** [microsoft/testfx#3068]
## Describe the bug
The ClassCleanup method is executed when ClassInitialize is not present in the TestClass and either the TestClass is ignored or when all TestMethod in a TestClass are ignored.

## Steps To Reproduce

Make a simple MSTest project that has a single ignored TestClass and no ClassInitialize method. See screenshots below.

## Expected behavior
ClassCleanup should not run when the TestClass is ignored or when all TestMethod in that TestClass are ignored regardless of the presence of ClassInitialize.

## Actual behavior
ClassCleanup is always run when ClassInitialize is not present in the TestClass, regardless of the Ignore attribute.

## Additional context

<img width="407" alt="image" src="https://github.com/microsoft/testfx/assets/99751010/a97f471b-fa67-44d3-9fae-c1fd3c58f8dc">

<img width="437" alt="image" src="https://github.com/microsoft/testfx/assets/99751010/1aae4938-7456-4001-9e0b-0c7087deb77d">

**Comment by nohwnd** [comment]
Are you reporting this because this is a regression (e.g. since last version. or since 2.x.x), or if this was always like this and you'd like it to change?

**Comment by jbne** [comment]
I'm not sure if this is a regression, I would have to check. I reported it because it is a bit of a deviation in consistent behavior when ignoring all tests in a test class. ClassCleanup is skipped when ClassInitialize is present vs. ClassCleanup is not skipped when ClassInitialize is not present. That behavior also deviates from TestInitialize and TestCleanup, which are always skipped regardless of the presence of methods marked with those attributes.

**Comment by Evangelink** [comment]
@jbne I have just tried to reproduce and I don't see this behavior using `3.4.3`, could you please provide a reproducer?

**Comment by jbne** [comment]
@Evangelink I was using older 2.x versions too, I updated them and confirmed I see the same thing. Attached is the sample project I used.

[TestProject_MSTest.zip](https://github.com/user-attachments/files/15892388/TestProject_MSTest.zip)

**Comment by Evangelink** [comment]
Thanks! I can reproduce the issue, I didn't pay attention that adding a `ClassInitialize` was fixing the `ClassCleanup` issue you reported. We will work on a fix.
