### ISSUE TITLE
Remove Usings.cs from samples

### ISSUE THREAD

**Issue by cremor** [microsoft/testfx#3069]
The global usings should not be needed any more with #2701

But they now need to be added to the "Below is the equivalent project configuration when not using MSTest.Sdk" sections in the csproj files as `<Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />`.

**Comment by nohwnd** [comment]
Thanks, please see the linked PR, I was not sure if I am getting your request correctly.
