### ISSUE TITLE
Incorrect test count in console output at end of test run

### ISSUE THREAD

**Issue by thomhurst** [microsoft/testfx#3088]
This is very vague as I don't know the cause, but I'm raising to track it anyway.

I've noticed a few times locally where the test run seemed to show the incorrect number of tests.
I've now had an instance where it's done this on my pipeline so you can see for yourself too.

My tests are source generated, and I've pre-built them, and then run my tests after with `dotnet run` and the `--no-build` flag so the source shouldn't be changing at all.

See here the failure:
https://github.com/thomhurst/TUnit/actions/runs/9466346639/job/26077821502

And here I've just re-ran that same job (so no code changes or new pushes, I've just pressed the re-run button), and you can see there's no failures:
https://github.com/thomhurst/TUnit/actions/runs/9466346639/job/26090355549

You can expand the step in the output to see the command input and output:
![image](https://github.com/microsoft/testfx/assets/30480171/cd96655e-a16e-47b6-a3d6-32eebb787f03)

And on the re-run where it succeeds:
![image](https://github.com/microsoft/testfx/assets/30480171/9cf325fb-1454-4d96-9b7d-5d111561bfb4)

There's also a `ListTestsModule` section of my pipeline, and you can see the tests in question are being picked up (Line 904):
![image](https://github.com/microsoft/testfx/assets/30480171/ced6faa9-0c12-491c-b697-bab964f4fbf0)
The one failing should be `Custom_Filter_One`.

A snapshot on my repository is this commit: https://github.com/thomhurst/TUnit/tree/5350c226564b89bcae402ead252502cd7f07d4eb

Edit:

I've attached `diag` files below. You can see that actually there are `86` tests being picked up and executed, but then the output says random numbers: 76, 84, 69, 72

**Comment by thomhurst** [comment]
I've added diagnostic log files as artifacts in my pipelines but I haven't gotten this issue since annoyingly

**Comment by thomhurst** [comment]
Got an even better example. It retried multiple times in the same pipeline and got different results each time: https://github.com/thomhurst/TUnit/actions/runs/9488409936/job/26147276523

```
dotnet run --no-build --project 
  /home/runner/work/TUnit/TUnit/TUnit.TestProject/TUnit.TestProject.csproj 
  --treenode-filter /*/*/PassFailTests/*[Category=Fail] --diagnostic 
  --diagnostic-output-fileprefix log_FailTests

Failed! - Failed: 76, Passed: 0, Skipped: 0, Total: 76 - TUnit.TestProject.dll 
  (ubuntu.22.04-x64 - .NET 7.0.20)



dotnet run --no-build --project 
  /home/runner/work/TUnit/TUnit/TUnit.TestProject/TUnit.TestProject.csproj 
  --treenode-filter /*/*/PassFailTests/*[Category=Fail] --diagnostic 
  --diagnostic-output-fileprefix log_FailTests

Failed! - Failed: 84, Passed: 0, Skipped: 0, Total: 84 - TUnit.TestProject.dll 
  (ubuntu.22.04-x64 - .NET 7.0.20)



dotnet run --no-build --project 
  /home/runner/work/TUnit/TUnit/TUnit.TestProject/TUnit.TestProject.csproj 
  --treenode-filter /*/*/PassFailTests/*[Category=Fail] --diagnostic 
  --diagnostic-output-fileprefix log_FailTests

Failed! - Failed: 69, Passed: 0, Skipped: 0, Total: 69 - TUnit.TestProject.dll 
  (ubuntu.22.04-x64 - .NET 7.0.20)



dotnet run --no-build --project 
  /home/runner/work/TUnit/TUnit/TUnit.TestProject/TUnit.TestProject.csproj 
  --treenode-filter /*/*/PassFailTests/*[Category=Fail] --diagnostic 
  --diagnostic-output-fileprefix log_FailTests

Failed! - Failed: 72, Passed: 0, Skipped: 0, Total: 72 - TUnit.TestProject.dll 
  (ubuntu.22.04-x64 - .NET 7.0.20)
```

Here's a log file:
[4_Run Pipeline.txt](https://github.com/user-attachments/files/15809883/4_Run.Pipeline.txt)

It's a bit polluted with test output exceptions, but if you just search for `Failed! - Failed:` then you can see 4 different test counts, even though the input commands are the same (which you can find by searching for `--treenode-filter`)

I've also managed to get 4 `diag` files from the `--diagnostic` option for you for each of the times it ran:
[log_FailTests_diag.zip](https://github.com/user-attachments/files/15809912/log_FailTests_diag.zip)

I hope that's helpful!

**Comment by thomhurst** [comment]
In fact, looking at the `diag` logs, it looks like the correct amount of tests were discovered and executed. It looks like just the output at the end has the wrong counts... I'll update the ticket

**Comment by nohwnd** [comment]
The message is written here, and reads the info from a field. 
https://github.com/microsoft/testfx/blob/main/src/Platform/Microsoft.Testing.Platform/OutputDevice/ConsoleDisplayService.cs#L256

The field is incremented here: 

https://github.com/microsoft/testfx/blob/main/src/Platform/Microsoft.Testing.Platform/OutputDevice/ConsoleDisplayService.cs#L527

So it looks like race condition between those two.

**Comment by thomhurst** [comment]
Thanks for the context @nohwnd - Just opened #3094 which might help/fix!
