### ISSUE TITLE
Make TestCleanUp behavior configurable on DataTestMethod

### ISSUE THREAD

**Issue by edwardzhu** [microsoft/testfx#309]
## Description
In MSTest V2 v1.2.0, I'm writing the unit tests for .net framework 4.6 library. The TestInitialize and TestCleanUp works as following:

> **TestInitialize**
> DataRow(1)
> **TestCleanUp**
> **TestInitialize**
> DataRow(2)
> **TestCleanUp**

It's cool in some scenarios. However, I hope, in some situations, I can run the `TestInitialize` and `TestCleanup` just before the whole `DataTestMethod` instead of each `DataRow`. It should work as below:

> **TestInitialize**
> DataRow(1)
> DataRow(2)
> **TestCleanUp**

## Suggestion
I hope you can add the property to the `DataTestMethod` to allow me to choose either of the behaviors.
The code sounds like this:

```` C#
[DataTestMethod(Policy = Bundle | Isolated)]
[DataRow(1)]
[DataRow(2)]
...
public void TestMethod(int value)
{
   ....
}
````

[AB#1408167](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1408167)

**Comment by Evangelink** [comment]
Given there was no traction on this request, I will move forward by closing it as "won't fix". If there is more activity/requests/thumbs-up we may reconsider this choice.
