### ISSUE TITLE
--blame-hang equivalent for AoT testing

### ISSUE THREAD

**Issue by martincostello** [microsoft/testfx#3095]
## Summary

Add a similar capability to dotnet test's `--blame-hang` functionality to make it easier to diagnose the source of hanging tests.

## Background and Motivation

I have a [test suite](https://github.com/martincostello/alexa-london-travel/blob/main/test/LondonTravel.Skill.NativeAotTests/EndToEndTests.cs) using the new AoT test runner where _sometimes_ something hangs in one of the tests, but only when it's running in native AoT. The effectively identical tests I have that use xunit via dotnet test don't exhibit the same behaviour where I could use `--blame-hang`.

Additionally, using `[Timeout(...)]` doesn't _seem_ to be having any effect. I'd expect the hanging test to timeout and fail, not hang.

## Proposed Feature

A similar (I assume identical would be too difficult within a native AoT environment) set of command-line switches to allow for dumps to be generated to identify tests that hang. For example:

```console
my-aot-tests.exe --blame-hang --blame-hang-dump-type <DUMP_TYPE> --blame-hang-timeout <TIMESPAN>
```

## Alternative Designs

None.

**Comment by thomhurst** [comment]
There's a [Microsoft.Testing.Extensions.HangDump](https://nuget.org/packages/Microsoft.Testing.Extensions.HangDump) package you can install. Info is here: https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-platform-extensions-diagnostics

Is that what you want?

**Comment by martincostello** [comment]
Thanks for the tip, I didn't know about that 🙇‍♂️

Of course, I'm now having trouble getting it to work properly on not-Windows...

**Comment by martincostello** [comment]
Alas, that lead me to #3097.

**Comment by Evangelink** [comment]
@martincostello I will close this ticket and we will handle support for hang dump in non-windows. We have explored multiple solutions and I don't recall the one we went with at the end.
