### ISSUE TITLE
Tests using ValueTask return type always succeed

### ISSUE THREAD

**Issue by Rans4ckeR** [microsoft/testfx#3136]
## Describe the bug

Using ValueTask return type causes a test to always succeed. It seems the ValueTask is not awaited.

## Steps To Reproduce

Using `Task` this test correctly fails:
```C#
[TestClass]
public sealed class TestClassX
{
    [TestMethod]
    public async Task TestMethodY()
    {
        await ValueTask.CompletedTask;
        Assert.Fail();
    }
}
```

Using `ValueTask` this same test succeeds:
```C#
[TestClass]
public sealed class TestClassX
{
    [TestMethod]
    public async ValueTask TestMethodY()
    {
        await ValueTask.CompletedTask;
        Assert.Fail();
    }
}
```

## Additional context

`MSTest.Sdk/3.4.3`

**Comment by Evangelink** [comment]
Hi @Rans4cker!

THanks for the bug report, I can reproduce the issue. We will work on a fix soon.
