### ISSUE TITLE
Build fails 'WindowsXaml\v15.0\Microsoft.Windows.UI.Xaml.CSharp.targets' was not found.

### ISSUE THREAD

**Issue by nietras** [Microsoft/testfx#314]
## Description
Build of ```7472b43265c1f237f3ba0bd23a2b448c7adc7474``` using `build.cmd` fails out-of-the-box.

## Steps to reproduce
Clone repo of the mentioned commit. Try running `build.cmd` from shell.

## Expected behavior
Builds and tests succeed out-of-the-box.

## Actual behavior
Builds fails. Seems to be missing something, but what exactly?
```
D:\oss\testfx [master ≡]> .\Build.cmd
... Perform-Restore: Started.
...     Starting toolset restore...
All packages listed in packages.config are already installed.
D:\oss\testfx\scripts\build\TestFx.targets(4,11): error MSB4226: The imported project "C:\Program Files (x86)\Microsoft
 Visual Studio\2017\Professional\MSBuild\Microsoft\WindowsXaml\v15.0\Microsoft.Windows.UI.Xaml.CSharp.targets" was not
found. Also, tried to find "Microsoft\WindowsXaml\v15.0\Microsoft.Windows.UI.Xaml.CSharp.targets" in the fallback searc
h path(s) for $(MSBuildExtensionsPath) - "C:\Program Files (x86)\MSBuild" . These search paths are defined in "C:\Progr
am Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\bin\MSBuild.exe.Config". Confirm that the path in
 the <Import> declaration is correct, and that the file exists on disk in one of the search paths. [D:\oss\testfx\src\A
dapter\PlatformServices.Universal\PlatformServices.Universal.csproj]
D:\oss\testfx\scripts\build\TestFx.targets(4,11): error MSB4226: The imported project "C:\Program Files (x86)\Microsoft
 Visual Studio\2017\Professional\MSBuild\Microsoft\WindowsXaml\v15.0\Microsoft.Windows.UI.Xaml.CSharp.targets" was not
found. Also, tried to find "Microsoft\WindowsXaml\v15.0\Microsoft.Windows.UI.Xaml.CSharp.targets" in the fallback searc
h path(s) for $(MSBuildExtensionsPath) - "C:\Program Files (x86)\MSBuild" . These search paths are defined in "C:\Progr
am Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\bin\MSBuild.exe.Config". Confirm that the path in
 the <Import> declaration is correct, and that the file exists on disk in one of the search paths. [D:\oss\testfx\src\T
estFramework\Extension.UWP\Extension.UWP.csproj]
```
## Environment
Windows 10, Visual Studio 15.4.4 installed. List of components installed attached:

[components.txt](https://github.com/Microsoft/testfx/files/1496113/components.txt)

**Comment by jayaranigarg** [comment]
@nietras : It appears from your components.txt file that you do not have UWP workload installed. Can you install workload for "Universal Windows Platform Development" and try to build again?

**Comment by nietras** [comment]
@jayaranigarg thanks for your reply. But I have UWP for C# installed etc. Installing the full "Universal Windows Platform Development" is a bit problematic given it requires 8GB of extra disk space... would it be possible to list the specific components required? Since adding that workload is quite a lot. In my case :|

What component contains the missing file?

**Comment by jayaranigarg** [comment]
@nietras : What do you mean when you say you have "UWP for C# installed" ?
For building UWP projects, you will need "Universal Windows Platform tools", which only comes as part of UWP workload. You can however install only the required components, and uncheck the optional components under "Universal Windows Platform development" node.

**Comment by jayaranigarg** [comment]
We were not provided by enough information to investigate the issue on our end. Closing the thread.
Please feel free to re-activate this if this is still blocking you.

**Comment by nietras** [comment]
@jayaranigarg sorry I didn't reply. Installing the workload you mentioned helped, but I had to install the "Windows 10 SDK (10.0.14393.0)" component too. This is why I asked for list of all individual components needed. When I said I had UWP for C# installed I meant I had the component "Windows 10 SDK (10.0.16299.0) for UWP: C#, VB, JS" installed.

It seems a little weird that perhaps the workload installs something that is not listed as an individual component.

Anyway, I am fine with closing this, but perhaps consider updating documentation with regards to what needs to be installed and test it.

**Comment by jayaranigarg** [comment]
@nietras : Thank you for your feedback.
Each workload brings bare minimum/essential components with it. Individuals components are more like add-ons/small stand alone components. That effectively means that some components can only be installed via workloads and not via individual components.

We will update the documentation surely :)

**Comment by spottedmahn** [comment]
>I had to install the "Windows 10 SDK (10.0.14393.0)" component too


![image](https://user-images.githubusercontent.com/14079228/40878604-5b0e619c-6661-11e8-86ee-49709e76c361.png)

![image](https://user-images.githubusercontent.com/14079228/40878607-688cc96c-6661-11e8-93a5-d8563666a60f.png)

**Comment by spottedmahn** [comment]
Do I not need the 10.0.15063.0 Windows 10 SDK then?

I only install the UWP workload to build testx...

**Comment by spottedmahn** [comment]
Looks like the [contritubtions guide](https://github.com/Microsoft/testfx-docs/blob/master/docs/contribute.md) has not been updated yet....  please correct me if I'm wrong, thanks.

**Comment by jayaranigarg** [comment]
@spottedmahn : Raised this [PR](https://github.com/Microsoft/testfx/pull/439). After this change, any Windows 10 SDK(10240 to 17134) installed on the machine should work fine.

**Comment by spottedmahn** [comment]
Great, thanks @jayaranigarg!

**Comment by liudonghua123** [comment]
I have the same problem, I have tried tips mentioned here.

![image](https://user-images.githubusercontent.com/2276718/49494315-3acd8680-f89a-11e8-96e1-9f0f1019e620.png)

![image](https://user-images.githubusercontent.com/2276718/49494350-56389180-f89a-11e8-8789-317fd53dae74.png)

![image](https://user-images.githubusercontent.com/2276718/49494332-4620b200-f89a-11e8-8e11-39621eb04146.png)

**Comment by jayaranigarg** [comment]
@liudonghua123 : UWP CPP is not supported currently in VS BuildTools. We already have an issue tracking this https://github.com/Microsoft/vstest/issues/1655. Please follow the above issue.
