### ISSUE TITLE
Comparing two instances of '(dynamic)null' fails in MSTest 3.2.2+

### ISSUE THREAD

**Issue by martinsuchan** [microsoft/testfx#3145]
Consider this one-liner:
`Assert.AreEqual<dynamic>((dynamic)null, (dynamic)null);`

In MSTest 3.2.1 it passed as true
in MSTest 3.2.2+ it fails with: 
```
Assert.AreEqual failed. Expected:<(null)>. Actual:<(null)>. 
   at CallSite.Target(Closure , CallSite , Type , Object , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
```

## Expected behavior
I'm no expert on the CLR `dynamic` specifics, but comparing two instances of `(dynamic)null` should probably pass, so the behavior in MSTest 3.2.2+ is the wrong one?

Tested in a .NET 4.8 Test project in VS 17.10.3

**Comment by martinsuchan** [comment]
Looks like the origin of that behavior is in https://github.com/microsoft/testfx/pull/2382 ?

**Comment by Evangelink** [comment]
Hi @MartinSuchan,

Thanks for the bug report. I confirm that I can reproduce the error and that at runtime, it seems to be picking the newly added overload with `IEquatable<T>` as you are pointing out. I will post back some update when I find what we can do.

**Comment by Evangelink** [comment]
Is your real use case with nulls or is it with some other dynamic and you used null as a simple repro?

**Comment by martinsuchan** [comment]
One of our tests started failing after updating MSTest, we use two paths to retrieve some db resources and we are comparing that both retrieve null. I was able to fix it already by using strong type instead of dynamic.
