### ISSUE TITLE
[Parallel] Tests should be run in STA by default

### ISSUE THREAD

**Issue by AbhitejJohn** [microsoft/testfx#320]
## Description
Tests running with in-assembly-parallelization run by default in MTA where-as the default for a non-parallelized run is STA. We would want this default to be the same irrespective of a parallel run.

### Workaround
A user can add an STATestClass/STATestMethod to ensure their tests requiring STA run in it. These attributes are part of [MSTest.STAExtensions](https://www.nuget.org/packages/MSTest.STAExtensions/1.0.3-beta)

**Comment by Evangelink** [comment]
We will fix running in STA/MTA but not in this way.
