### ISSUE TITLE
TreeNode Filter not working as expected in Release mode

### ISSUE THREAD

**Issue by thomhurst** [microsoft/testfx#3217]
This is a bizarre one.

If you check out this commit: https://github.com/thomhurst/TUnit/commit/75514db210d081bb3f9980c4c0c6834d7be4c934
And go to the "TUnit.TestProject" directory:

Run this command:
`dotnet run --treenode-filter /*/*/PassFailTests/*[Category=Fail]`

You'll get 86 tests that will run.

Now run this:
`dotnet run --treenode-filter /*/*/PassFailTests/*[Category=Fail] -c Release`

0 tests run.

It seems to be something to do with the `[Category=Fail` I believe, as tests run without that:
`dotnet run --treenode-filter /*/*/PassFailTests/* -c Release`

But very strange that the only thing that changes is Debug / Release mode.

**Comment by thomhurst** [comment]
This was something stupid caused by me. Never mind!

**Comment by Evangelink** [comment]
Hijacking this thread. @thomhurst now that you have been playing a bit with the new filter, do you have some feedback about it? What do you like? What do you dislike?
