### ISSUE TITLE
Support capture of stdout/stderr in the protocol

### ISSUE THREAD

**Issue by drognanar** [microsoft/testfx#3226]
Ensure that the stdout/stderr can be captured by the framework, so that they can appear in the UI.

The properties to implement are specified here #3225

**Comment by Evangelink** [comment]
@drognanar are you planning to update the implementation too or just the protocol? If only protocol, we should add some new lablel and don't assign the ones you have set.

**Comment by drognanar** [comment]
Currently I was planning to update the protocol and work on the client side implementation of the changes.

This ticket was supposed to express the work needed to implement the changes to the protocol on the server side, which is why I added the existing labels.

**Comment by MarcoRossignoli** [comment]
closed in https://github.com/microsoft/testfx/pull/3486
