### ISSUE TITLE
Duplicated UIDs for tests with data rows

### ISSUE THREAD

**Issue by jakubch1** [microsoft/testfx#3247]
## Describe the bug

UIDs for testing platform protocol are duplicated for tests with data rows. It is causing in VS Preview that if you click to run 1 test with data row => all tests are executed.
We are getting in repo:

Duplicated tests found for module 'D:\a\_work\1\s\artifacts\bin\Microsoft.CodeCoverage.VisualStudio.Extension.Tests\Debug\net481\Microsoft.CodeCoverage.VisualStudio.Extension.Tests.exe', total duplicate tests: 37
Duplicated tests found for module 'D:\a\_work\1\s\artifacts\bin\Microsoft.CodeCoverage.VisualStudio.Window.Tests\Debug\net481\Microsoft.CodeCoverage.VisualStudio.Window.Tests.exe', total duplicate tests: 22
Duplicated tests found for module 'D:\a\_work\1\s\artifacts\bin\Microsoft.VisualStudio.CoverageServices.Tests\Debug\net9.0\Microsoft.VisualStudio.CoverageServices.Tests.dll', total duplicate tests: 2
Duplicated tests found for module 'D:\a\_work\1\s\artifacts\bin\Microsoft.VisualStudio.TraceDataCollector.Tests\Debug\net481\Microsoft.VisualStudio.TraceDataCollector.Tests.exe', total duplicate tests: 18
Duplicated tests found for module 'D:\a\_work\1\s\artifacts\bin\Microsoft.VisualStudio.TraceDataCollector.Tests\Debug\net9.0\Microsoft.VisualStudio.TraceDataCollector.Tests.dll', total duplicate tests: 18

## Steps To Reproduce

Create MSTest runner project. Add data rows into test. Execute 1 of them in VS Preview with testing platform protocol enabled.

## Expected behavior

Only 1 test is executed (1 data row)

## Actual behavior

All tests are executed.

**Comment by Evangelink** [comment]
We did a few more investigations and tests and it seems the requirement from VS Test Explorer is no longer needed so we can change the TestNodeUID to be using the GUID from TestCase.
