### ISSUE TITLE
Tests with csv datasource for platform x64 failing with error "The 'Microsoft.Jet.OLEDB.4.0' provider is not registered on the local machine."

### ISSUE THREAD

**Issue by smadala** [Microsoft/testfx#325]
## Description
CSV datasource tests for /platform:x64 fails with error "The 'Microsoft.Jet.OLEDB.4.0' provider is not registered on the local machine."

## Steps to reproduce
1. Create MSTest v1/v2 test project 
2. Add CSV datasource tests, example below:
[TestClass]
    public class UnitTest1
    {
        public TestContext TestContext
        {
            get;
            set;
        }

        [TestMethod, DataSource("Microsoft.VisualStudio.TestTools.DataSource.CSV", "DatacenterForestEnvironment.csv", "DatacenterForestEnvironment#csv", DataAccessMethod.Sequential)]
        public void TestMethod2()
        {
            foreach (var item in this.TestContext.DataRow.ItemArray)
            {
                Console.WriteLine("item: " + item);
            }
        }
    }
3 Run tests with /platform:x64

## Expected behavior
 Tests should pass.

## Actual behavior
The unit test adapter failed to connect to the data source or to read the data. For more information on troubleshooting this error, see "Troubleshooting Data-Driven Unit Tests" (https://go.microsoft.com/fwlink/?LinkId=62412) in the MSDN Library.
Error details: The 'Microsoft.Jet.OLEDB.4.0' provider is not registered on the local machine.

**Comment by jayaranigarg** [comment]
User needs to install AccessDatabaseEngine_64.exe along with the fix to make this scenario work.

**Comment by parnasoft** [comment]
I am using the Visual Studio 2017 with the latest update and installed AccessDatabaseEngine_X64.exe.  My csv data driven tests are still failing with "Microsoft.VisualStudio.TestTools.DataSource.CSV" when I use <TargetPlatform>x64</TargetPlatform>  in my test settings file.  It seems work just fine with x86.   Now how do i get this fix that you are talking about in my visual studio.

**Comment by smadala** [comment]
What is the test adapter you are using, Please share sample repro. The fix is not yet release in stable nuget package. You can update your `MSTest.TestAdapter` package to `1.3.0-build-20180110-01` with nuget feed `https://dotnet.myget.org/F/mstestv2/api/v3/index.json` . https://dotnet.myget.org/feed/mstestv2/package/nuget/MSTest.TestAdapter

**Comment by parnasoft** [comment]
I thought I was using MSTest adapter but I seems like I was wrong.  I am using whatever is the default adapter in Visual Studio.  The repro steps are exactly the same as described by you.
