### ISSUE TITLE
TestingPlatformServer capability set for non MSTestRunner projects

### ISSUE THREAD

**Issue by drognanar** [microsoft/testfx#3287]
Issue is taken from this feedback - https://developercommunity.visualstudio.com/t/Error-running-xUnit-tests-on-NET-Framew/10702302.

There's an issue where test projects get marked to have the TestingPlatformServer capability, even though they are not meant to be run in server mode.

Looking into the binlog, the project follows the following reference structure:

```
TestProject.csproj
  - xunit/xunit.testadapter
  - TestUtilitiesProject.csproj
    - MSTest.TestAdapter
      - Microsoft.Testing.Platform.MSBuild
    - MSTest.TestFramework
```

Expected:
Because the Microsoft.Platform.MSBuild.targets is transitive, but MSTest.TestAdapter.targets is not transitive, all projects that reference MSTest.TestAdapter will include the TestingPlatformServer capability, regardless of them setting EnableMSTestRunner or not.

Actual:
TestingPlatformServer capability is only set if EnableMSTestRunner is true.

**Comment by Evangelink** [comment]
Will move as won't fix because the adapter should not be added to non runnable projects.
