### ISSUE TITLE
MSTEST0029 false positive on TestInitialize/TestCleanup

### ISSUE THREAD

**Issue by avivanoff** [microsoft/testfx#3291]
## Describe the bug

MSTEST0029 fires on TestInitialize/TestCleanup methods.

## Steps To Reproduce

1. Create a MSTest project.
2. Add {TestInitialize] and/or [TestCleanup] methods.
3. Enable MSTTEST0029 rule.
4. Build the project.

## Expected behavior
Project should build with no ewarnings/errors.

## Actual behavior
MSTEST0029 is triggered on TestInitialize/TestCleanup methods.

See [sample](https://github.com/user-attachments/files/16328130/MSTEST0029.ZIP) project.

**Comment by Evangelink** [comment]
Hi @avivanoff,

Thanks for letting us know! Indeed, there are some false positives here..
