### ISSUE TITLE
General Availability Timelines

### ISSUE THREAD

**Issue by thomhurst** [microsoft/testfx#3321]
I was going to start this as a discussion but they're not enabled on this repository. (Maybe that's worth enabling?)

Just wondering if you guys know when the new testing platform will be considered production ready.

I know it's available and working now but with some caveats:
- IDE support not enabled by default 
- treenode filtering and some other bits are still experimental 

Do you have timelines of when you expect this testing framework to be out of experimental phases and enabled in IDEs by default?

Also I know you don't make Rider, but are you working with the Jetbrains team at all to enable support, or is that all on them? Because I know visual studio can support it by enabling the preview setting, but I don't think rider supports it at all (yet).

**Comment by nohwnd** [comment]
> * IDE support not enabled by default

That would be a nice goal for next sprint, I can give it a lot of testing and fixes if needed.

**Comment by Evangelink** [comment]
Hi @thomhurst,

Starting with VS 17.12 GA, the option to enable the new platform will be disabled but visible to everyone (it is currently visible only in previews) and we aim at turning it on by default starting with VS 17.13 (this is going to give us time to collect more telemetry confirming everything is working fine for users).

For Rider, they have already enabled the support for the new platform.

As for the experimental parts like tree-node etc, I think it will need more time to build confidence (we only have a few users of these features) but this is something transparent to our users so this should not be blocking you from going GA.

cc @pavelhorak @webreidi

**Comment by thomhurst** [comment]
Sounds good! As users have options for ide support now I'm all happy (and so are they mostly, apart from a few teething issues which I'm sure will be fixed shortly) 😄
