### ISSUE TITLE
`MSTEST0008`: (non-abstract, non-generic) `[TestInitialize]` not allowed in abstract generic base class (or use case not explicitly forbidden)

### ISSUE THREAD

**Issue by LukasGelke** [microsoft/testfx#3324]
## Describe the bug
- `[TestInitialize]` is allowed on abstract non-generic types
- test inheritance allows multiple `[TestInitialize]` with one per class, which all run correctly

## Steps To Reproduce
```cs
public abstract class MyTestBase<T>
{
  protected int a;

  [TestInitialize]
  public void Init() => a = 1; // MSTEST0008
}

[TestClass]
public sealed class MyTest : MyTestBase<int>
{
  private int b;

  [TestInitialize]
  public void Init2() => b = 2;

  [TestMethod]
  public void MyTestMethod()
  {
    Assert.AreEqual(1, a); // ok
    Assert.AreEqual(2, b); // ok
  }
}
```

## Expected behavior
- either runtime Exception a la `UTA018: Example.Test.MyTest: Cannot define more than one method with the TestInitialize attribute.` 
- or make analyzer value `abstract` more than generic-ness
## Actual behavior
`MSTEST0008` gets diagnosed, but unit tests run both Init-Methods; and Init-Methods from abstract generic base classes correctly
## Additional context
I guess this would also be the same for `TestCleanup`.

But not sure how this relates to `ClassInitialize`/`ClassCleanup`, since it's also defined in 'this specific test-class' (contrary to `AssemblyInitialize`/ `AssemblyCleanup`).

**Comment by nohwnd** [comment]
> either runtime Exception a la UTA018: Example.Test.MyTest: Cannot define more than one method with the TestInitialize attribute.

This would be problem for Playwright which relies on multiple test setups and teardowns.

**Comment by Evangelink** [comment]
MSTEST0008 was buggy (see #3276), we got it fixed.
