### ISSUE TITLE
Allow user to set/configure MSTestV2 as default test framework & configure default project.

### ISSUE THREAD

**Issue by weedkiller** [Microsoft/testfx#338]
1. How can I switch out the old default `MStest` Testframework in Visual Studio 2017 with the new `MSTestV2` framework as default? question 1 in the picture
 2. How to force IntelliTest *to auto-gen all the test stubs for a class*, i.e. not one by one.
 3. How to default Intellitest to set/configure my MyTestProject as the target test project and not prompt me everytime? question 2 in the picture

Every time I create VS Intellitest *it prompts/defaults to the old MsTest Framework*. I would like for it to *configure/switch out to the current* `MStestV2` that was recently released. I looked in settings and could not find it.

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/gMYVg.png

**Comment by jayaranigarg** [comment]
@weedkiller : Thank you for reaching out to us. Please find our responses below:
> 1. How can I switch out the old default MStest Testframework in Visual Studio 2017 with the new MSTestV2 framework as default? question 1 in the picture

This is currenly in our backlog and there is no way you can make MSTestv2 default as of now. We will try prioritizing this.

>2 . How to force IntelliTest to auto-gen all the test stubs for a class, i.e. not one by one

IntelliTest already generates stubs for all methods in a class. You can change method name from drop down box located on top-left corner
![image](https://user-images.githubusercontent.com/17309452/34375939-1d8e1808-eb0f-11e7-9c9d-e400103bfc03.png)

> 3. How to default Intellitest to set/configure my MyTestProject as the target test project and not prompt me everytime? question 2 in the picture

You need to create project only once in the beginning. For further runs, don't do "Create Intellitest", just do "Run IntelliTest" and save the testcases. They will automatically be saved in the existing project.

**Comment by weedkiller** [comment]
hi, In my question 2), in the dialog box, _during creation of tests, there is no option to create all function stubs at a class level!._

In your picture - you're showing how to run all tests - which is not the same as create stubs for all public/internal functions of a class

**Comment by jayaranigarg** [comment]
@weedkiller : Which test stubs to create is picked up from testcontext i.e. where you do right-click.
If you right-click and do "create IntelliTest" from inside a method, only test stub for that method will get created. And if you do a right click inside the class but outside any method, test stubs for all the methods in that class will get generated.

![image](https://user-images.githubusercontent.com/17309452/34402898-c5126406-ebca-11e7-8b85-a397fa20d632.png)

**Comment by cltshivash** [comment]
@weedkiller : This is a change to the current visual studio experience. Kindly log this request at https://developercommunity.visualstudio.com/spaces/8/index.html so that the team can track it to closure. The code for this settings experience doesn't reside in this repo and hence the ask.
