### ISSUE TITLE
TestAdapter still calls AssemblyCleanup despite of test marked as Ignored

### ISSUE THREAD

**Issue by kabilanvk** [Microsoft/testfx#343]
## Description
Even though test is marked as [Ignore] the adapter still called the [AssemblyCleanup] method.

## Steps to reproduce
Mark any test with attribute [Ignore] and try debug using the TestExplorer.

## Expected behavior
Test run should complete without calling [AssemblyCleanup] static method and show Skipped status.

## Actual behavior
AssemblyCleanup called without AssemblyInitialize throws error in my test code.

## Environment
* VS 2017
* MSTest.TestAdapter 1.3.0-build-20171226-03
* MSTest.TestFramework 1.3.0-build-20171226-03

**Comment by cltshivash** [comment]
AssemblyCleanup works in pair with AssemblyInitialize and will be currently called even though the tests themselves are ignored. This is the current design.
