### ISSUE TITLE
Breaking change in exception handling in PrivateObject in comparison to Microsoft.VisualStudio.QualityTools.UnitTestFramework

### ISSUE THREAD

**Issue by leftler** [Microsoft/testfx#344]
Between 10.0.0.0 of `Microsoft.VisualStudio.QualityTools.UnitTestFramework` and the initial commit of `Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions` a breaking change was introduced in to the `PrivateObject.InvokeHelper` method.

https://github.com/Microsoft/testfx/blob/73f7ced91297dfe7a1462300bbf593335b14bc2f/src/TestFramework/UnitTestFramework.Extension.Desktop/PrivateAccessor.cs#L914-L928

This code is still relatively unchanged in the latest commit

https://github.com/Microsoft/testfx/blob/cebf0380074f1da1a6df1ffc2168d423ce69548f/src/TestFramework/Extension.Desktop/PrivateObject.cs#L728-L742

Looking at the decompiled source of `Microsoft.VisualStudio.QualityTools.UnitTestFramework.dll` we can see the old method was implemented via 

```C#
private object InvokeHelper(string name, BindingFlags bindingFlags, object[] args, CultureInfo culture)
{
    Helper.CheckParameterNotNull((object) name, nameof (name), string.Empty);
    try
    {
        return this.m_originalType.InvokeMember(name, bindingFlags, (Binder) null, this.m_target, args, culture);
    }
    catch (TargetInvocationException ex)
    {
        if (ex.InnerException == null)
        {
            throw;
        }
        else
        {
            Helper.ThrowInnerException(ex);
            throw;
        }
    }
}
```
This causes any code that depended on that inner exception being unwrapped to fail.

If support was dropped because the porting of the `Helper` class was not possible the code could use instead [ExceptionDispatchInfo](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.exceptionservices.exceptiondispatchinfo), here is a possible example replacement.

```C#
private object InvokeHelper(string name, BindingFlags bindingFlags, object[] args, CultureInfo culture)
{
    Helper.CheckParameterNotNull(name, "name", string.Empty);
    Debug.Assert(this.target != null, "Internal Error: Null reference is returned for internal object");

    // Invoke the actual Method
    try
    {
        return this.originalType.InvokeMember(name, bindingFlags, null, this.target, args, culture);
    }
    catch (TargetInvocationException e)
    {
        Debug.Assert(e.InnerException != null, "Inner exception should not be null.");
        if (e.InnerException == null) //This guard may be unnecessary with the Debug.Assert.
        {
            throw;
        }
        else
        {
            ExceptionDispatchInfo.Capture(e.InnerException).Throw();
        }
    }
}
```
Attached is a very simple repo of the issue, it contains two unit tests projects, both linked to the same UnitTest1.cs file. `UnitTestProject` Uses MSTest.TestFramework 1.2.0 and `V1TestProject` uses `Microsoft.VisualStudio.QualityTools.UnitTestFramework`. The V1TestProject test passes and the UnitTestProject test fails.

[UnitTestProject.zip](https://github.com/Microsoft/testfx/files/1601608/UnitTestProject.zip)

**Comment by PedroHerrarte** [comment]
Try using extension methods like this (use InvokeExt and InvokeStaticExt methods):

```
public static class PrivateTypeExtensions {
        // Breaking change in exception handling in PrivateObject 
        // in comparison to Microsoft.VisualStudio.QualityTools.UnitTestFramework
        public static object InvokeStaticExt(this PrivateType instance, string name, params object[] args) {
            try {
                return instance.InvokeStatic(name, args);
            }
            catch (TargetInvocationException ex) {                
                throw ex.InnerException;
            }
        }

        public static object InvokeExt(this PrivateObject instance, string name, params object[] args) {
            try
            {
                return instance.Invoke(name, args);
            }
            catch (TargetInvocationException ex)
            {
                throw ex.InnerException;
            }
        }
    }
```
