### ISSUE TITLE
Build with localization limited to locations with short path

### ISSUE THREAD

**Issue by kant2002** [Microsoft/testfx#346]
## Description
Currently build with generation of XLF files working only from directories shorter then 23 characters. Path `c:\d\user\GitHub\testfx` is the minimal path which exhibit broken build. When I change path to `c:\d\user\GitHub\tstfx` build with localization start working. Without passing -uxlf build is working on longer paths.

## Steps to reproduce
- Checkout source code to location at least of this length `c:\d\user\GitHub\testfx`
- Run .\build.cmd -uxlf

## Expected behavior
Build run correctly without errors

## Actual behavior
```
c:\d\user\GitHub\testfx\scripts\build\TestFx.Loc.targets(48,5): error MSB3073: выход из команды "xcopy /Y /I /S /E ..\..\..\packages\MSTest.Internal.TestFx.Localized.Documentation.1.0.0-build-20170420-1\contentFiles\any\any\Extensions\Desktop ..\..\..\artifacts\Debug\Extension.Desktop\" с кодом 4. [c:\d\user\GitHub\testfx\src\TestFramework\Extension.Desktop\Extension.Desktop.csproj]
```

## Environment
Windows 10 Home Russian language
MAX_PATH limit relaxed in the registry (or where it is allowed to have longer paths)

**Comment by karanjitsingh** [comment]
@kant2002, it seems this is an issue with xcopy, I don't seem to find any workaround with this, I'll go ahead and change xcopy to robocopy to fix this

**Comment by karanjitsingh** [comment]
@kant2002, I was trying to fix this issue, but it seems it's not reproing in the latest master, could you try the same thing on your end

**Comment by kant2002** [comment]
@karanjitsingh I could confirm that checking out to folder `c:\d\user\GitHub\dotnet\testfx` and running `.\build.cmd -uxlf` is produce build for me. I done completely clean build. Make sure that path is relatively long. Minimal length is length of `c:\d\user\GitHub\testfx` which is 23 characters.

**Comment by kant2002** [comment]
@karanjitsingh so seems to be this is Microsoft/MSBuild#53 related

**Comment by kant2002** [comment]
There seems to be related comment which has indication that issue could be solved with custom MSBuild tasks (https://github.com/Microsoft/msbuild/issues/53#issuecomment-425810095) not sure that you want to go that route.

**Comment by karanjitsingh** [comment]
@kant2002, here's a workaround I found https://blogs.msdn.microsoft.com/jeremykuhne/2016/07/30/net-4-6-2-and-long-paths-on-windows-10/

**Comment by karanjitsingh** [comment]
Closing this issue since it's non-actionable
