### ISSUE TITLE
should an invalid DisableParallelization config setting be ignored?

### ISSUE THREAD

**Issue by SimonCropp** [microsoft/testfx#3471]
specifically there is no else on the `bool.TryParse`

    private static void SetGlobalSettings(
        [StringSyntax(StringSyntaxAttribute.Xml, nameof(runsettingsXml))] string runsettingsXml,
        MSTestSettings settings)
    {
        XElement? runConfigElement = XDocument.Parse(runsettingsXml).Element("RunSettings")?.Element("RunConfiguration");

        if (runConfigElement == null)
        {
            return;
        }

        string? disableParallelizationString = runConfigElement.Element("DisableParallelization")?.Value;
        if (bool.TryParse(disableParallelizationString, out bool disableParallelization))
        {
            settings.DisableParallelization = disableParallelization;
        }
    }

AB#2200951

**Comment by Evangelink** [comment]
It would indeed makes sense if that's not already validated from somewhere else.

@engyebrahim could you please have a look?
