### ISSUE TITLE
MSTEST0008: Invalid signature detection not working in generic class

### ISSUE THREAD

**Issue by AliveDevil** [microsoft/testfx#3475]
## Describe the bug

When writing generic base-class tests, including TestInitializers/TestCleanups MSTEST0008 is set erroneously.

## Steps To Reproduce

```
[TestClass]
public class ConcreteTest : B<ConcreteTest>
{
	[TestMethod]
	public void Test()
	{
		Assert.IsNotNull(SharedState);
	}
}

//[TestClass] // has no effect
public abstract class B<T> where T : B<T>
{
	protected object SharedState { get; private set; }

	[TestInitialize]
	public void TestSetup() // MSTEST0008
	{
		SharedState = new();
	}
}
```

## Expected behavior
In an abstract generic class, when `[TestInitialize]` is technically valid, MSTEST0008 shouldn't be warned.

## Actual behavior
MSTEST0008 is falsely emitted.

**Comment by Evangelink** [comment]
Hi @AliveDevil,

Thanks for the report. This is duplicating #3276. I am in the process of releasing a bug fix version.

**Comment by AliveDevil** [comment]
Ah, didn't see that. Thanks :)

**Comment by Evangelink** [comment]
No worries! It's easier for me to recall what I have seen :) Also my ticket title kinda sucks :P
