### ISSUE TITLE
Please update sample to show `dotnet test` integration

### ISSUE THREAD

**Issue by bradwilson** [microsoft/testfx#3480]
Would it be possible to update the [code sample](https://github.com/microsoft/testfx/blob/main/docs/testingplatform/codesample.md) so that it works with `dotnet test`? Right now the sample only provides a standalone test execution experience, where most users will expect to be able to run tests via `dotnet test`.

Related: #3478

**Comment by bradwilson** [comment]
@MarcoRossignoli @drognanar

**Comment by MarcoRossignoli** [comment]
Answered here https://github.com/microsoft/testfx/issues/3478#issuecomment-2270577906
