### ISSUE TITLE
Please update sample to show Test Explorer integration

### ISSUE THREAD

**Issue by bradwilson** [microsoft/testfx#3481]
Would it be possible to update the [code sample](https://github.com/microsoft/testfx/blob/main/docs/testingplatform/codesample.md) so that it works with Test Explorer? Right now the sample only provides a standalone test execution experience, where most users will expect to be able to run tests via Test Explorer.

Related: #3479

**Comment by bradwilson** [comment]
@MarcoRossignoli @drognanar

**Comment by MarcoRossignoli** [comment]
Discussed here it's not needed at the moment xunit will use the testing framework to plug to the tooling, at least as first step. Discussion https://github.com/microsoft/testfx/issues/3479
