### ISSUE TITLE
Custom display name for DynamicDataAttribute

### ISSUE THREAD

**Issue by bstoney** [Microsoft/testfx#351]
## Description

Is it possible to add an option to the `DynamicDataAttribute` allowing similar functionality to the `DataRowAttribute.DisplayName`. This would allow tests with similar parameters to be given more meaningful names and therefore make it easier to determine which set of parameter is producing a particular result. 

A possible solution would be to set the a `DisplayName` property to the name of a method, just as `dynamicDataSourceName` is currently, and match the method signature of the default `GetDisplayName` method. This will allow a custom display name to be generated depending on the parameter set.  

## Current Behaviour

With the test class:

    [TestClass]
    public class Tests
    {
        [TestMethod]
        [DynamicData(nameof(Tests.TestMethodTests))]
        public void TestMethod(string param1, string param2)
        {
            Assert.IsNotNull(param1);
        }

        private static IEnumerable<object[]> TestMethodTests
        {
            get
            {
                yield return new object[] { "", null };
                yield return new object[] { null, "" };
            }
        }
    }

Displays output where it is not clear which set of parameters caused the failure

    Failed   TestMethod (,)
    Error Message:
        Assert.IsNotNull failed.
    Stack Trace:
        ...

## Possible Solution

    // ....
        [DynamicData(nameof(Tests.TestMethodTests), DisplayName = nameof(Tests.GetTestMethodDisplayName))]
    // ...
        public static string GetTestMethodDisplayName(MethodInfo methodInfo, object[] data)
        {
            // ....
        }
    // ....

## Current Workaround

As a work around I have been adding an unused sting parameter to identify the test e.g:

    // ....
        public void TestMethod(string testName, string param1, string param2)
    // ....
            yield return new object[] { "Param2 null", "", null };
            yield return new object[] { "Param1 null", null, "" };
    // ....

**Comment by cltshivash** [comment]
@bstoney This is a fair suggestion and we would be more than happy to welcome contribution for this feature addition.

**Comment by jayaranigarg** [comment]
If we have a DisplayName property in DynamicData attribute, then each row of data would effectively have same base name i.e.  GetTestMethodDisplayName, combined with data[] which be different. That is what happens in the normal workflow as well i.e. you have testmethod name combined with data[] for each row.

I think your ask is to have different base name for each row of data followed by data[]. Did I understand you correctly?

**Comment by bstoney** [comment]
Basically yes. Each row of data could have a different base name, though I was thinking that it would be up to the DisplayName implementation to add the data[] if necessary. I will add the feature and submit a  PR for you to review.
