### ISSUE TITLE
netstandard 2.0 support

### ISSUE THREAD

**Issue by monty241** [Microsoft/testfx#352]
## Use Case

We have a large number (20) of solutions, several of which we have migrated to netstandard over the last year. We create nuget packages in an automated way, sometimes debug, sometimes release.

In release, we skip the unit tests which require v1.2.0 of mstest. In debug, they are included. The deployment software in debug then typically prefers framework 4.7.

After some hours, the Android and iOS developers get the non-functioning update.

Of course the releasing person should always choose the right release target.

But it would be great when mstest would support netstandard 2.0.

**Comment by jayaranigarg** [comment]
Tagging @pvlakshm , @cltshivash to look into this ask.

**Comment by jayaranigarg** [comment]
@monty241 : MSTest is build for netstandard lower than 2.0 So ideally it should support 2.0
Can you tell us more about your scenario and how MSTest is blocking you from achieving that?

**Comment by cltshivash** [comment]
@monty241 Could you please provide a small repro that is representative of your problem ?

**Comment by jayaranigarg** [comment]
@monty241 : Please provide the information requested. Without this information, it will not be actionable and we will have to close this at our end.

**Comment by monty241** [comment]
Tried to reproduce issue. 

At time of issue registration we were using v1.2? of mstest and visual studio 2017 15.5 I think. 

The unit test projects can now use netstandard2.0 instead of net47. 

Problem is no longer reproducible.

Closing issue.
