### ISSUE TITLE
TestContext information is not available inside TestMethod Attribute Extension Execute Method

### ISSUE THREAD

**Issue by anshuls01** [microsoft/testfx#353]
## Description
TestExtension Execute method accepts only one parameter of type ITestMethod
during debug, if do quick watch on testMethod "((Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.TestMethodInfo)testMethod).TestMethodOptions.TestContext" 
shows the testcontext information, but same not able to retrieve inside Execute method, because of permission level, we tried to get the values through runtime properties, still not able to resolve because of abstraction.

the requirement is to know the tfs test run id, inside Execute method.

just for work Around
We tried to create a public property of testcontext type in test class, and try to access the values in Execute method using reflection, still not able to get.
testMethodAssembly.GetType(TestClassName).GetProperty("Testcontext")
the above line gives the property value, to GetValue required object of TestContext type, and that is not possible due to TestContext is a Abstract class, if use new Object then Target Mismatch Exception occurred.

## Steps to reproduce
> Implement TestMethod Attribute Extension
> inside Execute method not possible to get testContext, please find the attachment below:
![tc](https://user-images.githubusercontent.com/15679723/35571232-84981884-05f7-11e8-8636-a16022caf62d.jpg)

## Expected behavior
> Required Tfs Run id and Testcontext object inside Execute method

**Comment by jayaranigarg** [comment]
@anshuls01 : We have not exposed TestContext as part of [ITestMethod ](https://github.com/Microsoft/testfx/blob/master/src/TestFramework/MSTest.Core/Interfaces/ITestMethod.cs) interface.
Could you tell us what information do you need from this testcontext object apart from tfs run id?

**Comment by anshuls01** [comment]
Hello Jaya, 
Thanks for the response, We required few more information:
1. RunBy
2. Tfs_BuildNumber
3. Tfs_BuildPlatform
4. DeploymentDirectory
5. FullyQualifiedTestClassName
6. ResultsDirectory
7. TestDir
8. BuildDirectory
9. ControllerName (not sure)
10. Tfs_TeamProject
11. Tfs_TestPlanId

I think, most of the other information we can get after querying the TFS database, by using the run id.
in TFS TestResult.tbl_TestResult and dbo.tbl_TestRun contains all the information we required.

Thanks
Anshul

**Comment by VanKrock** [comment]
@jayaranigarg It's really to make instance of test class as part of ITestMethod? For example `object TestClassInstance`? It's well be cool for initializing test class by test method attributes.

**Comment by luis-cortina** [comment]
I also want to add or edit a Property in the test context to influence some behaviour in my test not related to test data. Is there any other way to do this?

**Comment by Camerus** [comment]
Just wanted to pile on here. Either exposing the TestContext or the test class instance (or both) to the ITestMethod interface would be incredibly valuable as it is not currently possible to use the parameters passed to the test method as part of shared test fixture setup in the TestInitialize method. I would like to either set them directly on the class or pass them in via the TestContext. As an added bonus, doing it this way would prevent me from having to change the signature of every single test method in my codebase.

**Comment by avibitran** [comment]
To add to the why we need the TestContext.
if I'm are using Data Driven test using DataSourceAttribute. The values of every iteration is inserted to the TestContext DataRow property, so if I want to determine the iteration number and I inserted it as part of the DataRow, I need the TestContext to get it.

**Comment by Baccanno** [comment]
This exact same issue has been raised before here and closed without even caring to answer : https://github.com/microsoft/testfx/issues/305
All people are saying the same simple thing. There is no way to retrieve the test DataRow in test initialization. And most are giving example.

People might have different reason to do so such as simply being able to create a Log file for each case.

So what is the solution or the workaround ?

**Comment by Evangelink** [comment]
Closing as won't fix
