### ISSUE TITLE
Detecting and warning the user about presence of multiple adapter versions

### ISSUE THREAD

**Issue by jayaranigarg** [Microsoft/testfx#356]
## Description
Moving from older adapter/framework nuget packages to new versions or having multiple versions of adapter/framework nuget packages in a solution causes version mismatch issues but doesn't give relevant error messages. 

## Steps to reproduce
1. Create 2 projects in a solution
2. Refer 1.1.18 version of nugets in first project.
3. Refer 1.2.0 version of  nugets in second project.
4. Build solution

## Expected behavior
An exception occurred while invoking executor 'executor://mstestadapter/v2': Constructor on type 'Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.UnitTestRunner' not found or some similar warning message.

## Actual behavior
Tests should be discovered or a proper error/message should be printed specifying that it is a version mismatch issue.

**Comment by cltshivash** [comment]
@jayaranigarg Shouldn't this issue be tracked at vstest repo ?

**Comment by cltshivash** [comment]
@jayaranigarg This is getting fixed with the PR https://github.com/Microsoft/testfx/pull/404
