### ISSUE TITLE
MSTest.Sdk should allow for test library/infra project

### ISSUE THREAD

**Issue by Evangelink** [microsoft/testfx#3567]
## Summary

Allow to specify if this is a test application or test "library".

## Background and Motivation

As of today, MSTest.Sdk is helping with simplifying project configuration but it's not taking into account shared test projects/infra projects that would either contain some common tests or some helper classes using assertions without being an executable test project.

## Proposed Feature

Add some option, either a boolean or enum, that specifies the kind of project this is (e.g. "library" or "test app").

## Alternative Designs

None

**Comment by Evangelink** [comment]
> Could this be driven by the existing property <OutputType>

I was thinking about it but when using `MSTest.Sdk` we don't set it as `Exe` it's done by the SDK. But maybe that's ok for our case, let me check.

cc @MarcoRossignoli

**Comment by MarcoRossignoli** [comment]
> Could this be driven by the existing property <OutputType>, even when it is implicit?

In a one to many setup we could have tests libs. I would go for custom MSBuild prop to opt-in only needed extensions dll.

**Comment by Evangelink** [comment]
Just had a quick chat with @MarcoRossignoli, let's use the `OutputType` as a starting point and if we get some feedback this is confusing/not clear enough, we will introduce a different property.

**Comment by Evangelink** [comment]
Re-opening because current solution is not working out. I didn't realize before because the SDK tests are broken, when working on re-enabling them, I have seen issues that are linked to how this is handled.

The problem is that .NET SDK is setting `OutputType` to `Library` by default when it's not set, so when we reach our target, `OutputType` will always be either `Library` (default OR user setting) or what the user as set. Because of that, we cannot check if this was actually set by the user.

I have tried to force setting it to `Exe` in our SDK prop but doing so I then end up in the situation where I am messing up with VSTest if the user is setting `UseVSTest`.

**Comment by nohwnd** [comment]
When you say target do you mean the .target specifically? You should be able to read and save the value in .props, which will run before what user has set (unless they import it manually at the end of their project). Pretty much doing the opposite of what you do when you would want user to customize your option.

**Comment by Evangelink** [comment]
> When you say target do you mean the .target specifically?

Yes

> You should be able to read and save the value in .props

No, at least, not with what I tried. Basically `Microsoft.NET.Test.Sdk` is imported before us and sets `OutputType` to `Library` so when we are called we never have empty which means that in the .target, I cannot differntiate `Library` set by user or by net sdk.

**Comment by nohwnd** [comment]
You are right, I don't know what I was thinking.
