### ISSUE TITLE
Strange runtime identifier printed in the banner

### ISSUE THREAD

**Issue by MarcoRossignoli** [microsoft/testfx#3579]
<img width="1089" alt="image" src="https://github.com/user-attachments/assets/b32dc725-d785-4c77-8578-5138ddeee35d">

Code here https://github.com/microsoft/testfx/blob/main/src/Platform/Microsoft.Testing.Platform/OutputDevice/TerminalOutputDevice.cs#L141

Why don't use the api https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.runtimeinformation.runtimeidentifier?view=net-8.0#system-runtime-interopservices-runtimeinformation-runtimeidentifier

**Comment by nohwnd** [comment]
Without getting the short name out of the framework description the information is too long. This is especially visible when you have the source assembly printed as well: 

![image](https://github.com/user-attachments/assets/5e113e18-47d1-4186-afed-b76606c1e969)


Each line would say .NET Framework 4.8.9261.0 taking a lot of screen estate. Parsing out the short name is quite involved: as seen here in our copy of nuget.frameworks that we use in vstest (or in the original code). 

https://github.com/microsoft/vstest/blob/80af388e851d0d8b88f93d07d46d47054acb9951/src/Microsoft.TestPlatform.ObjectModel/Nuget.Frameworks/NuGetFramework.cs#L196

We don't want to take dependency on nuget.frameworks, and I did not want to introduce the tens of classes we copy in vstest to do the work, so I just parsed the framework minimally, which is not enough.

> Why don't use the api https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.runtimeinformation.runtimeidentifier?view=net-8.0#system-runtime-interopservices-runtimeinformation-runtimeidentifier

This api is not available for .net framework, and it also has different information, this returns win-x64, or similar runtime id. Did you mean different api?

**Comment by nohwnd** [comment]
@MarcoRossignoli  please revert this to the more specific issue, it is better to have more issues open than to discuss x different things here :)

**Comment by MarcoRossignoli** [comment]
> We don't want to take dependency on nuget.frameworks, and I did not want to introduce the tens of classes we copy in vstest to do the work, so I just parsed the framework minimally, which is not enough.

What was there before? I recall that we had correct info or?

**Comment by MarcoRossignoli** [comment]
We had this one 
<img width="612" alt="image" src="https://github.com/user-attachments/assets/6dae722a-9c68-4f52-a694-cda8c629b6a2">

Wasn't so bad or? Also know the RID is useful imo or we don't understand from the output the OS.

**Comment by nohwnd** [comment]
![image](https://github.com/user-attachments/assets/71714f92-9208-41e0-83b1-2c833f996cec)
 this is what was shown in 3.4.3 on .NET Framework.

**Comment by nohwnd** [comment]
> We had this one <img alt="image" width="612" src="https://private-user-images.githubusercontent.com/7894084/358521068-6dae722a-9c68-4f52-a694-cda8c629b6a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3OTczMTQsIm5iZiI6MTcyMzc5NzAxNCwicGF0aCI6Ii83ODk0MDg0LzM1ODUyMTA2OC02ZGFlNzIyYS05YzY4LTRmNTItYTY5NC1jZGE4YzYyOWI2YTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTZUMDgzMDE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzgyYjJhMzY3MWU4ZmJjY2JhMTZlYjQyN2RjNTExNTEyNmIzZDMzYzlkNWVmNTE4NmZiZTEzOWZhNTljMWIzZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.QL0J6dbd5F7kF7uR-lOX0jrN_SV2QMBdz1U1I89BAsc">
> 
> Wasn't so bad or? Also know the RID is useful imo or we don't understand from the output the OS.

This is still there, for .NET. This issue is about .NET Framework. 

New .NET (Core) output is this: 
![image](https://github.com/user-attachments/assets/1ef447e1-5af3-4de7-8167-8ffecfd32805)

And yes there we lost the OS in the header, I can put it back. But won't put it into each of the assembly lines that are shown on `from *` lines.

**Comment by MarcoRossignoli** [comment]
ok so we need to do someting custom we don't expect any 4.9 for what I know so starting from > 4.7.* take only 2 value.

**Comment by nohwnd** [comment]
- [ ] show full rid in banner on .NET
- [ ] improve parsing of .NET Framework to show two digits unless 4.6.2, 4.7.1, 4.7.2, 4.8.1 - https://versionsof.net/
- [ ] double check net10
