### ISSUE TITLE
Questions about test adapter vs framework versions compatibility when using vstest.console.exe

### ISSUE THREAD

**Issue by pkruk2** [Microsoft/testfx#359]
Hello, 

1. If I have MSTest.TestFramework version X in project, do I have to use the same version for MSTest.TestAdapter? 

- For example, if I have framework 1.2.0,  do I have to use adapter 1.2.0 too?
- Or can I use for example 1.3.0?

2. Should I specify test adapter as argument to vstest.console, or should it be referenced from tested project?

I am asking because I have downloaded most recent vstest and mstest test adapter (Microsoft.TestPlatform 15.6.0-preview-20171211-02 and MSTest.TestAdapter 1.2.0) and tried using it to run tests which refer to various versions of MSTest framework, with or without adapter in project. There were several issues. I could not reliably run tests:
- if I specified test adapter 1.2.0 to vstest, I could run tests in project with mstest 1.2.0 and no test adapter, and in project with mstest 1.1.18 and adapter 1.1.18. But I had errors or no tests were executed for example in project with mstest 1.2.0 and adapter 1.2.0, or in project with mstest 1.1.18 and no adapter, or in project with mstest 1.1.14 and adapter 1.1.14
- if I did not specify adapter to vstest, I could run tests in project with framework 1.1.18 and adapter 1.1.18, but it did not work for project with framework/adapter 1.2.0 or 1.1.14

Here are tables which show tested combinations:

**Vstest (microsoft.testplatform.15.6.0-preview-20171211-02) with test adapter 1.2.0**

  | MSTest Framework   1.2.0 | MSTest Framework   1.1.18 | MSTest Framework   1.1.14
-- | -- | -- | --
No MSTest Adapter   in project | OK - tests   executed | Error (2) | No tests   discovered
MSTest Adapter   1.2.0 in project | No test discovered | Error (2) |  
MSTest Adapter   1.1.18 in project | Error (1) | OK - tests   executed |  
MSTest Adapter   1.1.14 in project |   |   | Error (3)

Errors:
1. An exception occurred while invoking executor 'executor://mstestadapter/v2': Method 'get_Arguments' in type 'Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.TestMethodInfo' from assembly 'Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' does not have an implementation.
2. Could not load type 'Microsoft.VisualStudio.TestTools.UnitTesting.ITestDataSource' from assembly 'Microsoft.VisualStudio.TestPlatform.TestFramework, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
3. Type 'Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.MSTestSettings' in assembly 'Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' is not marked as serializable.

**Vstest (microsoft.testplatform.15.6.0-preview-20171211-02) without test adapter**

  | MSTest Framework   1.2.0 | MSTest Framework   1.1.18 | MSTest Framework   1.1.14
-- | -- | -- | --
MSTest Adapter   1.2.0 in project | No tests   discovered | Error (1) |  
MSTest Adapter   1.1.18 in project | No tests   discovered | OK - tests   executed |  
MSTest Adapter   1.1.14 in project |   |   | No tests   discovered

Errors:
1. Could not load type 'Microsoft.VisualStudio.TestTools.UnitTesting.ITestDataSource' from assembly 'Microsoft.VisualStudio.TestPlatform.TestFramework, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

As a side note, I also checked nunit and xunit and I could basically run tests in projects with various versions of framework and adapters.

**Comment by jayaranigarg** [comment]
@pkruk2  : We apologize for the confusion and inconvenience.
>If I have MSTest.TestFramework version X in project, do I have to use the same version for MSTest.TestAdapter?
Yes, both adapter and framework should have same version and should both be installed in test project. We advise to install latest stable version (1.2.0) or beta(1.3.0-beta2).
>Should I specify test adapter as argument to vstest.console, or should it be referenced from tested project?
No, you don't have to specify test adapter to vstest.console. It should be referenced by test project itself.

**Comment by pkruk2** [comment]
Thank you, using the same version of test framework and test adapter indeed works.

I also checked that it also works with VsTestConsoleWrapper if the project does not have the test adapter installed.
