### ISSUE TITLE
Warning if the runsettings contains non supported element like datacollectors and logger inside the VSTestBridge

### ISSUE THREAD

**Issue by MarcoRossignoli** [microsoft/testfx#3599]
We should send a warning if in the runsettings there're section no more supported with a "we will ignore it" and the link to the website with the diff, same warning will end also in VS.

**Comment by Evangelink** [comment]
@MarcoRossignoli @nohwnd Do you think it's safe to also report on the `RunConfiguration` entries?

**Comment by MarcoRossignoli** [comment]
I would not, only notify that the sections will be ignored.
