### ISSUE TITLE
Test case with Test Method Extension, not visible in TFS window to associate with test case

### ISSUE THREAD

**Issue by anshuls01** [Microsoft/testfx#360]
## Description
in MsTestV2, created one test case with test method attribute Extension.
Trying to associate test case with TFS, but TFS window shows only the test case with [TestMethod] attribute in the assembly and not showing any test case with Test Method Extension to link with TFS.

## Steps to reproduce
> Create Test Method Extension as mentioned in the link: https://github.com/Microsoft/testfx-docs/blob/master/RFCs/003-Customize-Running-Tests.md
> Decorate test case with Test Method Extension
> Create Manual Test case in TFS, save and get test case id
> Go to work item with the generated test case id
> Associate Automation, only test case with [TestMethod] attributes are available to link with TFS, not the test case decorated with Test Method Extension

## Expected behavior
> Test case with TestMethod Attribute extension should be able to link with TFS Test case

## Actual behavior
> Test case with TestMethod Attribute extension not able to link with TFS Test case

## Environment
> VS 2017, MsTest 2
> WIn 10

**Comment by pvlakshm** [comment]
Association a test case to a work item is not yet supported. Please see here: https://developercommunity.visualstudio.com/content/problem/159801/cant-associate-test-case-to-work-item.html.

**Comment by anshuls01** [comment]
Hello pvlakshm,

I think there is some gap in my explanation.
![testcase_u](https://user-images.githubusercontent.com/15679723/35799158-e52327f6-0a8a-11e8-8692-ce5972b0cd98.jpg)
Please have a look the highlighted area with green color in above image.
Test Explorer can find both the test case.
1. MsTest V2 vanilla
2. Testmethod Attribute extension

now when I tried to link with Tfs Work Item, only test case with [TestMethod] attribute appears.
Please have a look at the below screenshot:

![selecttest](https://user-images.githubusercontent.com/15679723/35799579-32817f6a-0a8c-11e8-8a13-05cb33f1b37e.jpg)

any help will be really appreciated
Thanks
Anshul

**Comment by anshuls01** [comment]
Hello Jaya,

any update on the above..., still waiting for the reply.

Thanks
Anshul

**Comment by jayaranigarg** [comment]
@anshuls01 : As of now MSTestV2 does not support test case linking to a workitem. When you are trying to link and you see 'TestMethod2' is result of some bug and is unexpected behaviour. Ideally none of the testmethods should appear for linking to work items.

Thank you for your feedback! We are trying to prioritise bringing test case linking support in MSTestv2.
Tagging @pvlakshm to comment on the timeline.

**Comment by anshuls01** [comment]
Hello Jaya,
Do we have any update on this issue? It's a blocker for us to migrate to MsTestV2, is there any alternate way to associate the test case (may be api call)?  if Linking is not possible through IDE

Thanks
Anshul

**Comment by anshuls01** [comment]
Hello Jaya,

just to share the update, I am able to associate the test case after using Visual studio 2017 Preview 2.0 version 15.9 and greater. Extension part still needs to check and will confirm this. I am sure that will be much easier compared to MsTest, Already Pratap writes a detailed `[blog](https://blogs.msdn.microsoft.com/devops/2017/07/18/extending-mstest-v2/)` about this.

one question I've; when Preview version functionality will be available with Visual Studio main release.
Thanks
Anshul

**Comment by jayaranigarg** [comment]
@anshuls01 : Preview functionality will be available in the RTM release. Please try this using latest VS 15.9.

**Comment by anshuls01** [comment]
Thanks for update Jaya, I'll give a try.
