### ISSUE TITLE
++(full video Clip)​!​! Kha Nữ Lộ Video Thanh Thị Kha Nữ Original

### ISSUE THREAD

**Issue by gh-cobaia** [microsoft/testfx#3613]
Video Claiming to Show Tragic Final Moments of Dr Moumita Is Unrelated!

[Watch 🟢 ➤ ➤ ➤ 🌐 [Click Here To link (Full Viral Video Link](https://bit.ly/3xC5Gu8)

[🔴 ➤►DOWNLOAD👉👉 ([Full Viral Video Link](https://bit.ly/3xC5Gu8))]

In the aftermath of the horrific rape and murder of a junior doctor at RG Kar Medical College and Hospital in Kolkata, a video has surfaced on social media claiming to show her final moments. This video has caused widespread outrage and confusion. However, it has been confirmed upon investigation that the video is unrelated to the tragic incident.

Social Media Posts:
A viral short video clip purports to show the last moments of the doctor who was raped and murdered in Kolkata. The video claims to depict tragic scenes of the doctor recording herself shortly before her death.

The story gained traction on social media, and the sensational nature of the video further fueled the claim, which quickly spread across platforms like Facebook and YouTube.

The video was viral on TikTok also.

Fact-Check :
Recently, a video has gone viral on social media, claiming to show the final moments of the late Dr. Moumita Debnath, a doctor who was allegedly raped and murdered. This video has stirred significant emotions and concerns, prompting many to question its authenticity.

Source of the Video:
We searched for some of the first occurrences of the video and noticed they had been shared at least since August 15th, as seen here. While some initial videos were removed now, these posts claimed that the clip was an instance of the late Dr Moumita recording her last moments and sending them to her mother. However, we didn’t notice any report from international media of such a video being sent to Moumita’s mother.

While several users also highlighted the unrelated viral video making rounds, we couldn’t identify the source of the video; it appears to be a scene from a staged scene, not a recording by the victim. Also, upon close inspection, it appears that the face of the victim in this tragic incident, the late Dr Moumita Debnath, does not match that of the girl seen in the viral video either.

While the video appears to recreate the pain Dr Moumita endured during her last moments, its visual and thematic content matches scenes from a fictional production that has been taken out of context to mislead the public.

Police Findings:
According to the Kolkata Police, the doctor’s body was discovered in a brutal condition inside the hospital premises. Given the severity of her injuries and the circumstances of her death, it is highly unlikely that she could have recorded herself during or after the attack. Click here to read more.

Impact of Misleading Narratives and the Tragic Incident which send shockwaves around the region:
The circulation of this misleading video has misled the public and added to the distress of the victim’s family and friends. Sharing such misinformation can obstruct the investigation and spread false narratives, harming public understanding and the pursuit of justice.

The recent Kolkata doctor rape case has shocked the nation and sparked widespread protests. The incident involved the rape and murder of a 31-year-old female postgraduate trainee doctor at RG Kar Medical College and Hospital. Her body was found on August 9, 2024, in a seminar hall of the hospital.

The accused, identified as Sanjay Roy, a civic volunteer with the Kolkata Police Disaster Management force, was arrested after CCTV footage and other evidence linked him to the crime. On the night of the incident, he reportedly consumed alcohol with a patient’s relative before entering the seminar hall where the victim was resting. After committing the crime, he was seen leaving the premises around 4:30 AM. Following his arrest, he confessed to the crime.

This incident has triggered massive protests by the medical community, demanding justice and better safety measures. The protests have also highlighted alleged negligence by the hospital administration and lapses in security, leading to suspensions of several hospital officials. The Indian Medical Association (IMA) and other medical associations have held strikes in response to the incident.

In addition to protests within India, the case has garnered international attention, with rallies held in solidarity in places like Bangladesh. The West Bengal government, led by the Trinamool Congress, has faced significant criticism for handling the situation, with some accusing the authorities of attempting to cover up the incident.

The investigation is ongoing, and the accused is currently in police custody. More details about the tragic incident are here.

Conclusion:
The video claiming to show the last moments of the doctor in the Kolkata rape and murder case is fake. It is crucial to verify the authenticity of content before sharing it on social media, especially in sensitive cases like this. Misinformation can have serious consequences, including hindering investigations and causing additional harm to those affected by the tragedy

**Comment by isratjerinruba2** [comment]
https://skylivetvgo.com/viral/?Thanh


https://skylivetvgo.com/viral/?Thanh


https://skylivetvgo.com/viral/?Thanh


https://skylivetvgo.com/viral/?Thanh


https://skylivetvgo.com/viral/?Thanh


https://skylivetvgo.com/viral/?Thanh


https://skylivetvgo.com/viral/?Thanh


https://skylivetvgo.com/viral/?Thanh


https://skylivetvgo.com/viral/?Thanh


https://skylivetvgo.com/viral/?Thanh


https://skylivetvgo.com/viral/?Thanh


https://skylivetvgo.com/viral/?Thanh


https://skylivetvgo.com/viral/?Thanh


https://skylivetvgo.com/viral/?Thanh


https://skylivetvgo.com/viral/?Thanh


https://skylivetvgo.com/viral/?Thanh


https://skylivetvgo.com/viral/?Thanh


https://skylivetvgo.com/viral/?Thanh


https://skylivetvgo.com/viral/?Thanh


https://skylivetvgo.com/viral/?Thanh


https://skylivetvgo.com/viral/?Thanh


https://skylivetvgo.com/viral/?Thanh


https://skylivetvgo.com/viral/?Thanh


https://skylivetvgo.com/viral/?Thanh


https://skylivetvgo.com/viral/?Thanh


https://skylivetvgo.com/viral/?Thanh


https://skylivetvgo.com/viral/?Thanh


https://skylivetvgo.com/viral/?Thanh


https://skylivetvgo.com/viral/?Thanh


https://skylivetvgo.com/viral/?Thanh


https://skylivetvgo.com/viral/?Thanh


https://skylivetvgo.com/viral/?Thanh


https://skylivetvgo.com/viral/?Thanh


https://skylivetvgo.com/viral/?Thanh


https://skylivetvgo.com/viral/?Thanh


https://skylivetvgo.com/viral/?Thanh


https://skylivetvgo.com/viral/?Thanh


https://skylivetvgo.com/viral/?Thanh


https://skylivetvgo.com/viral/?Thanh


https://skylivetvgo.com/viral/?Thanh


https://skylivetvgo.com/viral/?Thanh


https://skylivetvgo.com/viral/?Thanh


https://skylivetvgo.com/viral/?Thanh
