### ISSUE TITLE
Parameters should not contain `?` or end with `-`

### ISSUE THREAD

**Issue by nohwnd** [microsoft/testfx#3658]
Parameters currently validate that they contain `a-z` `0-9` `-` (dash), or `?`. But `?` should IMHO be valid only as alias for --help, and ther should not be parameters that say `--what??`

Similarly we don't check that the name does not end with `-` so currently user can register `--i-am-so-incomplet-`.

**Comment by Evangelink** [comment]
I tend to agree with @MarcoRossignoli, I don't see much disadvantage in keeping it this way (besides it means less complex validation code to maintain). Similarly, we cannot validate that some extension would register (`--mysuperlongoptionneversplitanywhere`) which is not super uniform to what we do but I don't think this would be a good idea to say you register your option as a "sentence" and we take care of the formatting (actually it could be an option we provide but should not be the only choice).
