### ISSUE TITLE
Show targetted framework rather than effective runtime

### ISSUE THREAD

**Issue by nohwnd** [microsoft/testfx#3669]
## Describe the bug

![image](https://github.com/user-attachments/assets/4a810565-f5ce-47cd-b0e9-c62b6229f081)
![image](https://github.com/user-attachments/assets/1b84ecf9-a3e6-4078-a17d-73a8d6de21a5)

On .NET and .NET Framework we are showing the information from  RuntimeInformation.FrameworkDescription. This is the actual runtime that is being used to run the executable, and not the target framework user specifies in project.

Let's assume the dlls tested were built targetting net6 (with roll forward = latest), and net472.

To avoid confusion and losing information I would show:

- in header -> the effective runtime net8.0 / net489
- next to dll: the targeted framework as defined in TargetFrameworkAttribute on the assembly in this case net6.0 / net472

**Comment by MarcoRossignoli** [comment]
To me it's fine, check that `TargetFrameworkAttribute` is native aot preserved.

**Comment by MarcoRossignoli** [comment]
On `dotnet test` mode we need to find a way to show all these info too.

**Comment by Evangelink** [comment]
I like the idea, especially keeping the header with the runtime so we have both info
