### ISSUE TITLE
Only the first instance of `TestMethodAttribute.Execute` returning TestResult[] value is used, not all of them.

### ISSUE THREAD

**Issue by walterlv** [Microsoft/testfx#367]
## Description
> When I implement my own `TestMethodAttribute`, I can override the `Execute` method and return my own `TestResult[]`. But every code that calls `TestMethodAttribute.Execute` only takes the first one.
> 
> Can all the results be returned correctly?
> 
> ![image](https://user-images.githubusercontent.com/9959623/36063893-a8b6f6a8-0ebd-11e8-80e3-dc9c42fea73e.png)

## Steps to reproduce

> 1. Write my own `TestMethodAttribute`.
> 1. return multiple `TestResult`.
> 1. Run UnitTests and review the result.
> 
> ```csharp
> public override TestResult[] Execute(ITestMethod testMethod)
> {
>     return new[] { new TestResult(), new TestResult() };
> }
> ```

## Expected behavior
> All `TestResult`s should be used, not only the first one.

## Actual behavior
> Only the first `TestResult` is used.

## Environment
> Mstest v2

**Comment by jayaranigarg** [comment]
@walterlv: Thank you for reaching out to us. We already have an issue filed for same. Please follow https://github.com/Microsoft/testfx/issues/358 for the updates.
