### ISSUE TITLE
Request to include Create Unit Tests for VB.NET in VS 2017

### ISSUE THREAD

**Issue by Gandum** [microsoft/testfx#376]
VS 2017 does not support Create Unit Tests in VB projects.
Requesting to include functionality in VS 2017 and beyond.

**Comment by cltshivash** [comment]
Adding @ManishJayaswal

**Comment by ManishJayaswal** [comment]
I have created an internal bug to track this issue - (https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_queries?id=585861&fullScreen=false&_a=edit)
