### ISSUE TITLE
Advertise test framework that supports the new `Microsoft.Testing.Platform` built by Tom

### ISSUE THREAD

**Issue by MarcoRossignoli** [microsoft/testfx#3760]
@thomhurst  you're helping a lot in the shape of the new testing platform, we cannot do a lot to recognize your effort and time spent here, but what we can do is help the visibility of your framework if you're interested to challenge the OSS market.

If you're interested we can for now add a link here https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-platform-intro?tabs=dotnetcli#supported-test-frameworks that point to your documentation.

Clearly if you're not interested it's totally fine.

cc: other well known framework author for visibility @bradwilson @OsirisTerje

**Comment by thomhurst** [comment]
Ah thanks so much @MarcoRossignoli ! I'd absolutely love that !

I find advertising new OSS solutions one of the hardest things to do so I appreciate any help 😄

**Comment by MarcoRossignoli** [comment]
Feel free to drop here the link to your documentation on how to use the testing platform with your adapter, you can take inspiration by nUnit and MSTest pages.

**Comment by thomhurst** [comment]
I have a documentation page here already: https://thomhurst.github.io/TUnit/

Is that alright for you?

**Comment by MarcoRossignoli** [comment]
PR out https://github.com/dotnet/docs/pull/42490

**Comment by Evangelink** [comment]
@MarcoRossignoli Thank you and awesome suggestion! 

@thomhurst Thank you for trusting our new platform and for your super active collaboration.

I am moving this issue as fixed.
