### ISSUE TITLE
Test discovery not working in VS 2012

### ISSUE THREAD

**Issue by MaxTranced** [Microsoft/testfx#378]
## Description
> **IMPORTANT**: if the defect is reproduced only in a workflow from within the Visual Studio IDE then do not report the issue here - instead, please report it using Visual Studio's "Send Feedback" option that can be accessed from the Help menu OR using this link https://developercommunity.visualstudio.com.
>
> For a defect specific to the MSTest V2 test framework, describe the issue you've observed.

I could not easily find a way to report the bug from the VS 2012 IDE nor from that link. The IDE option for reporting a bug takes me to a "Microsoft Connect Has Been Retired" page and the site seems geared towards VS 2017, suggesting that I report from the IDE. If I should post somewhere else, please advise where.

## Steps to reproduce
> What steps can reproduce the defect?
> Please share the setup, sample project, target platform (desktop, core, uap)

The machine (VM using Windows 10 64 bit) has multiple VS installations (2012 Pro, 2012 Express for Web, 2017 Pro). The same solution, when loaded in VS 2017 detects all of the unit tests after a build, while in VS 2012 Pro and Express it does not load the unit tests list. After a full build I sometimes get "Rebuild All succeeded" and sometimes get "Unexpected error detected. Check the Tests Output Pane for details.". However, the output pane has absolutely no error details.

Output from VS 2012 Express for Web, at the end of a full build, which shows the above error message in the status bar:

------ Discover test started ------
C:\Users\<redacted>\AppData\Local\Temp\VisualStudioTestExplorerExtensions\MSTest.TestAdapter.1.2.0/build/_common/Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.dll
========== Discover test finished: 0 found (0:00:00.9691018) ==========

Output from VS 2012 Pro (only after clicking on the tests tab, as the build does not seem to trigger the test discovery, then the above error message flashes for a brief time):

------ Discover test started ------
========== Discover test finished: 0 found (0:00:00.7412048) ==========

I'm pretty sure that this worked at some point, I recall testing that things work when I switched to MSTest, but cannot figure out what changed in the meantime.

## Expected behavior
> Share the expected output

Tests list loads or I get a clear error message.

## Actual behavior
> What is the behavior observed?

Tests list does not load, no clear error message.

## Environment
> Please share additional details about the test environment.
> Operating system, Build version of vstest.console, Package version of MSTest
> framework and adapter

Mentioned above.

**Comment by cltshivash** [comment]
Please report the issue at https://developercommunity.visualstudio.com/
