### ISSUE TITLE
Are you planning to add `--filter` in Microsoft.Testing.Platform core?

### ISSUE THREAD

**Issue by bradwilson** [microsoft/testfx#3780]
xUnit.net has an [open issue for a generalized filter language](https://github.com/xunit/xunit/issues/1833) and my initial thought was to implement something like [MSTest's filter query language](https://github.com/microsoft/testfx/blob/main/docs/mstest-runner-graphqueryfiltering/graph-query-filtering.md).

In core Microsoft.Testing.Platform there is no `--filter` right now in 1.4. You will get one if you use the VSTest bridge (which implements the old VSTest filter syntax). I presume you'll also get one using MSTest 3.6, which implements the above-linked page.

Does this mean you think `--filter` is something that each test framework should be able to safely add, and it'll be test framework implementation dependent? That's my read right now, but I wanted to make sure, because:

* Previous discussions have highlighted that any conflicting switches will break the ability to run tests
* There is also a generalized filtering interface (`ITestExecutionFilter`) that, while currently only supported by `TestNodeUidListFilter` (to run specific tests) could in theory be extended in the future by Microsoft.Testing.Platform

So this is my official query, in two parts:

1. Am I safe to add `--filter` as a testing framework?
2. What are the future plans for `ITestExecutionFilter` beyond `TestNodeUidListFilter`?

**Comment by thomhurst** [comment]
I've raised #3590 as filters are locked down currently behind internal code. You could currently do it in a hacky way, by using a normal command line provider, it's just it won't populate that `ITestExecutionFilter` object.

> my initial thought was to implement something like [MSTest's filter query language](https://github.com/microsoft/testfx/blob/main/docs/mstest-runner-graphqueryfiltering/graph-query-filtering.md).

You don't have to re-implement this. When I was asking about filters months ago they opened this up (it's still got an experimental attribute on it though) for us framework creators, and I've successfully been using it in my library and it works great. Can filter by assembly, namespace, class name, test name, including wildcards, and also can filter based on test node properties.

If you do want that you can call  `testApplicationBuilder.AddTreeNodeFilterService(extension);` when setting up the test app builder.

Then where you handle filtering you can check if the `ITestExecutionFilter` is a `TreeNodeFilter` and then perform the filtering there. The `TreeNodeFilter` has a `MatchesFilter` method to do it for you.

**Comment by bradwilson** [comment]
> You don't have to re-implement this.

Unlike TUnit, I have two different command lines. I can't reuse their code on my native command line UX.

**Comment by thomhurst** [comment]
> > You don't have to re-implement this.
> 
> Unlike TUnit, I have two different command lines. I can't reuse their code on my native command line UX.

Oh right of course, you have different runners! Ignore me 😇

**Comment by Evangelink** [comment]
> Does this mean you think --filter is something that each test framework should be able to safely add, and it'll be test framework implementation dependent? That's my read right now, but I wanted to make sure, because:

For me, yes. Filtering is too depend to the framework. I think it'd be good to have some basic filtering capabilities available for all frameworks but I see it as specific filters (e.g. we could have `--filter-uid` where you can pass the node UID to run).

I am not a big fan of having `--filter` being tight to VSTest filter, and on the first release it was `--vstest-filter` but people were complaining (and we had no alternative implemented yet to justify not doing it).

**Comment by bradwilson** [comment]
After thinking about it more, and given that I'm planning to leave my other simpler filters in place, I may use `--filter-query` for this. I don't want to particularly elevate it above any other filter style.

**Comment by Evangelink** [comment]
Makes sense for me! I like the name too :)
