### ISSUE TITLE
[Issue] [AssemblyInitialize], [AssemblyCleanup], [ClassInitialize] and [ClassCleanup] are not listed as individual entries in the VS Test Explorer and TRX log

### ISSUE THREAD

**Issue by Vincezhaoc** [microsoft/testfx#3785]
## Describe the bug

From change log and PR 2904 [change log 3.5.0](https://github.com/microsoft/testfx/blob/main/docs/Changelog.md#350---2024-07-15) and https://github.com/microsoft/testfx/pull/2904. I am aware of MSTest should support `[AssemblyInitialize]`, `[AssemblyCleanup]`, `[ClassInitialize]` and `[ClassCleanup]` as separate entries in Visual Studio's Test Explorer and in TRX log. However, after upgrading MSTest.TestFramework, MSTest.TestAdapter and MSTest.Sdk to version 3.5.2, my local Visual Studio (Microsoft Visual Studio Enterprise 2022 (64-bit) - Current; Version 17.10.6) Test Explorer still only displays the test methods and not the four entries mentioned.

### IDE information

```
Microsoft Visual Studio Enterprise 2022
Version 17.11.2
VisualStudio.17.Release/17.11.2+35222.181
Microsoft .NET Framework
Version 4.8.09032

Installed Version: Enterprise
```

#### csproj

```
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<TargetFrameworks>net8.0;net472</TargetFrameworks>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<IsPackable>false</IsPackable>
		<OutputType>Library</OutputType>
	</PropertyGroup>

	<!-- Set C# 8.0 for net472 to support Nullable -->
	<PropertyGroup Condition="'$(TargetFramework)' == 'net472'">
		<LangVersion>8.0</LangVersion>
	</PropertyGroup>

	<ItemGroup>
		<!--<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />-->
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
		<PackageReference Include="Microsoft.ApplicationInsights" Version="2.22.0" />
		<PackageReference Include="MSTest.Sdk" Version="3.5.2" />
		<PackageReference Include="MSTest.TestAdapter" Version="3.5.2" />
		<PackageReference Include="MSTest.TestFramework" Version="3.5.2" />
		<PackageReference Include="MSTest.Analyzers" Version="3.5.2" />
		<PackageReference Include="Microsoft.Testing.Extensions.TrxReport" Version="1.3.2" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	</ItemGroup>

</Project>
```
#### UnitTest1.cs
```
namespace mstestfeatures_demo
{

    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using System;

    [TestClass]
    public class UnitTest1
    {

        [AssemblyInitialize]
        public static void AssemblyInit(TestContext context)
        {
            Console.WriteLine("Library init!");
        }

        [ClassInitialize]
        public static void ClassInit(TestContext context)
        {
            Console.WriteLine("Class UnitTest1 init!");
        }

        [ClassCleanup]
        public static void ClassCleanup()
        {
            Console.WriteLine("Class UnitTest1 do cleaning!");
            throw new Exception("Class UnitTest1 Cleanup failed.");
        }

        [TestMethod]
        public void TestMethod1()
        {
            Console.WriteLine("This test method1");
        }

        [TestMethod]
        public void TestMethod2()
        {
            Console.WriteLine("This test method2");
        }
    }
}
```

## Expected behavior

* `[AssemblyInitialize]`, `[AssemblyCleanup]`, `[ClassInitialize]` and `[ClassCleanup]` could be listed as individual entries in VS log and TRX log as mentioned from:
* [PR1698](https://github.com/microsoft/testfx/issues/1698)
* [PR2904](https://github.com/microsoft/testfx/pull/2904)
* [change log 3.5.0](https://github.com/microsoft/testfx/blob/main/docs/Changelog.md#350---2024-07-150)

## Actual behavior
![image](https://github.com/user-attachments/assets/9e6559d1-2fe7-4f18-931a-55b0415422ea)
![image](https://github.com/user-attachments/assets/3a38db9b-cc30-404a-a88c-b60a883ba883)
[testResults_net472_20240909111456.trx.txt](https://github.com/user-attachments/files/16924984/testResults_net472_20240909111456.trx.txt)

#### Purpose for finding this feature.
If an exception is thrown from `[AssemblyInitialize]`, `[AssemblyCleanup]`, `[ClassInitialize]` and `[ClassCleanup]`, it will be bound to the test methods' information view. I am trying to find any features support by MSTest to mark the four attributes as separate entries.

**Comment by Vincezhaoc** [comment]
Hi @Evangelink ,

Thanks for the prompt reply!

`[AssemblyInitialize]`, `[AssemblyCleanup]`, `[ClassInitialize]` and `[ClassCleanup]` can display in vs `Test Explorer` and the `.trx` log after add `<ConsiderFixturesAsSpecialTests>true</ConsiderFixturesAsSpecialTests>` inside ` <MSTest></MSTest` label section.

### This setting effects

#### .runsettings
```
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
  <!-- Configurations that affect the Test Framework -->
  <RunConfiguration>
    <!-- Use 0 for maximum process-level parallelization. This does not force parallelization within
    the test DLL (on the thread-level). You can also change it from the Test menu; choose "Run tests
    in parallel". Unchecked = 1 (only 1), checked = 0 (max). -->
    <MaxCpuCount>1</MaxCpuCount>
    <!-- Path relative to directory that contains .runsettings file-->
    <ResultsDirectory>.\TestResults</ResultsDirectory>
    <!-- true or false -->
    <!-- Value that specifies the exit code when no tests are discovered -->
    <TreatNoTestsAsError>true</TreatNoTestsAsError>
  </RunConfiguration>


  <!-- Adapter Specific sections -->

  <!-- MSTest adapter -->
  <MSTest>
    <TreatClassAndAssemblyCleanupWarningsAsErrors>true</TreatClassAndAssemblyCleanupWarningsAsErrors>
    <ConsiderFixturesAsSpecialTests>true</ConsiderFixturesAsSpecialTests>
    <AssemblyResolution>

    </AssemblyResolution>
  </MSTest>

</RunSettings>
```
#### Test Explorer
![image](https://github.com/user-attachments/assets/669248a3-a8ff-44c0-b015-1df14391335b)

### TRX Log
![image](https://github.com/user-attachments/assets/f13d2211-0c79-4160-94da-e409170b8ac6)


####Additon

Here I kindly forked from [MicrosoftDocs](https://github.com/MicrosoftDocs/visualstudio-docs) and add some content in my forked repo [Vincezhaoc/visualstudio-docs/configure-unit-tests-by-using-a-dot-runsettings-file.md](https://github.com/Vincezhaoc/visualstudio-docs/blob/main/docs/test/configure-unit-tests-by-using-a-dot-runsettings-file.md#mstest-element). May I know if it is appropriate to raise a PR and merge the additonal content into [MicrosoftDocs](https://github.com/MicrosoftDocs/visualstudio-docs)?

Please kindly let me know.


Thanks.

**Comment by Evangelink** [comment]
Yes please do file a PR! I am slowly trying to move all MSTest doc over to this doc https://learn.microsoft.com/dotnet/core/testing/unit-testing-mstest-configure#mstest-element. Would you mind also fixing it there?

Feel free to ping me on both the doc PR for review.

**Comment by Vincezhaoc** [comment]
Hi @Evangelink,

Here, I've created two PRs to update the usage instructions for `ConsiderFixturesAsSpecialTests`

Here's the breakdown:

* [PR 42567](https://github.com/dotnet/docs/pull/42567)
* [PR 42567](https://github.com/MicrosoftDocs/visualstudio-docs/pull/10391)

Please let me know if there are any mistakes.

#### Addition
Ping me additionally to assign some common tasks, as I will be using the MSTest framework extensively in both my learning and work, if you're open to it.

Feel free to reach out. 

Thank you!

**Comment by Evangelink** [comment]
Thank you so much @Vincezhaoc! I have approved with a small suggestion.

**Comment by Vincezhaoc** [comment]
Hi @Evangelink ,

I have updated the content based on the suggestions.

Thanks! 👍

**Comment by Evangelink** [comment]
I'll close this ticket, the doc team will review and merge your PR soon. Note that there is a bit of delay (few days) between the moment your PR is merged and the public website being updated.

**Comment by Vincezhaoc** [comment]
Many thanks! I accidentally removed the assignment  by mistake.

It's great to join this awesome repo.

My co-workers will know this features from official documentation soon. 😄 

Appreciate it.
