### ISSUE TITLE
Typo in MSTEST0016 description

### ISSUE THREAD

**Issue by Mertsch** [microsoft/testfx#3807]
## Describe the bug
https://learn.microsoft.com/en-us/dotnet/core/testing/mstest-analyzers/mstest0016
```
Rule description
A test class should have at least one test method or be static and have methods that are attributed with [AssemblyInitialization] or [AssemblyCleanup].
```
States `AssemblyInitialization`, but it should be `AssemblyInitialize`.

## Additional context
MSTest 3.6.0

**Comment by Evangelink** [comment]
We will be releasing a bug fix so I'll bakcport this fix into it.
