### ISSUE TITLE
MSTest.TestAdapter.Dotnet nuget package doesn't have a dependency on Microsoft.VisualStudio.TestPlatform.ObjectModel

### ISSUE THREAD

**Issue by rzio** [Microsoft/testfx#381]
## Description
I'm trying to use the MSTest.TestAdapter.Dotnet package inside an Azure function to execute tests on a schedule. When I'm adding nuget dependecy to the project it doesn't bring a dependecy on Microsoft.VisualStudio.TestPlatform.ObjectModel.
When I add a packageReference to  Microsoft.VisualStudio.TestPlatform.ObjectModel manually, I also have to add a binding redirect to version 14.0.0.0, since the loader looks for version 11.0.0.0.
All those steps work well in Console App, but since with Azure function I don't own the executable, the Microsoft.VisualStudio.TestPlatform.ObjectModel fails to load at all, since the loader doesn't even looks for it in the correct location.  (It doesn't look inside the function's code folder)

    *** Assembly Binder Log Entry  (3/16/2018 @ 10:13:48 AM) ***
    
    The operation failed.
    Bind result: hr = 0x80070002. The system cannot find the file specified.
    
    Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
    Running under executable  C:\Users\ALEXREZ\AppData\Local\Azure.Functions.Cli\1.0.9\func.exe
    --- A detailed error log follows. 
    
    === Pre-bind state information ===
    LOG: DisplayName = Microsoft.VisualStudio.TestPlatform.ObjectModel, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
     (Fully-specified)
    LOG: Appbase = file:///C:/Users/ALEXREZ/AppData/Local/Azure.Functions.Cli/1.0.9/
    LOG: Initial PrivatePath = NULL
    LOG: Dynamic Base = NULL
    LOG: Cache Base = NULL
    LOG: AppName = func.exe
    Calling assembly : (Unknown).
    ===
    LOG: This bind starts in default load context.
    LOG: Using application configuration file: C:\Users\ALEXREZ\AppData\Local\Azure.Functions.Cli\1.0.9\func.exe.Config
    LOG: Using host configuration file: 
    LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
    LOG: GAC Lookup was unsuccessful.
    LOG: Attempting download of new URL file:///C:/Users/ALEXREZ/AppData/Local/Azure.Functions.Cli/1.0.9/Microsoft.VisualStudio.TestPlatform.ObjectModel.DLL.
    LOG: Attempting download of new URL file:///C:/Users/ALEXREZ/AppData/Local/Azure.Functions.Cli/1.0.9/Microsoft.VisualStudio.TestPlatform.ObjectModel/Microsoft.VisualStudio.TestPlatform.ObjectModel.DLL.
    LOG: Attempting download of new URL file:///C:/Users/ALEXREZ/AppData/Local/Azure.Functions.Cli/1.0.9/Microsoft.VisualStudio.TestPlatform.ObjectModel.EXE.
    LOG: Attempting download of new URL file:///C:/Users/ALEXREZ/AppData/Local/Azure.Functions.Cli/1.0.9/Microsoft.VisualStudio.TestPlatform.ObjectModel/Microsoft.VisualStudio.TestPlatform.ObjectModel.EXE.
    LOG: All probing URLs attempted and failed.

## Steps to reproduce
* Create a console app in VS2017
* Add a package reference to MSTest.TestAdapter.Dotnet 1.0.4-preview
* Add code that uses MSTestDiscoverer
* Run (the executable will crash with unresolved binding)

## Expected behavior
Should run 

## Actual behavior
Crashes with
`Could not load file or assembly 'Microsoft.VisualStudio.TestPlatform.ObjectModel, Version=11.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`
To fix:
* Add a package reference to Microsoft.VisualStudio.TestPlatform.ObjectModel (only version 14.0.0.0 is available in Nuget)
* Add a binding redirect to app.config
```xml
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <probing privatePath="Extensions" />
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.VisualStudio.TestPlatform.ObjectModel" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
         <bindingRedirect oldVersion="1.0.0.0-14.0.0.0" newVersion="14.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
```
## Environment
* MSTest.TestAdapter.Dotnet 1.0.4-preview

**Comment by bc3** [comment]
Hey, I had a rather a like issue. I put the question on stackoverflow and answered it myself after also found the solution myself. The link to that stackoverflow article is: https://stackoverflow.com/questions/47155559/could-not-load-file-or-assembly-microsoft-visualstudio-testplatform-objectmodel/49360757#49360757

In short:

1) Install-Package Microsoft.TestPlatform.ObjectModel -Version 11.0.0 (will install the correct version of ObjectModel)
2) [DeploymentItem("Microsoft.VisualStudio.TestPlatform.ObjectModel.dll")] Add this item to a base class or so to make sure that this dll is deployed when testing

Regards Ben

**Comment by smadala** [comment]
@rzio MSTest.TestAdapter.Dotnet 1.0.4-preview is deprecated or shouldn't be used anymore. Use https://www.nuget.org/packages/MSTest.TestAdapter/1.2.0. 

Please let us know if you cann't use MSTest.TestAdapter for any reason.
