### ISSUE TITLE
Dark colors are printed incorrectly with FormattedTextOutputDeviceData

### ISSUE THREAD

**Issue by bradwilson** [microsoft/testfx#3821]
I noticed that dark colors (that is, `Black` and all the color names starting with `Dark`) are printed incorrectly, and are rendered as their lighter counterparts instead of the dark versions.

Here is a comparison between `Console.WriteLine` and `IOutputDevice.DisplayAsync`:

![image](https://github.com/user-attachments/assets/ac4879ce-79e3-4593-9257-d738866386e8)

The `Console` version:

```csharp
Console.WriteLine("This is the default color");

foreach (var consoleColor in Enum.GetValues<ConsoleColor>())
{
    Console.ForegroundColor = consoleColor;
    Console.WriteLine("This is foreground {0}", consoleColor);
}
```

The `IOutputDevice` version:

```csharp
await outputDevice.DisplayAsync(this, new TextOutputDeviceData("This is the default color"));

foreach (var consoleColor in Enum.GetValues<ConsoleColor>())
    await outputDevice.DisplayAsync(
        this,
        new FormattedTextOutputDeviceData(
            "This is foreground " + consoleColor.ToString()
        ) { ForegroundColor = new SystemConsoleColor { ConsoleColor = consoleColor } }
    );
```

I've attached the repro project.

[testfx.zip](https://github.com/user-attachments/files/16985841/testfx.zip)

**Comment by bradwilson** [comment]
@nohwnd @MarcoRossignoli

**Comment by MarcoRossignoli** [comment]
thanks for reporting this

**Comment by bradwilson** [comment]
Thanks for the quick fix!
