### ISSUE TITLE
MSTEST0036 is shown for cases where no shadowing happens

### ISSUE THREAD

**Issue by cremor** [microsoft/testfx#3824]
## Describe the bug
The following code shows MSTEST0036 (Do not use shadowing inside test class) even though no shadowing happens.

## Steps To Reproduce
```cs
namespace TestProject1;

[TestClass]
public class BaseTest
{
    protected TObject CreateObject<TObject>()
    {
        throw new NotImplementedException();
    }
}

[TestClass]
public class ExtendedTest : BaseTest
{
    // MSTEST0036 is shown here
    private SomeType CreateObject()
    {
        throw new NotImplementedException();
    }
}

public class SomeType;
```

## Expected behavior
No MSTEST0036 warning.

## Actual behavior
MSTEST0036 is shown.

## Additional context
This is a new problem in v3.6.0

I actually see MSTEST0036 twice in the error list - with different messages. It seems like one is from IntelliSense and the other one from actually building the project.

And the message "is already exist" should be fixed to be correct English.

![grafik](https://github.com/user-attachments/assets/8743f258-2d59-4b3e-990a-97ac1216bd77)

**Comment by Evangelink** [comment]
Hi @cremor!

Thanks for the bug report, indeed there are a few problems. We will work on them.
