### ISSUE TITLE
Inconsistency with DiaSession between MSTest and xUnit.net (as well as VSTest vs. Microsoft Testing Platform)

### ISSUE THREAD

**Issue by bradwilson** [microsoft/testfx#3832]
Quick summary of the problem:

We use `DiaSession` to map types to source in `xunit.runner.visualstudio`:
https://github.com/xunit/visualstudio.xunit/blob/main/src/xunit.runner.visualstudio/Utility/DiaSessionWrapper.cs
https://github.com/xunit/visualstudio.xunit/blob/main/src/xunit.runner.visualstudio/Utility/DiaSessionWrapperHelper.cs

(You can safely ignore the AppDomain gymnastics, as the bug report is using .NET 8.)

We get no source information when a test method comes from a base class in another assembly. MSTest does not have this problem, and I glanced at the source to ensure that they too are relying on `DiaSession`, so this probably comes down to me not understanding how I'm supposed to be using it in this scenario.

Also worth noting that everything works fine when we are in Microsoft Testing Platform mode (rather than VSTest mode), because in that scenario we don't ever see or invoke `DiaSession`; I assume MTP is doing all the source mapping under the hood for us, so it's also doing the right thing.

Any hints what I'm doing wrong in this scenario? Should I be trying to recurse up through the base classes when I get back "no answer" for a type?

For reference, the user issue with a repro project: https://github.com/xunit/xunit/issues/3023

**Comment by bjornhellander** [comment]
I found this: https://github.com/microsoft/testfx/blob/311fbc770c372ff53607e546e7e33c2deae165f5/src/Adapter/MSTest.TestAdapter/Discovery/UnitTestDiscoverer.cs#L151-L170

and this:
https://github.com/microsoft/testfx/blob/311fbc770c372ff53607e546e7e33c2deae165f5/src/Adapter/MSTest.TestAdapter/Discovery/TypeEnumerator.cs#L147-L150

Looks like MSTest makes sure to use the **declaring** type's name when looking up the source location. Could that be the important part in getting the correct behavior?

**Comment by bradwilson** [comment]
We don't have the declaring type available to us without recreating it with reflection.

We may be able to do that, but I'm not 100% sure. More importantly, though, I suspect the problem is larger than that, since it only affects things in a different assembly. I'd like to hear back from the VSTest team before moving forward.

**Comment by MarcoRossignoli** [comment]
@nohwnd I think that this one should be moved to VSTest, if I'm not mistaken the dia is an utility of VSTest

**Comment by nohwnd** [comment]
Tried to transfer, it is still being transferred, but this is imho TE issue. https://github.com/xunit/xunit/issues/3023#issuecomment-2367878443
