### ISSUE TITLE
[Question] IDE Test Output

### ISSUE THREAD

**Issue by thomhurst** [microsoft/testfx#3859]
Hey guys.

So my framework has had a bit of a boom and I've had a few questions from users that I'm not sure of the answers to.

People are asking how to see output in the test IDE.

So, in regards to testing platform, what do I need to do?

I've set `StandardOutputProperty` and `StandardErrorProperty` properties on the test nodes. Is that what would drive that? 

And also do you know if the VS test output has been implemented yet or is it a WIP?

**Comment by nohwnd** [comment]
We've seen [the video](https://www.youtube.com/watch?v=dtdgm8lKJZU) congrats on getting such a huge exposure 🙌🙌🙌

Looking at history Marco implemented the properties here: 
https://github.com/microsoft/testfx/pull/3748

and backported to (upcoming) 1.4.1 here, https://github.com/microsoft/testfx/pull/3749 

I think the plan is to release this week. The feature is flagged with [TPEXP](https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-platform-diagnostics)

**Comment by thomhurst** [comment]
Thanks @nohwnd !

I believe it's already in 1.4.0 because I'm already setting them here: https://github.com/thomhurst/TUnit/blob/964ec2626b05f91040b5a26b6730906bdf350f0a/TUnit.Engine/Services/SingleTestExecutor.cs#L226

I guess if nothing is showing it's just we have to wait for VS/Rider to implement the functionality.

**Comment by nohwnd** [comment]
Right, it's tagged 3.6.0 (== TP 1.4.0). https://github.com/microsoft/testfx/commit/ccf7de7eb21d773802ab940f110fd1308bf2b8fb

**Comment by thomhurst** [comment]
Thanks for the info 😄
