### ISSUE TITLE
Test methods with generic parameters don't show source locations in Microsoft.Testing.Platform mode in Test Explorer

### ISSUE THREAD

**Issue by bradwilson** [microsoft/testfx#3863]
When xUnit.net v3 test projects are in Microsoft Testing Platform mode, source information is missing when the test method parameter is generic.

https://github.com/user-attachments/assets/3c9f6e23-55f9-46c3-8cf8-fe57170726b6

Reproduced with:

- VS 2022 17.12 Preview 2
- NuGet package `xunit.v3` version `0.4.0-pre.20`

**Comment by bradwilson** [comment]
On a hunch, I brought back my implementation of https://github.com/microsoft/vstest/blob/main/docs/RFCs/0017-Managed-TestCase-Properties.md and now everything is working as expected.

I don't remember what issue it was in, but someone from the VSTest team told me this was outdated and no longer needed. That information appeared to be incorrect.

So...what's the story here? Is this working right now because Test Explorer hasn't been updated yet? Or is this working right now because the advice to just use `.FullName` was incorrect?

/cc @MarcoRossignoli 

Here's 2022 17.11 in VSTest mode:

![image](https://github.com/user-attachments/assets/a15cf6aa-2a64-45ed-896d-b49cc4821a73)

Here's 2022 17.12 Preview 2 in MTP mode:

![image](https://github.com/user-attachments/assets/63389433-ef38-45dc-b887-919614256b01)

Here's the diff: (note that `type.SafeName()` is an extension mode that just returns `type.FullName ?? type.Name` so that we can be guaranteed a non-null string value)

```diff
diff --git a/src/xunit.v3.common/Extensions/ReflectionExtensions.cs b/src/xunit.v3.common/Extensions/ReflectionExtensions.cs
index 39bd822f..6fde0a73 100644
--- a/src/xunit.v3.common/Extensions/ReflectionExtensions.cs
+++ b/src/xunit.v3.common/Extensions/ReflectionExtensions.cs
@@ -676,6 +676,55 @@ public static string ToSimpleName(this Type type)
 						: type.FullName;
 	}
 
+	/// <summary>
+	/// Converts a <see cref="Type"/> name into the correct form for a Microsoft.Testing.Platform
+	/// managed type name for using in managed TestCase properties.
+	/// </summary>
+	/// <remarks>
+	/// See <see href="https://github.com/microsoft/vstest/blob/main/docs/RFCs/0017-Managed-TestCase-Properties.md"/>
+	/// </remarks>
+	public static string ToTestingPlatformTypeName(
+		this Type type,
+		MethodInfo? testMethod = null,
+		Type? testClass = null)
+	{
+		Guard.ArgumentNotNull(type);
+
+		if (type.IsGenericParameter)
+		{
+			if (testMethod is not null)
+			{
+				var methodGenericArgs = testMethod.GetGenericArguments();
+				for (int i = 0; i < methodGenericArgs.Length; ++i)
+					if (methodGenericArgs[i] == type)
+						return "!!" + i;
+			}
+
+			if (testClass is not null)
+			{
+				var testClassGenericArgs = testClass.GetGenericArguments();
+				for (int i = 0; i < testClassGenericArgs.Length; ++i)
+					if (testClassGenericArgs[i] == type)
+						return "!" + i;
+			}
+		}
+
+		if (!type.IsGenericType)
+			return type.SafeName();
+
+		var baseTypeName = type.Name;
+		if (type.Namespace is not null)
+			baseTypeName = type.Namespace + "." + baseTypeName;
+
+		var genericTypes =
+			type
+				.GenericTypeArguments
+				.Select(t => ToTestingPlatformTypeName(t, testMethod, testClass));
+
+		return baseTypeName + "<" + string.Join(",", genericTypes) + ">";
+	}
+
 	static object? TryConvertObject(
 		object? argumentValue,
 		Type parameterType)
diff --git a/src/xunit.v3.core/ObjectModel/XunitTestCase.cs b/src/xunit.v3.core/ObjectModel/XunitTestCase.cs
index 03ac3416..db6a6b24 100644
--- a/src/xunit.v3.core/ObjectModel/XunitTestCase.cs
+++ b/src/xunit.v3.core/ObjectModel/XunitTestCase.cs
@@ -170,11 +170,11 @@ public XunitTestCase()
 
 	/// <inheritdoc/>
 	public string[] TestMethodParameterTypes =>
-		TestMethod.Parameters.Select(p => p.ParameterType.SafeName()).ToArray();
+		TestMethod.Parameters.Select(p => p.ParameterType.ToTestingPlatformTypeName(TestMethod.Method, TestClass.Class)).ToArray();
 
 	/// <inheritdoc/>
 	public string TestMethodReturnType =>
-		TestMethod.ReturnType.SafeName();
+		TestMethod.ReturnType.ToTestingPlatformTypeName();
 
 	/// <inheritdoc/>
 	public int Timeout { get; private set; }
```

**Comment by bradwilson** [comment]
I set up a branch for the changes: https://github.com/xunit/xunit/tree/testfx-3863

**Comment by bradwilson** [comment]
> I don't remember what issue it was in, but someone from the VSTest team told me this was outdated and no longer needed.

Found it: https://github.com/microsoft/testfx/issues/3478#issuecomment-2295821580

**Comment by bradwilson** [comment]
Also, if this is the answer:

> Is this working right now because Test Explorer hasn't been updated yet?

Then what is the migration path forward? Will Test Explorer support both styles into the future so as to preserve backward compatibility with test frameworks that are emitting the "VSTest" style vs. the "FullName" style? If so, for how long? We obviously don't want to unnecessarily degrade users who are stuck on older builds of Visual Studio that might still be supported.

**Comment by MarcoRossignoli** [comment]
> So...what's the story here? Is this working right now because Test Explorer hasn't been updated yet? Or is this working right now because the advice to just use .FullName was incorrect?

I suppose that use the full name in this case was not enough, so for now I think you can keep the fix you did, the second image attached is what I would expect. 

> Then what is the migration path forward? Will Test Explorer support both styles into the future so as to preserve backward compatibility with test frameworks that are emitting the "VSTest" style vs. the "FullName" style? If so, for how long? We obviously don't want to unnecessarily degrade users who are stuck on older builds of Visual Studio that might still be supported.

Test explorer will support both styles  I expect forever. VSTest is supported and will be for long time. So for adapters that won't support the VSTestBridge we use and evolve the `TestMethodIdentifierProperty` that's used in the new protocol workflow for VS too.

About `TestMethodIdentifierProperty` I had already a discussion ongoing to make it more useful and complete. We were thinking to have an object descriptor(or 2 different object props) that can be used in 2 way:
* descriptive information that VS can use to "show" to user the test method, something done for pure UX reason.
* a round trip object that let to the adapter to "precisely" point to a method info to allow quick discovery and invocation, tailored made on the current reflection api without the need of parsing and string manipulation.


cc: @drognanar @Evangelink

**Comment by nohwnd** [comment]
> > I don't remember what issue it was in, but someone from the VSTest team told me this was outdated and no longer needed.
> 
> Found it: [#3478 (comment)](https://github.com/microsoft/testfx/issues/3478#issuecomment-2295821580)

I am not sure if the is still any confustion, but: That specification is still valid when you are implementing a VSTest based test adapter. When Marco said this is the **old VSTest**, he meant that it is not relevant to your TestingPlatform implementation, not that it is not relevant to VSTest.

**Comment by bradwilson** [comment]
Solidified that this is about VSTest: https://github.com/xunit/xunit/commit/b4686ac5840771f72d63e0f1689d422b35ad118e

**Comment by MarcoRossignoli** [comment]
> For VSTest (via xunit.runner.visualstudio), that means setting TestCase.ManagedMethod and TestCase.ManagedType. For MTP, that means setting TestMethodIdentifierProperty. In both cases, I must use the "old VSTest" names or else Test Explorer is broken.

Ok I think you can use the "old VSTest" names, I don't see changes on parsing logic on TE side in near future.
