### ISSUE TITLE
CollectionAssert.AreEqual for collection of collections ignores even-items

### ISSUE THREAD

**Issue by acple** [microsoft/testfx#3879]
## Describe the bug

`CollectionAssert.AreEqual` for collection of collections ignores even-items in the collection.

## Steps To Reproduce

```csharp
int[][] expected = [[1, 2], [3, 4], [5, 6], [7, 8], [9]];
int[][] actual = [[1, 2], [999, 999, 999, 999, 999], [5, 6], [/*empty*/], [9]];
CollectionAssert.AreEqual(expected, actual); // Passed!
```

## Expected behavior
Collections are not equal

## Actual behavior
The test is passed

## Additional context
MSTest.TestFramework: v3.6.0 (since the CollectionAssert for collection of collections are enabled)

**Comment by Evangelink** [comment]
@engyebrahim please investigate and fix urgently so we can insert into 3.6.1.
