### ISSUE TITLE
Are there any unit tests for the static Assert class?

### ISSUE THREAD

**Issue by zippy1981** [Microsoft/testfx#388]
I started working on [a patch](https://github.com/zippy1981/testfx/commit/f5e7595462ca4281d5daa957d649bce25a1ace02) to implement #379. I couldn't find any tests that test Assert.AreEquals() etc. Do these not exist or am I looking in the wrong place.

If they don't exist, where should I add them?

**Comment by smadala** [comment]
Thanks for working on patch.
Looks like there is not tests for Assets.AreEquals(). You can add tests for your changes in https://github.com/Microsoft/testfx/blob/master/test/UnitTests/MSTest.Core.Unit.Tests/Assertions/AssertTests.cs
