### ISSUE TITLE
dotnet test --collect "Code Coverage;Format=cobertura doesn't seem to create a coverage file

### ISSUE THREAD

**Issue by veikkoeeva** [microsoft/testfx#3917]
The instructions
```
dotnet new mstest -o mstests
cd mstests
dotnet test --collect "Code Coverage;Format=cobertura"
```
do not seem to work. It creates a file with `<Project Sdk="MSTest.Sdk/3.5.1">` that does not work generate a coverage file on my computer. The output to console is also just 
```
dotnet test --collect "Code Coverage;Format=cobertura"
Restore complete (0,8s)
You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy
  mstests succeeded (2,0s) → bin\Debug\net9.0\mstests.dll
  mstests test succeeded (0,8s)

Test summary: total: 1; failed: 0; succeeded: 1; skipped: 0; duration: 0,3s
Build succeeded in 4,1s
```

I have a bit more elaborate GitHub setup at https://github.com/Lumoin/Verifiable/pull/377 and the issue seems to be the same that no output file is generated (at https://github.com/Lumoin/Verifiable/actions/runs/11203930073/job/31141727980#step:14:1, the command line ecludes XUnit still even if they aren't present, but it doesn't seem to get even that far due to there not being a file to read).

The `global.json` is

```
{
    "sdk": {
        "allowPrerelease": true,
        "version": "9.0.100-rc.1.24452.12"
    },
    "msbuild-sdks": {
        "MSTest.Sdk": "3.6.1"        
    }
}
```

I am not sure if this is the right place to note this, but I'm thinking at least the instructions
```
dotnet new mstest -o mstests
cd mstests
dotnet test --collect "Code Coverage;Format=cobertura"
```
should work so that a coverage file will be generated or then maybe some reason given if not. My OS is Windows 11 with the latest patches, with fi-FI settings,
```
> dotnet --version 
> 9.0.100-rc.1.24452.12
```

**Comment by jakubch1** [comment]
@Evangelink could you please help here?

**Comment by Evangelink** [comment]
Hi @veikkoeeva,

Thanks for reporting the issue. On .NET 9, we are making MSTest runner enabled by default (and we bind `dotnet test` experience to it) which means that some "extensions" are no longer working the same way they used to.

Coverlet is one of these extensions. As described here https://learn.microsoft.com/dotnet/core/testing/unit-testing-platform-extensions-code-coverage#coverlet, you will need to use coverlet global tool instead.

If you are not interested in benefiting from the new runner, you can revert to VSTest runner by adding (`<UseVSTest>true</UseVSTest>`) as documented on our SDK page (https://learn.microsoft.com/dotnet/core/testing/unit-testing-mstest-sdk#select-the-runner). Alternatively, you could keep the new runner but disconnect it from the `dotnet test` experience (so keep using VSTest when you do `dotnet test` by adding `<TestingPlatformDotnetTestSupport>false</TestingPlatformDotnetTestSupport>` to your project).

**Comment by jakubch1** [comment]
Hi @veikkoeeva,
For new MSTest runner you can use dotnet-coverage tool as you suggested. You can also run application and provide:
```
test/Project.Tests/bin/Debug/net9.0/Projects.Tests.exe --coverage --coverage-output report.cobertura.xml --coverage-output-format cobertura
```

Please check scenarios here: https://github.com/microsoft/codecoverage/tree/main/samples/Algorithms
Especially Scenario 04 and Scenario 07
