### ISSUE TITLE
Question: How to add custom attribute to specflow tests?

### ISSUE THREAD

**Issue by carlmacdiarmada** [Microsoft/testfx#392]
Hi,

I recently extended the MSTest V2 framework following the guide on how to create a custom test class, and override the test result. This works great for Unit Tests and Integ Tests but I can't seem to figure out how to implement it for specflow tests as they are written in a different way entirely. Is there any way to add this [CustomTestClass] attribute to specflows, or can I do a seperate override? 

PS. is there any way to extend the trx output file, so I can log which tests are being run through my custom attribute

Thanks
Carl

**Comment by ShreyasRmsft** [comment]
@carlmacdiarmada This extensibility is for **MsTest framework only.** 

I understand that SpecFlow (https://testingbot.com/support/getting-started/specflow.html) is a different test framework. (correct me if I am wrong).

**Comment by carlmacdiarmada** [comment]
Hi @ShreyasRmsft , thank you for the reply.

Specflow would be a different framework, but can be executed through MSTest / vstest.console so I was wondering if anyone had any experience in defining a custom test attribute for specflows that would override the execution/test result as it still spits out the same trx file that unit and integ tests do.

As far as I can tell, you can inject certain attributes into specflow, such as @ignore will set the [ignore] switch and skip the test.. but there doesnt seem to be any [TestClass] definition to put in my custom attribute and override.

Thanks
Carl

**Comment by ShreyasRmsft** [comment]
MStest.exe was a test runner and has nothing to do with the MsTest v2 Test framework.

For Extensibility support you will have to contact the owners of Specflow. 

We have nothing to do with the SpecFlow framework (MsTestv2 and SpecFlow are two completely separate entities with no correlation whatsoever). 

vstest.console.exe and mstest.exe will support running tests of different frameworks but this extensibility support you are asking for has to be provided by the framework owners it is not in our hands for frameworks other than MsTestv2.

Hope I've explained this clearly :) (I can understand getting confused between mstest.exe and the mstest framework)

Closing this issue.

**Comment by carlmacdiarmada** [comment]
Thanks @ShreyasRmsft completely understandable.

One other question I had was extending the trx file.. is this possible from the TestResult override method such as 

<testExecution>
<test-case name= "testName" classID = "123" customAttribute="true">
</testExecution>

or will I have to write my own custom logger.

thanks

**Comment by ShreyasRmsft** [comment]
@carlmacdiarmada You will have to author a custom logger.
