### ISSUE TITLE
MSTEST0036 gives warning on static AssemblyInitialize Method

### ISSUE THREAD

**Issue by SeMuell** [microsoft/testfx#3950]
## Describe the bug

When using the newest version, a static method with the same name as in the base class (AssemblyInitialize) gives the warning `warning MSTEST0036: Member 'AssemblyInitialize' already exists in the base class`.

However, since the base class is coming from another assembly, the AssemblyInitialize must be repeated (and we are forwarding the call to the base class). Renaming the method of course worked.

## Steps To Reproduce

1. Create two test projects
2. Create test class Class1 with static AssemblyInitialize and AssemblyInitialize attribute in project1.
3. Create test class inheriting Class1 with AssemblyInitialize method and attribute.

## Expected behavior

I personally would expect that the static methods with assembly initialize attribute would be ignored in the analyzer, or that the AssemblyInitialize would work when used from another project...

## Actual behavior

Warning is shown.

## Additional context

Not required, I think it's clear.

**Comment by engyebrahim** [comment]
Thanks for feedback, the shadowing happens even across different assemblies, so having the same assemblyInit function should add the warning. you can change naming

**Comment by Evangelink** [comment]
Closing as there is nothing wrong with the behavior from tests we have done.
