### ISSUE TITLE
How would I create a mock/dummy test host implementation?

### ISSUE THREAD

**Issue by thomhurst** [microsoft/testfx#3954]
I hope this makes sense.

Would I be able to create a dummy test host, basically mimicking if I was an IDE or the dotnet test host?

My thoughts are that I'd like to write some automated tests that verify that certain data is pushed to the message bus. I know it's an interface that I could mock, but I'd like to just do something like:

- Execute my dummy/example test project using my dummy host
- verify it received at least X discovered nodes
- execute the tests
- verify it received at least x passed/failed/skipped test nodes

Then if that ever drops I know I've knocked something out.

**Comment by nohwnd** [comment]
@drognanar did you have to solve something like this to test your server? If yes, could you help Thom here please?

**Comment by drognanar** [comment]
@nohwnd all of the VS/VSCode tests test against a real test host, start it in server mode and then validate the RPC being sent. @thomhurst
 would that be sufficient for the kind of tests you want to add?

the rough sketch of a client that interfaces with a protocol would look like this:

```csharp
Task RunTests()
{
  // Open a port that the test could listen on
  var listener = new TcpListener(new IPEndPoint(IPAddress.Loopback, port));
  listener.Start();

  // Start the test host and accept the connection from the test host
  var process = Process.Start($"myserver.exe --server --client-port {((IPEndPoint)listener.LocalEndpoint).Port}");
  var connection = listener.AcceptTcpClientAsync();

  // Establish the JSON-RPC communication
  var rpc = new JsonRpc(tcpClient.GetStream());
  var callback = new CallbackHandlder();
  rpc.AddLocalRpcTarget(callback);
  rpc.StartListening();

  // Send the initialize request alongside the discovery request:
  // https://github.com/microsoft/testfx/blob/main/src/Platform/Microsoft.Testing.Platform/ServerMode/JsonRpc/RpcMessages.cs
  // contains the shapes of payloads
  var discoveryId = Guid.NewGuid();
  await rpc.InvokeWithParameterObjectAsync<InitializeResponse>("initialize", initializationObject);
  await rpc.InvokeWithParameterObjectAsync("testing/discoverTests", new DiscoveryRequest(discoveryId));

  // Wait for callback handler to send back the empty message.
  // Verify the messages received.

  // Request the server to shutdown and wait for the process to exit.
  await rpc.NotifyWithParameterObjectAsync("exit", new object());
  process.WaitForExit();
}

class CallbackHandler
{
  [JsonRpcMethod("client/log", UseSingleObjectParameterDeserialization = true)]
  public Task LogAsync() {}

  // Note: if the update has an empty Changes property, treat as the end of the enumeration.
  [JsonRpcMethod("testing/testUdpates/tests", UseSingleObjectParameterDeserialization = true)]
  public Task TestsUpdateAsync(TestNodeStateChangedEventArgs) {}
}
```

**Comment by thomhurst** [comment]
That looks like it could do the trick, but what do I pass in for the process ID?

I'm getting: 

```
Unhandled exception. System.Collections.Generic.KeyNotFoundException: Key 'processId' was not found in the dictionary.
 ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Text.Json.JsonElement.GetProperty(String propertyName)
   at Microsoft.Testing.Platform.ServerMode.Json.Json.Bind[T](JsonElement element, String property) in /_/src/Platform/Microsoft.Testing.Platform/ServerMode/JsonRpc/Json/Json.cs:line 634
```

I'm sending:

`await rpc.InvokeWithParameterObjectAsync<InitializeResponseArgs>("initialize", new InitializeRequestArgs(Environment.ProcessId, new ClientInfo("RpcTests", "1.0.0"), new ClientCapabilities(true)));`

**Comment by drognanar** [comment]
I think it's that the Json deserializer has an implicit "testing" subcategory https://github.com/microsoft/testfx/blob/main/src/Platform/Microsoft.Testing.Platform/ServerMode/JsonRpc/Json/Json.cs#L470 that's not explicitly shown in the rpc object shape.

Here's how the JSON should look like expressed in typescript https://github.com/microsoft/testfx/blob/main/docs/mstest-runner-protocol/001-protocol-intro.md#determine-capabilities-during-test-runner-initialization.

It might be enough to change capabilities to match the following definition:

```csharp
class ClientCapabilities
{
  [JsonProperty("testing")]
  internal ClientTestingCapabilities Testing { get; set; }

  class ClientTestingCapabilities
  {
    [JsonProperty("debuggerProvider")]
    public bool DebuggerProvider { get; set; }

    [JsonProperty("attachmentsProvider")]
    public bool AttachmnetsProvider { get; set; }
  }
}
```

I can make the change to make the "testing" subcategory explicit in the object shape.

**Comment by thomhurst** [comment]
That fixed that! I'm most of the way there but having trouble deserializing, due to names not matching up, and because I don't own the models, I can't just use the simple `[JsonPropertyName]`.

So TestNode is coming through as null: ![Image](https://github.com/user-attachments/assets/5e900f0e-0ffa-46e8-86bf-a4fe1359584f)

The model's don't seem all that simple to try and recreate manually either.

So `TestNodeUpdateMessage` has a property `TestNode`, but in your spec, the JSON RPC serializer uses `JsonRpcStrings.Node`. Similar thing for parent too:

```
_serializers[typeof(TestNodeUpdateMessage)] = new JsonObjectSerializer<TestNodeUpdateMessage>(message =>
            new (string, object?)[]
            {
                (JsonRpcStrings.Node, message.TestNode),
                (JsonRpcStrings.Parent, message.ParentTestNodeUid?.Value),
            });
```

**Comment by thomhurst** [comment]
Also if my code is useful, it's here: https://github.com/thomhurst/TUnit/blob/06e6b9d02cd7d571f9d95886a8403126e2a46ac9/TUnit.RpcTests/Tests.cs

**Comment by drognanar** [comment]
I created the following message type to deserialize the update changes:

```
public record TestNodeStateChangedEventArgs(Guid RunId, TestUpdates[]? Changes);

public record TestUpdates(string? ParentId, Node Node);

public record Node
{
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionProperties { get; set; }

    [JsonPropertyName("uid")]
    public string? Uid { get; set; }

    [JsonPropertyName("display-name")]
    public string? DisplayName { get; set; }

    [JsonPropertyName("node-type")]
    public string? NodeType { get; set; }

    [JsonPropertyName("execution-state")]
    public string? ExecutionState { get; set; }
}
```

It's a good point that the RpcMessages.cs is coupled to the custom serializer/deserializer (so we can be NativeAOT friendly), but as a result it's not easy to move to another library.

I found the integration test code instead https://github.com/microsoft/testfx/tree/main/test/IntegrationTests/MSTest.Acceptance.IntegrationTests/ServerMode/v1.0.0 which has the System.Text.Json based definitions. It should be much easier to create the messages/client from these types instead.

**Comment by thomhurst** [comment]
Nice thanks @drognanar that worked! The only thing I'm confused about is my numbers aren't matching the standard CLI execution output 🤔 

In my RPC tests: 

```csharp
        var finished = executionResults.Where(x => x.Node.ExecutionState != "in-progress").ToList(); // Count: 2381
        var passed = finished.Where(x => x.Node.ExecutionState == "passed").ToList(); // Count: 2129
        var failed = finished.Where(x => x.Node.ExecutionState == "failed").ToList(); // Count: 236
        var skipped = finished.Where(x => x.Node.ExecutionState == "skipped").ToList(); // Count: 8
```

dotnet run CLI output:
```
  total: 2411
  failed: 245
  succeeded: 2159
  skipped: 7
  duration: 20s 055ms
```

dotnet test CLI output:
`Test summary: total: 2411, failed: 245, succeeded: 2159, skipped: 7, duration: 25.9s`

**Comment by drognanar** [comment]
It looks like TUnit is not able to serve multiple requests within one process lifetime, i.e. a new process must be created to serve the run requests.

Otherwise, it seems that some of the class/assembly hooks are not re-executed.
