### ISSUE TITLE
Hangdump fails when path to dump has spaces in it.

### ISSUE THREAD

**Issue by nohwnd** [microsoft/testfx#3961]
Hangdump fails when path to dump has spaces in it. This is caused by https://github.com/dotnet/diagnostics/issues/5020 but can be worked around by wrapping the path to dump in quotes. 

This only applies to .NET.

**Comment by nohwnd** [comment]
It is not recommended to apply the fix, it will be fixed in the netcore client package we consume, so it is fixed across runtimes.

**Comment by nohwnd** [comment]
Okay I might have just misunderstood about the workaround because the issue now says that we have a workaround and so it is not high prio. Applying the workaround

**Comment by Evangelink** [comment]
Closing as fixed (worked around) in [#3994](https://github.com/microsoft/testfx/pull/3994)
