### ISSUE TITLE
MSTEST0030 only warns when first method in class is marked with [TestMethod]

### ISSUE THREAD

**Issue by Malachi-Datacom** [microsoft/testfx#3968]
## Describe the bug

The warning [MSTEST0030](https://learn.microsoft.com/en-us/dotnet/core/testing/mstest-analyzers/mstest0030) only warns when the first method in the class is marked with `[TestMethod]`. It does not warn if for example there is a `[TestInitailize]` marked method that comes before a `[TestMethod]` marked method

## Steps To Reproduce

1. Create solution
2. Add MsTest unit test project
3. Add a method **Before** the default `TestMethod1` method as follows
```cs
public class DoesNotWarnMsTest0030
{
    [TestInitialize]
    public void Initialize()
    {

    }

    [TestMethod]
    public void TestMethod1()
    {

    }
}
```

Reproduction here: [Malachi-Datacom/MSTEST0030-Bug-Repro](https://github.com/Malachi-Datacom/MSTEST0030-Bug-Repro)

## Expected behavior
An info (or modified level) diagnostic should appear on the class for `MSTEST0030`

## Actual behavior
No diagnostic is produced for `MSTEST0030`

## Additional context
It does not seem to matter whether the first method is marked with any attribute (as long as it's not marked with `[TestMethod]`), it just needs to appear before the first `[TestMethod]` attribute

**Comment by Evangelink** [comment]
Hi @Malachi-Datacom,

Thank you for raising this issue, I confirm there is a bug in our analyzer. We will ship a fix on the next bug fix version (most likely next week).
