### ISSUE TITLE
Add traits to a TestNode properties

### ISSUE THREAD

**Issue by thomhurst** [microsoft/testfx#4007]
Based on this discussion: https://github.com/microsoft/testfx/discussions/3991

A few things:
- Currently a framework author would have to know about a specific `traits` key that needs adding to the `PropertyBag` - Leaking internal testing platform implementation details and could be easily missed or unknown. This could be abstracted away behind a custom property object.
- Authors would also need to know how Categories are defined vs Traits. (Seems to be the category is a key with no value, and a trait is a key value pair)
- `SerializableNamedKeyValuePairsStringProperty` which the VSTest bridge uses is internal, so framework authors don't have the option of using that.

Suggestion:

```csharp
public sealed record TestTraitsProperty(
        IEnumerable<string> Categories,
        IEnumerable<KeyValuePair<string, string>> Traits) : SerializableNamedKeyValuePairsStringProperty("traits",
    [
        ..Categories.Select(category => new KeyValuePair<string, string>(category, string.Empty)),
        ..Traits
    ]);
```

**Comment by thomhurst** [comment]
Even without this, there is still the issue they the underlying property type is internal. I think this is blocking framework authors from setting traits/categories unless there's a workaround?

**Comment by Evangelink** [comment]
Marking as bug although I don't have time to test/investigate right now. We **should** have supprot for traits/properties/metadata as it's a heavily used feature in VS.

**Comment by Evangelink** [comment]
It's probably a better idea that exposing this technical type, let me discuss with the team and get back to you.

**Comment by Evangelink** [comment]
Hey @thomhurst,

Good news, I was doing some checks and tests about this and found out we already implemented [TestMetadataProperty](https://github.com/microsoft/testfx/blob/9d65550bdbc1c39f564c201792e5af0a88582cc2/src/Platform/Microsoft.Testing.Platform/Messages/TestNodeProperties.cs#L313), it's public and it's already plugged into the communication protocol for Test Explorer.

I'll close as done but please if there are any bug please reopen/comment.

**Comment by thomhurst** [comment]
So for a category do I just add a metadata property with an empty key?

**Comment by Evangelink** [comment]
Null or empty string **value**, the category is the key. I guess we could provide a different ctor for that!

**Comment by thomhurst** [comment]
Thanks seems to be working great. Up to you if you want to leave this open to create a simpler constructor 😄
