### ISSUE TITLE
method marked with “DataTestMethod” fails CA1822.

### ISSUE THREAD

**Issue by Teddy1313** [Microsoft/testfx#406]
Using Visual Studio  2017 with MSTest V2  framework with Code Analysis 

A method marked with “TestMethod” is apparently exempt from CA1822
However, a method marked with “DataTestMethod” fails CA1822.

**Comment by jayaranigarg** [comment]
Workaround - 
Change the [DataTestMethod] attribute to [TestMethod] and take a dependency on "Microsoft.CodeAnalysis.FxCopAnalyzers" nuget package verson 2.6.0 and then do a rebuild. It should resolve the issue.

**Comment by jayaranigarg** [comment]
Issue fixed on rosyln side https://github.com/dotnet/roslyn-analyzers/issues/1678
