### ISSUE TITLE
User should be able to execute a specific data row in case of inline data driven test 

### ISSUE THREAD

**Issue by cltshivash** [Microsoft/testfx#409]
## Description
With data rows supported inline, the user should have a flexibility to run a specific data row and not all of them.

## Steps to reproduce
Create a testproject with inline data rows and try to execute the test.

## Expected behavior
Should be able to choose a particular data row for execution

## Actual behavior
All the data rows are executed

**Comment by jayaranigarg** [comment]
Closing as duplicate of https://github.com/Microsoft/testfx/issues/464
