### ISSUE TITLE
Missing localization for --minimum-expected-tests

### ISSUE THREAD

**Issue by Youssef1313** [microsoft/testfx#4123]
https://github.com/microsoft/testfx/blob/5c829c1633fdca211c4a96a52a200f61ec85bd5c/src/Platform/Microsoft.Testing.Platform/CommandLine/PlatformCommandLineProvider.cs#L44

**Comment by Evangelink** [comment]
@Youssef1313 thanks for noticing! Could you please move that to a resx?
