### ISSUE TITLE
Logging messages to be localized

### ISSUE THREAD

**Issue by Youssef1313** [microsoft/testfx#4133]
### Hang dump (#4145)

https://github.com/microsoft/testfx/blob/e4c08367b3203ef678645d9ce54816c838709cd7/src/Platform/Microsoft.Testing.Extensions.HangDump/HangDumpProcessLifetimeHandler.cs#L126

https://github.com/microsoft/testfx/blob/e4c08367b3203ef678645d9ce54816c838709cd7/src/Platform/Microsoft.Testing.Extensions.HangDump/HangDumpProcessLifetimeHandler.cs#L327

https://github.com/microsoft/testfx/blob/e4c08367b3203ef678645d9ce54816c838709cd7/src/Platform/Microsoft.Testing.Extensions.HangDump/HangDumpProcessLifetimeHandler.cs#L353

### MTP configurations

https://github.com/microsoft/testfx/blob/e4c08367b3203ef678645d9ce54816c838709cd7/src/Platform/Microsoft.Testing.Platform/Configurations/JsonConfigurationProvider.cs#L37

https://github.com/microsoft/testfx/blob/e4c08367b3203ef678645d9ce54816c838709cd7/src/Platform/Microsoft.Testing.Platform/Configurations/JsonConfigurationProvider.cs#L41

### MTP hosts

https://github.com/microsoft/testfx/blob/e4c08367b3203ef678645d9ce54816c838709cd7/src/Platform/Microsoft.Testing.Platform/Hosts/ConsoleTestHost.cs#L76

https://github.com/microsoft/testfx/blob/e4c08367b3203ef678645d9ce54816c838709cd7/src/Platform/Microsoft.Testing.Platform/Hosts/ConsoleTestHost.cs#L99

https://github.com/microsoft/testfx/blob/e4c08367b3203ef678645d9ce54816c838709cd7/src/Platform/Microsoft.Testing.Platform/Hosts/ConsoleTestHost.cs#L112

https://github.com/microsoft/testfx/blob/e4c08367b3203ef678645d9ce54816c838709cd7/src/Platform/Microsoft.Testing.Platform/Hosts/TestHostControllersTestHost.cs#L328

### MTP requests

https://github.com/microsoft/testfx/blob/e4c08367b3203ef678645d9ce54816c838709cd7/src/Platform/Microsoft.Testing.Platform/Requests/TestHostTestFrameworkInvoker.cs#L41 (Related to AB#2275339)

**Comment by Evangelink** [comment]
@Youssef1313 The logs should remain unlocalized as they are technical diagnostic info. If we start to localize them, we will have hard time diagnostising user issues.

**Comment by Evangelink** [comment]
I will move forward by closing this one as won't fix and will create another feature request/bug.
