### ISSUE TITLE
Build Testing Platform for .NET 9

### ISSUE THREAD

**Issue by thomhurst** [microsoft/testfx#4148]
Creating a specific target for .NET 9 means the compiler can make optimizations and use newer overloads of methods, meaning free performance boosts with 0 code changes.

**Comment by Youssef1313** [comment]
@thomhurst I'm wondering what optimizations you have in mind for .NET 9?

**Comment by Evangelink** [comment]
The lock is one example @Youssef1313 but globally I have seen many graphs with big perf improvement changing no API but just targeting net9.0 (under the hood improvements).
