### ISSUE TITLE
Remove .NET 7 Target for Testing Platform

### ISSUE THREAD

**Issue by thomhurst** [microsoft/testfx#4149]
.NET 7 has been end of life for over half a year now, so it probably makes sense to remove the build here too.

.NET 7 can still work via the .NET 6 build if users still haven't upgraded for some reason.

**Comment by Evangelink** [comment]
Sadly for us the life is harder :) Because VS allows creating projects with these TFMs we need to ensure they run. This is also considered as breaking change so we need to wait and group these changes in a v2.
