### ISSUE TITLE
Coded UI Test need to support MSTest V2

### ISSUE THREAD

**Issue by SoniaKaudjhis** [Microsoft/testfx#415]
## Description
I tried to to use MSTest V2 in my test Project. But I noticed there are a conflict with Dll  and  [CodedUITest] is not supported by MSTest V2
## Steps to reproduce
My OS is Windows 7 entreprise ( 6.1.7601)
I am using VS 2017 Version 15.6.6
irst all, I add nuget reference (MS.TestFramework) in my coded ui project 
See Pictures 
![image](https://user-images.githubusercontent.com/1808514/39724914-1e69d3be-5218-11e8-95ce-8098fc408676.png)
The following assembly dll is added : Microsoft.VisualStudio.TestPlatform.TestFramework and Microsoft.VisualStudio.TestPlatform.TestFramework.Extension
In my test Class : I have error of conflict  beetwen Microsoft.VisualStudio.QualityUnitTestFramework and Microsoft.VisualStudio.TestPlatform.TestFramework because they have the same test attributes as ClassInitialize and ClassCleanup, TestInitialize, TestCleanup, TestContext. 
I decided to remove Microsoft.VisualStudio.QualityUnitTestFramework to fix the conflict issue but I noticed that CodedUITest attribute is not included in Microsoft.VisualStudio.TestPlatform.TestFramework  and Microsoft.VisualStudio.TestPlatform.TestFramework.Extension
I would like to know the correct steps to be able to used MSTestV2 for Automation UI ? or If it is possible to add CodedUiTest attribute in Microsoft.VisualStudio.TestPlatform.TestFramework.Extension or Microsoft.VisualStudio.TestPlatform.TestFramework 

## Expected behavior
MS Test V2 should support CodedUiTest Attribute

## Actual behavior
MS Test V2   doesn't support CodedUiTest Attribute

## Environment
MS Test 1.2.1

**Comment by cltshivash** [comment]
@SoniaKaudjhis Currently there's no plan to support CodedUITest with MSTest V2.
