### ISSUE TITLE
Run Builds on MacOS

### ISSUE THREAD

**Issue by thomhurst** [microsoft/testfx#4150]
I see your builds run on Windows and Linux

![Image](https://github.com/user-attachments/assets/5abb2bc9-0c64-40f9-9cba-3ad0598ea2af)

I'd recommend adding MacOS too.

For example, the recent bug around the Console I added (#4146) seems to only be affecting my Mac builds: https://github.com/thomhurst/TUnit/actions/runs/12010805842/job/33478446031

**Comment by Evangelink** [comment]
There were some constraints with adding mac in the past but I see many projects using it so I'm going to mark it as approved and see if we get some issue with setting it up.
