### ISSUE TITLE
Nuget Package Updates Not Working

### ISSUE THREAD

**Issue by chocvanstraw** [microsoft/testfx#4188]
I just created an MSTest project targeting .net 9.  When I go to the Nuget package manager it says I have 4 updates for the following packages:

Microsoft.NET.Test.Sdk 17.11.1 -> 17.12.0
MSTest.Analyzers 3.6.1 -> 3.6.3
MSTest.TestAdapter 3.6.1 -> 3.6.3
MSTest.TestFramework 3.6.1 -> 3.6.3

If I update all of the packages they seem to update fine (the versions change in the project that was updated).  However, if I rebuild the solution, the 4 packages listed above all revert back to the previous version.  If I go to the nuget package manager, it shows 4 updates again. 

Before update:

![Image](https://github.com/user-attachments/assets/c55436c1-5911-4a3a-abea-905ac6cf052d)

After update:

![Image](https://github.com/user-attachments/assets/fc5b7608-e8af-47c4-ab0f-d13c43c59b37)

After building the solution:

![Image](https://github.com/user-attachments/assets/27cebe17-f779-4368-b196-abb7c8bf1124)

**Comment by Youssef1313** [comment]
@chocvanstraw Thanks for reporting this. Are you using MSTest.Sdk?

If you're using MSTest.Sdk, please have a look at the limitations documented in https://github.com/dotnet/docs/pull/43717 (this PR will hopefully get merged soon and the updates will be published to https://learn.microsoft.com/dotnet/core/testing/unit-testing-mstest-sdk)

**Comment by chocvanstraw** [comment]
Sorry for the delayed response.  The Packages I am referencing in the test project are as follows:

Microsoft.NET.Test.SDK
MSTest.Analyzers
MSTest.TestAdapter
MSTest.TestFramework

I also noticed that after updating the nugets to the latest version and building the solution the versions in the IDE solution explorer show the old version (as mentioned in my original post).  However, if I look at the csproj file for the test project they show the new versions:

![Image](https://github.com/user-attachments/assets/6022193f-93b7-40a4-aeb5-3f534bb144fa)


I also noticed that when creating a new test project there are several options that now have to be selected, which is a new experience for these types of projects.  It isn't really clear what the implication of selecting each option is.  Here is an example:

![Image](https://github.com/user-attachments/assets/56a55027-d151-4f18-b15e-f83a1e47f569)

Is the Use MSTest.Sdk checkbox causing the problem?

**Comment by chocvanstraw** [comment]
I created a new project with the following settings:

![Image](https://github.com/user-attachments/assets/6388be9d-da5c-4fa9-83d9-3c3a75930afd)

This included different nuget packages in the project:

![Image](https://github.com/user-attachments/assets/f4f8226b-c78b-47c2-bd53-96a2460f4e74)

These seem to play nicely with the nuget package manager.  When I manage nugets, I was able to update the listed packages to the latest version and they didn't change after re-building the solution and the versioning is consistent in solution explorer and the csproj file.  It might be worthwhile to have some explanation of what all these various settings accomplish.

**Comment by chocvanstraw** [comment]
In the original project I see the following: <Project Sdk="MSTest.Sdk/3.6.1">

In the new project, where I unchecked Use MSTest.SDK I see the following: <Project Sdk="Microsoft.NET.Sdk">

**Comment by Youssef1313** [comment]
@chocvanstraw So, the update functionality works correctly with `Microsoft.NET.Sdk` but not for `MSTest.Sdk` right? In that case, that's unfortunately the known limitation I referred to :(

**Comment by Evangelink** [comment]
> So, which is the preferred library? Microsoft.NET.Sdk or MSTest.Sdk?

It depends mainly on your feeling. We tend to recommend MSTest.Sdk as it reduces a lot of boilerplate in project configurations but we are aware that the limited integration for updates can be considered as blocker.

> It seems that Microsoft.NET.Sdk is installed regardless.

If the `Use MSTest Sdk` checkbox is used, your project will use this SDK otherwise (when unchecked) it uses the regular .NET SDK (Microsoft.NET.Sdk).

> what is the guidance for new projects when it comes to selecting the Use MSTest.SDK checkbox?

Cf question 1. We do think that provides a better experience but that's up-to-you. 

In case you have missed them, here is our blog post announcing the SDK feature https://devblogs.microsoft.com/dotnet/introducing-mstest-sdk/ and here is the official doc that explains the custom Sdk and its features https://learn.microsoft.com/dotnet/core/testing/unit-testing-mstest-sdk.
