### ISSUE TITLE
All analyzers are implemented for C#/VB but will only work for C# due to the way they are packaged

### ISSUE THREAD

**Issue by Youssef1313** [microsoft/testfx#4209]
https://github.com/microsoft/testfx/blob/3e7ac66744ee70c7e7f38ba47f9693bea566db15/src/Analyzers/MSTest.Analyzers.Package/MSTest.Analyzers.Package.csproj#L37-L38

We are packaging the dlls in C#-specific directory.

This issue is very separate and different from https://github.com/microsoft/testfx/issues/4031

@Evangelink I'm not sure how important this one is.

**Comment by Evangelink** [comment]
Oh well, I haven't tested that case so yup my bad!

**Comment by nohwnd** [comment]
is there a typo in the header? will only work for C# rather?

**Comment by Youssef1313** [comment]
Yup 😄 

Fixed.
