### ISSUE TITLE
Missing Microsoft.Testing.Extensions.CodeCoverage 17.13.1

### ISSUE THREAD

**Issue by sehra** [microsoft/testfx#4225]
## Describe the bug

MSTest.Sdk/3.6.4 references Microsoft.Testing.Extensions.CodeCoverage 17.13.1 which is not on NuGet

## Steps To Reproduce

1. Create a new project with Project Sdk=MSTest.Sdk/3.6.4
3. Build

## Expected behavior
Builds

## Actual behavior
error NU1102:
      Unable to find package Microsoft.Testing.Extensions.CodeCoverage with version (>= 17.13.1)
        - Found 12 version(s) in nuget.org [ Nearest version: 17.13.0 ]
        - Found 0 version(s) in Microsoft Visual Studio Offline Packages

**Comment by Evangelink** [comment]
Hi @sehra,

Thanks for raising this issue. It's my bad, I didn't pay attention the Code Coverage extension wasn't published to NuGet, we will fix that right now.

**Comment by Evangelink** [comment]
Fixed.

**Comment by martincostello** [comment]
Microsoft.CodeCoverage.MSBuild is also still missing.

**Comment by Evangelink** [comment]
@martincostello it's good now https://www.nuget.org/packages/Microsoft.CodeCoverage.MSBuild/17.13.1
