### ISSUE TITLE
Allow `[TestProperty]` to be set on a class

### ISSUE THREAD

**Issue by Evangelink** [microsoft/testfx#4248]
## Summary

Update `[TestProperty]` to allow usage on test classes.

## Background and Motivation

In xUnit, the `[Trait]` can be set on classes and with NUnit `[Property]` can also be set on classes. By doing this change, we would make it easier for people converting from NUnit and xUnit while allowing grouping of traits.

## Proposed Feature

1. Update the attribute to allow usage on classes.
2. Update related code analyzer to allow usage.

**Comment by nohwnd** [comment]
What would be the inheritance story here?

Should the property be inherited to all tests, should it be inherited to all inherited classes? 

Should custom attributes be respected? (we don't respect them for all other annontations, like owner of ignore).

**Comment by Evangelink** [comment]
> What would be the inheritance story here?
> 
> Should the property be inherited to all tests, should it be inherited to all inherited classes?

I would do like `TestCategory` which seems to respect inheritance (i.e. setting `[TestCategory("A")]` on base class applies it to all test methods of subclass).

> Should custom attributes be respected? (we don't respect them for all other annontations, like owner of ignore).

Sadly `TestProperty` isn't sealed so I think we should respect sub-types.
