### ISSUE TITLE
Parameterized test with null value not showing up as a test

### ISSUE THREAD

**Issue by Sean-Brown** [Microsoft/testfx#426]
I created a parameterized test method whose first parameter is a string. I want to test the behavior if the string is null, however the test runner excludes this test:
![image](https://user-images.githubusercontent.com/1503131/40434809-2b94f746-5e7d-11e8-8c93-b4f1edf177d1.png)

![image](https://user-images.githubusercontent.com/1503131/40434832-3a888a4c-5e7d-11e8-8c59-c39a5a4447ab.png)

**Comment by jayaranigarg** [comment]
@Sean-Brown: This issue looks similar to https://github.com/Microsoft/testfx/issues/284. 
Which version of MSTest.TestAdapter and MSTest.Testframework are you using? Can you move to latest version and try if that resolves the issue for you?
I am unable to repro this with version 1.3.0

**Comment by Sean-Brown** [comment]
I'm using MSTest.TestFramework version 1.3.1 and MSTest.TestAdapter version 1.3.1. This time I observed that it does initially see 5 tests (however the null test shows as `TestDeviceIdValidity(,True)`, but when I went to run the test that test got removed, so there definitely does seem to be something strange going on.

**Comment by Sean-Brown** [comment]
Sorry I believe this is a Resharper bug. If I run the tests through the "Test Explorer" window then it sees all the tests:
![image](https://user-images.githubusercontent.com/1503131/40557974-e644a598-601f-11e8-87a8-4b4934d0343e.png)
