### ISSUE TITLE
TestClassAttribute inheritance is inconsistent

### ISSUE THREAD

**Issue by Youssef1313** [microsoft/testfx#4278]
```csharp
namespace TestProject9;

[TestClass]
public class Test1
{
    [TestMethod]
    public void TestMethod1()
    {
        // Called. Correct behavior.
    }
}

public class Test2 : Test1
{
    [AssemblyInitialize]
    public static void AsmInit2(TestContext _)
    {
        // Called. Unexpected behavior.
    }

    [ClassInitialize]
    public static void ClassInit2(TestContext testContext)
    {
        // Not Called. Correct behavior.
    }

    [TestMethod]
    public void TestMethod2()
    {
        // Not called. Correct behavior
    }
}

```

Root cause seems to be:

https://github.com/microsoft/testfx/blob/97cb7b4cc9be8942ee3ce06fc113d0543a12a60a/src/Adapter/MSTest.TestAdapter/Execution/TypeCache.cs#L414

**Comment by Evangelink** [comment]
These bugs of derived vs non derived are endless..

**Comment by Youssef1313** [comment]
@Evangelink Willing to take a break here to fix this in minor version or should it be v4?

**Comment by Evangelink** [comment]
Sounds like a bug in the wanted/documented/expected behavior so I am fine to fix it.

PS: I think the ticket title should be "inconsistent".

**Comment by Youssef1313** [comment]
> PS: I think the ticket title should be "inconsistent".

Yup! Fixed the title.

**Comment by Youssef1313** [comment]
@Evangelink I added to 3.8 milestone. Feel free to move/remove accordingly.
