### ISSUE TITLE
Test Data defined in a parent class is not visible in child classes when using DynamicData

### ISSUE THREAD

**Issue by pingzing** [Microsoft/testfx#428]
## Description
When attempting to use the `[DynamicData]` attribute, in a derived class, properties and methods in the parent class are not visible to tests. They are reported as `null` at test run time.

## Steps to reproduce
Create a test class that inherits from any parent class. In the parent class, include some test data. In the child class, attempt to use that test data in a `[DynamicData]` attribute. The test will fail, as the test data will be null. I've [attached a test project](https://github.com/Microsoft/testfx/files/2053285/ExampleDynamicDataTest.zip) that demonstrates this behavior.

## Expected behavior
Test data defined in a parent class can be used in child classes.

## Actual behavior
Tests fail, and the test data appears as null at test run time.

## Environment
Windows 10, April 2018 update, using Visual Studio 2017 15.7.2, and MSTest TestAdapter 1.2.1, and MSTest TestFramework 1.2.1.

Sample project that demonstrates this: https://github.com/Microsoft/testfx/files/2053285/ExampleDynamicDataTest.zip

**Comment by jayaranigarg** [comment]
@pingzing : In case, the property or method exists in a class other than the test class, an additional Type argument should be passed to DynamicData constructor. Refer this RFC : https://github.com/Microsoft/testfx-docs/blob/master/RFCs/006-DynamicData-Attribute.md

So, if you modify your DynamicDataAttribute like below, things should just work fine for you :
>      [DataTestMethod]
>      [DynamicData(nameof(ParentTestData), typeof(ParentClass))]
>      public void TestParentTestData(int first, int second, int third)
>      {
>           Assert.AreEqual(third, first + second);
>      }

**Comment by pingzing** [comment]
A-ha! Didn't spot that in the intellisense, and various bits of Googling didn't bring it up. Thanks!

**Comment by jayaranigarg** [comment]
@pingzing : Glad to hear this helped. 
Closing the issue on our end. Please feel free to re-open if you hit any more blockers.
