### ISSUE TITLE
Latest packages won't compile with .Net core 2.1 release version.

### ISSUE THREAD

**Issue by hamidshahid** [Microsoft/testfx#432]
## Description
Unable to compile using latest version of MSTest v2 and .net core 2.1. 

I am looking to upgrade some of our test projects to MSBuild SDK format. Added reference to Nuget packages MSTest.TestAdapter and MSTest.TestFramework. when I try to compile, I get the following error

C:\Program Files\dotnet\sdk\2.1.300\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(198,5): error NU5100: The assembly 'content\Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.dll' is not inside the 'lib' folder and hence it won't be added as a reference when the package is installed into a project. Move it into the 'lib' folder if it needs to be referenced.

Started getting it when I upgraded to .Net core 2.1

## Steps to reproduce
Using Visual Studio 2017, create a .Net framework Unit test project.
Edit the project file to convert it into an SDK format
Add Nuget reference to MSTest.TestAdapter and MSTest.TestFramework.
compile the project

## Expected behavior
Should be compiled fine.

## Actual behavior
Getting error

> C:\Program Files\dotnet\sdk\2.1.300\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(198,5): error NU5100: The assembly 'content\Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.dll' is not inside the 'lib' folder and hence it won't be added as a reference when the package is installed into a project. Move it into the 'lib' folder if it needs to be referenced.

it worked with an earlier version of .net core SDK. It used to be a warning with version 2.1.104

> C:\Program Files\dotnet\sdk\2.1.104\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(194,5): warning : Description: The assembly 'contentFiles\any\net45\Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.dll' is not inside the 'lib' folder and hence it won't be added as reference when the package is installed into a project.

## Environment
Windows 10
.Net Core 2.1
Visual Studio 2017

**Comment by jayaranigarg** [comment]
@hamidshahid : Can you please share a repro project with us for investigation?

**Comment by jayaranigarg** [comment]
@hamidshahid : Any updates on this?

**Comment by jayaranigarg** [comment]
Without the asked information, we are unable to investigate this on our end. Please feel free to re-open it if you hit this again and kindly provide the repo project for the same.

**Comment by hamidshahid** [comment]
down vote
accepted
I was able to resolve the issue by setting the ExcludeAssets property for MSTest.TestAdapter to true. This is how my project file looked like in the end

<PackageReference Include="MSTest.TestAdapter" Version="1.2.1">
  <ExcludeAssets>all</ExcludeAssets>
</PackageReference>

**Comment by AmadeusW** [comment]
We're running into the same issue in the Visual Studio editor team when referencing MSTest.TestFramework v2.1.400. There is no issue when we reference v1.2.0-beta3. I have not binary-searched to a version which works.
I've emailed you @jayaranigarg regarding repro

**Comment by jayaranigarg** [comment]
Taking this offline. Closing the thread.

**Comment by pedramrezaei** [comment]
I am having the same issue. Can we reopen the thread?
