### ISSUE TITLE
build.cmd using VS Preview

### ISSUE THREAD

**Issue by spottedmahn** [Microsoft/testfx#436]
## Description
I'm trying to build via `build.cmd` and it failing:

>C:\Users\mdepouw\source\repos\GitHub\spottedmahn\testfx\scripts\build\TestFx.targets(4,11): error MSB4226: The imported
 project "C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\Microsoft\WindowsXaml\v15.0\Microso
ft.Windows.UI.Xaml.CSharp.targets" was not found. Also, tried to find "Microsoft\WindowsXaml\v15.0\Microsoft.Windows.UI
.Xaml.CSharp.targets" in the fallback search path(s) for $(MSBuildExtensionsPath) - "C:\Program Files (x86)\MSBuild" .
These search paths are defined in "C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\15.0\Bin\m
sbuild.exe.Config". Confirm that the path in the <Import> declaration is correct, and that the file exists on disk in o
ne of the search paths. [C:\Users\mdepouw\source\repos\GitHub\spottedmahn\testfx\src\Adapter\PlatformServices.Universal
\PlatformServices.Universal.csproj]

---

I found [this issue](https://github.com/Microsoft/testfx/issues/314#issuecomment-394100174) and I installed "Windows 10 SDK (10.0.14393.0)" but didn't fix it.

---

So I started looking more closely and I see it's trying to build w/ the preview version of VS:

![image](https://user-images.githubusercontent.com/14079228/40878880-916e31d2-6665-11e8-97d1-402b159e0ad7.png)

## Steps to reproduce
- install VS 2017
- install VS 2017 preview
- run `build.cmd`

## Expected behavior
- `build.cmd` should use VS 2017 not VS 2017 preview

## Actual behavior
- it is using VS 2017 Preview

## Environment
- Win 10, latest version of VS 2017 (15.7.3) and Preview (15.8.0 Preview 2.0)

**Comment by jayaranigarg** [comment]
@spottedmahn : This is by design that the latest version of VS which fulfills all the requirements (workloads/components) for building the repo is used. In case you have both VS 2017 and VS 2017 Preview installed on your box, probably both meets the requirements and hence preview build is getting used.

**Comment by spottedmahn** [comment]
>This is by design

Ok.

>Did you install Windows 10 SDK (10.0.14393.0) for VS Preview as well?

Yep, that fixed it.  Thanks 🙏!
