### ISSUE TITLE
Ensure MSTest.SourceGeneration is updated for DynamicData Autodetect mode

### ISSUE THREAD

**Issue by Youssef1313** [microsoft/testfx#4369]
`NativeAotTests_WillRunWithExitCodeZero` will be skipped temporarily in https://github.com/microsoft/testfx/pull/4340

**Comment by Youssef1313** [comment]
Re-opening. This if fixed in https://github.com/microsoft/testanywhere/pull/2492, but we need an updated version of MSTest.SourceGeneration to unskip the test.

**Comment by Youssef1313** [comment]
The test is now unskipped, but we still need to publish updated package to NuGet.org.

**Comment by Evangelink** [comment]
Do we? We are using packages from the `test-tools` feed.

**Comment by Youssef1313** [comment]
@Evangelink But we need something for end users to be able to use?

**Comment by Evangelink** [comment]
Yes when we will push publicly 3.8 preview or release stable 3.8. Or am I missing something you are thinking about?

**Comment by Youssef1313** [comment]
Yup. The milestone is set to 3.8. This is probably going to just be fixed on its own by the normal release procedure anyways. Fine for me if you want to close.

There is https://github.com/microsoft/testfx/issues/4443 for 3.7 though but that's irrelevant to the DynamicData support we did on the source gen.
