### ISSUE TITLE
Discover tests warnings

### ISSUE THREAD

**Issue by spottedmahn** [Microsoft/testfx#437]
## Description
Discover tests warnings:

>[6/2/2018 1:15:22 PM Informational] ------ Discover test started ------
>[6/2/2018 1:15:49 PM Warning] UTA001: TestClass attribute defined on non-public class Microsoft.VisualStudio.TestPlatform.MSTestAdapter.UnitTests.Execution.TestExecutionManagerTests+DummyTestClass
>[6/2/2018 1:15:49 PM Warning] UTA001: TestClass attribute defined on non-public class Microsoft.VisualStudio.TestPlatform.MSTestAdapter.UnitTests.Execution.TestExecutionManagerTests+DummyTestClassWithCleanupMethods
>[6/2/2018 1:15:49 PM Warning] UTA001: TestClass attribute defined on non-public class Microsoft.VisualStudio.TestPlatform.MSTestAdapter.UnitTests.Execution.TestExecutionManagerTests+DummyTestClassForParallelize
>[6/2/2018 1:15:49 PM Warning] UTA001: TestClass attribute defined on non-public class Microsoft.VisualStudio.TestPlatform.MSTestAdapter.UnitTests.Execution.TestExecutionManagerTests+DummyTestClassForParallelize2
>[6/2/2018 1:15:49 PM Warning] UTA001: TestClass attribute defined on non-public class Microsoft.VisualStudio.TestPlatform.MSTestAdapter.UnitTests.Execution.TestExecutionManagerTests+DummyTestClassForParallelize3
>[6/2/2018 1:15:49 PM Warning] UTA001: TestClass attribute defined on non-public class Microsoft.VisualStudio.TestPlatform.MSTestAdapter.UnitTests.Execution.TestExecutionManagerTests+DummyTestClassWithDoNotParallelizeMethods
>[6/2/2018 1:15:49 PM Warning] UTA001: TestClass attribute defined on non-public class Microsoft.VisualStudio.TestPlatform.MSTestAdapter.UnitTests.Execution.TestMethodFilterTests+DummyTestClassWithTestMethods
>[6/2/2018 1:15:49 PM Warning] UTA001: TestClass attribute defined on non-public class Microsoft.VisualStudio.TestPlatform.MSTestAdapter.UnitTests.Execution.TypeCacheTests+DummyTestClassWithTestMethods
>[6/2/2018 1:15:49 PM Warning] UTA001: TestClass attribute defined on non-public class Microsoft.VisualStudio.TestPlatform.MSTestAdapter.UnitTests.Execution.TypeCacheTests+DerivedTestClass
>[6/2/2018 1:15:49 PM Warning] UTA001: TestClass attribute defined on non-public class Microsoft.VisualStudio.TestPlatform.MSTestAdapter.UnitTests.Execution.TypeCacheTests+DummyTestClassWithInitializeMethods
>[6/2/2018 1:15:49 PM Warning] UTA001: TestClass attribute defined on non-public class Microsoft.VisualStudio.TestPlatform.MSTestAdapter.UnitTests.Execution.TypeCacheTests+DummyTestClassWithCleanupMethods
>[6/2/2018 1:15:49 PM Warning] UTA001: TestClass attribute defined on non-public class Microsoft.VisualStudio.TestPlatform.MSTestAdapter.UnitTests.Execution.TypeCacheTests+DummyDerivedTestClassWithInitializeMethods
>[6/2/2018 1:15:49 PM Warning] UTA001: TestClass attribute defined on non-public class Microsoft.VisualStudio.TestPlatform.MSTestAdapter.UnitTests.Execution.TypeCacheTests+DummyDerivedTestClassWithCleanupMethods
>[6/2/2018 1:15:49 PM Warning] UTA001: TestClass attribute defined on non-public class Microsoft.VisualStudio.TestPlatform.MSTestAdapter.UnitTests.Execution.TypeCacheTests+DummyTestClassWithInitAndCleanupMethods
>[6/2/2018 1:15:49 PM Warning] UTA001: TestClass attribute defined on non-public class Microsoft.VisualStudio.TestPlatform.MSTestAdapter.UnitTests.Execution.TypeCacheTests+DummyTestClassWithIncorrectInitializeMethods
>[6/2/2018 1:15:49 PM Warning] UTA001: TestClass attribute defined on non-public class Microsoft.VisualStudio.TestPlatform.MSTestAdapter.UnitTests.Execution.TypeCacheTests+DummyTestClassWithIncorrectCleanupMethods
>[6/2/2018 1:15:49 PM Warning] UTA001: TestClass attribute defined on non-public class Microsoft.VisualStudio.TestPlatform.MSTestAdapter.UnitTests.Execution.TypeCacheTests+DummyTestClassWithIncorrectTestMethodSignatures
>[6/2/2018 1:15:49 PM Warning] UTA001: TestClass attribute defined on non-public class Microsoft.VisualStudio.TestPlatform.MSTestAdapter.UnitTests.Execution.UnitTestRunnerTests+DummyTestClass
>[6/2/2018 1:15:49 PM Warning] UTA001: TestClass attribute defined on non-public class Microsoft.VisualStudio.TestPlatform.MSTestAdapter.UnitTests.Execution.UnitTestRunnerTests+DummyTestClassWithInitializeMethods
>[6/2/2018 1:15:49 PM Warning] UTA001: TestClass attribute defined on non-public class Microsoft.VisualStudio.TestPlatform.MSTestAdapter.UnitTests.Execution.UnitTestRunnerTests+DummyTestClassWithCleanupMethods
>[6/2/2018 1:15:54 PM Warning] [MSTest][Discovery][C:\Users\mdepouw\Source\Repos\GitHub\spottedmahn\testfx\artifacts\Debug\Extension.Core\Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions.dll] Input string was not in a correct format.
>[6/2/2018 1:15:55 PM Warning] [MSTest][Discovery][C:\Users\mdepouw\Source\Repos\GitHub\spottedmahn\testfx\artifacts\Debug\MSTest.CoreAdapter.Unit.Tests\Microsoft.VisualStudio.TestPlatform.MSTestAdapter.UnitTests.dll] Could not load type 'Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.AssemblyResolver' from assembly 'Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
>[6/2/2018 1:15:55 PM Warning] [MSTest][Discovery][C:\Users\mdepouw\Source\Repos\GitHub\spottedmahn\testfx\artifacts\Debug\MSTest.CoreAdapter\Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.dll] Input string was not in a correct format.
>[6/2/2018 1:16:01 PM Warning] [MSTest][Discovery][C:\Users\mdepouw\Source\Repos\GitHub\spottedmahn\testfx\artifacts\Debug\PlatformServices.Desktop\Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.dll] Unable to load types from the test source 'C:\Users\mdepouw\Source\Repos\GitHub\spottedmahn\testfx\artifacts\Debug\PlatformServices.Desktop\Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.dll'. Some or all of the tests in this source may not be discovered.
>[6/2/2018 1:16:01 PM Warning] [MSTest][Discovery][C:\Users\mdepouw\Source\Repos\GitHub\spottedmahn\testfx\artifacts\Debug\PlatformServices.Interface\Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface.dll] Input string was not in a correct format.
>[6/2/2018 1:16:01 PM Warning] [MSTest][Discovery][C:\Users\mdepouw\Source\Repos\GitHub\spottedmahn\testfx\artifacts\Debug\PlatformServices.NetCore\netstandard1.5\Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.dll] Input string was not in a correct format.
>[6/2/2018 1:16:03 PM Warning] [MSTest][Discovery][C:\Users\mdepouw\Source\Repos\GitHub\spottedmahn\testfx\artifacts\Debug\PlatformServices.Portable.Unit.Tests\MSTestAdapter.PlatformServices.Portable.UnitTests.dll] Could not load type 'Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.AssemblyResolver' from assembly 'Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
>[6/2/2018 1:16:03 PM Warning] [MSTest][Discovery][C:\Users\mdepouw\Source\Repos\GitHub\spottedmahn\testfx\artifacts\Debug\PlatformServices.Portable\Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.dll] Input string was not in a correct format.
>[6/2/2018 1:16:03 PM Warning] [MSTest][Discovery][C:\Users\mdepouw\Source\Repos\GitHub\spottedmahn\testfx\artifacts\Debug\PlatformServices.Universal.Unit.Tests\Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.UWP.UnitTests.dll] Could not load type 'Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.AssemblyResolver' from assembly 'Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
>[6/2/2018 1:16:03 PM Warning] [MSTest][Discovery][C:\Users\mdepouw\Source\Repos\GitHub\spottedmahn\testfx\artifacts\TestAssets\ComponentTests\TestProjectForAssemblyResolution.dll] Could not load file or assembly 'TestProjectForAssemblyResolution, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)
>[6/2/2018 1:16:11 PM Warning] [MSTest][Discovery][C:\Users\mdepouw\Source\Repos\GitHub\spottedmahn\testfx\test\ComponentTests\TestAssets\SampleFrameworkExtensions\bin\Debug\SampleFrameworkExtensions.dll] Could not load file or assembly 'SampleFrameworkExtensions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)
>[6/2/2018 1:16:19 PM Informational] ========== Discover test finished: 1119 found (0:00:56.3489172) ==========

## Steps to reproduce
- open TestFx.sln
- build sln
- review output -> tests window

## Expected behavior
- no warnings

## Actual behavior
- a bunch of warnings

## Environment
- Win 10, VS 2017 (15.7.3)

**Comment by jayaranigarg** [comment]
@spottedmahn : These warnings should not block you in any way. We do agree it is not great to be hit with such warnings. We would be happy to accept a contribution to fix these warning and help you in every possible way.

**Comment by parrainc** [comment]
Hi @jayaranigarg 
I have some free time that I could spend on this, if no body else is working on it right now :)
Please, let me know and I'll start right away.

**Comment by parrainc** [comment]
@jayaranigarg  I think this issue can be closed, since it was resolved on #480

**Comment by jayaranigarg** [comment]
@parrainc : Thank you. Closing the issue.
