### ISSUE TITLE
Cannot run UWP tests with 3.6.2

### ISSUE THREAD

**Issue by jnyrup** [microsoft/testfx#4371]
## Describe the bug
After upgrading from 3.6.1 to 3.6.4 I could no longer run tests from [UWP.Specs](https://github.com/fluentassertions/fluentassertions/tree/develop/Tests/UWP.Specs) in Visual Studio.

v3.6.2 was the first version that no longer worked for me.
I suspect it being related to #3949 as if I remove these three lines
https://github.com/microsoft/testfx/pull/3949/files#diff-9dfba7d4ed3c8c0e52817be015e3b388f7e1cd95cd6301c04684b604d720cb99R37-R39
or explicitly set `<EnableMSTestV2CopyResources>false</EnableMSTestV2CopyResources>` in my csproj the test is again runnable.

## Steps To Reproduce
1. Clone https://github.com/fluentassertions/fluentassertions
2. Checkout `c050f6bcaec68195f1d0dd0e44d233c6bbecf033`
3. Open `FluentAssertions.sln`
4. Change to release mode.
5. Right click on `UWP.Specs` and select build (the project is excluded from the configuration manager)
6. See that `Determining_caller_identity_should_not_throw_for_native_programs` is runnable and succeeds.
7. Edit `Tests\UWP.Specs\UWP.Specs.csproj` to use 3.6.2
8. Build `UWP.Specs` again
9. See that `Determining_caller_identity_should_not_throw_for_native_programs` is no longer runnable.

## Expected behavior
`Determining_caller_identity_should_not_throw_for_native_programs` should succeed

## Actual behavior
`Determining_caller_identity_should_not_throw_for_native_programs` is not runnable from VS

**Comment by Evangelink** [comment]
Perfect timing @jnyrup! I was about to start release of 3.7, including into that milestone so we fix and ship tomorrow.

**Comment by Evangelink** [comment]
Unrelated to your issue but as I am building I noticed:

![Image](https://github.com/user-attachments/assets/5a037514-7690-473b-9826-d3a7155b4796)

MSTest is also supporting the new platform and xUnit and NUnit are on their way too (beta/previews for them).

**Comment by Evangelink** [comment]
@jnyrup I am not managing to build the uwp package on the commit you gave me.

**Comment by Evangelink** [comment]
Ok so looks like we have a few problems, it's not yet fully clear as the issue is different for 3.7
