### ISSUE TITLE
Point VS At my Custom Test Discoverer?

### ISSUE THREAD

**Issue by spottedmahn** [Microsoft/testfx#438]
I've made a change to [`UnitTestElement.cs`](https://github.com/Microsoft/testfx/blob/master/src/Adapter/MSTest.CoreAdapter/ObjectModel/UnitTestElement.cs) in `MSTest.CoreAdapter` but I can't figure out how to tell VS to look at this new version.

I've reviewed the [contribute guide](https://github.com/Microsoft/testfx-docs/blob/master/docs/contribute.md#diagnostics) but I don't see anything about that.  Am I missing it?

---

Note: I have made changes to `MSTest.Core` and I'm able to see those changes as described in the [contribute guide under deployment](https://github.com/Microsoft/testfx-docs/blob/master/docs/contribute.md#deployment).

**Comment by jayaranigarg** [comment]
@spottedmahn : You have to upgrade both MSTest Adapter and framework nuget package. I guess you just upgraded MSTest.TestFramework and that is why you only see MSTest.Core changes. To see MSTest.CoreAdapter changes, please update MSTest.TestAdapter as well.

**Comment by spottedmahn** [comment]
Yep, that did it.

There has to be a quick dev cycle here but that's a different topic.  Thanks! 🙏
