### ISSUE TITLE
Message Cleanup

### ISSUE THREAD

**Issue by spottedmahn** [Microsoft/testfx#442]
## Description
VS and Rosyln are now providing better analysis of our code!  But now there are ~42 messages in the code base that need to reviewed

![image](https://user-images.githubusercontent.com/14079228/41037328-00ceafae-6961-11e8-9297-7eb7afac48df.png)

One example:

![image](https://user-images.githubusercontent.com/14079228/41037322-fd440cda-6960-11e8-8634-7235cf661bb6.png)

## Steps to reproduce
- Open Code w/ VS 2017 (15.7.3) or later

## Expected behavior
- No messages

## Actual behavior
- ~42 messages

Would you accept a PR that addressed these messages?

**Comment by singhsarab** [comment]
Although these are just suggestions, I guess it is good to clean up.

**Comment by parrainc** [comment]
@singhsarab It seems that no body's currently working on it...
Taking this issue :)
