### ISSUE TITLE
UWP tests do not run with 1.3.2 verion of the Framework,Adapter pair

### ISSUE THREAD

**Issue by AbhitejJohn** [Microsoft/testfx#444]
## Description
Create a UWP UT project targetting 1.3.2 version of the Framework and Adapter. 
Perform a "Run All" or try to run the test from commandline. The test does not complete. 
This works with 1.3.1 version of the tuple.

**Comment by AbhitejJohn** [comment]
@cltshivash  to triage.

**Comment by AbhitejJohn** [comment]
This is limited to projects targeting the 14393 UWP SDK. Works with projects targeting 16299 and higher. 
This could potentially also be related to TPV2 not supporting this SDK. 

One other thing that I've noticed with default projects targetting 14393 is that they do not have a reference to "Microsoft.Net.Test.SDK". Adding a reference to 15.7.0 version of that package does not seem to help for VS 15.7.3 but it does strangely work on the latest dogfooding build of VS 15.8. What do I do to get more data that can help debug this?
@genlu - FYI.

**Comment by jayaranigarg** [comment]
Tagging @mayankbansal018

**Comment by singhsarab** [comment]
@AbhitejJohn Reading the comments above, I don't think this is related to 1.3.2 release. Can we close this issue here ?

**Comment by ShreyasRmsft** [comment]
@singhsarab @mayankbansal018 @jayaranigarg what is our action item here?

**Comment by mayankbansal018** [comment]
current mstest package works fine with UWP, it seems a few were missed in initial analysis of this bug, we can close this issue

**Comment by ShreyasRmsft** [comment]
Closing this

**Comment by AbhitejJohn** [comment]
@mayankbansal018 , @singhsarab : Sorry, I missed this. I can repro this with a blank UWP project targeting SDK **14393** on VS 15.7.3 and 1.3.2 of the Fx/Adapter. A 'Run All' never finishes, so does a CLI test run I believe. This works on the latest VS version though(possibly because of a template change?). 
This does still look like an issue to me though unless this is a conscious break that we want documented. I'll go ahead and reopen this issue for tracking. Let me know otherwise.

**Comment by AbhitejJohn** [comment]
@jayaranigarg : Let me know if I can add more details. This look more like a bug than a question.

**Comment by jayaranigarg** [comment]
@AbhitejJohn : I tried on VS 15.7.2 with UWP UT Project targeting SDK 14393 and min version 10586/10240, works perfectly fine. This is TPV1 flow. 

Also, tried targeting SDK 16299 and min version 14393, works fine in this as well. This is TPv2 flow.

>This works on the latest VS version though(possibly because of a template change?). 

I am not sure which template change you are referring to?

If you hit this issue again, can you please share a repro machine with us?

**Comment by AbhitejJohn** [comment]
@jayaranigarg : That's odd. Can you give the attached project a shot? I just created a project targeting 14393 and upgraded the MSTest Fx and Adapter to 1.3.2.
[UnitTestProject8.zip](https://github.com/Microsoft/testfx/files/2169488/UnitTestProject8.zip)

I was referring to the changes in the templates/targets to get TPV2 working. Not completely sure of the list though.

**Comment by AbhitejJohn** [comment]
Here is the stack for a worker thread in the app. Doesn't look like the connection is made.
```
System.Private.CoreLib.ni.dll!System.Threading.Monitor.Wait
System.Private.CoreLib.ni.dll!System.Threading.Monitor.Wait(object obj, int millisecondsTimeout, bool exitContext)
System.Private.CoreLib.ni.dll!System.Threading.Monitor.Wait(object obj, int millisecondsTimeout)
System.Private.CoreLib.ni.dll!System.Threading.ManualResetEventSlim.Wait(int millisecondsTimeout, System.Threading.CancellationToken cancellationToken)
System.Private.CoreLib.ni.dll!System.Threading.Tasks.Task.SpinThenBlockingWait(int millisecondsTimeout, System.Threading.CancellationToken cancellationToken)
System.Private.CoreLib.ni.dll!System.Threading.Tasks.Task.InternalWait(int millisecondsTimeout, System.Threading.CancellationToken cancellationToken)
System.Private.CoreLib.ni.dll!System.Threading.Tasks.Task.Wait(int millisecondsTimeout, System.Threading.CancellationToken cancellationToken)
Microsoft.VisualStudio.TestPlatform.TestExecutor.Core.dll!Microsoft.VisualStudio.TestPlatform.TestExecutor.LocalWcfClient.StartPollingThread.AnonymousMethod__0()
System.Private.CoreLib.ni.dll!System.Threading.Tasks.Task.InnerInvoke()
System.Private.CoreLib.ni.dll!System.Threading.Tasks.Task.Execute()
System.Private.CoreLib.ni.dll!System.Threading.Tasks.Task.ExecutionContextCallback(object obj)
System.Private.CoreLib.ni.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)
System.Private.CoreLib.ni.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref System.Threading.Tasks.Task currentTaskSlot)
System.Private.CoreLib.ni.dll!System.Threading.Tasks.Task.ExecuteEntry(bool bPreventDoubleExecution)
System.Private.CoreLib.ni.dll!System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
System.Private.CoreLib.ni.dll!System.Threading.ThreadPoolWorkQueue.Dispatch()
System.Private.CoreLib.ni.dll!System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```
Could this be related to a dependent assembly versioning causing load failures? 
/cc: @pvlakshm , @mayankbansal018 to help triage please.

**Comment by jayaranigarg** [comment]
@AbhitejJohn : Tried on VS 15.8 Preview 4, it reproes for me with 1.3.2 version of adapter and works fine for 1.3.0. Although this could be related to platform changes as well. For now, acknowledging this to be a bug.

**Comment by jayaranigarg** [comment]
@AbhitejJohn : Currently the UWP projects targeting 14393 SDK and min version 10586/10240 goes via TPV1 flow. This seems like an intermittent issue and migrating the project to TPv2 is working fine. 

Tried on VS 15.9 Preview 1, creating a fresh project on my machine going via TPV1 is also working fine. Our recommendation is to move towards TPv2.
