### ISSUE TITLE
Unexpected overhead in test execution times when the number of test cases increases

### ISSUE THREAD

**Issue by kaadhina** [microsoft/testfx#446]
[Samples.zip](https://github.com/Microsoft/testfx/files/2082993/Samples.zip)
## Description
Unexpected overhead in test execution times when the number of test cases increases. The increase is non-linear with the increase in number of tests.

## Steps to reproduce
1. Execute a test run with one assembly containing 10k test cases => Takes ~ 10.65s
2. Execute a test run with one assembly containing 50k test cases => Takes ~ 165.87s

[Execute a test run with five assemblies each containing 10k test cases => Takes ~ 50.1s]

## Expected behavior
It should take around 50s for the second case

**Comment by pvlakshm** [comment]
Is this represented in the perf workloads we use? If so, is this a regression?

**Comment by Evangelink** [comment]
There are still multiple performance issues with MSTest but this issue as-is is not really actionable so I will close it.
