### ISSUE TITLE
The test that runs first in a test run has much higher test execution time than if it is not the first test to run

### ISSUE THREAD

**Issue by ShreyasRmsft** [microsoft/testfx#447]
![image](https://user-images.githubusercontent.com/25194518/41152944-e200b832-6b32-11e8-80f9-9352361c9cb9.png)

ValidateRerunDisabledForServiceResponse has lower exe time when not run first.

![image](https://user-images.githubusercontent.com/25194518/41152988-07ef1eda-6b33-11e8-9a0a-21bfecd88fd3.png)

ValidateRerunDisabledForServiceResponse has higher exe time when run first.

I suspect we are adding overheads to first test which ideally shouldn't be the case

**Comment by Evangelink** [comment]
Times displayed are not exact because of how Test Explorer is doing calculation.

There were a couple of updates on MSTest side to exclude counting Assembly/Class Init/Cleanup from test o this issue should no longer be relevant.
