### ISSUE TITLE
VSTS Test Runner matching framework issue

### ISSUE THREAD

**Issue by Travisimo** [Microsoft/testfx#448]
## Description
> **IMPORTANT**: if the defect is reproduced only in a workflow from within the Visual Studio IDE then do not report the issue here - instead, please report it using Visual Studio's "Send Feedback" option that can be accessed from the Help menu OR using this link https://developercommunity.visualstudio.com.
>
> For a defect specific to the MSTest V2 test framework, describe the issue you've observed.

## Steps to reproduce
Create an MSTest Project with Framework = 4.5
Create VSTS Release Test Task with /Framework:Framework45 setting
Add test project to VSTS Release Test Task
When Test Task is executing, VS Test Runner incorrectly displays warnings that framework and platform are not matching

![image](https://user-images.githubusercontent.com/1070048/41171406-4a4e9c34-6b05-11e8-8f8b-90780530dfd7.png)

## Expected behavior
Tests should execute

## Actual behavior
Incorrect warning displayed: "Following DLL(s) do not match framework/platform settings"

## Environment
Microsoft (R) Test Execution Command Line Tool Version 15.5.1

**Comment by jayaranigarg** [comment]
@Travisimo :  We see you are on an older version of TestPlatform i.e. 15.5.1. We fixed this issue in later releases. Please move to latest VS and see if it works for you.

**Comment by ShreyasRmsft** [comment]
@Travisimo any updates here?

**Comment by jayaranigarg** [comment]
Closing the issue. Please feel to re-open, if you face any issue after upgrading to latest version.
