### ISSUE TITLE
Failure reading app.config system.servicemodel\bindings with MSTest.TestAdapter

### ISSUE THREAD

**Issue by mack0196** [Microsoft/testfx#449]
`An error occurred creating the configuration section handler for system.serviceModel/bindings: Could not load file or assembly 'Microsoft.ServiceBus, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The parameter is incorrect. `

At the top of the stack we are opening a ChannelFactory for a service endpoint that is using netTcpRelayBinding which is defined in Microsoft.ServiceBus.

Test run as expected with MSTest.TestAdapter 1.2.1. Test fail with this error with v1.3.0 v1.3.1 and v1.3.2

VSTS agents and Visual Studio are running with latest versions.

**Comment by smadala** [comment]
@mack0196 Can you share sample repro project?

**Comment by smadala** [comment]
@mack0196 Also Pass /diag:log.txt to vstest.console and share log.txt and log.host.*.txt files.

**Comment by smadala** [comment]
@mack0196 Did you get chance to get simple repro or diagnostic logs? Without them this issue is not actionable.

**Comment by smadala** [comment]
Closing as no repro.

**Comment by mack0196** [comment]
[UnitTestProject1.zip](https://github.com/Microsoft/testfx/files/2251861/UnitTestProject1.zip)

The repro project has one test that creates a ChannelFactory<ITestService>. When config has the extension types specified with PublicKeyToken. MS Test Framework fails with exception below; this test runs and passes with both Resharper unit testing and MS Test Framework v1.2.1 NuGet.

When I remove the PublicKeyToken from the type specification the test passes with MS Test Framework v1.3.1. I checked the public key token of the assembly with sn.exe and it was 31bf3856ad364e35 as expected. 

...config line 16) ---> System.IO.FileLoadException: Could not load file or assembly 'Microsoft.ServiceBus, `Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG)) ---> System.ArgumentException: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))`

**Comment by mack0196** [comment]
Yes still having this issue.

**Comment by cltshivash** [comment]
[UnitTest1.zip](https://github.com/Microsoft/testfx/files/2696990/UnitTest1.zip)
@mack0196 I couldn't get the attached project to build. The package reference hint paths were incorrect. Updated to the attached version and it works fine. Could you please recheck ? (might want to update the target fx to 4.7.1. I had used 4.7.2)

**Comment by abhishkk** [comment]
@mack0196 Any updates on info asked by Shiva?

**Comment by abhishkk** [comment]
Closing due to no response. Please re-open if required.
