### ISSUE TITLE
MsTest stopped working

### ISSUE THREAD

**Issue by Legends** [Microsoft/testfx#454]
I have one unit-test class and two test-methods.

I have defined a wrong signature for the `ClassInitialize` method:
```
 //[ClassInitialize]
        //void setup()
        //{
       
        //}
```

The problem here is that the tests don't work anymore and you don't get any information back why this is the case! Neither TestExplorer nore the Output console is showing an error!

When I implement the correct signature using `TestContext` it works as expected.

This should definitely throw an error here and a message pointing to the source of error.

What is this for an hierarchy? UnitTests(2)-->UnitTests(2)-->UnitTest1(2) ???
What's that?

![image](https://user-images.githubusercontent.com/966368/41801551-8baba0ec-767b-11e8-83dc-e82911fd2210.png)

**Feel free to inform your colleagues from the VS2017 Pro (latest) Team.**

**Comment by Legends** [comment]
@jayaranigarg Thanks for your quick response.
Yes, I was using :

![image](https://user-images.githubusercontent.com/966368/41971634-697d619e-7a0f-11e8-91e8-a57e7acfba38.png)

Updating it to version 1.3.2 showed the expected error message.
It would be nice if one creates a new unit test project, to always get the latest stable nuget packages for test with every update of VS2017.

Now the hierarchy makes sense. My fault, bad naming of Assembly/Class/Namespace which confused me.

Thanks again, sorry for wasting your time!

**Comment by jayaranigarg** [comment]
@Legends : Glad to hear it got fixed for you. We do update the UnitTest Templates to point to latest version of nuget packages as they get released with each VS. Latest VS 15.8 preview points to 1.3.2.
