### ISSUE TITLE
What happened to TestContext.TestResultsDirectory, TestDir etc?

### ISSUE THREAD

**Issue by richard-browne** [Microsoft/testfx#455]
In a .NET Core test project, TestContext no longer has these properties:

ResultsDirectory
TestDeploymentDir
TestDir
TestLogsDir
TestResultsDirectory
TestRunDirectory
TestRunResultsDirectory

What is the replacement for these? When I run a test after migrating to .NET Core, I no longer see a TestResults directory being created. Where should a test read and write its files now?

Is there any documentation for MSTest V2? I can't find any. The page here (https://github.com/Microsoft/testfx-docs) links to (https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.testtools.unittesting) which is V1 documentation.

**Comment by jayaranigarg** [comment]
@richard-browne : Properties you specified are mainly used in scenarios where we deploy test dlls and resources to a deployment directory. This feature is not yet supported for .netcore projects.  We have this feature in our backlog and have an issue already opened [here](https://github.com/Microsoft/testfx/issues/96) to track this. Please feel free to vote it up.

**Comment by jayaranigarg** [comment]
Tagging @pvlakshm to comment on when do we plan to bring this feature in.

**Comment by JDCain** [comment]
Is there a suggested way to get the TestResultsDirectory from a runsettings file in core? While TestResultsDirectory is not a property does it get loaded as a item in TestContext.Properties?

**Comment by jayaranigarg** [comment]
@JDCain : 
>Is there a suggested way to get the TestResultsDirectory from a runsettings file in core?

Can you explain it a bit more? 


> While TestResultsDirectory is not a property does it get loaded as a item in TestContext.Properties?

We are afraid, TestResultsDirectory is not available for netcore as of now. Not even in TestContext.Properties.

**Comment by JDCain** [comment]
@jayaranigarg When using a runsettings file you can set the ResultsDirectory. I was needing to be able to know what that folder is from the test.

**Comment by jayaranigarg** [comment]
@JDCain : Yes, you can set ResultsDirectory in runsettings file. You can access that in your code something like we access it [here](https://github.com/Microsoft/testfx/blob/master/src/Adapter/PlatformServices.Desktop/Utilities/DeploymentUtility.cs#L634).

**Comment by jayaranigarg** [comment]
Closing the issue from here. Please feel free to vote up [this](https://github.com/Microsoft/testfx/issues/96)issue for bringing in support for deployment item which in turn will bring these test context properties. Please follow the same issue for getting any updates on this.

**Comment by jayaranigarg** [comment]
@raffaeler : For .net core, this support has not yet come. There is no alternate set of properties as of now. Please feel free to vote [this](https://github.com/Microsoft/testfx/issues/96) issue if you would like this feature to be added.

**Comment by raffaeler** [comment]
@jayaranigarg thank you, I will.
But at the moment how can you know the default directories? What is the default I can use to copy additional files or to verify the dlls that will be delay loaded?

**Comment by sdg002** [comment]
**My scenario**
We have lots of class libraries that take inputs and generate output files. These were written on .NET Framework and tested using unit tests written on MS Test. In all our existing unit tests we were using the **TestContext.DeploymentDirectory** to give us a nice and clean output folder where the results were expected

We are now porting our code to .NET Standard. We are doing this in stages.  We have a MS Test project (.NET Core) where we are migrating our older .NET Framework based code. The absence of  **DeploymentDirectory** is beginning to hurt us.  Even though we were not using explicitly using the DeploymentItemAttribute, we were heavily reliant on DeploymentDirectory for the aforementioned reason.

In the absence of DeploymentDirectory, we are now having to use ad hoc approaches. e.g. using TEMP folder, etc.  Not the end of the world  - but just ad hoc.

**Comment by jayaranigarg** [comment]
@sdg002 : We have added support for TestContext.DeploymentDirectory in this release https://github.com/microsoft/testfx/releases/tag/v2.0.0-beta4. Also, I would not encourage you to comment on closed issues for queries as we don't track them. Please feel free to open new issue.
