### ISSUE TITLE
TestContext should provide that is a TestMethod or a DataTestMethod

### ISSUE THREAD

**Issue by Tbd19** [microsoft/testfx#459]
I have some unit tests where I use the TestContext.TestName.
However if I use it in a DataTestMethod my tests are failing because there is a collision between the tests because of the TestName. 

Is there a way to determine if the test is a DataTestMethod? Or even better to retrieve the DisplayName from the TestContext.

**Comment by Evangelink** [comment]
MSTest 3.7 will contain a bunch of properties that should bring most of what is needed (display name and data).
