### ISSUE TITLE
Direct Link: appears to unconditionally set '<OutputPath>' or '<OutDir>'

### ISSUE THREAD

**Issue by spottedmahn** [Microsoft/testfx#462]
## Description
The following link could be improved:

![image](https://user-images.githubusercontent.com/14079228/43011698-3b668eba-8c12-11e8-8f1e-3981e28a71d2.png)

## Expected behavior
Direct link to: https://docs.microsoft.com/en-us/visualstudio/test/live-unit-testing-faq#error-messages-with-ltoutputpathgt-or-ltoutdirgt

## Actual behavior
Generic link to https://docs.microsoft.com/en-us/visualstudio/test/live-unit-testing-faq

**Comment by pvlakshm** [comment]
@ManishJayaswal, take a look, please.

**Comment by spottedmahn** [comment]
Not an optimal User Experience but ok, thanks for the response!
