### ISSUE TITLE
VsTest > VSO - Published result test count is incorrect- not matching with log file count

### ISSUE THREAD

**Issue by iPiyushPatel** [Microsoft/testfx#465]
## Description
While running Unit Tests on VM using VsTest build step (screenshot below), published total test run count is different than what is show in log file (which is correct, screenshot below). 

![image](https://user-images.githubusercontent.com/5212585/43114736-0ae2298e-8f1e-11e8-8aba-830edbb891a7.png)

![build_log](https://user-images.githubusercontent.com/5212585/43114748-1aab8ebe-8f1e-11e8-8a19-708c369030c1.png)

## Steps to reproduce
I'm using VsTest V2. 

## Expected behavior
It should publish correct test run count. in this case, it should say 120.

## Actual behavior
Test run count is incorrect, it says 109

## Environment
VsTest V2

Let me know if any other info required.

**Comment by iPiyushPatel** [comment]
Hey @pvlakshm - 
Thanks for reply. 
In fact, I've figured out the issue. Let me explain. In our solution, we publish Test Logs back to VSO (code snippet below ). I noticed that if log file name is > 70+ (approx) then it doesn't export all results to VSO correctly. 

![image](https://user-images.githubusercontent.com/5212585/43373735-408d10b2-93c9-11e8-9514-bd9f20fad63f.png)

Now,I've restricted log file name size to max 70 and everything looks as expected.

Is this the known issue ? Please advice.

**Comment by jayaranigarg** [comment]
@iPiyushPatel : Apologies for the delay. This thread got missed. This is not a known issue. Are you still hitting this?

**Comment by iPiyushPatel** [comment]
Hey @jayaranigarg - I haven't tried lately while removing char limit of log file. I'll do that and let you know that result. 

Thanks,

**Comment by vagisha-nidhi** [comment]
Hi @iPiyushPatel 
Can you let us know if this issue is still hitting you? Or can we close the thread?

**Comment by iPiyushPatel** [comment]
Hey @vagisha-nidhi 
It looks good now. Let me close this thread. Thanks,
