### ISSUE TITLE
Add a .NET Standard version of TestAdapter

### ISSUE THREAD

**Issue by dotMorten** [microsoft/testfx#469]
## Description
If the test adapter was targeting .NET Standard instead of/in addition to netportable, we could reuse the test discovery and execution on Xamarin.
The asserts. attributes etc are already net standard compatible, so it's really just this missing piece, and we can reuse it across all platforms.

(Of course on Xamarin you'd have to write your own UI to show the tests and execute them / log the results, but that's still less code than what we have to do today where we also have to write discovery and execution ourselves)

[AB#1575822](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1575822)

**Comment by dotMorten** [comment]
Alternatively, place the portable version of TestAdapter in the \lib\ folder of the nuget package, so it gets deployed to android and ios, and we can call into it from the host app.

**Comment by Evangelink** [comment]
This is most likely going to be fixed by #1095

**Comment by Evangelink** [comment]
Fixed by #1194
