### ISSUE TITLE
MSTest framework with Xamarin.Mac Version 2.0

### ISSUE THREAD

**Issue by victorylu** [microsoft/testfx#473]
## Description

Hi, I'm currently trying to get the MSTest framework installed on the MacOS version of Visual Studio, but I am getting the following message: "Could not install package 'MSTest.TestAdapter 1.3.2'. You are trying to install this package into a project that targets 'Xamarin.Mac,Version=v2.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author." Is there more information regarding this topic or is it not supported at this time?

**Comment by mayankbansal018** [comment]
closing this issue, unfortunately it doesn't seem we are picking this anytime soon
