### ISSUE TITLE
Enhance the TimeoutAttribute to be ignored while debugging

### ISSUE THREAD

**Issue by TiltonJH** [Microsoft/testfx#475]
## Description
I am looking for a way to tell the test system to not fail a test with an applied `TimeoutAttribute` if the timeout gets called while I am actively debugging the test.

I am thinking on lines of disabling the timeout while debugger is attached or even better, to not take stops on breakpoints into account (if possible).

Of course the workaround is to remove or disable (via comments) the attribute, but the undo of that may be missed/over look before check in or regular runs.

## Steps to reproduce
```
[TestMethod]
[Timeout(10)]
public void Test1()
{
    // do some work and have any number of breakpoints here
    // and the test fails because of timeout
}
```

## Expected behavior
Maybe something like that:
```
[TestMethod]
[Timeout(10, Disable(/Ignore)WhileDebuggerIsAttached = true)]
public void Test1()
{
    // do some work and have any number of breakpoints here
    // and test does not fail because of timeout
}
```

**Comment by jayaranigarg** [comment]
@TiltonJH : Thank you for the feedback. We do agree with your viewpoint. We have a similar issue filed for this here: https://github.com/Microsoft/testfx/issues/475. Please upvote and follow earlier issue.
