### ISSUE TITLE
TestAdapter grouping by Traits should not create separate groups for Description and WorkItem attributes

### ISSUE THREAD

**Issue by robdalsanto** [Microsoft/testfx#478]
I think the title and the picture illustrate where this can lead. Note also that Owner should not split into different groups. I don't believe this happened prior to MSTest-V2, at least not with WorkItem and Description.

Example of Description attribute:
```
        [TestMethod, SmokeTypeTest]
        [Description("Bug fix 1506 and 1516. If Alternative linked to Outage then Alternative date has to be updated to selected Outage occurrence date")]
        public void UpdateAlternative_LinkedToOutageTest()
        {
```

![image](https://user-images.githubusercontent.com/31216152/44291509-a0d2c700-a233-11e8-805e-5a019820b2e6.png)

**Comment by jayaranigarg** [comment]
@robdalsanto : The behaviour has always been like this from adapter side, in both MSTestV1 and MSTestV2.

Tagging @AbhitejJohn @genlu to look into if there has been some behavior difference from test explorer end.

**Comment by robdalsanto** [comment]
@jayaranigarg @AbhitejJohn We are seeing this duplication in VS2015, which occurred immediately after we started to use the NuGet MSTestV2 instead of the MSTestV1 shipped in VS2015.

We don't have a lot of these attributes, and they don't provide much value, like allowing TFS to link to the test-methods from the work-item. So we will likely remove them. Still it is odd to see these 3 attributes as traits.

**Comment by singhsarab** [comment]
@robdalsanto We identified and fixed the issue. It will be available in the next preview release of the adapter.
