### ISSUE TITLE
ITestDataSource : how to access TestContext

### ISSUE THREAD

**Issue by Styxxy** [Microsoft/testfx#479]
## Description
I would like to use a directory as a datasource, where each file from this directory is a DataRow.
I found the ITestDataSource extensibility, where you can develop an attribute using this.

However, how can I access the TestContext to determine the TestRunDirectory (where for example my DeploymentItems are copied to)?

I currently use `Environment.CurrentDirectory`, however this doesn't feel like the right solution.

My currently developed attributed:
```cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Styxxy.UnitTesting
{
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Method, AllowMultiple = false)]
    public class DirectoryDataSourceAttribute
        : Attribute
        , ITestDataSource
    {
        public string Directory { get; }
        public string Filter { get; }

        public DirectoryDataSourceAttribute(string directory)
            : this(directory, null)
        { }

        public DirectoryDataSourceAttribute(string directory, string filter)
        {
            Directory = directory;
            Filter = filter;
        }

        public IEnumerable<object[]> GetData(MethodInfo methodInfo)
        {
            return System.IO.Directory.GetFiles(
                System.IO.Path.Combine(Environment.CurrentDirectory, Directory),
                Filter)
                .Select(s => new object[1] { s });
        }

        public string GetDisplayName(MethodInfo methodInfo, object[] data)
        {
            return string.Format(
                System.Globalization.CultureInfo.CurrentCulture,
                "{0} ({1})",
                methodInfo.Name,
                data?.FirstOrDefault() ?? string.Empty);
        }
    }
}
```

## Environment
Windows 7
Visual Studio 2017 (15.7.6)
Microsoft.NET.Test.Sdk (15.8.0)
MSTest.TestAdapter (1.3.2)
MSTest.TestFramework (1.3.2)
TargetFramework net47

**Comment by jayaranigarg** [comment]
@Styxxy : Thank you for reaching out to us.
Talking about adapter internal flow :  data which needs to be passed to testmethod as arguments is extracted first and we set/fill-in values for TestContext object just before we invoke a testmethod, . This basically means you cannot leverage TestContext values in your custom attribute because they would not have been set, even if TestContext object was somehow available to you.

Using `Environment.CurrentDirectory` should be a totally acceptable solution.

**Comment by Styxxy** [comment]
@jayaranigarg Thanks for the feedback.

Using `Environment.CurrentDirectory` feels not right because this might be subject to change depending on how the test runner behaves, but hopefully it won't change.

**Comment by ShreyasRmsft** [comment]
@jayaranigarg is it something that is likely to change in the future?

**Comment by jayaranigarg** [comment]
@Styxxy : As of now there is no plan to change this behavior in future.

**Comment by ShreyasRmsft** [comment]
@Styxxy closing this issue. Please re-open if you need any more information or clarification.

**Comment by Styxxy** [comment]
@jayaranigarg @ShreyasRmsft 
Thank you for the information.
