### ISSUE TITLE
Upgrade target framework of PlatformServices.Portable project

### ISSUE THREAD

**Issue by parrainc** [microsoft/testfx#481]
## Description
The target framework for the Portable project in ... should be upgraded to at least .net standard version 1.3.x or maybe the latest one. 

Why? I'm trying to fix this issue #394 but unfortunately since .net standard implementation doesn't have Path.GetFullPath() method, I haven't been able to make the PR (to replicate the same behavior as in the full CLR implementation of the TestContext).

## Steps to reproduce
> Clone the testfx repo
> Open the TestFx sln
> Build it
> Go to PlatformServices.Portable project
> Open any of the ns10... files, and
> Try typing Path.GetFullPath() -- you will see warning next to method name, and intellisense stating that GetFullPath() method is not available.

## Expected behavior
> users should be able to use Path.GetFullPath() method across all the projects (Portable, NetCore, and Universal)

## Actual behavior
> Since target net standard version is 1.0.x or lower than 1.3.x, the Path.GetFullPath() and other methods are not implemented.

<img width="416" alt="path-missing2" src="https://user-images.githubusercontent.com/10530861/44614793-e9bce980-a7f8-11e8-92cf-2f59635058dd.PNG">

## Environment
> Windows 10, build 1803.
> Visual Studio 2017
> MSTest V2
> .Net Core 2.1.3

[AB#1575898](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1575898)

**Comment by parrainc** [comment]
I'm available and dispose to work on this issue, but would need some help (i.e. what do i need to change in order to upgrade the target framework).

**Comment by Evangelink** [comment]
This will be handled by #1095

**Comment by Evangelink** [comment]
Fixed by #1163
