### ISSUE TITLE
UWP UnitTests runs can suspend

### ISSUE THREAD

**Issue by dotMorten** [Microsoft/testfx#495]
## Description
Recently moved our UWP UnitTests to use the newer MSTest nuget package, but we're now finding that our automated unit tests will often hang on server executing them.
The moment we sign into the server, the unit tests will continue executing, indicating that the Test Runner is getting suspended by the OS. Is MSTest v2 forgetting to extend execution time for UWP apps?

## Steps to reproduce
> Long-running 1000s of test runs on a server without a user connected
> Using v1.3.2

## Expected behavior
> Tests complete

## Actual behavior
> Tests stop executing after a while, but resume the moment you remote in to the server.

**Comment by jayaranigarg** [comment]
@dotMorten : This is a known issue which has been fixed in RS5. Please follow the original issue here : https://github.com/Microsoft/vstest/issues/1524 
Closing this as duplicate.
