### ISSUE TITLE
Removing the [Ignore] attribute does not permit a previously ignored test to run. 

### ISSUE THREAD

**Issue by StingyJack** [Microsoft/testfx#497]
This is effectively the same report as 

https://developercommunity.visualstudio.com/content/problem/269026/vs-wont-run-a-unit-test-that-used-to-have-an-ignor.html

...and a second one with more information...

https://developercommunity.visualstudio.com/content/problem/353013/vs-wont-run-a-unit-test-that-used-to-have-an-ignor-1.html

... a step recording and test diagnostics are attached to the later report. 

I have a unit test that is a pseudo integration test that only is run when troubleshooting some functionality for a Zebra ZPL based printer. Since we do not want this method to run as part of the rest of the unit test suite (it will try to connect to a printer), its marked with `[Ignore]`.  When we want to use it, the `[Ignore]` attribute is removed or commented out and we used to be able to run/debug the test to execute the method. 

This no longer works because the test is never found during discovery. Cleaning and rebuilding the project does not resolve it, nor does unloading and reloading the solution. **EDIT**: _Closing VS, renaming the .vs folder for the solution and retrying does not resolve it either._

When right clicking in the method body and choosing Run Test(s) or Debug Test(s), the test Output window just says (paths and names redacted)
```
[10/10/2018 10:25:04 AM Diagnostic] Discovering tests in c:\tfs\UnitTest\PrinterTests\ZebraTests.cs
[10/10/2018 10:25:06 AM Warning] No test matches the given testcase filter `FullyQualifiedName=.ZebraTests.TestActualPrintingStuff` in c:\tfs\UnitTest\PrinterTests\bin\x64\Debug\PrinterTests.dll
[10/10/2018 10:25:06 AM Diagnostic] Not showing nuget adapter message for project PrinterTests even though it uses framework MSTESTV1 because either MSTestV1 or NUnit VSIX are installed.
Also the adapter settings in tools options are: UseSpecifiedAdapterLocations: True and FallbackToGlobalVsix: True which ensures that VSIX adapter gets used.
[10/10/2018 10:25:06 AM Diagnostic] VirtualReadOnlyTestDataStore.OperationStateChanged State=OperationSetFinished, operationInProgress=False
[10/10/2018 10:25:06 AM Diagnostic] TestDiscoveryStats.OperationStateChanged State=OperationSetFinished, InProgress=False
[10/10/2018 10:25:06 AM Diagnostic] ***    Run finished using 'InMemoryUnitTestWriter' ***
[10/10/2018 10:25:06 AM Informational] ========== Run test finished: 0 run (0:00:03.4671319) ==========
```

Yet the test is clearly visible in the Test Explorer. 
![image](https://user-images.githubusercontent.com/15381181/46744109-74a65600-cc78-11e8-9d15-25e4279383fc.png)

Test discovery seems to have a few problems which may be related to this... 

1) I instructed VS which test to run, yet a more complete discovery is still executed despite not being necessary. 

2) Discovery is attempting to discover tests in non test project classes. There are dozens of entries like this in the Tests output window. Nothing in the Source folder is a unit test project, so it makes no sense for any discovery to be happening.
```
[10/10/2018 10:25:14 AM Diagnostic] Discovering tests in c:\tfs\Source\Common\Expressions\ExpressionValidator.cs
[10/10/2018 10:25:15 AM Diagnostic] Discovering tests in c:\tfs\Source\Core\Resources\WorkFlows\Expression.cs
[10/10/2018 10:25:16 AM Diagnostic] Discovering tests in c:\tfs\Source\Common\Printing\Printer.cs
```
**EDIT**: #506 has been logged for this second item.

I need to be able to toggle the `[Ignore]` attribute and run these tests and not have to now resort to the overhead of a bunch of console applications.

**Comment by acesiddhu** [comment]
Tagging folks from the IDE team @ManishJayaswal @AbhitejJohn can you take a look?

**Comment by acesiddhu** [comment]
@StingyJack I had a chat with @AbhitejJohn. As you mentioned you have already raised an issue of [devcom](https://developercommunity.visualstudio.com/content/problem/353013/vs-wont-run-a-unit-test-that-used-to-have-an-ignor-1.html). Can you provide relevant information to Abhitej on devcoms? I am closing the issue here so that we can track the issue on devcoms instead.

**Comment by StingyJack** [comment]
This is what I mean about searching for the issue. 
![image](https://user-images.githubusercontent.com/15381181/50518286-eb3a3f00-0a82-11e9-9e5e-91539ca01e1e.png)


If I remove the "Items I follow" filter, this one shows up as the second result (despite being a match on the title).
![image](https://user-images.githubusercontent.com/15381181/50518305-06a54a00-0a83-11e9-89c0-681d0026e046.png)

Given that it can be very hard for users to see the updates to devcomm issues when they are made, I'll leave it up to you to either retain this issue as the open item and close the devcomm one, or close this one and leave the devcomm one open.

**Comment by StingyJack** [comment]
In either case I need someone to please sanitize any program names out of [this post](https://developercommunity.visualstudio.com/comments/362321/view.html). I'm not logged into devcomm, but I can still see these details and they should be private.

**Comment by acesiddhu** [comment]
@stingyjack apologies that the experience for you on devcoms wasn’t great. I will pass on that feedback to relevant team. I will also ask Abhitej to strip off the program names in his post. I suggest we track this issue on devcoms
