### ISSUE TITLE
Assembly Initialize/Cleanup methods not being reached out when inheriting TestClass attribute

### ISSUE THREAD

**Issue by parrainc** [Microsoft/testfx#503]
## Description
When inheriting from `TestClassAttribute` class, and using the newly create attribute in a test class (somehting like `[MyTestClass]`) neither the assembly initialize/cleanup methods are being called.

i.e.:
```
public class ModifiedTestClassAttribute : TestClassAttribute { }

[ModifiedTestClass]
public class MyTestClass { ... }
```

## Steps to reproduce
In order to reproduce this issue, you should do the following:
1. Create a MSTest test project in VS.
2. Create a class that inherits from TestClassAttribute.
3. Create a test class, and use the class created in previous step as its attribute.
4. Define Assembly initialize/cleanup methods with some logic inside.
5. Create a simple test method and run it.

## Expected behavior

> Call to AssemblyInitialize
> Call to ClassInitialize
> Call to TestMethod(s)
> ...
> Call to ClassCleanup
> Call to AssemblyCleanup

_should be the same behavior when using `[TestClass]`_

## Actual behavior
> Call to ClassInitialize
> Call to TestMethod(s)
> ...
> Call to ClassCleanup

_No Assembly initialize/cleanup method was executed_

## Environment
- OS: Windows 10
- MSTest: 1.3.2 (latest as of today)

**Comment by parrainc** [comment]
Just figured out that the problem is in the [IsAttributeDefined](https://github.com/Microsoft/testfx/blob/master/src/Adapter/MSTest.CoreAdapter/Helpers/ReflectHelper.cs#L32) method from the `ReflectHelper`. When inherit from `TestClass`, it is just looking for an attribute match in the `memberInfo` param with the specified `attributeType` (which is TestClassAttribute).

I'm working on the fix for this issue.

**Comment by parrainc** [comment]
Closing this issue since it was fixed as part of PR #525

**Comment by KitoCoding** [comment]
@parrainc 

I know this is an old ticket, but this problem seems to be happening again.

**Comment by Haplois** [comment]
@KitoCoding, will you able to share a quick repro with us? If not, could you share the Test Platform version (and other NuGet packages you use with their versions) with us?
