### ISSUE TITLE
TestContext.BeginTimer(String) Method throws System.NotSupportedException

### ISSUE THREAD

**Issue by robdalsanto** [microsoft/testfx#504]
After looking over the TestResults schema, I was hoping to be able to make use of the named timers in some cases we implement, and hence find these values in the TRX file. But when I try the method in 1.3.2, I get a System.NotSupportedException.

So I ask, can this be added ? If not, please explain why not. It would be useful for us in unit tests. There are traces around the web that suggest it is only for load tests, which seems like an unreasonable/unnecessary limitation.

The MSDN [page](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.testtools.unittesting.testcontext.begintimer?view=mstest-net-1.3.2#Microsoft_VisualStudio_TestTools_UnitTesting_TestContext_BeginTimer_System_String_) really provides no insight into this.

**Comment by mayankbansal018** [comment]
@robdalsanto , Can you please share a small snippet of code, for us to understand what exactly you are doing

**Comment by mayankbansal018** [comment]
@robdalsanto I'll need to take a deeper look into this, so far it seems that begin timer is part of Mstest adapter, which is not extensible. It is the framework which user can extend. Also when I looked into BeginTimer code, it's just implemented for full CLR, & there too it just throws [NotImplementedException](https://github.com/Microsoft/testfx/blob/3197e7bb9f7fd4219c7855be575fb5def205aff7/src/Adapter/PlatformServices.Desktop/Services/DesktopTestContextImplementation.cs#L242).

At this point I'm not sure what exact purpose this guy serves.

Just to understand your requirement better, you would want to have a named timer, which would be an attribute that you would implement, & apply to your TestMethods, eventually hoping that what ever that attribute is supposed to do, gets logged in trx file?

**Comment by robdalsanto** [comment]
@mayankbansal018 This is not meant to be used as an attribute, but within the test, like we might use the TestContext for other things, e.g.:
` TestContext.WriteLine("my message");`

We are using the full CLR in our case.
Hopefully the code below helps illustrate what we'd like, i.e. that the TRX will include a timer with a duration of 30 ms, while the whole test duration is about 100 ms.
` 
       /// <summary>
        /// This test, if the BeginTimer/EndTime would work, would demonstrate how
        /// we would like to use the named timers so we get output in the TRX file.
        /// </summary>
        [TestMethod]
        public void BeginEndTimer_IncludeTiming_TimesRecorded()
        {
            // Arrange
            // Create the test specific data needed to exercise the function under test.
            // This might be time consuming. Simulate with a sleep.
            Thread.Sleep(60);

            // Act
            const string timerName = "function execution";
            // Bracket the function in a timer so we can separate the duration of the
            // test-method (which includes setup) from the execution-time we are interested in.
            TestContext.BeginTimer(timerName);
            Thread.Sleep(30);
            TestContext.EndTimer(timerName);

            // Assert
            // Maybe this is time consuming too.
            Thread.Sleep(10);
        }
`

**Comment by mayankbansal018** [comment]
@robdalsanto I think I get your scenario, as per current behavior the trx file will include entire `100ms` as part of test run, but what you want is to classify the timers saying that `60ms` was part of Set-up, `30ms` is part of actual execution, & remaining part of validation/asserts ?

Did I get your ask correctly? If that's the case then here the behavior change in required in both mstest adapter/framework, & the way Trx logger works.

**Comment by robdalsanto** [comment]
@mayankbansal018 Yes, that is what we're after. Note I've updated my previous comment. I can believe the TRX logger might need an update. Seems a shame that BeginTimer/EndTimer are not supported already, given they are part of the TestContext public interface.

If I were to go-to-town, I'd ask to improve BeginTimer to return an IDisposable where Dispose() calls EndTimer, but I can create that class easily enough, and that's separable from making supporting the current interface for timers.

**Comment by mayankbansal018** [comment]
@robdalsanto my initial concern was that if trx logger schema would require, then taking a fix this, would not be easy, as we have to maintain back compact, but since that is not the case(thanks for taking a look at trx logger schema, & updating us) given the current schema of trx logger, where it can already support multiple timers, I suppose we can take a fix at Mstest adapter end, where it supports named timers.

Would it be possible for you to take a shot at it?

**Comment by robdalsanto** [comment]
@mayankbansal018 I'll take a shot at this. I'd welcome any guidance &/or comments on commits as I make them.
Mostly I want to get more familiar with testfx as we've a need to extend test isolation.

**Comment by Evangelink** [comment]
Given that this API never worked and that changes of trx in TP sides are not moving forward, I will close this issue as won't fix and create a PR making the API obsolete so we can remove it on a later update.
