### ISSUE TITLE
Possible issues with fakes

### ISSUE THREAD

**Issue by avivanoff** [Microsoft/testfx#507]
We are in process in converting MSTest V1 tests to V2. We have ~20 unit test projects, one of them uses Microsoft Fakes. All projects output to the same directory. After converting to MSTest V2 none of the tests execute (either from Visual Studio not from command line via vstest.console.exe). If I delete the fakes assemblies from the output folder, then tests execute just fine.

Unfortunately, a sample project I created to reproduce the issue works fine.

How do I go about figuring out what is going on?

**Comment by avivanoff** [comment]
Actually, I was able to create a simple project to reproduce the issue.

To sum it up, if there is more than one test and method level parallelization is enabled, tests would not execute. See attached project. If you leave only one test (comment out TestMethod1 or TestMethod2 in the attached project) or disable parallelization (comment out [assembly: Parallelize(Scope = ExecutionScope.MethodLevel)]), then it works.

**Comment by vagisha-nidhi** [comment]
The sample project that you shared works just fine. Both the tests are executing with parallelization enabled as well.
```
 ------ Run test started ------
 MSTest Executor: Test Parallelization enabled for E:\CodeBase\Fakes\Bin\UnitTest1.dll (Workers: 12, Scope: MethodLevel).
 ========== Run test finished: 2 run (0:00:01.7119919) ==========
```
Is there something else needed to be done repro this?

**Comment by avivanoff** [comment]
I am not sure. I can easily reproduce this issue on any of our dev boxes.
Which version of Visual Studio are you using? What OS?

**Comment by vagisha-nidhi** [comment]
Microsoft Visual Studio Community 2017
Version 15.8.7

Which version are you on?

**Comment by avivanoff** [comment]
Microsoft Visual Studio Enterprise 2017, Version 15.8.8.

How do I collect execution logs?

**Comment by vagisha-nidhi** [comment]
Hi @avivanoff 
Please collect execution logs by running the sample project through **vstest.console** and pass --**diag:log.txt** switch and share those logs with us. 
Refer [this](https://msdn.microsoft.com/en-us/library/jj155796.aspx) for the command line options.

**Comment by avivanoff** [comment]
I do not want to share the logs publicly. They contain some sensitive information (user names, local path info). Is there another way to send them to you?

**Comment by avivanoff** [comment]
Any updates? This issue has become blocking and critical for us.

**Comment by vagisha-nidhi** [comment]
Hi @avivanoff 
Sorry for the delay, but I was able to get a repro for this. This issue has already been fixed and will be available in **TestPlatform v15.9.0**. [Here](https://github.com/Microsoft/vstest/issues/1671) is the corresponding issue tracking this, and the [fix](https://github.com/Microsoft/vstest/pull/1682/commits/15d72a1070487c7b9b47cf2b3010f2c04520c31d) for the same. You can get unblocked on this by using the latest version of TestPlatform.

**Comment by avivanoff** [comment]
Will this fix be available in the upcoming Visual Studio 2017 15.9 release?

**Comment by avivanoff** [comment]
Can I install TestPlatform v15.9.0 into Visual Studio 2017 15.8?

**Comment by vagisha-nidhi** [comment]
@avivanoff You have to update your VS to 15.9 in order to get 15.9 test platform version. The pre release versions are out and you can get them. Also, I would suggest using the tools installer task in your definition (which does not require VS to be present on your agent machine) and gets immediate updates as soon as we release test platform. 
![image](https://user-images.githubusercontent.com/13175100/47768197-fbd96d80-dcfc-11e8-8b54-3b83b0fe100f.png)

Add this task before your VsTest task and select the latest pre release as the version. Now in your VsTest task, set the Test Platform Version field as below:
![image](https://user-images.githubusercontent.com/13175100/47768252-3e02af00-dcfd-11e8-9b0e-e10e6afd7722.png)

Please let us know if this works for you.

**Comment by vagisha-nidhi** [comment]
@avivanoff You have to install the 15.9 pre release version of VS to get the 15.9 test platform. It is available [here](https://visualstudio.microsoft.com/vs/preview/). The stable release for the same will be out by mid November.
