### ISSUE TITLE
DoNotParallelize does not works when "Run Selected Tests" clicked

### ISSUE THREAD

**Issue by Sopholos** [Microsoft/testfx#508]
When I click Run All - test methods  that marked with DoNotParallelize attribute waits till other marked same are executed, but when I click "Run Selected Tests" they run in parallel.

## Steps to reproduce

1. Create few tests, make them available to run in parallel 
2. Select few marked with attribute
3. Click "Run Selected Tests"

## Expected behavior
I expect that tests will wait each other to finish

## Actual behavior
Methods run in parallel

## Environment
VS 2017
MSTest.TestAdapter 1.3.2
MSTest.TestFramework 1.3.2
.NET 4.6.1

In VS Test Explorer "Run Tests in Parallel" toggled

Also I use next test config
```
<?xml version="1.0" encoding="utf-8" ?>
<RunSettings>
  <RunConfiguration>
    <MaxCpuCount>0</MaxCpuCount>
  </RunConfiguration>

  <MSTest>
    <Parallelize>
      <Workers>0</Workers>
      <Scope>MethodLevel</Scope>
    </Parallelize>
  </MSTest>
</RunSettings>
```

**Comment by vagisha-nidhi** [comment]
Hi @Sopholos,
Test methods marked as `DoNotParallelize` attribute should not run in parallel. Can you please share a sample repro project where you faced this issue? Also, when using "Run Selected Tests", did you select all tests and checked the ones marked with the attribute are running in parallel?

**Comment by Sopholos** [comment]
Looks like bug disappeared after visual studio restart. today I could not reproduce it on same project.
