### ISSUE TITLE
Problems encountered in parallel testing

### ISSUE THREAD

**Issue by Terryxxx** [Microsoft/testfx#511]
## Description
When I tried to run two UI automation test case in parallel, I encounter problems. Only one test case can run successful and another always failed. 

Failed test case shows "Can't find some element , time out.". But if I run failed test alone, it will pass.

Can someone help solve this problem?

## Environment
MSTest V2 1.3.2
OS: Windows 10
VS: Visual Enterprise 2017 Version 15.8.7

**Comment by Terryxxx** [comment]
@pvlakshm I had reading the article. It seems only run in Parallel test with different .dll ?

**Comment by karanjitsingh** [comment]
Here's an extract from what @pvlakshm commented,

Partition tests in terms of a taxonomy as follows:
(1) “Pure Unit Tests” (can run in parallel)
(2) Functional Tests that can run in parallel with some modifications (e.g.: 2 functional tests trying to create/delete the same folder can be ‘fixed’ to remove the assumption that they have exclusive use to the folder).
***(3) Functional Tests that cannot be modified to run in parallel (e.g.: 2 Coded UI tests doing mouse actions on the desktop, 2 functional tests writing to the Bluetooth/IR port, etc.)***

You should not try to run tests in parallel unless the tests are controlling different application processes.
