### ISSUE TITLE
Test Display Name should be Extensible

### ISSUE THREAD

**Issue by ahmedalejo** [Microsoft/testfx#515]
Description
Following the extensibility initiative in MsTest V2. It would help to be able to define Display Names (i.e TestName) for tests thereby making human-readable(serves as better documentation of codebase as well) names that show up in the test explorer .

Test frameworks like xUnit this via configuration https://github.com/xunit/xunit/issues/759

**Expected behavior**

```csharp
[TestMethod("Consecutive authentication attempts with invalid credentials should fail")]
public void MyTest()
{ ... }
//or

[MyAppTestMethod]
public void Consecutive_authentication_attempts_with_invalid_credentials_should_fail()
{ ... }

//Given the following definitions
public class TestMethodAttrubte : Attribute
{
    public string DisplaName { get; set; }

    public virtual string GetDisplayName(System.Reflection.MethodInfo methodInfo) =>
        string.IsNullOrWhiteSpace(this.DisplaName) 
        ? methodInfo.Name 
        : this.DisplaName?.Trim();

   ...
}

public class MyAppsTestMethodAttrubte : TestMethodAttrubte
{
    public override string GetDisplayName(MethodInfo methodInfo) =>
        methodInfo
            .Name
            .Replace("_", " ")
            .Replace(".", ", ");
}
```
![image](https://user-images.githubusercontent.com/7012074/48248473-9cefb480-e3de-11e8-9025-664a00070f0d.png)

**Actual behavior**
The display name is "machine" readable.
![image](https://user-images.githubusercontent.com/7012074/48248171-68c7c400-e3dd-11e8-9562-146f2340f52f.png)

This proposal is also similar to #410

**Comment by karanjitsingh** [comment]
Hi @ahmedalejo, thanks for suggesting that. I've marked this as an enhancement and we'll be happy to accept any contribution.

**Comment by jadaml** [comment]
It might be me reading GitHub incorrectly, but I do not quite understand what is the decision here; are you saying that the feature request&mdash;to apply a display name altering the test case name displayed&mdash;is the same as #644 or it was just mentioned there and the decision is then ... what exactly?

**Comment by ahmedalejo** [comment]
@jadaml like metioned in #644, 

Merging #644 would complement the implementation of #515, i.e if or when it is done.

**Comment by jadaml** [comment]
So the decision is then is that you'll solve these two under the same issue, as both issues affects the display of the test, but both method of controlling the name (prettifying the method name, and overriding it with an attribute) will be available in the end?
