### ISSUE TITLE
Error not shown for DataTestMethod in TFS

### ISSUE THREAD

**Issue by LokiMidgard** [Microsoft/testfx#518]
## Description
For `DataTestMethod` with `DataRow` attributes it is not easely possible to find out why the test faild in TFS (TestResult view).

## Steps to reproduce
```c#
        [TestMethod]
        [DataRow(0)]
        [DataRow(1)]
        [DataRow(2)]
        public void Test(int i)
        {
            if (i == 1)
                throw new NotSupportedException("Only for test Purpose.");
        }
```

## Expected behavior
The TestResult view shows the reason why the test faild. Multiple reasons if more then one `DataRow` faild. Identical to when a normal test method fails.

OR

One TestResult entry per `DataRow` with its own attachments.

## Actual behavior
TestResult shows error (in version 1.3.1 it does actually show passed) but the Error section has no entry.

To get the information you need to navigate to the test run summery then download the correct trx file (I don't know how I can find out which trx file corresponds to which test result). This then will open (a new) Visual Studio instance where you need to find the correct result.

## Environment
OS Win 7 
MSTest (Framework and Adapter) `1.4.0-beta`, `1.3.2` and `1.3.1`
TFS `2018 Update 3.1`
Agent version `2.136.0`
vstest task `2.3.28`
With and without ForcedLegacyMode in `.runnsettigs` file

**Comment by divais** [comment]
We have addressed this feedback in the upcoming release of TFS 2019 and on Azure DevOps Service with hierarchical results. Can you test this with your test Azure DevOps account (if any) or TFS 2019 RC1 and share feedback

**Comment by LokiMidgard** [comment]
I tried Azure DevOps and I wasn't able to see which data Row faild:

![grafik](https://user-images.githubusercontent.com/389101/48469144-41626400-e7ee-11e8-9023-e16525021a85.png)

**Comment by divais** [comment]
You will be able to see it in Pipelines - Test tab in the build or release instance.

**Comment by LokiMidgard** [comment]
Ok,

I found it. Thank you. I think it could be easeayer to discover (especially when your looking under "Test Plans" > "Runs"). But I'm glad it will be possible to see it.
