### ISSUE TITLE
TestProperties breaking change

### ISSUE THREAD

**Issue by dotMorten** [Microsoft/testfx#520]
## Description
A change was made for several classes to no longer inherit from TestProperty in this PR: https://github.com/Microsoft/testfx/pull/482

## Steps to reproduce
This code used to compile/run:

```cs
DescriptionAttribute da = new DescriptionAttribute();
var attribute = (TestPropertyAttribute)da; //Invalid cast
var key = da.Key; //No longer exist
var value = da.Value; //No longer exist
```
Some are compile time, but 3rd party libraries that were compiled against an older version will get runtime errors.

## Expected behavior
Continued binary and code compatibility across minor updates. If this was an intended change, they should be marked deprecated, and not removed until the next major version change (ie v2.0)

## Actual behavior
Compile time or runtime errors.

**Comment by singhsarab** [comment]
@dotMorten Do you still have concerns around this one ?

**Comment by singhsarab** [comment]
@dotMorten Closing this issue for now, please let know if you have any concerns.
