### ISSUE TITLE
Add support for 'TypeConverters' in argument matching for DataRowTests

### ISSUE THREAD

**Issue by julealgon** [microsoft/testfx#521]
## Description
Currently, the argument matching between the constants specified in the `DataRow` attribute and the corresponding method parameters appears to be done using basic reflection plus direct argument passing without any processing. This ends up enforcing exact matches on types most of the time. Due to this, advanced scenarios like converting `string`s to `Type` objects or `Uri` instances for example are not supported.

Adding support for the `TypeConverter`-based system during the matching phase would allow richer scenarios without having to fallback to using `[DynamicData()]` which leads to more complex code overall.

Creating `TypeConverter` classes is a very common and widely used mechanism to allow conversions between arbitrary types, so supporting them wouldn't create coupling in the test framework to anything non-standard.

For more information on the `TypeConverter` and `TypeDescriptor` system, here is the main page:
- https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.typeconverter?view=netframework-4.7.2

Notice from the inheritance tree how much converters are used. A few very useful ones that could be leveraged for testing:

- System.UriTypeConverter
- System.ComponentModel.DateTimeConverter
- System.ComponentModel.DateTimeOffsetConverter
- System.ComponentModel.EnumConverter
- System.ComponentModel.GuidConverter
- System.ComponentModel.TimeSpanConverter

Keep in mind that to support these there is no need to create custom implementations for each one: just fetching the `TypeDescriptor` for an object generically will already ensure the default `TypeConverter` is used for that type.

## Steps to reproduce
This is what I'm proposing:
```csharp
[DataTestMethod]
[DataRow("http://www.google.com")]
[DataRow("http://www.github.com")]
public void MyTest(Uri url)
{
   ...
}
```

## Expected behavior
The strings passed in the `DataRow` attribute should be converted into the parameters in the method respecting the specified `TypeConverter` applied on the parameter type.

Because the `Uri` type already references the `UriTypeConverter` via an attribute (from [referencesource](https://referencesource.microsoft.com/#System/net/System/URI.cs.html), this would work automatically without having to specify any converter on the argument itself:
```csharp
[Serializable]
[TypeConverter(typeof(UriTypeConverter))]
public partial class Uri : ISerializable {
``` 

## Actual behavior
An exception is thrown:

> Result1 StackTrace:	
   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

## Environment
- MSTest.TestAdapter 1.2.0
- MSTest.TestFramework 1.2.0

**Comment by karanjitsingh** [comment]
Hi @julealgon, currently the `DynamicData` attribute is the only way to achieve this. This is a completely valid ask hence marking this issue as `up-for-grabs` and `enhancement`. You can raise a PR for the same and we'll be happy to take a look.

**Comment by parrainc** [comment]
Have been a while since this issue was opened, and was wondering if @julealgon or anyone else is working on it, or plan to do it? Otherwise, I can take this up, and make a PR with the proper changes.
Let me know, thanks!

**Comment by julealgon** [comment]
Sorry I missed your comment @parrainc . I have not managed to look into this one yet, unfortunately.

**Comment by parrainc** [comment]
Been a while tho;
I'll see if I manage to get some time and put some code for this.

**Comment by Evangelink** [comment]
Hi @julealgon,

I will move forward by marking this issue as `won't fix`. There wasn't much upvotes in couple of years and I don't see much value as you could simply pass the string and convert it inside of the method.

**Comment by julealgon** [comment]
> Hi @julealgon,
> 
> I will move forward by marking this issue as `won't fix`. There wasn't much upvotes in couple of years and I don't see much value as you could simply pass the string and convert it inside of the method.

Fair enough @Evangelink . I still run into this quite a bit on my tests, but I'm using xUnit now (same issue there).

You might want to leverage the new close option in github (there is a native "close won't fix" now that appears in gray (in contrast to the purple one for actually completed issues).

**Comment by Evangelink** [comment]
> You might want to leverage the new close option in github (there is a native "close won't fix" now that appears in gray (in contrast to the purple one for actually completed issues).

Thanks! I didn't pay attention there was this new option (as it's hidden - maybe because of Refined GitHub).

> Fair enough @Evangelink . I still run into this quite a bit on my tests, but I'm using xUnit now (same issue there).

Out of curiosity, what benefit do you see in being able to call a converter as some kind of attribute or property to the `DataRow` attribute vs doing the conversion your self in the "arrange" section of your test?

**Comment by julealgon** [comment]
> Out of curiosity, what benefit do you see in being able to call a converter as some kind of attribute or property to the `DataRow` attribute vs doing the conversion your self in the "arrange" section of your test?

I'm not necessarily proposing passing a converter as an attribute or property, but instead that all standard type converters be automatically considered when strings are present and the value doesn't directly match the argument type. To add new type converters (custom ones for example) you could do in a centralized manner, maybe via a static call in an assembly initialize or similar.

The overall advantage is that the test becomes much simpler to read. By being forced to directly parse values inside the test, it complicates the test logic, which we always want to keep as clean as possible. Alternatively, moving the data initialization to a `DynamicData` source, moves the data away from the method unnecessarily, also making it overall less readable.

Out of these 2, I still prefer moving the datasource into a separate (usually inner) class, but I'd rather be able to specify the values directly when possible.

**Comment by Evangelink** [comment]
> Alternatively, moving the data initialization to a `DynamicData` source, moves the data away from the method unnecessarily, also making it overall less readable.

Fully aligned with you on that. If it wouldn't be for the Test Explorer view, I would not use `DynamicData` and do a local loop. 

> but instead that all standard type converters be automatically considered when strings are present and the value doesn't directly match the argument type.

That's interesting indeed. I didn't get what you were suggesting correctly it seems. Maybe I am getting biased by my personal view but I usually don't like magic conversion and prefer to be in control of what I am doing.

If we go for such design, we should probably do the same with data coming from other sources to offer consistent behavior.

At the moment we don't get much traction from community so it's hard to do the right balance calls. I will keep this closed for the time being and will reconsider suggesting it when/if we manage to get more people contributing ideas/feelings about this tool.

Thank you so much for the valuable time and feedback @julealgon!
