### ISSUE TITLE
MSTest V2 - Data Driven Test - execution appears as 3 since it was executed for 2 browsers only

### ISSUE THREAD

**Issue by shirishnagarnz** [Microsoft/testfx#535]
## Description
> **IMPORTANT**: I have data driven test execution for 2 browsers (Chrome and Firefox). On execution, I can observe that it is getting executed for both browsers well. On completion and in execution result window, it writes 3 entries, 1st the name of TestMethod, 2nd Name of TestMethod with Data Row 0 i.e. for Chrome and 3rd as Name of TestMethod with Data Row 1 i.e. for Firefox.

Initially I was ignoring but similar result is getting displayed on CI/CD pipeline too.
>
> For a defect specific to the MSTest V2 test framework, describe the issue you've observed.

## Steps to reproduce
> I have 2 browsers in CSV file and both are getting read while execution

## Expected behavior
> I should expected only 2 entries i.e. <Name of TestMethod> Data Row 0 and <Name of TestMethod> Data Row 1>

## Actual behavior
> On completion and in execution result window, it writes 3 entries, 1st the name of TestMethod, 2nd Name of TestMethod with Data Row 0 i.e. for Chrome and 3rd as Name of TestMethod with Data Row 1 i.e. for Firefox.

![mstestiterations](https://user-images.githubusercontent.com/31267418/49622344-14405480-fa2e-11e8-92fd-22c0e8cd3f09.JPG)

## Environment
> VS2017, MSTEST1.3.2, Window10

**Comment by prawalagarwal** [comment]
@shirishnagarnz This is expected behavior today for data driven tests starting MsTest Adapter 1.3.2 and above. The first row is the parent result for the data rows and holds collevtive information for all the data rows.

**Comment by jayaranigarg** [comment]
Similar to https://github.com/Microsoft/testfx/issues/494. This change is intentional to ensure that the data driven tests work fine in different CI scenarios like distribution and rerun.

**Comment by prawalagarwal** [comment]
@shirishnagarnz can you share of screen shot of what behavior you observer? Not clear what you mean by 3 executions.

**Comment by shirishnagarnz** [comment]
@prawalagarwal , @jayaranigarg 

Below is the screenshot from TestAssemblies from Azure CI/CD pipeline execution. You can see, it says 3 Pass since TestMethod has been executed only twice i.e. for Chrome and Firefox.

![image](https://user-images.githubusercontent.com/31267418/49781236-cfdaee80-fd76-11e8-845f-c09bcf7cb8cf.png)

I expect it to show only 2 Passed instead of 3. any solution to overcome this?

Regards,
-Shirish

**Comment by jayaranigarg** [comment]
@shirishnagarnz : This is expected. Total tests show aggregation of parent and child results and there is no way to change this.

**Comment by shirishnagarnz** [comment]
Hi @jayaranigarg , @prawalagarwal 

Thanks for confirming that it is as expected but don't you think to count parent in Total count is not a right behavior.

Parent is just a name, the actual execution happen is for its Data Row 0, Data Row 1.

So for me, its not a correct behavior and even same has been mentioned by another user in #488.

Would be great if you guys to correct this or give some option to user whether to include Parent in count or not.

Regards,
-Shirish

**Comment by shirishnagarnz** [comment]
Thanks @prawalagarwal  for reply.

Little confused here :)

- What exactly you mean from  test lab?
- Do you mean Test Plans >> Runs as in below screenshot or something else? Below screenshot still shows 3 runs which includes Parent and child both.
![image](https://user-images.githubusercontent.com/31267418/49894595-3b29db00-feb3-11e8-9e96-06f234910277.png)



- We are not using console output for reply but it always requires to debug on failures.

- One more question related to console but not directly to this post. For printing logs in test assemblies, I tried Console.Write, WriteLine, System.Console.Write, Writeline, Extent logs but none of these logs are getting appended in test assemblies console output. Can you please confirm which logs are getting printed in console test assemblies output?

Regards,
-Shirish

**Comment by prawalagarwal** [comment]
@shirishnagarnz Can we have a quick skype call? I am available till 7PM IST today.

**Comment by shirishnagarnz** [comment]
Sure, can I have your Skype details?

I might take 3-4 hrs. Will ling you before I call.

Thanks,
Regards,
Shirish
+64221877642

**Comment by shirishnagarnz** [comment]
Hi @prawalagarwal ,

Can you please share your skype details?

**Comment by prawalagarwal** [comment]
Let's use jisi:

To join the video meeting, click this link: https://meet.jit.si/ShirishMeeting
To join by phone, dial +1.512.402.2718 and enter this PIN: 3391499888#

**Comment by prawalagarwal** [comment]
@nigurr this is closed offline. We advised Shirish to use Platform Installer task to get the correct reporting. Closing.

**Comment by shirishnagarnz** [comment]
Hi Everyone,

yes I have been advised with required solution and its working as demoed by @prawalagarwal .

Regards,
-Shirish

**Comment by shirishnagarnz** [comment]
Hi @prawalagarwal ,

not re-opening this ticket but have 1 question from the same.

instead of data row 0, data row 1, is it possible to display its value. I am using this DataDriven test for browser.

Like Login Data Row 0 is Login - Chrome and Firefox for Data Row 1.

So referring to below screenshot, is it possible to display like Login - Chrome, Login Firefox

![image](https://user-images.githubusercontent.com/31267418/50118362-4bc3c200-02b4-11e9-9f54-6013e6e48c86.png)

Regards,
-Shirish

**Comment by nigurr** [comment]
@shirishnagarnz, currently this functionality doesnt exist

**Comment by shirishnagarnz** [comment]
Thanks @nigurr for the reply.

Any plans to implement this functionality?

Regards,
-Shirish

**Comment by jayaranigarg** [comment]
@shirishnagarnz :

**Comment by shirishnagarnz** [comment]
Thanks @jayaranigarg 

Tried as seen in below snapshot but didn't achieved the require result, neither in console not in azure devops

![image](https://user-images.githubusercontent.com/31267418/50189450-1a1d2a80-038a-11e9-8168-e32b72536ff4.png)

Is I am doing it wrong?

Regards,
-Shirish

**Comment by prawalagarwal** [comment]
@shirishnagarnz 

DataSource attribute does not support DisplayName. The code snippet which Jaya provided was one of the ways of writing a data driven test (using DataRow attribute). You don't have to copy that as you are already using DataSource. In case display names are important for you, we suggest to move to dynamic data tests (as explained in this [blog](https://www.meziantou.net/2018/02/05/mstest-v2-data-tests). DynamicData attributes support display names.
