### ISSUE TITLE
Custom TestMethodAttribute breaks TestInitialize

### ISSUE THREAD

**Issue by wasabii** [Microsoft/testfx#542]
Looks like when I use a custom `TestMethodAttribute` that the original `TestInitializeAttribute` no longer functions. Even if all my custom one does is call `base.Execute`. Is this intended? If so, how do I ... not do that?

**Comment by abhishkk** [comment]
@wasabii 
Can you elaborate the issue? In addition, can you share a sample repro project with us?

**Comment by abhishkk** [comment]
@wasabii Any updates here?

**Comment by wasabii** [comment]
Can't seem to reproduce it. Will open if I can.
