### ISSUE TITLE
Dynamically control test time (including initialize/cleanup) and have more granular timeouts. 

### ISSUE THREAD

**Issue by johnmog** [microsoft/testfx#543]
## Description
For years my team has needed more flexibility with test timeouts. There are several characteristics of the problem:

Test time expectation variance: If you lazily initialize test requirements for functional tests, any test may be the one that needs to initialize. For example, imagine you are creating a test database and the first test that needs that kind of database pays the price for creating it. Based on this test A may take 6m if it is the first one to run and 10s if not.  Marking all tests at 6 minutes to account for this problem almost makes test timeouts useless.

Test portion time expectation variance: We may have a test that is expected to take 6 minutes at max, but there is a portion of the test where we attempt to do an operation that should only take 30 seconds. If it takes any longer, something is wrong and we want to fail the test. However, there is no way to do this. In fact, this portion could take 5 minutes, and then we will pass or timeout much later in the test hiding the major regression.

## Expected behavior
How we've solved this internally is to:

1. Force everyone to use a standard base class
2. Disallow use of the TimeoutAttribute
3. Create a new DynamicTimoutAttribute which serves the same purpose but is controlled by us.
4. Create a new concept called a TimeoutScope which has the following properties:
- When a timeout scope is created you pass a name and timeout value. We log that a new timeout scope has started.
- We create one of these when the test starts using the timeout from the DyanmicTimeoutAttribute or a default value if the attribute was not provided.
- When a timeout scope is active, it keeps track of time against the timeout and if we hit the timeout, the scope causes the test to fail.
- When a new timeout scope is created, if one is already active, it will pause it. Thus you only have one active scope. Pausing of a timeout scope is logged.
- When a timeout scope is disposed, it unpauses the last timeout scope that was added.
5. In our base class we wrap scopes around test init and test cleanup.
6. We also assert that there are no active scopes when the test ends.

This enabled patterns like this:
public void TestMethod()
{
    // Assume a timeout scope is already running for the main test method and is set to 30 seconds

    // This call may be trivially fast, or take a long time depending on whether it is set up already
    EnsureDatabaseExists();

    // … the rest of the test
}

public void EnsureDatabaseExists()
{
    // We want to pause the test's timer but only give this call 30 seconds to succeed.
    using (new TimeoutScope(nameof(EnsureDatabaseExists), TimeSpan.FromSeconds(30))
    {
        var creds = GetDatabaseCredentials();
       // … Ensure Database Exists
    }
}

public Credential GetDatabaseCredentials()
{
    // When this method is called, we were inside of the EnsureDatabaseExists timeout scope
    // But since we're starting a new one, we'll pause that until this one finishes.
    using (new TimeoutScope(nameof(GetDatabaseCredentials), TimeSpan.FromSeconds(60))
    {
        // Here we will call out to our secret store which can take some time if it is having issues.
        // However, if it takes longer than 60 seconds, we want to fail the test to raise visibility
    }
}

**Comment by abhishkk** [comment]
@johnmogensen Correct. TestInitialize time is part of test timeout and thus forces user to increase timeout for individual test. Thanks for the suggestions for the issue.
@PBoraMSFT Marking as enhancement.
