### ISSUE TITLE
French resources in Italian

### ISSUE THREAD

**Issue by mikelapierre** [Microsoft/testfx#549]
## Description
>The following French resource file contains Italian translations:
https://github.com/Microsoft/testfx/blob/master/src/Adapter/PlatformServices.Desktop/Resources/xlf/Resource.fr.xlf.
>Translations are the same as the Italian resource file:
https://github.com/Microsoft/testfx/blob/master/src/Adapter/PlatformServices.Desktop/Resources/xlf/Resource.it.xlf

## Steps to reproduce
>Run tests generating messages in a French environment.

## Expected behavior
>The messages should be in French.

## Actual behavior
>The messages are in Italian.

**Comment by vagisha-nidhi** [comment]
@v-zbsail Can you please look at this?

**Comment by janbaltus** [comment]
Fixed the #549 issue and updated PR
