### ISSUE TITLE
Test assemblies (containers) are not isolatedd from each other

### ISSUE THREAD

**Issue by Daniel-Svensson** [microsoft/testfx#552]
## Description
I've update a solution from mstest v1 to mstest v2 (1.4.0) only to get problem with a couple of tests which get problem with assembly loading. All tests run and pass if they are executed one project at a time but two of the projects (OpenRiaServices.DomainsServices.Tools*.Tests) get problem with conflicting assemblies if they are run at the same time as the "*.Client.Test" assembly.

Is there a way for the differet test assemblies/containers to execute so that they do not affect each other (so that assemblies loaded for one test container do not affect other test containers)? (I have tried the Isolated setting without succes).
 
This can be reproduced both when running vstest.console aswell as from within visual studio.

Source (with azure-pipelines.yml) is availible at https://github.com/Daniel-Svensson/OpenRiaServices/tree/feature/mstest2

I recommend using VS 2015 and RiaServices.sln (follow step in azure-pipelines yml)

Test log is availible here:
https://svensson-daniel.visualstudio.com/OpenRiaServices/_build/results?buildId=230&view=ms.vss-test-web.test-result-details

## Steps to reproduce

1. Setup azure pipeline with yml support againsts https://github.com/Daniel-Svensson/OpenRiaServices
2. Build the feature/mstest2 branch

or.

1. build RiaServices.sln using VS2015
2. run setup-testdatabases.ps1
3. Start "website full trust" project without debugging
4. Run all tests (client and tooling projects are enough)

## Expected behavior

I expect test to pass (different test containers should not affect each other), they should execute in different appdomains (or processes)

## Actual behavior

Test fails with message:

```System.IO.FileLoadException: API restriction: The assembly 'file:///D:\a\1\s\OpenRiaServices.DomainServices.Client\Test\Desktop\bin\Release\OpenRiaServices.DomainServices.Client.dll' has already loaded from a different location. It cannot be loaded from a new location within the same appdomain.```

## Environment

azure pipelines hosted build pool
.
> Operating system, Build version of vstest.console, 
vs 2015 with all updates (similar behaviour with vstest 15.x)

Package version of MSTest framework and adapter: 1.4.0

**Comment by Daniel-Svensson** [comment]
Unfortenatly vstest 15 (and 15.9) introduce a bunch of other issues. You find a build with logs over at https://svensson-daniel.visualstudio.com/OpenRiaServices/_build/results?buildId=255&_a=summary&view=logs.

I believe several of the issues are related to vstest 15 but I have not had the time yet to open an issue over there.

**Comment by Daniel-Svensson** [comment]
@singhsarab i have tried both parallel and the in isolation setting in different combinations but no change in behaviour

**Comment by singhsarab** [comment]
@Daniel-Svensson Can you share the logs for when parallel is enabled (passing /parallel as argument or setting MaxCPUCount in the runsettings) ?

**Comment by Daniel-Svensson** [comment]
Logs with parallel on https://svensson-daniel.visualstudio.com/OpenRiaServices/_build/results?buildId=279&view=logs

**Comment by Daniel-Svensson** [comment]
New build queued  with debug true @singhsarab , https://svensson-daniel.visualstudio.com/OpenRiaServices/_build/results?buildId=286&view=logs

**Comment by singhsarab** [comment]
@Daniel-Svensson If you look at the logs, I see there were multiple testhosts that were created for the run, one for each dll under test.
I don't understand your test code, is it possible for you to give us a simpler repro ?

**Comment by Daniel-Svensson** [comment]
@singhsarab after upgrading the solution to VS2017 it is much easier to troubleshoot, I have also added some printing to console/debug which can be helpful.

I believe it is so since some more assemblies are copied to test output directory than before (not verified).
However the same kind of exception (for another assembly) happens _without having to run 2 different testcontainers at the same time_.

I believe this might have something to do with mstest2 loading *some assemblies* from bin\debug\net461 folder but still copies those to the test output folder (where *other assemblies* are loaded from). When running code in master all? (at least the relevant) assemblies are loaded from the test output directory.

new Simpler repro steps:
* clone repository
* checkout feature/mstest2 branch
* Open RiaServices.sln (with VS 2017)
* Run/Debug test _T4CodeGenBasicTest2_ (in Tools.TextTemplates.Test project) 
  (The test project will be listed at the bottom with 12 tests)
just checkout the branch

Summary of what the code does and my guess of the cause

1. It generates some code (using 2 different methods) and for each of those it compiles 
an an in memory assembly using roslyn. When generating the assembly "OpenRiaServices.Common.DomainServices.Test" is provided as a reference.
_typeof(TypeInAssembly).Assembly.ManifestModule.FullyQualifiedName_ is to get the path to the assenbly from the tests point of view. *This returns path to bin directory*
2. Assemblies are "ReflectionOnly" loaded using path (same as above)
3. Type information from both assemblies are compared
* When getting attribute data for property "TestDomainServices.A.RequiredString" it needs to create an instance of the attribute and need to fully load the assembly.
My guess is that the runtime tries to load it from the TestResult folder (since that is the assembly loading path) which fails.

My current guess is that the same scenario was triggered for the previous build using VS2015, but for another assembly which probably was only copied to TestResult folder by some test but nut for other.


The exact same test (and thoose in the other "Tools" project) works perfectly fine when running in master branch, (using mstest1). In that case assemblies seems to not be loaded from bin folder but from TestResult folder


**What I don't get** is that assembly location information for the referenced (maybe not yet loaded) assembly shows the path to the bin directory but still later looks like it tries to load it from another directory.

At the moment I cannot produce a simpler repo, and I am unsure when I would be able to do so, since I currently don't have much spare time.

The project is the open source fork based on the WCF Ria Services source code provided by microsoft. If you have access to the original code maybe you can easily locate somebody who did work at the unit tests if you need better insights.

**Comment by Daniel-Svensson** [comment]
@singhsarab Any thoughts on the strange dll path behaviour? Is there some way to get the same loading behaviour as in mstest1?

**Comment by Daniel-Svensson** [comment]
@singhsarab Any update on this?

**Comment by jayaranigarg** [comment]
@Daniel-Svensson : 
>What I don't get is that assembly location information for the referenced (maybe not yet loaded) assembly shows the path to the bin directory but still later looks like it tries to load it from another directory.

This looks like some CLR bug to me. I have seen instances in the past where the location that is being shown and the location that actually gets used to load assemblies do not match.  These appdomains can be really tricky to deal with sometimes.
Owing to the confusing nature of appdomains and assembly loading, all of this stuffed has been dropped .net core world. I would encourage you to move away from app-domains soon.

For now, can you pass runsettings to your tests with below configuration:
```
<RunSettings>
    <RunConfiguration>
        <DisableAppDomain>False</DisableAppDomain>
    </RunConfiguration>
</RunSettings>
```
or by CLI switch 
```
vstest.console --settings:test.runsettings -- RunConfiguration.DisableAppDomain=true
```
and see if that helps?

**Comment by Daniel-Svensson** [comment]
Thanks for the suggestion @jayaranigarg but no luck.
I dont belive this is a CLR bug, it seems more probable that this has something to do with how the mstest adapter loads the assemblies. Probably from the "wrong" path (from my perspective).

I've  tried to set DisableAppDomain both to [False](https://svensson-daniel.visualstudio.com/OpenRiaServices/_build/results?buildId=301&view=ms.vss-test-web.build-test-results-tab) as suggested  and to [True](https://svensson-daniel.visualstudio.com/OpenRiaServices/_build/results?buildId=304&view=ms.vss-test-web.build-test-results-tab) with many more failed test if I change the setting to true.

**Comment by ShreyasRmsft** [comment]
@Daniel-Svensson does this repro when using a private agent? If so let me know what setup I need to perform on my local machine to use it as private agent to run these tests so that I can attach a debugger and check where the assembly load is happening from and why.

It would be super helpful if you could do this as it will take me some time to get the setup ready etc. The source code is available here and all you'll have to do is build and replace the bits locally.

**Comment by Daniel-Svensson** [comment]
@ShreyasRmsft you can repro it from within Visual Studio using the Test Explorer.

Steps to repro:
* ensure that you have [silverlight 5 sdk](https://download.microsoft.com/download/3/A/3/3A35179D-5C87-4D0A-91EB-BF5FEDC601A4/sdk/silverlight_sdk.exe) installed or you will build errors for some projects
 *  See https://github.com/OpenRIAServices/OpenRiaServices/wiki/Getting-Started for a list of components which needs to be selected in the Visual Studio installation
* run setup-testdatabases.ps1
* build RiaServices.sln using VS2017 or VS2019
* Start "website full trust" project without debugging
* Run all tests (client and tooling projects are enough)

**Comment by ShreyasRmsft** [comment]
@Daniel-Svensson it'll take some to get this up, meanwhile if you run tests from a single assemble at a time do you still face this problem?

**Comment by ShreyasRmsft** [comment]
Also is it possible to repro this in insolation of your webapp, with a simple skeleton repro that just loads the same dlls but has not code? So that we can isolate the issue as much as possible...

**Comment by Daniel-Svensson** [comment]
> @Daniel-Svensson it'll take me some time to get this set up, meanwhile if you run tests from a single assemble at a time do you still face this problem?

@ShreyasRmsft All tests run and pass if they are executed one assembly/project at a tim.
Two of the projects (OpenRiaServices.DomainsServices.Tools*.Tests) get problem with conflicting assemblies if they are run at the same time as the "*.Client.Test" assembly.

So to repro start test "Client" test at the same time as one of the "Tools" test projects.

> Also is it possible to repro this in insolation of your webapp, with a simple skeleton repro that just loads the same dlls but has not code? So that we can isolate the issue as much as possible…

The error is very specific to running tests (and only with mstest v2) so is not applicable to an actual application

**Comment by ShreyasRmsft** [comment]
Not actual application, I meant a unit test that just references these dlls. No code inside the test other than the test project referencing these dlls that are running into conflicts

**Comment by ShreyasRmsft** [comment]
@Daniel-Svensson any updates on the simplified repro? If this is indeed any issue we should be able repro it with a basic set of units tests that depend on some common dll.

**Comment by Daniel-Svensson** [comment]
@ShreyasRmsft it seems like I am running into a new (related?) issue now that have updated to mstest2 code to the latest master and use VS2017.

I've created a small repro of it at link below. 
Just uncomment DeploymentItem and all tests will pass.

The issue is triggered when "TestResults" folder is used


https://gist.github.com/Daniel-Svensson/4a52116251c30d177bb4bb4c7a99cc7a

**Comment by ShreyasRmsft** [comment]
@Daniel-Svensson we'll take a look.

**Comment by ShreyasRmsft** [comment]
@Daniel-Svensson 	

WorkingIfFiailingDoesNotRun

This fails even if i run it alone. Is that supposed to happen?

**Comment by ShreyasRmsft** [comment]
running this statement i get this

assembly.GetExportedTypes().Where(t => typeof(ICloneable).IsInstanceOfType(t)).ToList();

Count = 2
    [0]: {Name = "Class1" FullName = "ClassLibrary1.Test.Class1"}
    [1]: {Name = "UnitTest1" FullName = "ClassLibrary1.Test.UnitTest1"}

**Comment by ShreyasRmsft** [comment]
And your assert             
Assert.AreEqual(1, class1.Count, "Should find 1 matching type");
fails

**Comment by ShreyasRmsft** [comment]
And either way i'm not getting any assembly load exceptions

**Comment by Daniel-Svensson** [comment]
> running this statement i get this
> 
> assembly.GetExportedTypes().Where(t => typeof(ICloneable).IsInstanceOfType(t)).ToList();
> 
> Count = 2
> [0]: {Name = "Class1" FullName = "ClassLibrary1.Test.Class1"}
> [1]: {Name = "UnitTest1" FullName = "ClassLibrary1.Test.UnitTest1"}

Sorry. The code had a where clause with *t.Name == "Class1"* , it should only find the class. 
I did the mistake of a late change in the code, the where clause should also have checked icomparable

**Comment by Daniel-Svensson** [comment]
This specific scenario do not get type load failures, instead it seems to load two different instances of the same assembly where "Coass1"is not equal to "Class1". Solving this without modifying the code might solve the original problem

**Comment by ShreyasRmsft** [comment]
@Daniel-Svensson i'm confused.

**Comment by ShreyasRmsft** [comment]
@Daniel-Svensson could you please create a new github repo with the barest minimal repro (csproj and all, with the appropriate version of mstest etc., along with probably a cmd script to run the test so that nothing is different when i attempt to run it?). The moment you bring in your application or lots of test code the more complicated the situation gets.

**Comment by Daniel-Svensson** [comment]
Try https://github.com/Daniel-Svensson/mstestrepo I set it up on mobile but 98% sure it will work.it currently use mstest v1 so it passes. Install mstest 1.4.0 framework and adapter to repro.

**Comment by Daniel-Svensson** [comment]
@ShreyasRmsft 

There is now a repro in https://github.com/Daniel-Svensson/MsTestRepro for my "other" bug which currently prevents me from producing a repro of my original issue.
I will try to extract this to a separate issue.

Open the sln file in VS2017 (15.9) build and run all tests from within test explorer.


Actual behaviour:
* The tests fails
* if you only run the test without [DeploymentItem] it will succeed

Expected behaviour
* The tests should pass

Observations:
* The assembly load seems to be loading assemblies from the wrong assembly path (from bin directory instead of the TestResult/Out directory, so I suspect it is related to the testadapter code)
* This seems to be working if you use VS 2019 (and probably also for VS 2015) (I haven't tried the actual repro project in either of them but the original code seems to work)
* It should work with mstestv1
* Running tests from azure pipelines also triggers the issue so it is not VS specific

**Comment by ShreyasRmsft** [comment]
@Daniel-Svensson I got the behavior you are describing but since both the tests are in the same project/dll they will not be isolated from each other. They will both run in the same appdomain if appdomain is not disabled.

**Comment by ShreyasRmsft** [comment]
And if you run with the deployment item then the TestResults\Out folder is used as additional dependencies need to be copied to a temp location before running the tests.

**Comment by ShreyasRmsft** [comment]
But I get your issue that when you are try to load the assembly using Assembly.Load it is picking it up from the bin directory and not the testresults\out directory

**Comment by ShreyasRmsft** [comment]
And thank you for simplifying the repro this helped a lot.

**Comment by Daniel-Svensson** [comment]
Thanks @ShreyasRmsft for having a look

* I did notice that this issue does not happen when running from within VS2019 (but it happens when using vstest console when running azure pipelines etc). 

Since most of this thread is now about this other issue I am considering changing the name and opening a new issue for the original once the issue is solved if the original issue persists, any thoughts about that? 
If this does not fix the original issue I suspect looking into https://github.com/microsoft/testfx/issues/57 might help

**Comment by mack0196** [comment]
I have a solution that now has multiple MSTest projects and I am getting failures because they have different assembly version dependencies. When project1 assembly dependencies are copied after project2's assembly dependencies, some of project2 tests fail.

What is the guidance to work around the behavior for deployment of all test projects into a single TestResults out directory?

**Comment by ShreyasRmsft** [comment]
@mack0196 add this to your runsettings file to stop deployment and run the tests from their respective bin folders

```
  <MSTest
    <DeploymentEnabled>False</DeploymentEnabled>
  </MSTest>
```

**Comment by mack0196** [comment]
I have tried setting DeploymentEndabled to false in the runsettings file, but my tests still ran in a TestResults folder.

I do have DeploymentItem attributes in my test code.

I am trying to get this no-deployment or individual testresults-per-test-project working in Azure DevOps with this Exectute Unit Tests VSTests step.

![image](https://user-images.githubusercontent.com/6463105/62625461-db24f080-b8ea-11e9-98fb-fb7d892cbf96.png)

**Comment by ShreyasRmsft** [comment]
@mack0196 I would recommend moving away from deployment items as there is a fundamental flaw with the system as it does not take care of conflicting dependencies. 

I would advise you to add whatever dependencies you need to the csproj itself.

**Comment by kaadhina** [comment]
Please re-open if the above does not help

**Comment by Daniel-Svensson** [comment]
@kaadhina 
 Can you at least document that DeploymentItems and using Deployment directories are not supported and will not work for many scenarios where mstest v1 works.
Maybe you should also mark it as obsolete.

The code base with tests are a quite large one inherited from microsoft (formerly WCF RIA Services) and I do not have the time to remove them all.

The only current valid workaround is to drop all thoughts about mstestv2 and continue to use v1
