### ISSUE TITLE
In-assembly parallel tests (IAP) issues with Thread Ripper processors

### ISSUE THREAD

**Issue by singhsarab** [microsoft/testfx#562]
## Description
The problem
In-assembly parallel tests don’t scale on latest ThreadReaper processors and fail to utilize >10% of CPU. So basically, this feature has no to little effect on some modern CPU configurations. 

I faced this problem on my home built 2950x CPU with 16 cores and 32 threads due to recent weather, which required me to work from home. 

Generally, the problem is broader than just IAP and I can replicate/mitigate it in other .NET apps, but can’t mitigate for IAP tests feature.

Example in C# in a typical app
var result = inputs.AsParallel().Select(HeavyComputationsAndAllocationsFunc);

This will fail to utilize available cores and CPU usage will be ~10% for 2950x processor. If you debug an app you’ll see that lots of threads are being spawned, they just fail to actually do the job efficiently and utilize available cores. 

## Workaround
Making this change in app.config for a .NET app will fix the issue:
https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/thread-useallcpugroups-element 

```
<configuration>  
   <runtime>  
      <Thread_UseAllCpuGroups enabled="true"/>  
      <GCCpuGroup enabled="true"/>  
      <gcServer enabled="true"/>  
   </runtime>  
</configuration>  
```
## Explanation
Apparently, .NET fails to utilize available cores efficiently for the newest ThreadRipper processors by default, you have to specify Thread_UseAllCpuGroups  explicitly, and this requires to switch to gcServer behavior for Garbage Collector.

When I run the same application with this change I get up to 100% CPU utilization and without this change it is ~10%. I can consistently reproduce these results.

This could be a bug in .NET GC, but at least for apps I have a workaround.

**Comment by HeroMaxPower** [comment]
I'm thinking of buying a threadripper for 'testing' purposes, Thanks for this information that its not working properly.
