### ISSUE TITLE
Tests failing due to custom TimeSpan JsonConverter

### ISSUE THREAD

**Issue by tucanus** [Microsoft/testfx#566]
## Description
If I register globally a Newtonsoft.Json.JsonConverter<TimeSpan>, every test fails after execution with error message similar to `Error converting value "PT1.0311192S" to type 'System.TimeSpan'. Path 'TestRunCompleteArgs.ElapsedTimeInRunningTests'`

## Steps to reproduce
- Create a Net Core MsTest project, 
- add nuget Newtonsoft.Json package 
- remove default class (UnitTest1)
- add a TimeSpanNewtonsoftConverterTest class
- substitute code with code provided below (due to buggy code formatting, please pay attention to select test from === Source code start === to === Source code end ===)
- execute test

***=== Source code start ===***
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Text;
using System.Xml;

namespace testUnitTest
{
    public class TimeSpanNewtonsoftConverter : JsonConverter<TimeSpan>
    {

        public override TimeSpan ReadJson(JsonReader reader, Type objectType, TimeSpan existingValue, bool hasExistingValue, JsonSerializer serializer)
        {
            switch (reader.TokenType)
            {
                case JsonToken.String:
                    return XmlConvert.ToTimeSpan((string)reader.Value);
                default:
                    throw new NotImplementedException($"Cannot convert {reader.TokenType} to TimeSpan");
            }
        }

        public override void WriteJson(JsonWriter writer, TimeSpan value, JsonSerializer serializer)
        {
            writer.WriteRawValue($"\"{XmlConvert.ToString(value)}\"");

        }
    }

    [TestClass]
    public class TimeSpanNewtonsoftConverterTest
    {
        [TestInitialize]
        public void initializeJsonConvertDefautSettings()
        {
            JsonConvert.DefaultSettings = () => new JsonSerializerSettings()
            {
                Converters = new List<JsonConverter>() { new TimeSpanNewtonsoftConverter() }
            };
        }

        [TestMethod]
        public void testSerialization()
        {
            TimeSpan ts = TimeSpan.Zero;
            var json = JsonConvert.SerializeObject(ts);
            var output = JsonConvert.DeserializeObject<TimeSpan>(json);
            Assert.AreEqual(ts, output);
        }

    }
}
***=== Source code end ===***

## Expected behavior
[08/02/2019 10:38:40 Informational] ------ Esecuzione test avviata ------
[08/02/2019 10:38:41 Informational] ========== Esecuzione test completata: 1 esecuzione (0:00:00,6044291) ==========
## Actual behavior
[08/02/2019 10:39:45 Informational] ------ Esecuzione test avviata ------
[08/02/2019 10:39:46 Error] L'esecuzione dei test attivi è stata interrotta. Motivo: Error converting value "PT0.08165S" to type 'System.TimeSpan'. Path 'TestRunCompleteArgs.ElapsedTimeInRunningTests'.
[08/02/2019 10:39:46 Informational] ========== Esecuzione test completata: 0 esecuzione (0:00:00,5894198) ==========

## Environment
OS Windows 8.1, vstest.console 15.9.0, MSTest 1.3.2 (both framework and adapter)

**Comment by nigurr** [comment]
@tucanus 
Thanks for reaching us out and reporting this issue.
Currently this is known issue and we currently use "Newton Json 9" version and if you are using any higher version, it might break.
We suggest you to add `config` file for assembly redirection for your test assembly to mitigate this issue.

We are already working towards isolating Newton Json dependency, however we don't have tentative timelines for the same.
