### ISSUE TITLE
What is the purpose of the `Assert.IsTrue` and `Assert.IsNull` methods?

### ISSUE THREAD

**Issue by walterlv** [Microsoft/testfx#567]
## Description

We have these methods with the same meaning:

```csharp
// null
Assert.AreEqual(null, foo);
Assert.IsNull(foo);

// true
Assert.AreEqual(true, foo);
Assert.IsTrue(foo);
```

So what is the purpose of the two concrete methods in the case that we have an `Assert.AreEqual` for replacement.

## Why I want to ask this question here?

My team writes unit tests using MSTest v1.4, but we can't determine to use which one for team conventions.

**Comment by nigurr** [comment]
@walterlv it's flexibility and simplicity. Please choose whatever you prefer and both achieves the same.
