### ISSUE TITLE
Run test with COM references throws System.Runtime.InteropServices.COMException

### ISSUE THREAD

**Issue by KexyBiscuit** [Microsoft/testfx#568]
## Description

Run test with COM references throws System.Runtime.InteropServices.COMException.

## Steps to reproduce

1. Add a COM reference to the test project, whose tfm is `net48`.
2. Create an instance of a COM object.

## Expected behavior

It succeeds.

## Actual behavior

```
System.Runtime.InteropServices.COMException
  HResult=0x80040154
  Message=Retrieving the COM class factory for component with CLSID (omitted) failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).
  Source=mscorlib
  StackTrace:
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   (further stack trace is omitted)
```

## Environment

```xml
<PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.0.0-preview-20190203-03" />
<PackageReference Include="MSTest.TestAdapter" Version="2.0.0-beta2" />
<PackageReference Include="MSTest.TestFramework" Version="2.0.0-beta2" />
```

```
Microsoft Windows [Version 10.0.18334.1]
```

**Comment by acesiddhu** [comment]
@KexyBiscuit can you confirm that when you the same code on same machine with a console app things work fine. The error code generally means that the com component is not registered for that process arch from where you r running the test code. Few things to check
1) Repro the same issue with console app. 
2) If COM component is x64 then ensure test are running in x64 mode.
3) try to register the com component via regsvr.exe and try again

**Comment by KexyBiscuit** [comment]
@acesiddhu [Running the unit test as a 64-bit process](https://docs.microsoft.com/en-us/visualstudio/test/run-a-unit-test-as-a-64-bit-process) resolved the problem, thanks a lot.
