### ISSUE TITLE
Allow to add properties to TestContext from TestMethodAttribute

### ISSUE THREAD

**Issue by luis-cortina** [Microsoft/testfx#569]
While creating my custom test method attribute, I want set some data in the TestContext so it can be available for the test to behave depending on its value. I don't want to use DataRows or data source related approach because I want it to work in parallel.

Simple scenario:

```
[AttributeUsage(AttributeTargets.Method, AllowMultiple = false)]
public class IterativeTestMethodAttribute : TestMethodAttribute
{
    private int stabilityThreshold;

    public IterativeTestMethodAttribute(int stabilityThreshold)
    {
        this.stabilityThreshold = stabilityThreshold;
    }

    public override TestResult[] Execute(ITestMethod testMethod) 
    {
        var results = new List<TestResult>();
        for(int count = 0; count < this.stabilityThreshold; count++)
        {
            testMethod.TestContext["iteration"]=count; //I will read this value in the test and do something 
            var currentResults = base.Execute(testMethod);
            results.AddRange(currentResults);
        }

        return results.ToArray();
    }
}
```

**Comment by jayaranigarg** [comment]
@luis-cortina :
Few things -
1. Test Context is a readonly object and no framework allows users to edit/add values in testcontext.
2. Can you please explain how do you plan to achieve parallelism by using TestContext properties? Since multiple tests will be running in parallel,  some tests will be editing this property and some will be reading this property. How do plan to manage these race conditions?
3. Wondering if the use of static variables can help to get the things done?

**Comment by luis-cortina** [comment]
@jayaranigarg answers below:

1. I meant adding a new property inside the Properties dictionary of the test context. I believe this is allowed, correct?
2. This is a custom test method info that will not be allowed to run in parallel
3. I think the TestInitialize method has a ref of the test context so that might help me. I guess I can go that route.

**Comment by jayaranigarg** [comment]
@luis-cortina : No, adding/editing any property in the Properties dictionary is not allowed. User cannot edit testContext object in any way.

**Comment by jayaranigarg** [comment]
Closing the thread as we will not allow any modifications to TestContext Object.
