### ISSUE TITLE
Deployment directories should be at a per source level.

### ISSUE THREAD

**Issue by AbhitejJohn** [microsoft/testfx#57]
## Description
Separate Deployment directories should be created for each source that requires deployment item

## Steps to reproduce
1. Create two C# UnitTest Projects.
2. Add Deployment Item in only one of the projects and not in second one.
3. Build the solution.
4. Put breakpoints in both the tests.
5. Select both the tests in Test Explorer and do debug selected tests.

## Expected behavior
Only one test dll having [DeploymentItem] attribute should have been copied to Deployment Directories(i.e. UnitTestProject76) and other one should have run from UnitTestProject1/bin/debug and should not get copied to Deployment Directory.

## Actual behavior
Both the test dlls gets copied in the Deployment Directories that are created.

This actually changes the behavior of tests when run on their own versus when run with other test assemblies that have deployment items causing confusion.

**Comment by Evangelink** [comment]
Because this bug is open for years now and based on similar fix we did for v3, I don't know if we should fix this or not because people are now relying on this behavior.

**Comment by Evangelink** [comment]
Moving forward by closing this ticket. Let's see if we get some requests in the future.
