### ISSUE TITLE
ITestDataSource.GetDisplayName to append to the testresult display

### ISSUE THREAD

**Issue by luis-cortina** [Microsoft/testfx#570]
Hi:

I have a Custom TestDataSource and a CustomTestMethodAttribute and I want to concatenate the title in my ITestDataSource.GetDisplayName method with my TestResult DisplayName. Currently is one or the other. Any suggestions on how to achieve this?

**Comment by jayaranigarg** [comment]
You will have to do that concatenation inside your ITestDataSource.GetDisplayName() implementation itself.

**Comment by luis-cortina** [comment]
I guess the question is inside my ITestDataSource.GetDisplayName() implementation (which is the last one called and the current behaviour is to override the test resultt display name) how do I get the display name I set in the test result. This is the definition of GetDisplayName()

 `string ITestDataSource.GetDisplayName(MethodInfo methodInfo, object[] data)`

I don't see from there how to get the DisplayName and do the concat.
Makes sense?

**Comment by jayaranigarg** [comment]
@luis-cortina : 
 `string ITestDataSource.GetDisplayName(MethodInfo methodInfo, object[] data)`
You can do a methodInfo.Name inside your getDisplayName() to get the testMethod name.

Please refer this implementation of DynamicDataAttribute which implements ITestDataSource. I believe you are trying to achieve something similar. https://github.com/Microsoft/testfx/blob/master/src/TestFramework/MSTest.Core/Attributes/DynamicDataAttribute.cs#L176

**Comment by jayaranigarg** [comment]
Closing the thread. Let us know if you need further assistance on this.
