### ISSUE TITLE
Request for StackTraceHelper.TypeToBeExcluded to allow for custom namespaces

### ISSUE THREAD

**Issue by daryllabar** [microsoft/testfx#573]
This is in response to #564.  Basically the ability to add extension methods to the Assert class is a great first step, but the debugging experience is extremely poor in that normally, one's own extension method shows up as the lowest level in the stack trace of the failed unit test.  The work around listed is to put your own extension methods in one of the namespaces hard-coded in the `Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.StackTraceHelper.TypeToBeExcluded` ([as seen here](https://github.com/Microsoft/testfx/blob/b231cade5faa80a53d367a109251b04a954e78ab/src/Adapter/MSTest.CoreAdapter/Execution/StackTraceHelper.cs#L36)).  This issue is a request for making this list configurable, possibly by one of the ways listed below:

1. Reading from a defined value in the app.config
2. Provide a method or hook in which to register the namespaces programatically: `MsTest.AddNamespaceToExcludeInStackTrace("My.Custom.Namespace");`
3. Define some unique custom namespace prefix that the Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.StackTraceHelper ignores completely so maybe `MSTestAsserts` and if I have my own `My.Custom.Namespace.MSTestAsserts.`  It would get removed from the stack trace since it is in a namespace that ends in `MSTestAsserts`.

**Comment by acesiddhu** [comment]
@daryllabar we havent heard any feedback on this particular ask from community. We are prioritizing other workitem right now and might not be able to take this up. Feel free to contribute and we would be happy to review.

**Comment by daryllabar** [comment]
Of the three options I list, is there an option that would be preferred?

**Comment by Evangelink** [comment]
We will move forward by closing this issue as won't fix because there was not much upvote from community.
