### ISSUE TITLE
Test failure suggests using [UITestMethod] for non-UWP projects

### ISSUE THREAD

**Issue by GearedToWar** [microsoft/testfx#574]
## Description
> Create a MsTest based UT project that calls into code that must run on the UI thread (asserted using ThreadHelper.ThrowIfNotOnUIThread();) The test fails to run and shows the message - "…must be called on the UI thread.. If you are using UI objects in test consider using [UITestMethod] attribute instead of [TestMethod] to execute test in UI thread."

## Steps to reproduce
> Create a MsTest based UT project that calls into code that must run on the UI thread (asserted using ThreadHelper.ThrowIfNotOnUIThread();)

## Expected behavior
> The error message suggests something actionable and appropriate for the project

## Actual behavior
> The error message suggests using the [UITestMethod] attribute which is only applicable for UWP projects.

## Environment
> I am using MsTest v2 testing a project based on .NET 4.7.2 that uses VS services.

**Comment by jayaranigarg** [comment]
@GearedToWar : Thank you for the feedback. It would be nice if you can share a repro project with us.

**Comment by acesiddhu** [comment]
@GearedToWar unfortunately we don't have a repro to debug the issue. I am closing the issue for now. if you are still facing the issue please reopen the issue and attach a repro for the same

**Comment by GearedToWar** [comment]
Tagging @AbhitejJohn 
I don't know how a repro project would help beyond the description.
Did you try creating a test project with the above attribute and assertion?

**Comment by acesiddhu** [comment]
@GearedToWar we will fix the error message. but it is not possible to run UI based test in a normal UT (Net 451). That capability only exists in UWP based test, due to dependency we take to invoke test methods on UI Thread.

**Comment by AbhitejJohn** [comment]
@acesiddhu : Should we evaluate the use of [JoinableTaskFactory](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.threading.joinabletaskfactory?view=visualstudiosdk-2017) to achieve this for Net Framework based tests as well? Nuget [link](https://www.nuget.org/packages/Microsoft.VisualStudio.Threading/).

**Comment by GearedToWar** [comment]
Using JTF is how users are working around the issue.
Fixing the misleading documentation is the first step. However, if we intend to make the attribute more useful beyond its current limitations, the code-behind should be augmented as well.

**Comment by acesiddhu** [comment]
I will rather evaluate how many customers need this. Running code that needs to be run on ui thread as part of test seems a corner scenario to me unless I am missing something. I haven’t heard that feedback before. Do u have customers who want this?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by GearedToWar** [comment]
As a VS extension author, my tests access code that use VS services which must be called on the UI thread to ensure correctness.
There certainly are alternatives, which I am also using to write my tests.
It was surprising to see an attribute defined for this purpose but hobbled by the UWP requirement.

**Comment by acesiddhu** [comment]
@GearedToWar given that we havent heard about this feedback from others we wont pick up this work. The ability to write your own TestMethod is available even today and you can use that extensibility point in your code base to run ui tests. The implementation can use JTF or any other framework to write the tests. We will fix the error message appropriately
