### ISSUE TITLE
Exception in callback from UWP API caught when test "Debug"'d but not "Run"'d

### ISSUE THREAD

**Issue by sarkreth** [Microsoft/testfx#575]
## Description
I'm writing code around the Windows 10 Bluetooth Low Energy API. I have a callback that is invoked by the OS when a BLE Peripheral is discovered during Scanning. If I "Run Selected Test" and an exception occurs in the callback, it is not apparently detected by the running test process. The exception doesn't prevent the unit under test from otherwise running normally and the test passes. However, if I "Debug Selected Test", Visual Studio alerts me of the exception like it would if I was debugging an app!

Is there something "different" about how a Windows API like [BluetoothLEAdvertisementWatcher.Received][1] would determine how exceptions are routed and caught by a process?

  [1]: https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.advertisement.bluetoothleadvertisementwatcher.received

## Steps to reproduce
    void ScartScan()
    {
        _BleWatcher = new BluetoothLEAdvertisementWatcher();
        _BleWatcher.Received += ScanDiscovered;
        _BleWatcher.Start();
    }

    // this usually fires in under a second, and always in under ten seconds
    void ScanDiscovered(BluetoothLEAdvertisementWatcher watcher, BluetoothLEAdvertisementReceivedEventArgs bleAdvert)
    {
        Debug.WriteLine("This handler was indeed called.");
        throw new Exception();
    }

    [TestMethod]
    async Task UnitTestMethod()
    {
        StartScan();
        await Task.Delay(10000);
        // this always completes, even though I see the debug message in the Output
    }

## Expected behavior
Test fails and Test Explorer message indicates the "throw new Exception()" line.

## Actual behavior
Test passes when I "Run Selected Tests", but not when I "Debug Selected Tests".

## Environment
The project is targeting .NET Standard 2.0, using [this trick](https://blogs.windows.com/buildingapps/2017/01/25/calling-windows-10-apis-desktop-application/) for accessing UWP APIs.

**Comment by mayankbansal018** [comment]
@sarkreth , while debugging can you please make try to enable all exceptions in VS, & try to see if you get the required exceptions.

If that doesn't work, can you please share a small repro project for this.

**Comment by mayankbansal018** [comment]
@sarketh, any update on this?

**Comment by mayankbansal018** [comment]
closing this, please comment if it needs to be reopened.
