### ISSUE TITLE
Parallelization not work: annotations in source code 

### ISSUE THREAD

**Issue by luyajun0205** [Microsoft/testfx#578]
## Description
Following in my code, but output is unexpected, i not setting configure in runsetting file
[assembly: Parallelize(Workers = 0, Scope = ExecutionScope.MethodLevel)]
namespace OpenPublishing.Backend.E2ETesting.TestCase

**output:**
MSTest Executor: Test Parallelization enabled for G:\SourceCode\TestCode\OpenPublishing.E2ETesting\OpenPublishing.Backend.E2ETesting\bin\Debug\OpenPublishing.Backend.E2ETesting.dll (Workers: 4, **Scope: ClassLevel**).

here is my runsetting file:
![image](https://user-images.githubusercontent.com/15990849/54185266-8cae2a00-44e3-11e9-9fc5-cf2b5e6daef6.png)

**Comment by luyajun0205** [comment]
Actual i want some cases  can run in parallel model by MethodLevel, some test cases run parallel by ClassLevel (some cases in same cs file have dependency, need run one by one)

**Comment by luyajun0205** [comment]
Does following is support now?
=========================================================
In MSTest, it would be nice to be able to specify that certain traits must run sequentially together, but can run in parallel with other tests. I could see it looking something like:

// Run tests in CategoryA sequentially in one thread.
[assembly:TestParallelizationCategoryAffinity("CategoryA");

// Run test in CategoryB sequentially in one thread.
[assembly:TestParallelizationCategoryAffinity("CategoryB");

// Run tests in CategoryC and CategoryD sequentially in one thread.
[assembly:TestParallelizationCategoryAffinity("CategoryC", "CategoryD", ...);
With something like this, you could accomplish test runs like this:

Thread 0: Test1WithNoCategory -> Test2WithNoCategory -> Test3WithNoCategory
Thread 1: Test1WithCategoryA  -> Test2WithCategoryA  -> Test1WithCategoryB  -> Test2WithCategoryB
Thread 2: Test1WithCategoryC  -> Test1WithCategoryD  -> Test2WithCategoryC  -> Test2WithCategoryD

**Comment by ShreyasRmsft** [comment]
@luyajun0205 to be frank in an ideal scenario one would author unit tests to be independent of one another. 

but you can refer to https://www.meziantou.net/2018/03/01/mstest-v2-execute-tests-in-parallel
to excluded those tests you don't want to run in parallel using the [DoNotParallelize] attribute.
