### ISSUE TITLE
TestMethod failures are masked by TestCleanup exceptions in the outcome.

### ISSUE THREAD

**Issue by AbhitejJohn** [Microsoft/testfx#58]
## Description
Failures in the TestMethod are masked by TestCleanup exceptions in the outcome.

## Steps to reproduce
1. Create an MSTest V2 based unit test project.
2. Throw an exception in the TestMethod and the TestCleanup.
3. Run the test.

## Expected behavior
An indication of the test method exception and stack trace should be shown in the outcome.

## Actual behavior
Only the TestCleanup stack is shown.

**Comment by AbhitejJohn** [comment]
Reopening this - This is both misleading and is a compat break from MSTest V1 which displays both the details. For instance with the below code
```
[TestMethod]
        public void TestMethod1()
        {
            Assert.Inconclusive();
        }

        [TestCleanup]
        public void TC()
        {
            throw new NullReferenceException();
        }
```
this is the error info in Test Explorer.
![testcleanupissues](https://cloud.githubusercontent.com/assets/18014426/24452479/14f32692-14a1-11e7-83eb-57a03d6c30ca.PNG)

**Comment by smadala** [comment]
Customer are hitting this issue: Assembly load failures in `TestInitialize()` are not getting reported When there is failure in `TestCleanup()`.

**Comment by kevintbrown** [comment]
I'd also like to add that when Debugging a single test in Visual Studio 2017, there is no exposure to the user that the `[TestInitialize()]` and `[TestMethod()]` attributed methods are even executed (you can put breakpoints at the top of each method and they are skipped).

Next think you know an exception is thrown in `[TestCleanup()]`, which makes it really hard to debug your underlying issue.  I had to engage the MSTest team to figure out what was going on.

(Thanks again for the help!)

**Comment by smadala** [comment]
Enable logging also helps to find root cause,following blog post helps how to enable logging [enable unit test execution logs](https://blogs.msdn.microsoft.com/aseemb/2012/03/01/how-to-enable-ute-logs/)
