### ISSUE TITLE
Add explicit support for netstandard 2.0 to reduce the dependencies for 2.x+ consumers

### ISSUE THREAD

**Issue by maxcalvin** [microsoft/testfx#582]
@parrainc , as dotMorten mentioned, the lower the version for .net standard, the wider the range for platforms we can cover. For e.g. if we move to > NS1.4, then it won't work with UWP, & we would need to have separate build scripts to fix that.

_Originally posted by @mayankbansal018 in https://github.com/Microsoft/testfx/pull/411#issuecomment-437657536_

Noticed this in a PR and wanted to request support for 2.0 (while keeping the 1.x line going). This isn't to fix an issue but to reduce the number of dependencies for people that are compatible (which, going forward, will be more and more). For example the [.Net Standard](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support) page recommends:

> However, targeting lower .NET Standard versions introduces a number of support dependencies. If your project targets .NET Standard 1.x, we recommend that you also target .NET Standard 2.0. This simplifies the dependency graph for users of your library that run on .NET Standard 2.0 compatible frameworks, and it reduces the number of packages they need to download.

I'm not sure about the UWP support for netstandard these days, but if UWP doesn't support 2.0 then that's more baggage that can be cut out of the 2.0 library :).

I can see the appeal in keeping just the 1.x version if it reduces the support overhead, but if it's no great burden I think it would be great to get this in at some point.

[AB#1575880](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1575880)

**Comment by SymbioticKilla** [comment]
@shreyasharmamsft  @cltshivash  @mayankbansal018 
Hi,

is there any plans to update to NETStandard 2.0?

Related: https://github.com/microsoft/testfx/issues/866

**Comment by Evangelink** [comment]
This will be handled by #1095

**Comment by Evangelink** [comment]
Fixed by #1194
