### ISSUE TITLE
Specflow Parallel Execution using MsTest not working

### ISSUE THREAD

**Issue by anandprasathm** [Microsoft/testfx#586]
**Specflow Parallel Execution using MsTest**

### SpecFlow Version:
- [ ] 3.0
- [ ] 2.4
- [x] 2.3
- [ ]	2.2
- [ ]	2.1
- [ ]	2.0
- [ ]	1.9
 
### Used Test Runner 
- [ ] SpecFlow+Runner
- [x]	MSTest 
- [ ]	NUnit
- [ ]	Xunit

Version number:

### Visual Studio Version
- [x]	VS 2017
- [ ]	VS 2015
- [ ]	VS 2013

### Are the latest Visual Studio updates installed?
- [x]	Yes
- [ ]	No
 
### .NET Framework:
- [x]	>= .NET 4.5
- [ ]	before .NET 4.5
- [ ] .NET Core 2.0
- [ ] .NET Core 2.1
- [ ] .NET Core 2.2
- [ ] .NET Core 3.0

### Test Execution Method:
- [x]	Visual Studio Test Explorer
- [ ]	TFS/VSTS/Azure DevOps – Task – PLEASE SPECIFY THE NAME OF THE TASK
- [ ]	Command line – PLEASE SPECIFY THE FULL COMMAND LINE
 
### &lt;SpecFlow> Section in app.config
```
<specFlow>
    <!-- For additional details on SpecFlow configuration options see http://go.specflow.org/doc-config -->
  <!-- For additional details on SpecFlow configuration options see http://go.specflow.org/doc-config --><unitTestProvider name="mstest.v2" /></specFlow>
```

### Issue Description
Hi Friends,
I am trying to run my Specflow Tests in Parallel using MsTest V2.
Below is the Test Runner file that i am using to run my Specflow Tests in Parallel. I have this configured on Test Settings as well but still my tests are running one by one. Not sure if i am missing some other settings. Could someone please assist me on this?

**Test Runner File:**
```
<RunSettings>
<!-- MSTest adapter -->
  <TestAdaptersPaths>//MS Test Adapter Path</TestAdaptersPaths>
  <MSTest>
    <Parallelize>
      <Workers>0</Workers>
      <Scope>ClassLevel</Scope>
    </Parallelize>
  </MSTest>
</RunSettings>
```
Thanks in Advance.

**Comment by ShreyasRmsft** [comment]
Can you provide a sample repro project with a few dummy tests?

**Comment by ShreyasRmsft** [comment]
You might want to set this `<Workers>0</Workers>` to the number of parallel threads you want. Re-open this issue if this doesn't work you and also please provide a repro sample when re-opening if you need further assistance.

**Comment by anandprasathm** [comment]
@ShreyasRmsft  Thanks for your support on this.
I have tried with Workers set to 4 but still my tests are running one by one.
I have added the project files in the below clone URL.
Could you please have a look at this and help me with my parallel execution?
https://github.com/anandprasathm/MsTestV2.git

Thanks.

**Comment by anandprasathm** [comment]
@ShreyasRmsft Could you please re-open this issue?

**Comment by ShreyasRmsft** [comment]
@anandprasathm I ran your tests locally. The reason they do not run in parallel has got something to do with the way specflow is creating these unit tests on the fly. You might have to take this up with the specflow owners. 

If the unit test discovered is an individual unit test with the UnitTest attribute then mstest parallelizes them. Specflow has abstracted a lot of the details (I do not yet fully understand what they do) and mstest was never designed to support parallelism in a scenario such as this.

I'm sorry that I do not have time to fully understand how specflow works and to give you guidance on what they can change to support this. But this is something they should verify within the specflow.mstest package.


Additionally whatever your sample test project is doing I see a way to achieve the same using mstest purely without specflow wherein I can give you the guarantee that they will run in parallel. If you can let me know what specflow does that you think mstest cannot I can probably be of help there. Thanks.

**Comment by jayaranigarg** [comment]
@anandprasathm: Any updates on this?

**Comment by singhsarab** [comment]
@anandprasathm Closing this one based on the https://github.com/Microsoft/testfx/issues/586#issuecomment-475532153
Please let us know if you disagree.
