### ISSUE TITLE
Regarding multiple browsers execution on Class

### ISSUE THREAD

**Issue by shirishnagarnz** [microsoft/testfx#588]
## Description
> As a part of my execution on multiple browsers, I am using DataSource option to browse [TestMethod] on multiple browsers. This execution works fine but since DataSource works only on [TestMethod] browser opens and close before-after every [TestMethod] and hence consumes an extra time for execution.

[DataSource("Microsoft.VisualStudio.TestTools.DataSource.CSV", "Parameters.csv", "Parameters#csv", DataAccessMethod.Sequential)]

Tried to work with DataSource on ClassInitialize but it didn't work.

I can always create 2 separate class for Chrome and Firefox but that is not an ideal option.

Is there any way that I can run whole Class in 2 or more browsers instead of using DataSource at TestMethod?

## Environment
> MSTESTV2

**Comment by KitoCoding** [comment]
Hi shirish

I believe you are going about this in a more difficult way. You have to ask your self, why am I testing in Chrome, and why firefox. Are you testing a specific feature that only appears in Firefox? Or are you just making sure that the feature works as expected in all browsers. if that is the case you should set up runSettings that hold a browser Type variable.  When running all your tests, you can override that paramter with a new value.  Create 2 runs, with different overwritten values and bingo bango, you solved the issue.  This also helps for different enviornments, we integrate with VSTS and the runSettings can be applied to local versions of our code, vs the prod version, vs the dev and so forth.

**Comment by shirishnagarnz** [comment]
Hi @KitoCoding , 

Thanks for your reply. Can you please provide snippet of code you are referring here? and the number of files I need to use or something similar knowledge you can transfer will be great.

Regards,
-Shirish

**Comment by ShreyasRmsft** [comment]
@shirishnagarnz here's a sample doc https://devblogs.microsoft.com/devops/supplying-run-time-parameters-to-tests/

It's a little outdated but the crux of it is still the same even today.

**Comment by ShreyasRmsft** [comment]
Closing this issue. Please re-open if our suggestions to not work for you.

**Comment by shirishnagarnz** [comment]
Hi @ShreyasRmsft , thanks for sharing link above. 

What I can see or understood from this is that it still passing parameter or appURL or browser from [TestMethod] i.e. will invoke browser or browse URL at every [TestMethod]

What I need is something that I can do at [ClassInitialize] level i.e. opening browser (by supporting multiple browser) at [ClassInitialize] level and once browser opens it executes all [TestMethod], once executed all [TestMethod], it should close the 1st browser and repeat the execution on 2nd browser and so on.

I remember, this behavior is well supported in [TestNG]-java but I am not able to do this in MSTEST.

Will be great to have a solution for the one I am looking for and apologize if I misunderstood anything above.

-Shirish

**Comment by ShreyasRmsft** [comment]
@shirishnagarnz test run params can be accessed in the class initialize level. You will still have to invoke your tests multiple times (one for each browser you want to run against) using a different runsettings file each time.

**Comment by ShreyasRmsft** [comment]
```
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace MyTests
{
  [TestClass]
  public sealed class TestAssemblyInitialize
  {
    [ClassInitialize]
    public static void Initialize(TestContext context)
    {
      var b = context.Properties["browsertToUser"];
    }
  }
}
```

**Comment by shirishnagarnz** [comment]
Hi @ShreyasRmsft , still not working for me. Can I please have a session with you?

**Comment by ShreyasRmsft** [comment]
@shirishnagarnz can you create a GitHub repo with sample code (or actual test code, your choice) so that i can take a look at what you are trying?

And additionally it would help if you could create a public project on AzureDevops (it's free FYI) with the build definition that runs your test (you can replicate the same steps you are doing locally on the pipelin). I can suggest changes based on what you are doing.

**Comment by jayaranigarg** [comment]
@shirishnagarnz : Any updates on this?

**Comment by singhsarab** [comment]
@shirishnagarnz Gentle ping!

**Comment by shirishnagarnz** [comment]
Hi Microsoft guys,

Apologize for no reply in last month. 

I am on annual leave at the moment and will resume office on 6/5/19.

I can reply only after this date.

-Shirish

**Comment by singhsarab** [comment]
@shirishnagarnz looking forward to hear from you.

**Comment by shirishnagarnz** [comment]
Hello guys,

Thanks for waiting so long.

As far as sharing code on git, talked to my senior and I am sorry as I am not allow to share it over there. Still I can attach few files which executes in below flow

Below files are used in project to execute any [TestMethod]

1. **RunSetting.runsettings**
attached below file have all the configuration to execute mentioned parameter. Attached file we are using is for local execution only. On CI/CD server, same has been configured to execute on server (as in screenshot below)
---------------------------------------------------------------------------------
[RunSetting - Copy.txt](https://github.com/microsoft/testfx/files/3154663/RunSetting.-.Copy.txt)

![CI-CD](https://user-images.githubusercontent.com/31267418/57335745-b13b2100-7177-11e9-93a0-9ad8bb90b36f.JPG)

---------------------------------------------------------------------------------

2. **Suite.cs**
Suite.cs is a parent class to any other class where **AssemblyInitialize** and **AssemblyCleanUp** has been configured. Below are the content of file.

---------------------------------------------------------------------------------
[Suite - Copy.txt](https://github.com/microsoft/testfx/files/3154564/Suite.-.Copy.txt)

[SeleniumHandler - Copy.txt](https://github.com/microsoft/testfx/files/3154705/SeleniumHandler.-.Copy.txt)
---------------------------------------------------------------------------------

fyi, Suite.cs is inheriting the file SeleniumHandler.cs, which is attached above

3. **ContactRunner.cs**
ClassRunner.cs is having body of ClassInitialize, ClassCleanUp, TestInitialize, TestCleanUp and TestMethod. If you see closely, in [TestMethod], there is 1 DataSource file mentioned (**Parameters.csv**), which has more than 1 browser name and getting called at line 113 (in TestMethod).

testCase.DriverParams = TestContext.DataRow["DriverParams"].ToString(); 

---------------------------------------------------------------------------------
[ContactRunner - Copy.txt](https://github.com/microsoft/testfx/files/3154567/ContactRunner.-.Copy.txt)

[Parameters - Copy.txt](https://github.com/microsoft/testfx/files/3154588/Parameters.-.Copy.txt)

---------------------------------------------------------------------------------

4. **ContactSeq.cs** 
Sequence file is containing all the steps require to execute the [TestMethod]. 
---------------------------------------------------------------------------------
[ContactSeq - Copy.txt](https://github.com/microsoft/testfx/files/3154577/ContactSeq.-.Copy.txt)
---------------------------------------------------------------------------------


**CONCERN FOR ME** - As mentioned that Browser initiating with DataSource is currently happening at [TestMethod] level but DataSource supports at this level only and as a reason I need to login and logout before and after every [TestMethod] since I want it to get it initiate at [ClassInitialize] level so that once I login at ClassInitialize level, then execute all the TestMethod and then Logout at ClassCleanUp  level.

Let me know if you need any more details or need to discuss over session.

-Shirish

**Comment by jayaranigarg** [comment]
@shirishnagarnz: Thank you for the detailed information. But unfortunately we don't  have a first class support for your scenario i.e. trying to use DataSource at ClassLevel.

We recommend you to either have two seperate runs for each of the browsers or define static instances of the browsers at the class level and use those instances at test method level.

**Comment by shirishnagarnz** [comment]
Can you provide any example for definition static definition at class level
and calling at test method level?

**Comment by jayaranigarg** [comment]
Below is a high level snippet of what I am proposing. Please see if that works for you.

`using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace MyTests
{
  [TestClass]
  public sealed class MyTestClass
  {
    static var chromeBrowserInstance;
    static var firefoxBrowserInsatnce;
    [ClassInitialize]
    public static void Initialize(TestContext context)
    {
      chromeBrowserInstance = // launch chromeBrowser here and store its instance/process-id here
      firefoxInsatnce = // similarly store for firefoxInstance here
    }

    [TestMethod]
    [DataSource(...)]
    public void MyTest()
    {
            if(String.equals(TestContext.DataRow[browserToUse],"chrome")
            // use  chromeBrowserInsatnce to run the tests, no need to relaunch it
            else if (String.equals(TestContext.DataRow[browserToUse],"firefox")
           // use firefoxBrowserInstance to run the tests
  }
}`

**Comment by jayaranigarg** [comment]
Closing the issue from our end due to no response. Let us know if you still need assistance on this.
