### ISSUE TITLE
[loc][Query][testfx | Test Adapter for ASP.net ] Localizability of string: 0; "DynamicDataIEnumerableEmpty"

### ISSUE THREAD

**Issue by PDostalek** [Microsoft/testfx#589]
Hi,
please help localization team to answer question from translator.

In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.

Could you help please? Thanks!**

Source:
Property or method {0} on {1} returns empty IEnumerable<object[]>.

File Name:
TestFramework\MSTest.Core\Resources\xlf\FrameworkMessages.xlf

Resource ID:
0; "DynamicDataIEnumerableEmpty"

Query:
Please clarify the meaning of the placeholders and IEnumerable<object[]>.

**Comment by jayaranigarg** [comment]
@PDostalek : We don't need translation of {0}, {1} and IEnumerable<object[]>. Let them as they are.

For reference, you can see how translation is done for 'DynamicDataIEnumerableNull' in https://github.com/Microsoft/testfx/blob/master/src/TestFramework/MSTest.Core/Resources/xlf/FrameworkMessages.xlf#L275

**Comment by PDostalek** [comment]
@jayaranigarg THanks for your reply, I get it. But we would like to know what placeholders stand for to make the rest of string properly localized.

**Comment by jayaranigarg** [comment]
@PDostalek : 
String - Property or method {0} on {1} returns empty IEnumerable<object[]>
{0} - can be a method/property name
{1} - Class name containing the above property/method.

Let me know if you need more details.

**Comment by jayaranigarg** [comment]
@PDostalek : Any updates on this?

**Comment by PDostalek** [comment]
Thanks for provided info

**Comment by jayaranigarg** [comment]
@PDostalek : Will you be raising a PR for this loc string?

**Comment by jayaranigarg** [comment]
@PDostalek : Any updates on this?
