### ISSUE TITLE
[Test] Desktop CLI Tests do not verify stack trace information.

### ISSUE THREAD

**Issue by AbhitejJohn** [Microsoft/testfx#60]
## Description
Desktop CLI Tests do not show stacktrace information correctly for x64 scenarios and hence cannot be validated.

## Steps to reproduce
The code at test/E2ETests/Automation.CLI/CLITestBase.ValidateFailedTests() skips verification of stack trace information in x64. This needs to be resolved.

**Comment by pvlakshm** [comment]
This is being validated in IDE and Manual validation matrices.
