### ISSUE TITLE
Updating from latest stable to beta and rolling back to stable cause issue

### ISSUE THREAD

**Issue by parrainc** [Microsoft/testfx#600]
## Description
While updating to latest version of MSTest (framework and adapter) and rolling back to previous version, tests stop working.

## Steps to reproduce
1. Create a new solution
2. Create a new MSTest project
2.1. versions: MSTest.TestAdapter v1.3.2, MSTest.TestFramework v1.3.2, Microsoft.NET.Test.Sdk v15.9.0, Microsoft.NetCore.App v2.1.0
3. Update the following packages to its latest (with 'Include prerelease' checked):
3.1. MSTest.TestAdapter - v2.0.0-beta2
3.2. MSTest.TestFramework - v2.0.0-beta2
3.3. Microsoft.NET.Test.Sdk v16.0.1
4. Build Solution
5. [Optionally] Run the tests
6. Go back to previous versions of the packages.
7. Try running the tests.

> Sample project:
[MSTest.Demo.zip](https://github.com/Microsoft/testfx/files/3062241/MSTest.Demo.zip)

## Expected behavior
> tests should run without any issue

## Actual behavior
> Tests are not running. Getting this in the Output log for Tests:
```
[4/10/2019 2:13:54 AM Error] An exception occurred while invoking executor 'executor://mstestadapter/v2': Method 'get_Properties' in type 'Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.TestContextImplementation' from assembly 'Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' does not have an implementation.
[4/10/2019 2:13:54 AM Informational] ========== Run test finished: 0 run (0:00:00.9860032) ==========
```

## Environment
> Win10 Pro Version 1803
> Visual Studio 2017
> MSTest 1.3.2 (latest stable)

**Comment by cltshivash** [comment]
@parrainc The issue is due to the binaries from the latest version of the adapater being present in the source output folder. MSTest.TestAdapter.props sets the copy condition to be preserve newest. A rebuild of the sources should address this.

**Comment by parrainc** [comment]
Deleted the packages folders and the content in bin folder, then rebuild the solution. That fixed it.
Thanks :)
