### ISSUE TITLE
<licenseUrl> tag deprecating soon, specify license in the package directly

### ISSUE THREAD

**Issue by jayaranigarg** [Microsoft/testfx#601]
## Description
Uploading nuget apckages giving following warning : 
![image](https://user-images.githubusercontent.com/17309452/55875933-f178a500-5bb3-11e9-8348-8ec43d0a1a0a.png)

**Comment by parrainc** [comment]
Is this something you're going to work on?
I'm asking because I submitted a PR in another repo for this exact issue. So, if you don't mind, I can quickly create one updating the licenseUrl tag for the new license tag in all the .nuspec files inside the Package folder.

**Comment by jayaranigarg** [comment]
@parrainc : Can you point me to the set of changes you did for that other repo? Please feel free to pick this up.

**Comment by parrainc** [comment]
sure, there you have: [repo](https://github.com/nunit/nunit/pull/3192/files).

I already have the changes locally but need some input from your end. What's the license type of the testfx project? I see we have a [LICENSE](https://github.com/Microsoft/testfx/blob/master/LICENSE) file with MIT in the repo, but in the `.nuspec` files, we have a [url](http://www.microsoft.com/web/webpi/eula/net_library_eula_enu.htm). 

So, wanted to know if it's fine to put it as MIT in the nuspec, or if it requires the existing one from the url. 
In case we need the one from the url, we should added it to the repo in a `.txt` or `.md` file (according to the [docs](https://docs.microsoft.com/en-us/nuget/reference/nuspec#license) (or maybe have it ending as the extensions specified in the same url it is).

Let me know and I'll push my changes.

**Comment by cltshivash** [comment]
@parrainc We should rename the LICENSE file to LICENSE.txt and point to LICENSE.txt in the nuspec file. Thanks for the offer to contribute.

**Comment by parrainc** [comment]
Alright. PR created, preview review it and make your comments if any.
Thanks!
