### ISSUE TITLE
Running build.cmd locally results in failure.

### ISSUE THREAD

**Issue by mitchdenny** [microsoft/testfx#605]
## Description
I just cloned down the netfx repository to have a go at implementing #579 and when I ran build.cmd I got the following error.

## Steps to reproduce
Environment: Visual Studio 2017 and 2019 installed.

1. Clone repo.
2. Open VS2019 developer command-prompt.
3. Run build.cmd

```
C:\Code\testfx>build
```

## Expected behavior
I expected a successful initial build before I started changing anything.

## Actual behavior
Build failed with:

```
... Perform-Restore: Started.
...     Starting toolset restore...
All packages listed in packages.config are already installed.
Error parsing solution file at C:\Code\testfx\TestFx.sln: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
The restore failed with an exit code of '1'.
At C:\Code\testfx\scripts\build.ps1:166 char:5
+     throw "The restore failed with an exit code of '$lastExitCode'."
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (The restore fai...it code of '1'.:String) [], RuntimeException
    + FullyQualifiedErrorId : The restore failed with an exit code of '1'.
```

## Environment

```
C:\Users\mitch> ver
Microsoft Windows [Version 10.0.18877.1000]
```

Both Visual Studio 2017 and 2019 installed. I noticed by spelunking through build.ps1 and the files it references that is looking in the worng place for MSBuild (at least for VS2019).

**Comment by mayankbansal018** [comment]
can you please run you build.cmd with -verbose, & share those with us, it should list out in detail that from where did it pick msbuild, & what error was thrown.

**Comment by jayaranigarg** [comment]
@mitchdenny : This is a known issue https://github.com/Microsoft/testfx/issues/596 and comes when we have both VS2017 and VS2019 installed on the machine. 
For now, the only workaround would be to uninstall VS2019. This is being tracked as part of this issue: https://github.com/Microsoft/testfx/issues/606 , which is planned for this quarter.

**Comment by singhsarab** [comment]
We will be tracking this with CPS change. Closing.
