### ISSUE TITLE
Warning when vsmdi files are passed in.

### ISSUE THREAD

**Issue by AbhitejJohn** [Microsoft/testfx#61]
## Description
The adapter currently throws the following warning when a vsmdi file is passed to it:
"A testsettings file or a runsettings with a ForcedLegacyMode set to true is not supported with the MSTest V2 Adapter."
This does not indicate that this is an unsupported scenario.

## Steps to reproduce
1. unzip the mstestv2 project from the attachments.
2. Discover tests.
3. Ensure that the test settings via the Test-> TestSettings is pointing to a vsmdi file.
4. Discover Tests

## Expected behavior
A warning that indicates this is an unsupported behavior.

## Actual behavior
The following warning shows up: "A testsettings file or a runsettings with a ForcedLegacyMode set to true is not supported with the MSTest V2 Adapter."

[Repro.zip](https://github.com/Microsoft/testfx/files/757711/Repro.zip)

**Comment by pvlakshm** [comment]
Validate and close, please.
