### ISSUE TITLE
16.0.1 does not respect LogFileName

### ISSUE THREAD

**Issue by roozbehid-ic** [microsoft/testfx#611]
## Description
I was running tests previously on my Appveyor and now they are failing which was probably due to them updating to newer version of Visual Studio.
## Steps to reproduce
     dotnet vstest $([IO.Path]::GetFullPath("$Env:APPVEYOR_BUILD_FOLDER/Output/AnyCPU/$Env:CONFIGURATION/netcoreapp2.2/MyTest.dll")) --% /logger:trx;LogFileName=results.trx

It now produces following output
```
Microsoft (R) Test Execution Command Line Tool Version 16.0.1
Copyright (c) Microsoft Corporation.  All rights reserved.
Starting test execution, please wait...
Results File: C:\projects\myproject\TestResults\results_2019-05-21_12-02-21-189.trx
Total tests: 3. Passed: 3. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 2.3310 Seconds
```

It used to produce following
```
Microsoft (R) Test Execution Command Line Tool Version 15.9.0
Copyright (c) Microsoft Corporation.  All rights reserved.
Starting test execution, please wait...
Results File: C:\projects\myproject\TestResults\results.trx
Total tests: 3. Passed: 3. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 2.3422 Seconds
```

Note the change in result file name!

## Expected behavior
Result filename should be result.trx

## Actual behavior
Result filename is results_2019-05-21_12-02-21-189.trx

## Environment
Visual studio 2017 msbuild version '15.9.21.664'
Windows

**Comment by jayaranigarg** [comment]
@roozbehid-ic : We apologize for the inconvinience. This is a known issue. This behviour was made intentionally in 16.0.0 but a lot of customers faced this issue so we reverted it in [16.0.2-Preview-20190502-01](https://github.com/Microsoft/vstest-docs/blob/master/docs/releases.md#1602-preview-20190502-01).

Here is a similar [thread ](https://github.com/microsoft/vstest/issues/1951)for your reference explaining this issue in details. 

Note - This repo is strictly for MSTestAdapter and framework issues. Please file TestPlatform related issues on [vstest](https://github.com/microsoft/vstest) repo.

**Comment by roozbehid-ic** [comment]
Thanks
