### ISSUE TITLE
DataTestMethodAttribute vs TestMethodAttribute

### ISSUE THREAD

**Issue by cactuaroid** [microsoft/testfx#614]
Which should I specify with `DataRowAttribute`? No explicit guideline is found on reference.
- [DataTestMethodAttribute](https://docs.microsoft.com/ja-jp/dotnet/api/microsoft.visualstudio.testtools.unittesting.datatestmethodattribute?view=mstest-net-1.2.0)
- [TestMethodAttribute](https://docs.microsoft.com/ja-jp/dotnet/api/microsoft.visualstudio.testtools.unittesting.testmethodattribute?view=mstest-net-1.2.0)
- [DataRowAttribute](https://docs.microsoft.com/ja-jp/dotnet/api/microsoft.visualstudio.testtools.unittesting.datarowattribute?view=mstest-net-1.2.0)

Could you put some explanations on [DataTestMethodAttribute](https://docs.microsoft.com/ja-jp/dotnet/api/microsoft.visualstudio.testtools.unittesting.datatestmethodattribute?view=mstest-net-1.2.0) ?

`DataTestMethodAttribute` has been included since [initial commit](https://github.com/microsoft/testfx/blob/73f7ced91297dfe7a1462300bbf593335b14bc2f/src/TestFramework/vnext/DataTestMethodAttribute.cs). According to #238, now `DataTestMethodAttribute` seems to be integrated into `TestMethodAttribute` in the commit. I think `DataTestMethodAttribute` is now obsolete and just for backward compatibility.

[DataRowAttribute example](https://docs.microsoft.com/ja-jp/dotnet/api/microsoft.visualstudio.testtools.unittesting.datarowattribute?view=mstest-net-1.2.0#examples) uses `TestMethodAttribute`, whereas [this example](https://github.com/dotnet/samples/blob/c1ba91d690939449213e410a0089ca6dc42bc33f/core/getting-started/unit-testing-using-mstest/PrimeService.Tests/PrimeService_IsPrimeShould.cs#L25) uses `DataTestMethodAttribute`.

I found the same confusion here.
https://stackoverflow.com/questions/46904953/datatestmethod-vs-testmethod

**Comment by ShreyasRmsft** [comment]
Hi @cactuaroid DataTestMethod is not needed.

Go ahead and use TestMethod with DataRows to data drive your tests.

For any more doubts follow the official docs at https://github.com/microsoft/testfx-docs

**Comment by cactuaroid** [comment]
Thank you @ShreyasRmsft, understood.

I found exactly same question in the testfx-docs repository too. 
https://github.com/microsoft/testfx-docs/issues/64

**Comment by ShreyasRmsft** [comment]
Closing this here. Please track the issue on the docs repo.
