### ISSUE TITLE
Assert.IsNotInstanceOfType fails on value null

### ISSUE THREAD

**Issue by Saeras** [microsoft/testfx#617]
## Description
Assert.IsInstanceOfType succeeds when value is null, while the MSDN specifies it should throw an error.
AssertFailedException : 'value is null or expectedType is not found in the inheritance hierarchy of value.'
This behavior was broken under issue #178 where Assert.IsNotInstanceOfType was incorrectly changed to fail when the value is null.

## Steps to reproduce
Create a standard .net core test project from visual studio 2017, and create a dummy class. then use the following method:
`public void TestMethod1() { Assert.IsNotInstanceOfType(null, typeof(Dummy)); }`

## Expected behavior
The test should succeed

## Actual behavior
The test throws AssertFailedException and fails

## Environment
Windows 10 version 1709 (build 16299.125)
Visual Studio version 15.9.11
MSTest.TestAdapter version 1.3.2
MSTest.TestFramework version 1.3.2

**Comment by ShreyasRmsft** [comment]
@Saeras thank you for reporting this. We will be fixing this.

**Comment by ShreyasRmsft** [comment]
Fixed in PR https://github.com/microsoft/testfx/pull/620
