### ISSUE TITLE
Failed to attach files from: MSTestAdapterV2 - This operation is not supported for a relative URI. 

### ISSUE THREAD

**Issue by bgoggan** [microsoft/testfx#619]
## Description
We're running in to an issue when attempting to attach a test report using the AddResultFile method in the new version of the test adapter (we're using the not yet released versions of MSTest.TestAdapter and MSTest.TestFramework version 2.0.0-build-20190602-01). Our tests are running in an Azure Devops hosted linux agent environment and we're building the path to where the test file will be by doing the below:
                this.currentDir = Directory.GetCurrentDirectory();
                ParentDir = Directory.GetParent(this.currentDir).Parent.FullName;
                Directory.CreateDirectory(Path.Combine(ParentDir, "AUTResults"));
                FileName = TestContext.TestName + "_" + DateTime.Now.ToString("yyyy-MM-dd-HHmmss", CultureInfo.CreateSpecificCulture("en-US")) + ".html";
                var htmlReporter = new ExtentV3HtmlReporter(Path.Combine(ParentDir, "AUTResults", FileName));
                FilePath = Path.Combine(ParentDir, "AUTResults", FileName);

The call to the method looks like this: TestContext.AddResultFile(FilePath);

After each test runs we're receiving the following error, Failed to attach files from: MSTestAdapterV2
Error Details: System.InvalidOperationException:System.InvalidOperationException: This operation is not supported for a relative URI.
   at System.Uri.get_LocalPath()
   at Microsoft.TestPlatform.Extensions.TrxLogger.Utility.Converter.ToResultFiles(AttachmentSet attachmentSet, Guid testResultExecutionId, TestRun testRun, String trxFileDirectory)
   at Microsoft.TestPlatform.Extensions.TrxLogger.Utility.Converter.UpdateTestResultAttachments(TestResult rockSteadyTestResult, TestResult testResult, TestRun testRun, String trxFileDirectory, Boolean addAttachments)

The tests are built using .netcoreapp2.2.

Is there anything you all have seen in your testing of adding this method back to the netcore implementation?

**Comment by ShreyasRmsft** [comment]
@bgoggan this is indeed broken on Linux machines. We are in the process of investigating the root cause.

**Comment by bgoggan** [comment]
@ShreyasRmsft Thank you for the update. Please let me know if you need anything else from us to assist with the research.

**Comment by ShreyasRmsft** [comment]
@bgoggan you can take a shot at fixing it. The code is after all open source. But if not we will be fixing it in a couple of days before a stable version for 2.0 is releasesd.

**Comment by ShreyasRmsft** [comment]
If you are interested in fixing it I can help point you the code and help out with the pull request.

**Comment by bgoggan** [comment]
@ShreyasRmsft I'm good either way. I can wait a couple days for a release from you all or I'm more than happy to make the change if you know what needs to be made.

**Comment by ShreyasRmsft** [comment]
@bgoggan we still need to investigate. I believe it is a small fix but not sure of the exact changes needed.

**Comment by bgoggan** [comment]
@ShreyasRmsft Ok, sounds good. I'll fork the repo and poke around to see if I can find anything. If I do I'll be in contact for assistance with a PR. If not, I'll just wait to hear from you all with a possible pre-release version to work with. Thanks again.

**Comment by bgoggan** [comment]
Hello @ShreyasRmsft have you had any luck finding a resolution for this issue yet? I was unable to track it down myself so I just wanted to follow up. Just let me know. Thanks.

**Comment by ShreyasRmsft** [comment]
@bgoggan I'm sorry we haven't had time yet to take a look at this.

**Comment by mayankbansal018** [comment]
@vagisha-nidhi is this closed?

**Comment by vagisha-nidhi** [comment]
@mayankbansal018 Yes this is fixed. Please use the latest version of vstest and mstest to resolve the issue.
