### ISSUE TITLE
Usage of singleton 'That' from the Assert class breaks CA / IDE rules

### ISSUE THREAD

**Issue by mateusz-dobrowolny** [microsoft/testfx#623]
## Description
I am using singleton ```That``` from the class ```Assert```
It is design to write custom extension methods for the ``` Assert ``` class.

## Steps to reproduce
```
public void MyCustomAssert(this Assert assert, string name)
{
   Assert.IsTrue(name == "");
}
```

## Expected behavior
I expect that this is a valid code according to the best practices and rules.

## Actual behavior
On Visual Studio 2017 a static code analysis rule **CA1801: Review unused parameters - Visual Studio** breaks.
On Visual Studio 2019 a new rule **IDE0060 (Remove unused parameter 'assert' if it is not part of a shipped public API)** breaks.
I must suppress the rule.
However, I am not supposed to suppress it, because it is not safe according to MSDN documentation:
https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1801-review-unused-parameters?view=vs-2017

This issue has already been discussed with documentation team:
https://github.com/MicrosoftDocs/visualstudio-docs/issues/2170

## Environment
VS 2017, VS 2019
Type: Microsoft.VisualStudio.TestTools.UnitTesting.Assert
Assembly: Microsoft.VisualStudio.TestPlatform.TestFramework, Version=14.0.0.0

**Comment by cltshivash** [comment]
Exposing That as non-static property is one option here. But that would be a workaround to suppress this warning and not a necessity.

**Comment by gewarren** [comment]
@cltshivash Are you suggesting that the proper fix is to change the code analysis rule to ignore the "this" parameter?

**Comment by cltshivash** [comment]
@gewarren No that is not the recommendation. 

Because the functions in this class (Assert) are static there's no need to access the 'this' paramter to extend the functionality of the Assert class. The class itself could be made static, but then can't be extended.

**Comment by airbreather** [comment]
See: dotnet/roslyn#50761
