### ISSUE TITLE
[loc][Query][TestAdapter] Localizability of "UTA_WrongThread"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/testfx#624]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
{0} For UWP projects, if you are using UI objects in test consider using [UITestMethod] attribute instead of [TestMethod] to execute test in UI thread.

File Name:
Adapter\MSTest.CoreAdapter\Resources\xlf\Resource.xlf

==========================================
Query:
What will {0} be replaced with?

**Comment by jayaranigarg** [comment]
@PDostalek : {0} will re replaced by the actual exception message. After that this statement will come "For UWP projects, if you are using UI objects in test consider using [UITestMethod] attribute instead of [TestMethod] to execute test in UI thread" as a suggestion for the user.

**Comment by PDostalek** [comment]
Thanks
