### ISSUE TITLE
Framework Extension points

### ISSUE THREAD

**Issue by elv1s42** [microsoft/testfx#626]
Hi, 

Are their any framework extension points for reporting purposes? 
Or are thier any plans to create such extension points like NUnit [event listeners](https://github.com/nunit/docs/wiki/Event-Listeners)? Can't find any related documentation.

Thank you

**Comment by kaadhina** [comment]
We have extension points from the test platform that you can use to achieve this: https://github.com/microsoft/vstest-docs/blob/master/docs/extensions/datacollector.md
Is this something that will help you?

**Comment by elv1s42** [comment]
Hi @kaadhina !

Thank you, I was not able to find this documentation. I'll give it a try. Basically I need to capture test results and test data (like test output) in real-time mode.

**Comment by kaadhina** [comment]
Yes, this should help you achieve that. Feel free to get back if it does not. Closing this for now. Thank you!
