### ISSUE TITLE
Cannot get Last Exception

### ISSUE THREAD

**Issue by dmcdowellsqs** [microsoft/testfx#628]
## Description
I am working on a unit test project. I have a base test file where I have the following line in my Assembly Initialize method.

`AppDomain.CurrentDomain.FirstChanceException += (s, e) => LastException = e.Exception;`

This line will store the last thrown exception in the Last Exception field. This can then be called by the following line and inserted into reports.

`WebUtility.HtmlEncode(LastException.Message)`

This worked in the old Test Framework NuGet package:
`VS.QualityTools.UnitTestFramework (version 15.0.27323.2)`

but in the new Test Framework NuGet package:
`MSTest.TestFramework (version 1.4.0)`

I see the following error passed to the Last Exception field.
`Could not load file or assembly 'Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.resources, Version=14.0.0.0, Culture=en-GB, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.`

## Steps to reproduce
1. Put the following line in a test class:
`public static Exception LastException { get; private set; }`
1. Put the following line in a test method:
`AppDomain.CurrentDomain.FirstChanceException += (s, e) => LastException = e.Exception;`
1. Follow that line with this line:
`throw new System.Exception("Test Error Message");`
1. Run the unit test in debug mode
1. When the exception is thrown, press F10 to step to the next line
1. When execution moves to LastException = e.Exception, hover over e.Exception

## Expected behavior
Last Exception should equal System.Exception with a message of "Test Error Message".

## Actual behavior
An error is displayed:
`Could not load file or assembly 'Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.resources, Version=14.0.0.0, Culture=en-GB, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.`

## Environment
Windows 10
.Net Framework 4.7.2
MSTest.TestFramework (version 1.4.0)
MSTest.TestAdapter (version 1.4.0)

**Comment by karanjitsingh** [comment]
@dmcdowellsqs, I tried your repro steps and it seems to be working fine for me.

![image](https://user-images.githubusercontent.com/4632805/61609433-b89ca180-ac73-11e9-94e1-fe16de6d0870.png)

Can you try to reproduce the problem in a sample project and share here?

**Comment by dmcdowellsqs** [comment]
@karanjitsingh Thanks for your quick reply. I have updated the steps slightly. I have also taken a screenshot and created an example project.

![Last Exception Bug](https://user-images.githubusercontent.com/46569371/61724526-101b3a00-ad66-11e9-84a0-301843d63d5f.png)

[LastException.zip](https://github.com/microsoft/testfx/files/3422777/LastException.zip)

**Comment by karanjitsingh** [comment]
@dmcdowellsqs, I'm still not able to repro this on my machine. It's possible it is because of your machine's culture info `en-GB`. The adapter might be trying to find the culture specific resources but fails and hence catches the exception internally. Which is why you're seeing that exception as the last one. Can you confirm this by trying the `en-US` language pack?

**Comment by karanjitsingh** [comment]
@dmcdowellsqs, since we don't support this language pack, your work around can be to ignore the exceptions thrown by mstest and only keep exceptions you're interested in.

**Comment by dmcdowellsqs** [comment]
@karanjitsingh I have added the following as the first line of the Test Method. I get the same error.
`CultureInfo.DefaultThreadCurrentCulture = new CultureInfo("en-US");`

If you add the following, can you reproduce my issue?
`CultureInfo.DefaultThreadCurrentCulture = new CultureInfo("en-GB");`

**Comment by karanjitsingh** [comment]
@dmcdowellsqs, I'm beginning to think problem is slightly different here, could you run this with dotnet fusion logs turned on and share the logs with me?

The command for fusion log viewer is `fuslogvw` in VS Developer console

**Comment by dmcdowellsqs** [comment]
[Logs.zip](https://github.com/microsoft/testfx/files/3447238/Logs.zip)

**Comment by karanjitsingh** [comment]
@dmcdowellsqs, 

I've tried `CultureInfo.DefaultThreadCurrentCulture = new CultureInfo("en-GB");` and I even tried changing my language pack. I'm still not able to reproduce this issue.

The exception that you're getting in `LastException`, can you give me the stack for it?

**Comment by dmcdowellsqs** [comment]
Do you see the issue if you open my zip of the Last Exception solution? 
Have you tried pressing F10 after the exception is thrown and checking the value of e.exception?
How do I change my language pack?

Exception:
{"Could not load file or assembly 'Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.resources, Version=14.0.0.0, Culture=en-GB, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.":"Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.resources, Version=14.0.0.0, Culture=en-GB, PublicKeyToken=b03f5f7f11d50a3a"}

Stack Trace:
"   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)\r\n   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)"

**Comment by karanjitsingh** [comment]
> Do you see the issue if you open my zip of the Last Exception solution?
> Have you tried pressing F10 after the exception is thrown and checking the value of e.exception?

I've been trying to reproduce on the project that you sent and I'm not getting that issue.

> How do I change my language pack?

Search for language settings in the settings app (windows 10) and make sure it's at the top of the list

![image](https://user-images.githubusercontent.com/4632805/62239447-836e1d00-b3f2-11e9-9ac1-90d135fd7873.png)

![image](https://user-images.githubusercontent.com/4632805/62239607-d21bb700-b3f2-11e9-82bf-28a545af45c1.png)


> Exception:
> {"Could not load file or assembly 'Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.resources, Version=14.0.0.0, Culture=en-GB, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.":"Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.resources, Version=14.0.0.0, Culture=en-GB, PublicKeyToken=b03f5f7f11d50a3a"}
> 
> Stack Trace:
> " at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)\r\n at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)"

Sadly this doesn't give me anything. Just dotnet failing to load the particular culture dll.

**Comment by dmcdowellsqs** [comment]
I tried changing my default language to English (US) using your steps, restarted Visual Studio and ran the test again but unfortunately, the issue persists.

@karanjitsingh As you are unable to see the issue, could I share my screen with you in a live call?

**Comment by WiseJoeyD** [comment]
I've been following this topic - recently revisited an old framework project and discovered this behaviour too.  

I've seen the same issues as dmc is facing - I'm surprised that this seems so tightly tied in to the language - does this mean that users who are using other international language packs will face the same issue?  

Can share my stack traces as well if it helps

**Comment by karanjitsingh** [comment]
> I tried changing my default language to English (US) using your steps, restarted Visual Studio and ran the test again but unfortunately, the issue persists.

@WiseJoeyD, after this, it doesn't seem so. Also since I'm not able to reproduce by changing language packs issue seems to be something else.

@dmcdowellsqs, email me at `karsin @ microsoft . com` so i can send you a meeting invite

**Comment by karanjitsingh** [comment]
Found a workaround this issue the culture needs to be set on culture `en` instead of `en-US`.

Tried `Thread.CurrentThread.CurrentUICulture = new CultureInfo("en");` and it seems to be working. By the same logic `CultureInfo.DefaultThreadCurrentUICulture = new CultureInfo("en");` should work as well.
