### ISSUE TITLE
method level parallelization with process isolation?

### ISSUE THREAD

**Issue by jol64** [microsoft/testfx#629]
I have lots of unit and integration tests in my project and executing them takes quite some time. Thus I now looked into parallelizing tests, and made quite some progress in isolating the resources the tests use. However there are still parts in which my code relies on singletons tied to a process (not thread, my code is heavily multi-threaded).

I read https://devblogs.microsoft.com/devops/mstest-v2-in-assembly-parallel-test-execution/ (and other documentation). 
With the standard "run parallel" of VS or "Coarse-grained process-parallelization" I get multiple processes with proper isolation for my singletons, but parallelization is restricted to distinct assemblies. With "in-assembly parallel execution of tests" I can specify method level parallelization, but the parallelization is not using processes but threads - breaking my singletons.

Is there a way to have method level parallelization with process level isolation?

I am using Visual Studio 2019 (16.2) at present.

**Comment by ShreyasRmsft** [comment]
@jol64 sadly there is not support for this today.

You'd have to manually launch multiple vstest.console.exe processes with custom testcase filters to achieve this today.

**Comment by joachimlindenberg** [comment]
how can I do this and still leverage test explorer (as tests may fail)?
can this be done dynamically with code/plugin?

Actually I was looking into getting rid of my singletons, but there is also an issue with UI threads. I think that in particular for integration tests, it would be really handy to get this supported somehow...

**Comment by ShreyasRmsft** [comment]
@joachimlindenberg hmm, that would be pretty tricky to make it work with test explorer. You'd have to author a custom extension to go about it.

The main reason we don't do this is because launching a separate process for each method is overkill especially in the case of unit tests.

The way to go about it is to ensure your tests don't share any resources.

**Comment by ShreyasRmsft** [comment]
@joachimlindenberg you can reach out to the IDE team on developer community. Make sure you specify that the issue/feature request is for the testexplorer.
