### ISSUE TITLE
Missing support for LongPaths

### ISSUE THREAD

**Issue by chewiiieee** [microsoft/testfx#633]
## Description
My application code works fine.  But testing my code via MSTest however results in the same code failing.  See https://blogs.msdn.microsoft.com/jeremykuhne/2016/06/21/more-on-new-net-path-handling/

## Steps to reproduce
Solution attached.  Run AppMain.  It works as expected.  Run the code via Test Explorer.  Tests fail.

## Expected behavior
Unit tests should be passing.  And there does not appear to be a way to enable LongPath support for unit tests.

## Actual behavior
Results when run via AppMain.vb

Longpath test1 Success=True Length=442 Path=C:\Users\hubertd\AppData\Local\Temp\1ae29e84-d5a3-47ed-ad0c-7ab1aa8e710c\e6364917-254e-4ca4-b344-146c68e72d07\71c60aa3-01ad-446d-8504-33cf93ca35dd\bfcddebe-4d9f-4ec8-add9-627bedb94d0d\a3853351-8674-4cf3-917f-9bd467ed9b12\20d04a49-9db7-46ad-b930-a8ad136a6f0b\b664c005-da5e-4b79-ae10-47bf8373c8ae\89efb9d8-2a91-4e9d-b169-a4136bfcd25c\28c2cee1-e4ec-4da6-9897-0df5942040ba\38569303-2eb2-4deb-914d-68b6a4f9c09f\f18c5b0f-acf7-4990-80f4-483aace16828
Longpath test2 Success=True Length=442 Path=C:\Users\hubertd\AppData\Local\Temp\2eb00b74-6707-4615-bb41-20551bab309c\c2abe175-55d5-47b5-adf0-73b84df6e10b\ecaad737-823a-458e-9c7a-75a7fb1e1544\da53ab4a-d8b3-4903-83b0-18128f3e765b\219a5192-47c5-43ce-95ee-0e9b3bb207f8\0ae75696-809e-4c60-b693-f30f019cf0f2\41b646dd-c37e-48bb-8264-e00935caaa61\7d2755a8-a54f-4ae6-954e-46d25fa97d62\565f68e2-b13a-416b-ac4b-7c3b8660b0ef\ed71f7b0-4dde-4bea-8172-0be4a70005a7\17a61ab5-f2f3-4deb-b7ad-82a9db5d4eb1
Longpath success!

Results when run via Test Explorer
 TestInUTLongPath
   Source: TestLongPathSupport.vb line: 119
   Duration: 210 ms

  Message: 
    Assert.Fail failed. Long filepath support without "\\\\?\\" is broken
  Stack Trace: 
    at UnitTestLongPath.UTLongPathTest(Boolean bUseLongPathsyntax) in TestLongPathSupport.vb line: 51
    at UnitTestLongPath.TestInUTLongPath() in TestLongPathSupport.vb line: 131
[LongPath.zip](https://github.com/microsoft/testfx/files/3527995/LongPath.zip)

## Environment
Windows 10 1803
Visual Studio 16.2.1
MSTest.TestFramework v2.0.0-beta4
MSTEst.TestAdapter v2.0.0-beta4
Microsoft.TestPlatform v16.3.0-preview-20190808-03

**Comment by chewiiieee** [comment]
It's been a few weeks now and it appears to be taking an excessive amount of time for this to issue to be evaluated.

**Comment by vagisha-nidhi** [comment]
@chewiiieee 
From the sample project that you have given, I dug around and found this is the main part of code where you are having discrepancy in production code and tests being run.
```
Dim basicpath As String = "c:\"
Dim LONGPATHSYNTAX As String = "\\?\"
Dim basiclongpath As String = $"{LONGPATHSYNTAX}{basicpath}"
Dim foo = System.IO.Directory.Exists(basiclongpath)
```
In the test method, `System.IO.Directory.Exists` returns false.
If I just run this part of code in a different unit test project, this works as expected, i.e. `System.IO.Directory.Exists` returns true. So this does not seem like an issue with the testing infrastructure. I am not sure what your test project is doing. You can try to add a different unit test project and check for the code above.

**Comment by vagisha-nidhi** [comment]
Closing as this external issue. Please feel free to reopen if there is a test framework issue.
