### ISSUE TITLE
No release for NuGet package 2.0.0

### ISSUE THREAD

**Issue by abatishchev** [microsoft/testfx#636]
I see that NuGet package MSTest.TestFramework version [2.0.0](https://www.nuget.org/packages/MSTest.TestFramework/2.0.0) has been released recently. However, the [releases section](https://github.com/microsoft/testfx/releases) of this repo lists only 2.0.0-beta4 dated back in April. So it's hard to see "what's new" in ver. 2.0.0.
Please create the release. Meanwhile where I can read what's new?

**Comment by vagisha-nidhi** [comment]
I have created the release here https://github.com/microsoft/testfx/releases/tag/v2.0.0.
Also, the release notes have been added https://github.com/microsoft/testfx-docs/blob/master/docs/releases.md#200-september-2019
Closing the issue for now. Please feel free to reopen if any other concern.
