### ISSUE TITLE
.dbg files not deleted from OUT directory when using DeploymentItem on Class

### ISSUE THREAD

**Issue by swegele** [microsoft/testfx#638]
## Description
> It seems when adding the [DeploymentItem("my_file_name")] attribute on the test class, the *.pdb files from the project are not deleted after test run.  
>
> The TestRun directory will start to bloat quickly with content, as I have over 20Mb of pdb files in each OUT directory now.

## Steps to reproduce
> Add the DeploymentItem attribute to test class.  In my case I am copying a .bak file from my build directory (copy always).  This .bak file is used in a [ClassInitialize] method to create a zero-pop database used by all tests.
> Run any test method

## Expected behavior
> When finished the OUT directory is empty

## Actual behavior
> The OUT directory has all .pdb files

## Environment
> MS Test v2
> .NET 4.7.2 - Visual Studio 2019

![OUT_Directory](https://user-images.githubusercontent.com/6868671/65625156-1e611e80-df80-11e9-846e-7acccbe0cea4.jpg)

**Comment by kaadhina** [comment]
Hi, I'm not able to reproduce this issue, can you please share a sample repro project?

**Comment by swegele** [comment]
Yes I have attached a simple test project...instructions to reproduce behavior
1. Open solution and restore nuget packages
2. Rebuild solution
3. Debug the test
4. Look in the TestResults...out directory and see .dbg files

[DemoTestProject.zip](https://github.com/microsoft/testfx/files/3653836/DemoTestProject.zip)

**Comment by kaadhina** [comment]
Thank you for the repro. I was able to repro this and can see there are pdb files left behind during the debug scenarios. (Please note that this does not happen in a run test scenario however. The out directory gets cleaned up completely).
Thank you for this feedback but this is not high on our priority list right now to pick up.
