### ISSUE TITLE
.runsettings file: how to configure connection string information?

### ISSUE THREAD

**Issue by bertrandpons** [microsoft/testfx#639]
Hello,

Question based on the following documentation: https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2019

Could you please indicate how to set connection string within .runsettings file?

Thank you

**Comment by kaadhina** [comment]
Hi, there is a node called <TestRunParameters> that can be used to passed along via the settings and accessed in test code using https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.testtools.unittesting.testcontext.properties?view=mstest-net-1.2.0#Microsoft_VisualStudio_TestTools_UnitTesting_TestContext_Properties

**Comment by bertrandpons** [comment]
@kaadhina  thank you for your reply.

Basically, how would it be used within Azure DevOps pipeline for running Unit Tests with Visual Studio Test task ?

**Comment by kaadhina** [comment]
You can specify runsettings in the pipeline as input. 
If your question is more specific about overriding the runsettings parameter in the pipeline, then you can use the override test run parameter option in the task to do that:
https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/VsTestV2/README.md
https://devblogs.microsoft.com/devops/supplying-run-time-parameters-to-tests/

**Comment by bertrandpons** [comment]
@kaadhina can you inject connectionString information in TestRunParameters section of a runsettings file? I do not see how.

**Comment by kaadhina** [comment]
You can pass along any key value pairs as string content in the xml. If the connection info you want to pass can be one single value or split into multiple key value pairs, then it can be.

**Comment by bertrandpons** [comment]
I tested multiple times with connection string key/value pair and it did not work.

**Comment by kaadhina** [comment]
can you please share your debug logs for me to take a look? (set system.debug = true in your pipeline)

**Comment by kaadhina** [comment]
can you please share your debug logs for me to take a look? (set system.debug = true in your pipeline)

**Comment by bertrandpons** [comment]
in a first time, I would like to know how to write the runsettings file with connection string information. Thank you

**Comment by kaadhina** [comment]
To write a runsettings with connection string (or any key value pair for that matter) you can use the TestRunParameters tag as mentioned here: https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2019

To override the value in pipeline run, you can use the override test run parameter input as mentioned here: 
https://devblogs.microsoft.com/devops/supplying-run-time-parameters-to-tests/ 

While the blog explains this using an example of a deployment url, this would work for any key value. I believe your connection string will be a combination such as "db=mydbsource;property1=value1" etc. I've tried this in the pipeline and did not face any issue. If you have one particular combination of special characters that is not working, please share that.

**Comment by bertrandpons** [comment]
Thank you for your reply. I would like to inject the following key/value pair for the connection string named _ProjectEntities_

`name="ProjectEntities" value="metadata=res://*/ProjectEntities.Model.csdl|res://*/ProjectEntities.Model.ssdl|res://*/ProjectEntities.Model.msl;provider=System.Data.SqlClient;provider connection string=&quot;Data Source=tcp:<SQL_SERVER>,1433;Initial Catalog=<DB_NAME>;Persist Security Info=False;User ID=<USER_ID>;Password=<USER_PWD>;MultipleActiveResultSets=True;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;App=EntityFramework&quot;"`

**Comment by kaadhina** [comment]
Hi thank you for the sample. The below works for me. 
`<TestRunParameters>
    <Parameter name="connectionstring" value="metadata=res://*/ProjectEntities.Model.csdl|res://*/ProjectEntities.Model.ssdl|res://*/ProjectEntities.Model.msl;provider=System.Data.SqlClient;provider connection string=&quot;Data Source=tcp:&lt;SQL_SERVER&gt;,1433;Initial Catalog=&lt;DB_NAME&gt;;Persist Security Info=False;User ID=&lt;USER_ID&gt;;Password=&lt;USER_PWD&gt;;MultipleActiveResultSets=True;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;App=EntityFramework&quot;" />
  </TestRunParameters>`
Please note that you need to escape less than symbols etc. in an xml as in above
In the pipeline, if you want to override, specify the string you have typed in **within quotes**. in the override parameter input text box for value

**Comment by bertrandpons** [comment]
Thank you for your help,

I get the following error when I do as you indicate:

Error: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Data.Entity.Core.EntityException: The underlying provider failed on Open. ---> System.Data.SqlClient.SqlException: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 0 - No such host is known.) ---> System.ComponentModel.Win32Exception: No such host is known

Like if it does not take the runsettings file into account, neither the override

**Comment by kaadhina** [comment]
can you please print the connection string in your test to see if it is correct

**Comment by bertrandpons** [comment]
the print of the connection string shows the wrong value, as if the runsettings file does not make effect

**Comment by kaadhina** [comment]
What value does it show, i mean what is the diff from the value in the settings. How are you accessing the value in your test, please share code snippet

**Comment by bertrandpons** [comment]
By default, it takes connection string value from App.config file, set to localdb. So far, I use app config transform to apply connection string value that targets a specific environment's database. 
What I would like to do is to use runsettings file from which I override value instead of having to generate multiple app config transform in the case I want to perform tests on different environments.

**Comment by kaadhina** [comment]
When u use the runsettings as above, print the value TestContext.Properties["The_key_you_used_in_runsettings"] in your test code. What is the output you get for this?

This blog explains the scenario you are trying to achieve in detail: https://devblogs.microsoft.com/devops/supplying-run-time-parameters-to-tests/

**Comment by bertrandpons** [comment]
ok thanks a lot. I will take a look at it.
