### ISSUE TITLE
There is no clear way to catch an unhandled exception in a TestMethod and TestCleanup

### ISSUE THREAD

**Issue by elgatov** [microsoft/testfx#640]
## Description
There is no clear way to catch an unhandled exception in a TestMethod and TestCleanup.

We are using Selenium with MSTest to run tests. I would want to take an screenshot if the TestMethod or TestCleanup fails. However, creating a new TestMethodAttribute only let's me change how the test is run and wrapping the method in a try-catch is no good as I need a EventFiringWebDriver instance to take the screenshot.

TestCleanup cannot be changed as far as I am aware, so if TestCleanup throws exception I also cannot take a screenshot.

What we are doing is setting a TestBase class which already has all the previous configuration set up and I was trying to avoid wrapping each action in TestMethod in a try-catch.

I understand this is not an issue per se, but I don't know where else to turn to for information in MSTest. If you search for exceptions regarding MSTest absolutely everything talks about asserting exceptions but nothing about how to handle unexpected ones.

So my question is: What is the proper way to handle an unhandled exception at the TestMethod level so I am able to take a screenshot before the TestMethod throws the exception? And, is this also possible for TestCleanup?

Thank you

## Environment
> Visual Studio 2015 update 3
> Windows 10 x64 (17134.885). MSTest 1.4.0

**Comment by elgatov** [comment]
I take it is literally impossible as of right now.

Would the events in [TestExecution class](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.testtools.unittesting.testexecution?view=visualstudiosdk-2017) work if I had Visual Studio 2017?

**Comment by vagisha-nidhi** [comment]
To take snapshots of a test you can use the following code:

```
public TestContext currentTestContext { get; set; }
public void AddAttachments(DriverManager driverManager)
{
Screenshot screenshot = ((ITakesScreenshot)driverManager.Driver).GetScreenshot();
string attachmentsPath = Directory.GetCurrentDirectory() + currentTestContext.TestName +
".png";
screenshot.SaveAsFile(attachmentsPath);
currentTestContext.AddResultFile(attachmentsPath);
}
```

Every test class inherits from the TestBase class that contains the code above.
In every test class, the function above defined as [TestCleanup] so the snaphots is taken in the end of the test.
You can wrap the code  in a try-catch to take the screenshot when there is exception (in test method as well as test cleanup). Can you check if this works for you?

**Comment by elgatov** [comment]
hi @vagisha-nidhi i did something like your suggestion:

`        protected void UploadScreenshot(string exceptionName)
        {
            var path = Directory.GetCurrentDirectory() + "\\" + TestContext.TestName 
                + "_" + exceptionName + "_" + DateTime.Now.ToString("yyyyMMdd_HHmm") + ".png";
            SeleniumHelper
                .GetWebDriver()
                .GetScreenshot()
                .SaveAsFile(path, ScreenshotImageFormat.Png);
            TestContext.AddResultFile(path);
        }`

However, a couple of problems arise from this approach:

1. The code in the test method now has to be wrapped like this:
`           catch (WebDriverException e)
            {
                UploadScreenshot(e.GetType().Name);
                throw;
            }`
which resets the StackTrace and makes it a little more difficult to follow
2. For a test suite of say 100-200 this is quite literally boilerplate code that is easy to forget to add to the test.

I would like the developers to please consider adding two new stages to a TestClass

1. AfterTestMethod
2. AfterTestCleanup

Thank you.
Regards.

**Comment by vagisha-nidhi** [comment]
There is already a TestCleanup for AfterTestMethod to be executed. We have other attributes which you can look for here https://www.meziantou.net/mstest-v2-test-lifecycle-attributes.htm. The usage of AfterTestCleanup is not clear to me except what you are saying that you don't want the repeated code in all TestCleanups. The TestCleanup method is already capable to perform all cleanup operations needed.
