### ISSUE TITLE
Package not installed correctly when using new VS2017 format

### ISSUE THREAD

**Issue by MikeChristensen** [microsoft/testfx#648]
## Description
When using the new VS2017 CSPROJ format, package is not installed correctly.

## Steps to reproduce
1. Create a simple .SLN with MSTest.TestAdapter and MSTest.TestFramework installed
2. Convert to new VS2017 format using a tool such as [this one](https://github.com/hvanbakel/CsprojToVs2017)
3. Try to build

## Expected behavior
Should build correctly

## Actual behavior
When NuGet packages are restored, package is not downloaded.  The directory ./packages/MSTest.* should exist, but does not.  This works when we use a packages.config file.  Other NuGet packages restore correctly, so I don't think this is an issue with VS or NuGet.

## Environment
Attached .ZIP file with solution that will reproduce the issue.

**Comment by MikeChristensen** [comment]
[TestApp.zip](https://github.com/microsoft/testfx/files/3763991/TestApp.zip)

**Comment by MikeChristensen** [comment]
Project code:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net461</TargetFramework>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <AssemblyTitle>ConsoleApp1</AssemblyTitle>
    <Product>ConsoleApp1</Product>
    <Copyright>Copyright ©  2019</Copyright>
    <OutputPath>bin\$(Configuration)\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugType>full</DebugType>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MSTest.TestAdapter" Version="2.0.0" />
    <PackageReference Include="MSTest.TestFramework" Version="2.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Net.Http" />
  </ItemGroup>
</Project>
```

Note that we refer to the package using `<PackageReference Include="MSTest.TestAdapter" Version="2.0.0" />`, but NuGet restore does not download them.  These packages do not appear in the `packages` folder.

**Comment by anshii03** [comment]
@MikeChristensen - This issue is not reproducable. I downloaded your project and  built it in VS 2017. Packages were successfully downloaded in .nuget/packages folder.

Even if you run from command line , packages are getting downloaded.

Is there anything I missed?

**Comment by MikeChristensen** [comment]
Maybe it's a VS2019 thing.  Can you confirm the full path of where the package was downloaded to?  Is the path different than the old style NuGet/VS?  I've confirmed the program still works, and DLLs are copied to the output directory.  I'm thinking there's a new path for packages, which is why our build broke.

**Comment by MikeChristensen** [comment]
Ok, seems to be by-design then.  One last question, though.

When does NuGet use the "packages" folder off the solution directory (C:\MySolution\packages) and when does it use the "packages" folder off the user's profile directory (C:\Users\Mike\.nuget\packages)?  Is this a setting in NuGet?  Is this a behavior of the new VS2017 CSPROJ format?  Thanks!

**Comment by ShreyasRmsft** [comment]
I believe it is to do with the csproj format.

**Comment by jayaranigarg** [comment]
Closing the issue from our end. Let us know if you still need assistance on this.
