### ISSUE TITLE
TransactionScope in async Init

### ISSUE THREAD

**Issue by alexey-gusarov** [microsoft/testfx#649]
## Description
Async context started in TestInitialize method is not flow across thread continuations in Test method

## Steps to reproduce
```
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Threading.Tasks;
using System.Transactions;
using System.Threading;

namespace testfail
{
    [TestClass]
    public class UnitTest1
    {
        TransactionScope _transactionScope;
        AsyncLocal<string> _asyncLocal;
        [TestInitialize]
        public async Task Init()
        {
            _transactionScope = new TransactionScope(System.Transactions.TransactionScopeAsyncFlowOption.Enabled);
            _asyncLocal = new AsyncLocal<string>();
            _asyncLocal.Value = "teststr";
            await Task.Delay(100);
            Assert.IsNotNull(Transaction.Current, "Transaction.Current in Init is null");
        }

        [TestCleanup]
        public void TestCleanup()
        {
            _transactionScope?.Dispose();
        }

        [TestMethod]
        public void TestMethodUsesTransactionFromInit()
        {
            Assert.IsNotNull(Transaction.Current, "Transaction.Current is null");
            Assert.AreEqual("teststr", _asyncLocal.Value);
        }

        [TestMethod]
        public async Task TestMethodUsesTransactionCreatedBySelf()
        {
            using (var localTransactionScope = new TransactionScope(System.Transactions.TransactionScopeAsyncFlowOption.Enabled))
            {
                Assert.IsNotNull(Transaction.Current, "Transaction.Current before await is null");
                await Task.Delay(100);
                Assert.IsNotNull(Transaction.Current, "Transaction.Current after await is null");
            }

        }
    }
}
```

## Expected behavior
Test passed because async context flow across thread continuations

## Actual behavior
Async context flow only in Init method. Also if I started async operation in TestMethod it's also worked.

## Environment
.NETCoreApp,Version=v3.0
Microsoft (R) Test Execution Command Line Tool Version 16.3.0

**Comment by singhsarab** [comment]
@jayaranigarg Is this by-design ?

**Comment by jayaranigarg** [comment]
@alexey-gusarov : Apologies for the delay. TestInitialize method have async Task as return type and hence you are observing this unexpected behaviour.

Please edit you code to following and things should work fine:
```
[TestInitialize]
        public void Init()
        {
            _transactionScope = new TransactionScope(System.Transactions.TransactionScopeAsyncFlowOption.Enabled);
            _asyncLocal = new AsyncLocal<string>();
            _asyncLocal.Value = "teststr";
            Assert.IsNotNull(Transaction.Current, "Transaction.Current in Init is null");
        }
```

**Comment by alexey-gusarov** [comment]
> @alexey-gusarov : Apologies for the delay. TestInitialize method have async Task as return type and hence you are observing this unexpected behaviour.

Hello! Thank you for response.
My init code contains calls to async methods. If I remove async from TestInitialize then I need a lot of Waits.

**Comment by jayaranigarg** [comment]
@alexey-gusarov : As a workaround, you can store the value of Transaction.Current in a static member variable and use that member variable instead in your test methods.

**Comment by alexey-gusarov** [comment]
@jayaranigarg 
Thank you for workaround!

Do you have plans to support async flow in TestInit methods?

**Comment by singhsarab** [comment]
@alexey-gusarov Thanks for the confirmation. 
We do not have plans to add support for it. Thanks.

**Comment by ajbeaven** [comment]
This is really disappointing, particularly because this worked in previous versions of .NET (at least it does on my old, .NET Framework 4.8 app). Is this an issue with .NET Core?
