### ISSUE TITLE
When the base project is on a different solution than the derived one, the inherited test methods are not discovered. 

### ISSUE THREAD

**Issue by nmesar** [microsoft/testfx#651]
## Description

As per issue #23. Deriving test methods from a base test class should be working.
But it seems to be working only when the base and derived project exist under the same solution.

When the base project is on a different solution than the derived one, the inherited test methods are not discovered. 

## Steps to reproduce
Add a base test class TestClassBase in assembly1.dll in Solution 1.
Add a derived test class TestClassDerived in assembly2.dll in Solution 2 and add reference to assembly1.dll. 

TestClassDerived extends TestClassBase.

## Expected behavior
TestClassBase's tests should be discovered under TestClassDerived.

## Actual behavior
TestClassBase's tests are not discovered under TestClassDerived.

## Environment
Package version of MSTest - 2.0.0

**Comment by ydemetriades** [comment]
@nmesar I managed to reproduce your issue!
@AbhitejJohn Any ideas?

**Comment by AbhitejJohn** [comment]
Looks like that should be the default now. I haven't been on this project for a while. Tagging @jayaranigarg  and @singhsarab

**Comment by singhsarab** [comment]
@nmesar @ydemetriades Do you mind sharing the repro projects please ?
I wasn't able to reproduce the issue.

**Comment by nmesar** [comment]
Sorry guys but the issue was on my code, I introduce a new Attribute which was blocking the base tests to be discovered.
Thank you for replying back to me guys and for your time.
I will close the issue.
