### ISSUE TITLE
PathTooLongException is thrown when calling AddResultFile with a file path greater than or equal to 260 characters

### ISSUE THREAD

**Issue by icnocop** [microsoft/testfx#655]
## Description
A `PathTooLongException` is thrown when calling `AddResultFile` with a file path greater than or equal to 260 characters.

## Steps to reproduce
1. Clone the repository https://github.com/icnocop/PathTooLongException
2. Restore NuGet packages.
3. Build in Visual Studio 2017.
4. Run the test in Visual Studio 2017 or on the command line.

## Expected behavior
I expected the file to be added as a test result file.

## Actual behavior
A `PathTooLongException` is thrown.
```
System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.PathHelper.GetFullPathName()
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.TestContextImplementation.AddResultFile(String fileName)
   at MyUnitTestProject.UnitTest1.TestMethod1() in C:\github\icnocop\PathTooLongException\MyUnitTestProject\UnitTest1.cs:line 24
```

## Environment
Windows 10 Version 1903 (OS Build 18362.418) 64-bit
Visual Studio 2017 v15.9.17
MSTest.TestAdapter v2.0.0
MSTest.TestFramework v2.0.0
vstest.console.exe 15.9.1
Long Paths Support Enabled:
`HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem!LongPathsEnabled=dword:1`

**Comment by Evangelink** [comment]
Hi @icnocop,

Thanks for the bug report. I have looked at the implementation and we are using `Path.GetFullPath` which is throwing the exception you are mentioning above. That's a known limitation of .NET Framework, although for regular applications it's possible to work around this limitation using some app.config settings, this is not a feature supported by the Test Platform.

As the length check is remove from .NET Core/.NET and there was no upvote on your issue, I will move forward by closing the issue as won't fix.

**Comment by JoseAngelSalmeronMorote** [comment]
kk
