### ISSUE TITLE
No way to set timeout for whole test run

### ISSUE THREAD

**Issue by arnath** [microsoft/testfx#656]
MSTest v2 appears to have a way to set a per test timeout value using this setting in a .runsettings file:
```xml
<Runsettings> 
  <MSTestV2> 
    <TestTimeout>5000</TestTimeout>   
  </MSTestV2> 
</Runsettings> 
```

However, there does not appear to be a way to set a timeout for the entire test run. Does this feature exist? If not, can it be added?

**Comment by hvinett** [comment]
Hey @arnath, you can set the timeout for the entire test run using test session timeout  in run settings file

```ruby
<RunSettings>
<RunConfiguration>   
    <TestSessionTimeout>100</TestSessionTimeout>
  </RunConfiguration>  
</RunSettings>
```

Refer [this](https://github.com/microsoft/vstest-docs/blob/master/docs/configure.md) for further information.

**Comment by arnath** [comment]
Do cleanup methods get called when the tests are aborted like this (AssemblyCleanup, ClassCleanup, etc)? If not, is there a way to have the test session timeout but still try to clean up?

**Comment by ShreyasRmsft** [comment]
Clean up methods do not get called when this happens. The timeout for all you know could happen in the clean up code. This is a hard abort.

What you are requesting for would be an enhancement. You can open another issue requesting for the feature and provide the link here. We will track it along with the other enhancement asks.
