### ISSUE TITLE
Redundant calls to MatchTestCase

### ISSUE THREAD

**Issue by dennis-yemelyanov** [microsoft/testfx#658]
TestExecutionManager.ExecuteTestsInSource has a call to filter tests that should be executed: https://github.com/microsoft/testfx/blob/bec913906cce0a3e8182ec3b9f82168ab96dbb6c/src/Adapter/MSTest.CoreAdapter/Execution/TestExecutionManager.cs#L239

However the same filtering is also done earlier in UnitTestDiscoverer.SendTestCases: https://github.com/microsoft/testfx/blob/3197e7bb9f7fd4219c7855be575fb5def205aff7/src/Adapter/MSTest.CoreAdapter/Discovery/UnitTestDiscoverer.cs#L116

If UnitTestDiscoverer is expected to produce filtered tests, then filtering again during test execution seems redundant, since any test cases that made it to that stage have already passed the filter.

Can one of these calls be removed to improve performance?

**Comment by jayaranigarg** [comment]
@dennis-yemelyanov : Thank you for reaching out to us.

There are a bunch of scenarios where these calls are not redundant. If we only want to discover tests and not actually execute them, then we need filtering at the time of discovery. Also, for executing tests, there are certain scenarios where we don't do discovery first and straight away jump to executing tests. SO in such cases we need filtering while execution. 

To cater to the above mentioned scenarios, we will not be removing these calls.

**Comment by dennis-yemelyanov** [comment]
Thank you, @jayaranigarg .

If we can execute tests without doing discovery first as you mentioned, it will be helpful. Is there some setting or parameter that can be passed to skip discovery?

**Comment by jayaranigarg** [comment]
@dennis-yemelyanov : There is no setting as such to skip discovery. When you give only selected tests that need to run using IDE via 'Run Selected' option or if you run selected tests using vstest.console commandline with /tests switch, in these scenarios discovery is skipped and we directly go to execution.

**Comment by jayaranigarg** [comment]
Closing the issue as it is not actionable from our end.
