### ISSUE TITLE
Live Unit Testing not Discovering Tests

### ISSUE THREAD

**Issue by spottedmahn** [microsoft/testfx#668]
## Description
Live unit testing isn't working w/ `2.1.0-beta2`.  

## Steps to reproduce
> What steps can reproduce the defect?
File -> New MS Test Core Project -> Install `2.1.0-beta2` packages

[Sample code](https://github.com/spottedmahn/Experiments/tree/master/MS%20Tests%20Friendly%20Test%20Names).

## Expected behavior
Live unit tests should run

## Actual behavior
they don't run

![image](https://user-images.githubusercontent.com/14079228/71112419-6e273e80-2199-11ea-97ba-4798fc84f731.png)

## Environment
VS 2019 Preview, 16.5.0 Preview 1.0

**Comment by ManishJayaswal** [comment]
This works in latest build of VS and additionally it is a VS issue and not MSTest issue. @nohwnd - please close this issue.

**Comment by spottedmahn** [comment]
>This works in the latest build of VS

What version? 🤔

Still a problem for me on version Version 16.5.0 Preview 2.0...  I'll open VS dev community issue.

![image](https://user-images.githubusercontent.com/14079228/74159229-6b6d2680-4be9-11ea-8137-ff65edf838fd.png)

**Comment by nohwnd** [comment]
@spottedmahn Michael I can see the live unit tests run in 16.4.2 with 2.1.0-beta2 and with 2.1.0 as well, not sure what is going wrong on your side.

**Comment by spottedmahn** [comment]
[Dev community issue](https://developercommunity.visualstudio.com/content/problem/912911/live-unit-testing-not-discovering-tests.html)

**Comment by spottedmahn** [comment]
>not sure what is going wrong on your side

Not sure but that makes more sense to me.  I'm not a fan of "I tried it and it works w/ the latest".  That leads to situations like this...

Thanks for the input!  Hopefully the [dev community issue](https://developercommunity.visualstudio.com/content/problem/912911/live-unit-testing-not-discovering-tests.html) will get debugged.

**Comment by ekennedy6334** [comment]
Update to VS2019.5 and my NUnit tests are gone. Since I was using ReSharper to run I tried running with the NUnit plugin and it couldn't run the unit tests either. Rider cannot discover the tests either.

Error message 'vs-test case is missing' may display.

Was there a path change with the latest update or maybe a change to .net core 2.1 causing the environment to not be able to discover the tests?

**Comment by Kaelum** [comment]
@spottedmahn and @ekennedy6334 
Check your solution files and see if they have a "**GlobalSection(NestedProjects) = preSolution**" section.  If they do:

* Close Visual Studio.
* Make a copy of your solution file for safe keeping.
* Completely delete that section in your solution file.

Once I did that, "**Live Unit Testing**" started working again.  I'm not sure what that section of the solution file does, but deleting it doesn't appear to have negative side effects for me.

**Comment by ekennedy6334** [comment]
Didn't work for me. But changing my unit test solutions to v3.1 let's it work. So it's something that MS did with an update to v2.1 that broke it.

**Comment by Kaelum** [comment]
@ekennedy6334 there are at least 2 different issues that result in the same **Live Unit Test** issue.

It sounds like the issue that you have is that a NuGet package for the test adapter is not defined in your projects.  Simply adding the NuGet package for the test adapter to your project file, will fix that issue.  If that doesn't work, then it's yet another issue.

**Comment by Kaelum** [comment]
After upgrading to 16.6.2, the work-around no longer works either.

Live Unit Testing is completely DOA.

**Comment by DekuDesu** [comment]
Just posting in case anybody has this issue recently like me.
I had the exact same issue on Visual Studio 2019 Target: .NET 4.7.1.
Absolutely no fixes on any thread, testing framework, or anything would fix the issue including restoring NuGets, Repairing VS, and adding adapter references.
My **solution** was to **reset all values in Test > Live Unit Testing > Options** to EXACTLY match the following from [How to configure and use Live Unit Testing](https://docs.microsoft.com/en-us/visualstudio/test/live-unit-testing?view=vs-2019#supported-test-frameworks)  ![](https://docs.microsoft.com/en-us/visualstudio/test/media/lut-options.png?view=vs-2019)
