### ISSUE TITLE
Display Name not Shown Until I Build

### ISSUE THREAD

**Issue by spottedmahn** [microsoft/testfx#669]
## Description
I have to build for `TestMethod(displayName: "Some Display Name")` to show up properly in test explorer.

## Steps to reproduce
![build to show display name](https://user-images.githubusercontent.com/14079228/71113085-d88cae80-219a-11ea-8296-601afd5976c4.gif)

[Sample code](https://github.com/spottedmahn/Experiments/tree/master/MS%20Tests%20Friendly%20Test%20Names)

## Expected behavior
I shouldn't have to build

## Actual behavior
I have to build

## Environment
VS 2019 Preview, 16.5.0 Preview 1

**Comment by nohwnd** [comment]
Probably some more work needs to be done in discovery? Do you want to tackle this and make a PR or should I have a look?

**Comment by singhsarab** [comment]
This would probably be an enhancement in source based discovery (where the adapter is not involved).

@shyamnamboodiripad can you please take a look.

**Comment by AbhitejJohn** [comment]
Thats correct, Source Based Discovery does not consider Display Name at the moment. We'd want to consider adding that in.

**Comment by spottedmahn** [comment]
>This would probably be an enhancement in source based discovery

Does that mean in Visual Studio?

**Comment by ManishJayaswal** [comment]
This is a VS issue in SBD. I think we might already have a bug tracking this. This however does eventually gets fixed after build though. 
@nohwnd - we should just close this issue.
@shyamnamboodiripad  - FYI

**Comment by spottedmahn** [comment]
>This however does eventually gets fixed after build though

Sure but it's annoying and confusing IMHO

**Comment by spottedmahn** [comment]
[Dev Community issue](https://developercommunity.visualstudio.com/content/problem/912912/display-name-not-shown-until-i-build.html)
