### ISSUE TITLE
Precheck Class for verfiying the environment before running the actual test

### ISSUE THREAD

**Issue by Grauenwolf** [microsoft/testfx#670]
## Background

When writing integration tests, we often have to run through some prechecks to ensure the environment is properly configured. 

Currently the way we do it is to catch any exceptions and call `Assert.Inconclusive`. This way actual test failures can be distinguished from environmental issues.

## Proposal

Create a class called `Precheck`. This would expose the same methods as `Assert`, but return an inconclusive status instead of a failed status.

**Comment by Evangelink** [comment]
Hi @Grauenwolf,

Thanks for the suggestion!
It seems that it didn't get much traction so we will close it.
