### ISSUE TITLE
TestResult missing ComputerName

### ISSUE THREAD

**Issue by aukevin** [microsoft/testfx#675]
## Description
The [`TestResult`](https://github.com/microsoft/testfx/blob/6c1ee30a895fcef6e751f0f503192aeb0df99b5e/src/Adapter/MSTest.CoreAdapter/ObjectModel/UnitTestResult.cs#L157) object that MsTestV2 produces does not have the [`ComputerName`](https://github.com/microsoft/vstest/blob/3ae085959f000a384ec76f3a53771a695287cfd2/src/Microsoft.TestPlatform.ObjectModel/TestResult.cs#L93) set anywhere. Could this field be added to the `TestResult` object?

## Steps to reproduce
Run any test and view the resulting `TestResult` object. It should not have `ComputerName` set.

## Expected behavior
The expectation was for this field to be set. It was set in previous versions of mstest.

## Actual behavior
The field is null.

## Environment
OS: Windows 10 Entierprise 10.0.18363
vstest.console: 16.4.0
mstest package version: 2.0.0

[AB#1686844](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1686844)

**Comment by aukevin** [comment]
The `TestResult` generating code in this repo looks like it's here:
https://github.com/microsoft/testfx/blob/6c1ee30a895fcef6e751f0f503192aeb0df99b5e/src/Adapter/MSTest.CoreAdapter/ObjectModel/UnitTestResult.cs#L157

**Comment by Evangelink** [comment]
Hey folks! Really sorry for the huge delay in handling this regression.

We will fix it in the next version of MSTest (v3).

@engyebrahim you can refer to the class/method mentioned by @aukevin. In this conversion method, you can set `Environment.MachineName` in the property.
