### ISSUE TITLE
TestResults folder names are not cross platform compatible

### ISSUE THREAD

**Issue by mikeparker** [microsoft/testfx#678]
## Description

Hi, i'm from the Docker team. We are getting user issues creating test results folders on Linux which are then synchronised with the host (Windows) filesystem.

Using `dotnet test` with the default out of the box MSTest configuration creates TestResults folders which are not cross platform compatible due to using invalid characters in the names, specifically the colon character `:`, for example: `TestResults/Deploy_ 2020-01-22 14:14:56`

I believe the offending code is here https://github.com/microsoft/testfx/blob/master/src/Adapter/PlatformServices.NetCore/Utilities/NetCoreDeploymentUtility.cs#L51 `string dateTimeSufix = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss", DateTimeFormatInfo.InvariantInfo);`

Despite the code running this result through `ReplaceInvalidFileNameCharacters` this runs through a platform specific `GetInvalidFileCharacters` for the current platform and does not consider the cross platform file sync case.

You could argue this is a problem for the file sharing sync system (and I would somewhat agree), however whilst we can catch and translate invalid file name characters whenever we synchronise files going across the OS boundary, this is a lossy process and it's possible for users to create 2 different folders or files on Linux which map to the same filename on Windows (and mapping back the other way perfectly becomes impossible). This also means any scripts that run on linux and windows or export artifacts across the boundary will need to reference different folder names.

My suggestion is to have cross platform compatible names from the start and not include `:` or any other invalid windows characters in the directory names regardless of which platform the code is currently running on. We're going to implement as much as we can our side too but I suggest to prevent further issues we just stop using `:` in directory names, there is no real need to do it and anything that reduces friction working with cross-platform environments is a good thing.

**Comment by atruskie** [comment]
I've just hit this case as well. I have an unrelated cross-platform library that excludes colons from the valid characters allowed for filenames for consistency. It is balking at a path returned by mstest on azure pipelines in an OSX environment because there are colons in the path.

A solution would be to allow us to customise this.

I think the best solution would be changing the date format to: 
`DateTime.Now.ToString("yyyyMMddTHHmmss", DateTimeFormatInfo.InvariantInfo);`.
 It is cross-platform, short, and a valid representation of ISO8601.

**Comment by nohwnd** [comment]
Permalink https://github.com/microsoft/testfx/blob/efa1a6d93497719b51ada27787d7f6fcfdd24afe/src/Adapter/PlatformServices.NetCore/Utilities/NetCoreDeploymentUtility.cs#L40

@mikeparker @atruskie could you help me reproduce this? I tried running it via dotnet test, but the deployment item attribute does not create the deployment folder on dotnet core. I can only see the behavior on full net framework project (with the old csproj template), and there the folder created is 
`Deploy_jajares 2020-02-26 16_44_23`. Please provide a simple repro project (delete the bin and obj folders, zip it and drop it here please).

**Comment by mikeparker** [comment]
@nohwnd are you trying in linux, not windows right?

> Despite the code running this result through ReplaceInvalidFileNameCharacters this runs through a platform specific GetInvalidFileCharacters for the current platform and does not consider the cross platform file sync case.

**Comment by atruskie** [comment]
@nohwnd - it's not really a case of producing a repo for a bug. It's more of an undesired behaviour in cross-platform applications. Nevertheless, here you go:

1. dotnet new mstest
2. added code
3. dotnet test

- Environment: Ubuntu 18.04 (WSL2)
- Directory: /home/anthony/GitHub/test
- dotnet version: 3.1.101

Code:

```csharp
using System.IO;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace test
{
    [TestClass]
    public class UnitTest1
    {
        public TestContext TestContext { get; set;}

        [TestMethod]
        public void TestMethod1()
        {
            var content = "hello world";

            var outPath = this.TestContext.TestRunResultsDirectory + Path.DirectorySeparatorChar + "hello.txt";

            File.WriteAllText(outPath, content);

            Assert.IsTrue(File.Exists(outPath));
            Assert.IsTrue(outPath.Contains(':'));
            
            // must fail or else test results cleaned up automatically
            Assert.Fail($"Test deployment directory contains colons in it:\n`{outPath}`");
        }
    }
}
```

Output;

```bash
anthony@ANTHONY-QUT2018:~/GitHub/test$ dotnet test
Test run for /home/anthony/GitHub/test/bin/Debug/netcoreapp3.1/test.dll(.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 16.3.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
  X TestMethod1 [37ms]                                                                                                                                                                                                                                                                                                                                 
  Error Message:
   Assert.Fail failed. Test deployment directory contains colons in it: 
`/home/anthony/GitHub/test/TestResults/Deploy_anthony 2020-03-16 12:45:38/In/ANTHONY-QUT2018/hello.txt`
  Stack Trace:
     at test.UnitTest1.TestMethod1() in /home/anthony/GitHub/test/UnitTest1.cs:line 24

                                                                                                                                                                                                                                                                                                                                                       
Test Run Failed.
Total tests: 1
     Failed: 1
 Total time: 0.8205 Seconds
```

Repo project:
[test.zip](https://github.com/microsoft/testfx/files/4335814/test.zip)

---

As an aside, here is another example of a sub-optimal cross-platform experience:

![image](https://user-images.githubusercontent.com/1452968/76719126-8ac91780-6784-11ea-9a59-c511ab387723.png)

While looking to zip up the example above, I browsed to the folder in WSL, using the 9P server sharing feature, found the test results directory, and found the result folders with colons in their names, which had the symbols transparently replaced by U+F03A (``).

It is not a deal-breaker but it is needlessly different across platforms.

**Comment by nohwnd** [comment]
@mikeparker @atruskie thanks a lot, and no I was not trying it on Linux... That's why having a clear and simple repro helps 🙂 We can also discuss this more easily with the rest of the team, and I can also code it into an Acceptance test. Thanks a lot! 🙂  

Can we discuss the [proposed format](https://github.com/microsoft/testfx/issues/678#issuecomment-597456538) `yyyyMMddTHHmmss`? 

Personally I find that a bit hard to read, would you agree to use this?
` yyyy-MM-ddTHH-mm-ss -> 2020-03-16T08-34-44`

The full format would then be `Deploy_anthony_2020-03-16T08-34-44`. This would still be passed via the function that fixes the name based on `GetInvalidFileNameChars`, to make sure we can write the folder, but this time it would likely not hit anything, on the major operating systems. 

---

I also think that this should use InvariantCulture and not CurrentCulture: 
https://github.com/microsoft/testfx/blob/efa1a6d93497719b51ada27787d7f6fcfdd24afe/src/Adapter/PlatformServices.NetCore/Utilities/NetCoreDeploymentUtility.cs#L43

**Comment by atruskie** [comment]
Using a hyphen a delimiter in the time section would be a violation of [ISO8601](https://en.wikipedia.org/wiki/ISO_8601).

TBH I find `yyyyMMddTHHmmss` to be perfectly readable, and compact. I'll admit though I'm quite used to working with dates in this format.

One has to ask why the date is even in the folder name? I imagine the answer is to create a unique results folder. File explorers or command line tools (`ls`/`Get-ChildItem`) have functions that format and show created/modified timestamps - does the date stamp in the test results folder have to be readable?

If you're still concerned about readability then the following forms would be OK (common enough that they're understood):

- `yyyy-MM-ddTHHmmss`  (technically a violation)
- `yyyy-MM-dd HHmmss` (equivalent to the Windows version now, technically a violation, accepted by Python's ISO8601 parser etc...)

**Comment by nohwnd** [comment]
I think I would go with `yyyyMMddTHHmmss`, it is standardized which should make it easy to consume by multiple tools. 

Too bad there is no built in format that would be easy to use from C# / powershell. You have to provide the format manually.

**Comment by nohwnd** [comment]
Adding to 16.7 for consideration for the next milestone. I think we have the requirements pretty clearly nailed down.

**Comment by nohwnd** [comment]
> One has to ask why the date is even in the folder name? I imagine the answer is to create a unique results folder. File explorers or command line tools (ls/Get-ChildItem) have functions that format and show created/modified timestamps - does the date stamp in the test results folder have to be readable?

Yes that is the reason. It's probably less ugly, and more informative than putting guid at the end of the name.  It is also discouraged to have any interactive session with a build server, so I can imagine that you'd lose the directory info when moving folders from your CI server to your artifacts drop location. But I am just speculating here.
