### ISSUE TITLE
Why are AssertExceptions thrown within Assembly/Class Initializations differentiated?

### ISSUE THREAD

**Issue by andrewphamvk** [microsoft/testfx#687]
## Description
When an AssemblyInitialize or ClassInitialize throws an Exception (in most cases), it is formatted like: 

`Assembly Initialization method {0}.{1} threw exception. {2}: {3}. Aborting test execution.`

When an AssemblyInitialize or ClassInitialize fails with an Assert exception, the message is like:

`Assert.IsTrue failed.`

## Ask

Is it possible to always format it like the former so that it is clear the initialization failed?

**Comment by jinweili1** [comment]
Are there any updates? I'm curious about this as well. And I would like to know how I could determine whether a test failed because assembly init or class init failed. I find all properties and fields in test results, but none of them works.

**Comment by Evangelink** [comment]
Fixed by #1147
