### ISSUE TITLE
Inconclusive tests are treated like skipped tests

### ISSUE THREAD

**Issue by osolo** [microsoft/testfx#689]
## Description

Tests that fail with `Assert.Inconclusive()` at treated by the `vstest.console` just like skipped test.

The result is that these tests:
1. Don't show the failure message or stack trace.
2. Down-stream adaptors don't show any failure information: [Visual Studio Test Explorer bug](https://developercommunity.visualstudio.com/content/problem/907934/test-explorer-incorrectly-handles-inconclusive-tes.html) and [Azure Pipelines test task bug](https://github.com/microsoft/azure-pipelines-tasks/issues/12336).

## Steps to reproduce
1. Create a test that fails with `Assert.Inconclusive()`
2. (Optional) Have the test write to the `TestContext` (e.g. `TestContext.WriteLine("foo")`)
3. Run `vstest.console` on the above assembly.

```csharp
    [TestClass]
    public class UnitTest1
    {
        public TestContext TestContext { get; set; }

        [TestMethod]
        public void MyTestMethod()
        {
            TestContext.WriteLine("From Test Context");
            Assert.Inconclusive("Hello World");
        }
```

## Expected behavior
Error message + stack trace should appear.  If anything was written to the test context, it should appear.

Basically, the information shown should be like failed tests.  Something like below:

```
Microsoft (R) Test Execution Command Line Tool Version 16.4.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
  ! TestMethod [12ms]
  Error Message:
   Assert.Inconclusive failed. Hello World
  Stack Trace:
     at VSBug5.UnitTest1.TestMethod() in C:\prj\VSBug5\VSBug5\UnitTest1.cs:line 19

  Standard Output Messages:


TestContext Messages:
From Test Context


Test Run Failed.
Total tests: 1
     Inconclusive: 1
 Total time: 0.8147 Seconds
```

## Actual behavior
Simply says that the test was skipped.  No further information displayed.

```
Microsoft (R) Test Execution Command Line Tool Version 16.4.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
  ! TestMethod [14ms]

Test Run Successful.
Total tests: 1
    Skipped: 1
 Total time: 2.0095 Seconds                                                                                                                                                       
```

**Comment by StingyJack** [comment]
This sounds very much like the silent test failures reported in #499 or #241.

**Comment by nohwnd** [comment]
Hello, thank you for the bug report. The problem here is that TestPlatform does not have an option to represent Inconclusive, so Inconclusive is mapped to Skipped here: 

https://github.com/microsoft/testfx/blob/19acefa11712c387774784a79dafcf7b3dbee64c/src/Adapter/MSTest.CoreAdapter/Helpers/UnitTestOutcomeHelper.cs#L44-L52

Adding more states to TestPlatform would have to be added to the output, and also to TestExplorer in VisualStudio. At the moment we don't have any plans to do that.

**Comment by StingyJack** [comment]
@nohwnd the request is to report them as failures, because they did not pass

**Comment by nohwnd** [comment]
Oh I can't read. In that case you just enable the existing option. https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2019#mstest-element

**Comment by nohwnd** [comment]
https://github.com/microsoft/testfx/blob/19acefa11712c387774784a79dafcf7b3dbee64c/test/UnitTests/MSTest.CoreAdapter.Unit.Tests/MSTestSettingsTests.cs#L84-L89

This would be example of minimal runsettings that do just this.
