### ISSUE TITLE
Add [MaxTime] Attribute

### ISSUE THREAD

**Issue by HeroMaxPower** [microsoft/testfx#693]
We could add, similar to NUnit a MaxTime attribute. in order to Assert on Test performance.

1. Any assert fails will take priority
2. If a test passes but the time it took was too long then it will fail showing the allowed time in ms and then the time it took.

**Comment by nohwnd** [comment]
There is already a timeout attribute (even though it does not work very well), would this be sufficiently different from that? 

Is this also possible to get this functionality on assertion level, for example by using FluentAssertions. I am not sure if we have any guidance on this, but personally like the xUnit approach where they keep the Assertion library minimal to only provide the core assertions, and allow it to be replaced by a library that does just assertions.

**Comment by HeroMaxPower** [comment]
So this in turn is different from Timeout attribute. 

[TimeOut] has the behaviour kill the test process with no TestCleanup() method being called. i believe its primary focus is to stop rogue test processes clogging up CI builds.
[MaxTime] is more of an assertion it runs all the TestMethod and looks at the execution time and reports assertion failure overtime with TestCleanup(). This makes it more of a performance tool for test execution. This works well with AAA pattern.

I can't think of any other way to implement a timing assertion apart on a Attribute. 

However they have both of these concepts on NUnit

**Comment by nohwnd** [comment]
The intended behavior of TimeOut is to stop the currently running test and call the clean up, I see I forgot to paste the link, I meant to link to #522. 

I think that if TimeOut worked correctly it would be very similar to MaxTime, while implementing MaxTime we would face the exact same problems as with TimeOut.

**Comment by HeroMaxPower** [comment]
Ok then fixing that is the best course.
