### ISSUE TITLE
PlatformServices.AssemblyResolver throws IndexOutOfRangeException

### ISSUE THREAD

**Issue by shueybubbles** [microsoft/testfx#707]
I am trying to write some tests for code that has some dynamic code loading. The nature of our dev machine builds is it's too easy to mix non-delay signed with delay signed binaries. Tests were failing with this exception and we couldn't readily identify the real issue. During this call:

```C#
return assembly.CreateInstance(objectType,
                        false, BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.CreateInstance,
                        null, null, CultureInfo.InvariantCulture, null);
```

The assembly resolver in Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.dll throws an IndexOutOfRangeException.

I assume it has to do with the code expecting at least a delay-signed version, but the local DLL is not delay signed. 
```
+		requestedName	{Microsoft.SqlServer.Management.Sdk.Sfc, Version=16.200.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91}	System.Reflection.AssemblyName
+		foundName	{Microsoft.SqlServer.Management.Sdk.Sfc, Version=16.200.0.0, Culture=neutral, PublicKeyToken=null}	System.Reflection.AssemblyName
+		requestedPublicKey	{byte[0x00000008]}	byte[]
		foundPublicKey	{byte[0x00000000]}	byte[]
		i	0x00000000	int
```

```
System.IndexOutOfRangeException
  HResult=0x80131508
  Message=Index was outside the bounds of the array.
  Source=Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices
  StackTrace:
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.AssemblyResolver.RequestedAssemblyNameMatchesFound(AssemblyName requestedName, AssemblyName foundName) in E:\A\_work\3259\s\src\Adapter\PlatformServices.Desktop\AssemblyResolver.cs:line 346

```
The version of PlatformServices we're using is `14.00.3930.6`

The resolver is obscuring the real bug by throwing here.

**Comment by nohwnd** [comment]
Do you have a repro that we can use to debug this? Can you tell us the exact version of the nuget packages you are using please?

**Comment by shueybubbles** [comment]
I don't have a repro available now.

**Comment by Haplois** [comment]
Can you share the package versions you're using in your tests, and diagnostic output? https://github.com/Microsoft/vstest-docs/blob/main/docs/diagnose.md

**Comment by shueybubbles** [comment]
Sorry, but our pipelines have evolved a fair amount since this issue was opened and I don't think we have any setup that's like this now.

**Comment by Evangelink** [comment]
I have tried a few things locally and I couldn't manage to reproduce the issue.

I will move forward and close the issue. @shueybubbles sorry for our late replies! Please feel free to open new issue(s) if you are experiencing any new issue with MSTest.

Thanks!
