### ISSUE TITLE
Better DisplayNames for DataSource tests

### ISSUE THREAD

**Issue by AbhitejJohn** [microsoft/testfx#713]
## Description
The test result from a test adorned by a DataSourceAttribute today has a display name as follows:
```
TestMethodName (DataRow0)
TestMethodName (DataRow1)
.
.
.
TestMethodName (DataRown)
```
The only way one can know what values were passed in is to open the data source (excel/xml etc) and get a mapping. It'd be great if there was a way to configure this or even add a default with the values being used.

## Steps to reproduce
Any testmethod adorned with a DataSource should exhibit this behavior.

[AB#1408169](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1408169)

**Comment by Evangelink** [comment]
When implementing this change, we need to check for the test ID generation strategy as the DisplayName strategy uses the display name as part of the ID generation. This means that updating DisplayName will be considered as breaking change, causing ID instability.

This is however fine for the other strategies.

**Comment by Evangelink** [comment]
I will close as won't fix because it's not clear if we will work toward supporting this in netcore one day.
