### ISSUE TITLE
any means to differentiate between run and debug in testattribute?

### ISSUE THREAD

**Issue by jol64** [microsoft/testfx#720]
## Description

In an effort to parallelize my integration tests that heavily rely on singletons, I implemented a custom TestMethodAttribute that runs tests each in a dedicated process (also using a custom test runner app). Works great. But occasionally I need to debug. While I can set a breakpoint in my TestMethodAttribute or flip a global and force in process execution, I definitely would prefer to ask some test context about whether this is a run or debug execution.

Is that information available somewhere? Can it be added?

## Environment
Visual Studio 16.6.2 on Windows 1909, vstest.console 16.6.0, mstest 16.0.29721.120

**Comment by nohwnd** [comment]
Internally we use the diagnostics debugger.isattached, but that's probably not answering exactly the same question you ask. Well that depends on the question you are asking. But if you are just interested in whether or not you are debugging the test run. that this should be good enough.

**Comment by jol64** [comment]
Thanks, that appears to be good enough.
