### ISSUE TITLE
Inconsistent test execution results using MSTest V2 

### ISSUE THREAD

**Issue by ruhullahshah** [microsoft/testfx#722]
## Description
- We have a unit test that relies on the fact that the assembly under test will be copied to the `TestDeploymentDir`.
- A second unit test expects a deployment item to be present in the `TestDeploymentDir`
- Executing the first test alone produces a failure, however executing all the tests in the test container leads to no failures.

## Steps to reproduce
- [UnitTestSample.zip](https://github.com/microsoft/testfx/files/4912519/UnitTestSample.zip) contains the minimal code, unit tests, and the `runsettings` that elucidate the scenario.
- To execute both the tests, use `"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" Bin\Debug\UnitTestSampleTests.dll /Settings:my.runsettings /Platform:x86` 
- To observe the failure, use `"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" Bin\Debug\UnitTestSampleTests.dll /Settings:my.runsettings /Platform:x86 /Tests:AssemblyLoadDirectoryShouldBeTheSameAsTestDeploymentDir`
- Reproducible using the TestRunner of VS2019 as well.

## Expected behavior
`AssemblyLoadDirectoryShouldBeTheSameAsTestDeploymentDir` test in the attached sample should pass when executed individually.

## Actual behavior
`AssemblyLoadDirectoryShouldBeTheSameAsTestDeploymentDir` test in the attached sample does not pass when executed individually.

## Environment
- OS: Win10
- vstest.console: 15.0.28307.421
- MSTest framework and adapter: 2.1.2

## Misc
We tried running with vstest.console 16.0.29506.90, but the results were the same.

**Comment by ruhullahshah** [comment]
The tests have been combined under a single `TestClass` for the sake of demonstration, in reality they can reside in different test classes and the behavior should be consistent(we expect both the tests to pass) in both the cases.

**Comment by ruhullahshah** [comment]
@jayaranigarg Any thoughts? I found an issue with similar symptoms https://github.com/microsoft/testfx/issues/490, maybe this defect is correlated?

**Comment by ruhullahshah** [comment]
@nohwnd Could you please provide your comments here? This issue has blocked our migration to MSTest v2. Thanks.

**Comment by Evangelink** [comment]
Hi @ruhullahshah,

I don't find a lot of documentation about the exact scope of `DeploymentItem` so I cannot really say if that's a bug or not. Basically, tests marked with `DeploymentItem` are being copied to the `TestDeploymentDir` location which isn't the case for other tests. When running the 2 tests in parallel, then the dll is copied upfront because one of the test is marked with `DeploymentItem` so the 2nd test can work properly. You can move the `DeploymentItem` to the class level, this way all tests of the class, even run in isolation are going to be run from the `TestDeploymentDir`.
