### ISSUE TITLE
Uncaught ArgumentException caused by MSTestAdapter.PlatformServices.AssemblyResolver

### ISSUE THREAD

**Issue by jnm2** [microsoft/testfx#723]
## Description

There is a third-party library that we load in our unit tests. The third-party framework uses AppDomain.ResourceResolve to call `Assembly.Load(string)` with an argument such as `{aba5ee45-d30c-478e-9730-0b6c1d8bc65b}, PublicKeyToken=3e56350693f7355e`. I'm not sure why it does so, but it would ordinarily succeed. The problem is that the MSTest adapter's assembly resolve handler passes this assembly name to AppDomain.CurrentDomain.ApplyPolicy:

https://github.com/microsoft/testfx/blob/7bc997580abbbdeb48eca0a4bd1a4dcc5e36fd94/src/Adapter/PlatformServices.Desktop/AssemblyResolver.cs#L402

Which causes an ArgumentException

> The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))

Which causes a FileLoadException in the Assembly.Load call done by the third-party library:

> Could not load file or assembly '{aba5ee45-d30c-478e-9730-0b6c1d8bc65b}, PublicKeyToken=3e56350693f7355e' or one of its dependencies. The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))

Which causes a TypeInitializerException, preventing the third-party library types from even being loaded and failing the tests.

This same code successfully loads the `{aba5ee45-d30c-478e-9730-0b6c1d8bc65b}` assembly when the app is running and MSTest is not in the picture. No exception is thrown, even internally.

## Steps to reproduce

The target framework is `net48`. Package references:

```xml
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.6.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="2.1.2" />
    <PackageReference Include="MSTest.TestFramework" Version="2.1.2" />
```

## Expected behavior

No interruption of whatever it is that this third-party dependency is doing; passing tests.

## Actual behavior

Tests failing due to TypeInitializerException wrapping FileNotFoundException wrapping ArgumentException, none of which are thrown when MSTestAdapter.PlatformServices.AssemblyResolver is not involved.

## Environment

Running and debugging tests from Test Explorer in Visual Studio 16.6.3. Windows 10.0.18363.900.

**Comment by jnm2** [comment]
Full repro. The test fails due to a thrown exception. If you make this project into a console app, no exception is thrown.

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.6.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="2.1.2" />
    <PackageReference Include="MSTest.TestFramework" Version="2.1.2" />
  </ItemGroup>

</Project>
```

```cs
using System;
using System.Reflection;
using Microsoft.VisualStudio.TestTools.UnitTesting;

[TestClass]
public class ReproTests
{
    [TestMethod]
    public void ReproTest()
    {
        Assembly OnAssemblyResolve(object sender, ResolveEventArgs e)
        {
            var parsed = new AssemblyName(e.Name);

            if (parsed.Name == "{aba5ee45-d30c-478e-9730-0b6c1d8bc65b}")
            {
                // Return something strongly named to simulate what the third-party library does
                return Assembly.Load("mscorlib");
            }

            return null;
        }

        AppDomain.CurrentDomain.AssemblyResolve += OnAssemblyResolve;
        try
        {
            Assembly.Load("{aba5ee45-d30c-478e-9730-0b6c1d8bc65b}, PublicKeyToken=b77a5c561934e089");
        }
        finally
        {
            AppDomain.CurrentDomain.AssemblyResolve -= OnAssemblyResolve;
        }
    }
}
```

**Comment by Evangelink** [comment]
Hey @jnm2,

Sorry to see this issue was overlooked for so much time 🙏 

I did some investigation and it seems that the only solution would be for us to provide some extra settings where we would accept a list of assembly names (or a regex) and we would skip these assemblies on all our custom resolution paths. Because this is a netfx only issue and you are the only person to have raised this issue, I'd prefer to avoid introducing such feature.

I will move forward by closing this as "won't fix bug". If we are getting more requests/thumbs up, we will reconsider the resolution state.
