### ISSUE TITLE
TestCaseFilter with custom properties?

### ISSUE THREAD

**Issue by pkrukp** [microsoft/testfx#731]
Hello,

I'm trying to use `TestCaseFilter` with custom properties. Is that possible?

I was trying to pass various forms of `/TestCaseFilter` to `vstest.console.exe` but without success. Works with `TestCategory` but not with custom properties.

For example in MSTest:

```
        [TestProperty("Bug", "12345")]
        [TestMethod]
        public void TestMethod2()
```

For XUnit it's `Trait` and for NUnit it's `Property`.

In https://github.com/Microsoft/vstest-docs/blob/master/docs/filter.md#syntax there's a list of "Supported properties":
* for MSTest there's no `TestProperty` there :(
* for XUnit there's `Traits` listed but I could not make it work (filter didn't match any test)
* no NUnit listed

I'm attaching a simple solution with 3 UT projects (mstest, xunit, nunit): [ClassLibrary1.zip](https://github.com/microsoft/vstest/files/5085228/ClassLibrary1.zip)

I have used vstest.console.exe 16.7.0 from Microsoft.TestPlatform nuget package.
(In fact I'd like to pass the TestCaseFilter through RunSettings when vstest is used programmatically through IVsTestConsoleWrapper API, but I have started by checking how it works in the vstest.console.exe - I assume it works the same in API, from microsoft/vstest#2273).

AB#2050968

**Comment by nohwnd** [comment]
@pkruk2 moved your issue to testfx (MSTest), to make it easier for you. No need to file another issue.

Related https://github.com/microsoft/testfx/issues/201

**Comment by pkruk2** [comment]
Thank you. I'll try to file FR for other test adapters soon
