### ISSUE TITLE
Satellite Assembly issue

### ISSUE THREAD

**Issue by Moccassins** [microsoft/testfx#732]
## Description
In our productive solution we encountered an issue in the behavior of MsTest.
Some UnitTest run well, but throws following error messages in the test output:

```
---------- Starting test run ----------
Problem bei der Testlaufbereitstellung: Fehler beim Abrufen der Satellitenassemblys für Bereitstellungselement "C:\Users\xxx\Desktop\SatelliteAssemblyTest\ClassLibrary.Tests\bin\Debug\ClassLibrary.dll": System.ArgumentOutOfRangeException: startIndex darf nicht länger als die Länge der Zeichenfolge sein.
```

We have made some researches on that and created a simple test solution to reproduce this error.
I will attach the test project to these issue for further analysis. 
[SatelliteAssemblyTest.zip](https://github.com/microsoft/testfx/files/5128934/SatelliteAssemblyTest.zip)

We found, the error gets raised if 2 conditions are met:
1.	There is a project with assembly name “xxx.Resources”
2.	The unit test uses the “DeploymentItem” attribute

## Environment
The target framework is net 4.7.0
Package References:
```
<package id="MSTest.TestAdapter" version="2.1.1" targetFramework="net47" />
<package id="MSTest.TestFramework" version="2.1.1" targetFramework="net47" />
```
Running and debugging tests from Test Explorer in Visual Studio 16.7.2. Windows 10.0.19041

We also have tested it with the MSTest current version 2.1.2 but the issue occurs there to.

**Comment by Haplois** [comment]
This should be fixed with the latest release of TestFx.
