### ISSUE TITLE
Investigate build issues

### ISSUE THREAD

**Issue by Sanan07** [microsoft/testfx#735]
## Description
There are couple of errors occuring during the build of the solution. Also some references looks very old, f.e TestPlatform.ObjectModel.dll is very old inside the project. In near future we will do changes in ObjectModel and need that changes in testFx, additionally changing dll version in one project inside solution creates new build errors. 

- [x] Review build.cmd script
- [x] Update references to Test Platform
- [x] Review packages folder inside project (most of them look old (2017 year) and not used inside project)

## Steps to reproduce
Run build.cmd inside solution

## Expected behavior
> Successful build

## Actual behavior
> Errors indicating assembly reference issues.

## Environment
> Please share additional details about the test environment.
> Operating system, Build version of vstest.console, Package version of MSTest
> framework and adapter

**Comment by nohwnd** [comment]
> Review packages folder inside project (most of them look old (2017 year) and not used inside project)

Which folder would that be? I think `packages` is not part of the repository, but rather the place where nuget restores the packages based on packages.config?

**Comment by Sanan07** [comment]
Yes, you are right. After updating to new TP assemblies and nuget packages - it should be okay.

**Comment by Haplois** [comment]
TestFx is referencing older packages mostly because of profile259 and UAP support. I am removing dependencies like `Microsoft.TestPlatform.ObjectModel, v11.0.0` as part of modernization.

**Comment by Sanan07** [comment]
Closing this as it is done.
