### ISSUE TITLE
.NET 5 TFM Support?

### ISSUE THREAD

**Issue by michael-hawker** [microsoft/testfx#750]
## Description
I'm trying to follow [these docs](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-enhance#net-5-preview-8-and-later-use-the-target-framework-moniker-option) about using the new .NET 5 TFMs for access to the Windows APIs (specifically [App Service](https://docs.microsoft.com/uwp/api/Windows.ApplicationModel.AppService.AppServiceConnection)).

The same setup works fine if I use the `netcoreapp3.1` TFM with the `PackageReference` (also described in that document):

```xml
<PackageReference Condition="'$(TargetFramework)' == 'netcoreapp3.1'"
                  Include="Microsoft.Windows.SDK.Contracts"
                  Version="10.0.19041.0" />
```

Trying to upgrade this to the recommended .NET 5 path doesn't seem to work with the MSTest project type in VS or on the command line.

I discovered this in my PR here: https://github.com/windows-toolkit/WindowsCommunityToolkit/pull/3580/files#diff-bcd2accc8655a3a705591da25274a0ebe6740eaf0dac109958fee2f4f553bf1eR6

And reverted back to using the .NET Core 3.1 approach.

## Steps to reproduce
Revert the commit here from this PR: https://github.com/windows-toolkit/WindowsCommunityToolkit/pull/3580/commits/3bf27d9740c588913d9ccc24155bbcc847d7663e

Otherwise, if you start a new MSTest project with .NET Core 3.1/PackageReference to include a Windows API call, try upgrading to .NET 5 TFM after...

## Expected behavior
Able to build MSTest project which references Windows API with .NET 5 Windows TFM.

## Actual behavior
Fails to build, Windows APIs can't be found.

## Environment
VS 2019 16.8.2
Azure Hosted environment and Windows 10 19042 (20H2).

FYI @andrewleader think this would be an issue for the Notifications tests too, eh?

**Comment by michael-hawker** [comment]
FYI @AdamBraden this is an issue following the comment I had pinged you on here: https://github.com/windows-toolkit/WindowsCommunityToolkit/pull/3580#issuecomment-736683045

**Comment by michael-hawker** [comment]
Ah, I had also left some of the old properties in:
```xml
    <TargetFrameworkIdentifier>.NETCoreApp</TargetFrameworkIdentifier>
    <TargetFrameworkVersion>v3.1</TargetFrameworkVersion>
```

Removing them to this format got me further:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net5.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17134.0</TargetPlatformMinVersion>
```

Now it might be some underlying dependencies we're using need updates as well. But it'd be good to know if this is the recommended format for this support. Thanks!

**Comment by AdamBraden** [comment]
That is the recommended model. A couple notes:
1. Setting the TFM sets the minimum TFM that all consuming apps must use to 'build'. This is only impacts the apis used as a reference. This might be what you are running into with dependencies. 
2. Note if you are using 18362 or 19041 apis and running on 17134, the TPMinV doesn't yet provide appropriate compile time checks for lightup until this feature is implemented - https://github.com/microsoft/CsWinRT/issues/411.
