### ISSUE TITLE
Proposal: Test adapter should test  multiple versions of depedent assemblies.

### ISSUE THREAD

**Issue by mujdatdinc** [microsoft/testfx#764]
### Problem 
We have a product A which uses different versions of other product B's assemblies.   Both products have its own versioning. Version 1 of A can run on the top of Versions 1 2 3 4 5 of B. A is always **compiled** against **latest** version of B and discovers version of B at runtime and loads its assemblies behaves according at runtime . So there is one version of binary(or binaries) A which runs on every version of B .  For version 1 of B, A loads version 1 of assembly of B from where B is installed.
 We have unit tests for A and want to run same tests for all versions of B. Using assembly resolution config is not solving becasue AssemblyResolver only loads the exact version of required assembly. For example, when directory points to version 1 and A is compiled with lasted version 5. Tests are not discovered and run.
```
    <AssemblyResolution>  
      <Directory path="C\:PathtoVersion1" includeSubDirectories="false" MatchVersions="false"/>  
    </AssemblyResolution>
```

### Solution
Directory path should have default true `MatchVersion` attritbute which causes not to match assembly versions during assembly resolution.

**Comment by Evangelink** [comment]
@mujdatdinc is this something you are still interested about? If so, could you please provide more information about what you are trying to do?

**Comment by Evangelink** [comment]
Ping @mujdatdinc
