### ISSUE TITLE
license extension rename broke links

### ISSUE THREAD

**Issue by anqre** [microsoft/testfx#777]
## Description
> **IMPORTANT**: if the defect is reproduced only in a workflow from within the Visual Studio IDE then do not report the issue here - instead, please report it using Visual Studio's "Send Feedback" option that can be accessed from the Help menu OR using this link https://developercommunity.visualstudio.com.
>
> For a defect specific to the MSTest V2 test framework, describe the issue you've observed.

Side effect generated by #603. Also, taking in consideration that Github support LICENSE, why add the `.txt`?
I can open an MR, but in my opinion the problem is the file extension. Waiting for feedback.

## Steps to reproduce
* Go to the License section on [README.md](https://github.com/microsoft/testfx/blob/master/README.md) and click on the _MIT license_ link

## Expected behavior
Open license content

## Actual behavior
404

**Comment by Haplois** [comment]
Thank you for the feedback. Let's remove the extension to comply with GitHub. I started a PR and abandoned it; if we're removing the extension, we need to update the build script and all other references to it. 

Let me know if you like to do the PR, or I can do it as well.

**Comment by anqre** [comment]
I can do the PR, no problem.

**Comment by Haplois** [comment]
Thank you, please @ me after you've created with the PR.

**Comment by jnyrup** [comment]
Nuget seems to have [problems](https://github.com/NuGet/Home/issues/7601) linking to extension-less license files

![image](https://user-images.githubusercontent.com/919634/111742072-cdd23500-8887-11eb-80bb-44f288fa13a9.png)


I guess nuget gallery has some workaround to display the correct link on
https://www.nuget.org/packages/MSTest.TestAdapter/

Some possible workarounds:
* Rename `LICENSE` -> `LICENSE.md` and edit csproj (and readme and others) to point at that file ( the .md extension should be [GitHub friendly](https://docs.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository) as well)
* Keep `LICENSE` extensionless in git, but package _with_ an extension it in the .nupkg
* Change csproj to use `<PackageLicenseExpression>MIT</PackageLicenseExpression>`
* Use both `<PackageLicenseExpression>` and include the license, see https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Newtonsoft.Json.csproj

**Comment by Haplois** [comment]
Hi,

It's not about extensionless license files. The issue you're having is because `licenseUrl` is [depracated](http://aka.ms/deprecateLicenseUrl). Even if we update this, you should stop using that and use the license expression included with the package itself.
