### ISSUE TITLE
Referencing MSTest.TestFramework but not MSTest.TestAdapter

### ISSUE THREAD

**Issue by RobSwDev** [microsoft/testfx#780]
## Description
We have several test utility libraries. They don't contain test cases, but rather methods used by test projects.
Ideally, these target NetStandard. 
However, if we target NetStandard, we cannot reference MSTest.TestAdapter. Fair enough - these libraries don't contain test code. We still reference MSTest.TestFramework, so we can use the Assert methods.
But the test log spits out multiple warnings

```
Test project XXX does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project.
It's recommended to reference NuGet test adapters in each test project in the solution.
```

How does Visual Studio decide that XXX is a "test" project? Presumably because of the reference to MSTest.TestFramework? Is there a way of avoiding the multiple warnings? (Everything seems to work, but some devs are concerned the warnings will obscure real issues)

## Environment
Windows 10
Visual Studio 2019 16.7.3
MSTest.TestFramework/MSTest.TestAdapter 2.1.0

**Comment by Haplois** [comment]
You should be able to edit the `.csproj` file, add the following code segment to designate it "not a test project".

```
<PropertyGroup>
  <IsTestProject>false</IsTestProject>
</PropertyGroup>
```
