### ISSUE TITLE
Upgrading .NET Framework project to use MSTest v2.2.1 introduces a large number of unwanted .NET Core dependencies

### ISSUE THREAD

**Issue by brianberns** [microsoft/testfx#788]
## Description
I have a unit test project that is built with .NET Framework 4.6.1 and MSTest v2.1.2. When I attempt to upgrade to MSTest v.2.2.1, a large number of dependencies on .NET Core packages (of the form System.*.4.3.0) are introduced.

## Steps to reproduce
See above.

## Expected behavior
Since this is a .NET Framework project, I wouldn't expect upgrading MSTest to take dependencies on .NET Core packages.

## Actual behavior
See above.

## Environment
Visual Studio 2019.
![Untitled-1](https://user-images.githubusercontent.com/11883138/109673625-34dfb200-7b44-11eb-82db-1c67a0a7bac0.png)

[AB#1337991](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1337991)

**Comment by Haplois** [comment]
@brianberns Thank you for reporting. This is fixed with v2.2.4 release.
