### ISSUE TITLE
Looks endless loop

### ISSUE THREAD

**Issue by JaggerWu** [microsoft/testfx#791]
https://github.com/microsoft/testfx/blob/32f53aea32c4aac68a8880ec74ee84de56fcdf12/src/TestFramework/MSTest.Core/Assertions/StringAssert.cs#L580

**Comment by JaggerWu** [comment]
This method returns itself, which might cause infinite loops

**Comment by nohwnd** [comment]
Do you want to PR a fix? It should be quite easy, I think a parameter is just missing to pass this call to another overload.

**Comment by JaggerWu** [comment]
Fixed with #792. @nohwnd
