### ISSUE TITLE
DynamicDataSource::GetData is called multiple times per test

### ISSUE THREAD

**Issue by mayerj** [microsoft/testfx#810]
## Description
> DynamicDataAttribute datasource is called multiple times after [this](https://github.com/microsoft/testfx/pull/544) pull request

## Steps to reproduce
> See project at [TestMethodRunner](https://github.com/mayerj/mstest-testmethodrunner).  Essentially, put a breakpoint in any DynamicData source (IE, the method that generates the IEnumerable<object[]> and you will see it is hit twice per call to RunSingleTest

## Expected behavior
> Not sure.  I would have expected the method to be called once, in my case we noticed the behavior because we were 
creating and returning an IDisposable object that represented some global resource, and noticed that tests started failing because the 2nd one that was created was failing to access the global resource because the first hadn't been cleaned up by the test (because it wasn't given to the test).  (This worked in 1.4 and versions prior to the PR above).

## Actual behavior
> Method is called multiple times.

## Environment
> MsTest framework/adapter 2.1.2, windows.

**Comment by Haplois** [comment]
Hi mayerj,

We call that method during test discovery, if we can serialize all data produced it won't be called again. I case we find the data not serializable, it'll be called again during execution. Does this impact your test runs? 

Can you describe the impediment you have with this? Does this affect your workflow?

**Comment by mayerj** [comment]
Hello,

I noticed this because one of our DynamicData tests creates an IDisposable object to be provided to the test (the test knows to dispose this when the test finishes).  However, after updating as above, the resource that the IDisposable projected was being created multiple times, which was causing issues in the test.

IE, something like this:

`
public static IEnumerable<object> GetTestArguments()
{
  for(int i=0; i<10; i++)
  {
    yield return new object[] { i, GetDisposableObject() };
  }
}
`

It doesn't feel safe to test if the arguments were IDisposable and then dispose them, but maybe instead of calling GetData twice the result can be cached after the first call, to be reused again for the test arguments?  After all, it's just using the Any() call to test for an error condition.

**Comment by Haplois** [comment]
@mayerj,

We discover the tests once (assuming you're using VS, and not rebuilding) cache the test cases and reuse it. In you case, 10 test cases will created, `TestCase (1,DisposableObject)`, `TestCase (2,DisposableObject)`,  etc. After discovery we'll serialize these parameters and cache them. They'll be reused on execution (assuming serialization does not fail - if it does, they'll be rediscovered during execution.)

We're working on providing an opt-out from this feature, you can track #905.
