### ISSUE TITLE
After upgrading to 2.2.4 from 2.2.3 nullable enums are not valid for DataRowAttribute

### ISSUE THREAD

**Issue by DOliana** [microsoft/testfx#838]
## Steps to reproduce
Create a Testmethod that accepts a nullable enum as parameter (`MyEnum? enumValue`) using the [DataTestMethodAttribute]
and two DatarowAttributes. Observe an Exception being thrown when using "MSTest.TestAdapter" Version="2.2.4" and "MSTest.TestFramework" Version="2.2.4"  instead of Version 2.2.3
The exception is thrown both when executed in Visual Studio and in a pipeline in Azure DevOps server.

Sample code
```
enum MyEnum { val1, val2 }

[DataTestMethod]
[DataRow(null)]
[DataRow(MyEnum.val1)]
public async Task MyTest(MyEnum? enumValue)
{
}
```

## Expected behavior
test executes with different rows

## Actual behavior
Exception is thrown when `DataRow(MyEnum.val1)` is used. Thrown Exception:
Test method MyTest
threw exception: 
    System.ArgumentException: Object of type 'System.Int32' cannot be converted to type 'System.Nullable`1[MyEnum]'.

## Environment
dotnet core 3.1 test project

**Comment by Haplois** [comment]
Thank you for reporting this, it's a known issue - we're working on it. It's tracked [here][1].

[1]: https://github.com/microsoft/testfx/issues/837

**Comment by Haplois** [comment]
Ref: https://github.com/microsoft/vstest/issues/2925
