### ISSUE TITLE
After upgrading to 2.2.3 to 2.2.4 getting a argument exception on datarow unit test

### ISSUE THREAD

**Issue by davesmits** [microsoft/testfx#839]
## Steps to reproduce

Create this unit test

```
[TestClass]
    public class Test
    {
        [DataTestMethod]
        [DataRow(52.131d)]
        public void Doubles(double value)
        {
        }
    }
```

results in :
 Test method Pandora.Reasoning.Rules.Tests.Extensions.Test.Doubles threw exception: 
    System.ArgumentException: Object of type 'System.Decimal' cannot be converted to type 'System.Double'.

## Expected behavior
Unit test completes successfully 

## Actual behavior
unit test fails in Test method Pandora.Reasoning.Rules.Tests.Extensions.Test.Doubles threw exception: 
    System.ArgumentException: Object of type 'System.Decimal' cannot be converted to type 'System.Double'.

**Comment by Akinzekeel** [comment]
I am also encountering this problem. I also have problems with tests that use a Type or a char in the DataRow attribute (char cannot be converted to string, System.Type cannot be serialized)

**Comment by Sanan07** [comment]
Did you also update Microsoft.NET.Test.Sdk in project? I do not see any changes related to DataRow logic in 2.2.4.
@Haplois can you please look at these issues after upgrading to 2.2.4?

**Comment by davesmits** [comment]
Just created a new project; updated the nuget packages
now using

```
 <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.10.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="2.2.4" />
    <PackageReference Include="MSTest.TestFramework" Version="2.2.4" />
    <PackageReference Include="coverlet.collector" Version="3.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

```

this is this unit test:

```
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace TestProject1
{
    [TestClass]
    public class UnitTest1
    {

        [DataTestMethod]
        [DataRow(52.131d)]
        public void Doubles(double value)
        {
        }

    }
}

```


same output

here is the project I used: [TestProject1.zip](https://github.com/microsoft/testfx/files/6548802/TestProject1.zip)

**Comment by chriswelles** [comment]
Something has clearly broken with how DataRow's are serialized.  With the update to 2.2.4 (from 2.2.3), I get the error:

`An exception occurred while invoking executor 'executor://mstestadapter/v2': Type 'System.String[]' with data contract name 'ArrayOfstring:http://schemas.microsoft.com/2003/10/Serialization/Arrays' is not expected. Add any types not known statically to the list of known types - for example, by using the KnownTypeAttribute attribute or by adding them to the list of known types passed to DataContractSerializer.`

The test that breaks things has DataRow's that look like:

`[DataRow(DeviceState.Offline, Severity.Offline, new string[] { "1" }, Severity.Critical, new string[] { }, Severity.Warning, new string[] { }, Severity.Informational, new string[] { }, Status.Offline)]`

It can't handle String arrays (along with all sorts of other things it seems).

**Comment by Haplois** [comment]
Ref: https://github.com/microsoft/vstest/issues/2925
