### ISSUE TITLE
[MSTest.TestAdapter] Failure while discovering tests on latest version (2.2.4)

### ISSUE THREAD

**Issue by andessi** [microsoft/testfx#843]
## Description
I am able to repro in both VSO and in Visual Studio locally when I update to the latest versions of MSTest.TestAdapter + related nugets. When I try to run tests, it errors out with the following: 

`An exception occurred while invoking executor 'executor://mstestadapter/v2': Type 'System.Runtime.Serialization.DateTimeOffsetAdapter' with data contract name 'DateTimeOffset:http://schemas.datacontract.org/2004/07/System' is not expected. Add any types not known statically to the list of known types - for example, by using the KnownTypeAttribute attribute or by adding them to the list of known types passed to DataContractSerializer.`

Interestingly, this only appears to affect one of my two test projects. I am able to mitigate by downgrading the nuget back to 2.2.3, clearing the project's state (git clean -xdf), and re-opening visual studio. Downloading the update produces the error again. 

## Steps to reproduce
Run tests for the project, note that tests do not execute. 

## Expected behavior
The tests are found and executed

## Actual behavior
The tests are not found

## Environment
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.10.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="2.2.4" />
    <PackageReference Include="MSTest.TestFramework" Version="2.2.4" />

**Comment by andessi** [comment]
#837 Discusses this more. Closing out this as a duplicate

**Comment by Haplois** [comment]
Ref: https://github.com/microsoft/vstest/issues/2925

**Comment by Haplois** [comment]
Thank you for reporting this, it's a known issue - we're working on it. It's tracked [here][1].

[1]: https://github.com/microsoft/testfx/issues/844
