### ISSUE TITLE
error BC40027: Return type of function 'TestContext' is not CLS-compliant

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/testfx#848]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/error-BC40027:-Return-type-of-function-/1405892)._

---
I am using VS 2019 version 16.9.4 and trying to run a build.  It keeps failing because of a CLS Compliant error (all VB unit tests).  A few other co-workers of mine have older version's of VS 2019 and running a build on their machines works completely fine.  Looked on line for a fix but all it says is to switch <CLSCompliant(True)> to <CLSCompliant(False)> and I don't want to do that.

---
#### Feedback Bot on 4/23/2021, 03:11 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Emanuel Heidinger on 4/28/2021, 00:29 PM: 

<p>In my scenario, file version with the CLS Compliance issue was 16.0.31004.209. Version 16.0.30801.237 was fine.</p>

#### Feedback Bot on 5/5/2021, 10:24 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Adrian Stanley on 5/6/2021, 06:42 PM: 

<p>I have just ran into this problem after upgrading a self-hosted build agent from VS 2019 16.0.3 to 16.9.4, and now my builds are failing. I have an ADO build pipeline with a <strong>Visual Studio build</strong> step. With 16.9.4 I now get errors like this, which fail the build:</p>
<pre><code>error CS3003: Type of <span class="hljs-string">'MyTests.TestContext'</span> <span class="hljs-keyword">is</span> <span class="hljs-keyword">not</span> CLS-compliant 
error CS3001: Argument type <span class="hljs-string">'TestContext'</span> <span class="hljs-keyword">is</span> <span class="hljs-keyword">not</span> CLS-compliant
</code></pre>
<p>Please can we have a fix?</p>
<p>As a workaround, I added <strong>/p:TreatWarningsAsErrors=false</strong> to the MSBuild Arguments in my <strong>Visual Studio build</strong> step in the ADO build pipeline, so that the TestContext warnings are not treated as errors. However, this is a global setting so I can no longer catch genuine warnings as errors.</p>

---
### Original Solutions
(no solutions)

[AB#1335756](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1335756)

**Comment by Evangelink** [comment]
Moving back MSTest to be CLS compliant would require some effort and we fail to see any good reason to do so. This concept is relatively old and is no longer a priority in modern development. Besides, test projects don't really need to be shipped or reused so being able to be CLS compliant doesn't seem to be such an advantage.
