### ISSUE TITLE
MSTest.TestFramework 2.2.4: 'TestContext' does not contain a definition for 'TestRunDirectory' in net5.0-windows10.0.19041 project

### ISSUE THREAD

**Issue by xantiva** [microsoft/testfx#851]
## Description
After updating MSTest.TestFramework from 2.2.3 to 2.2.4 a test project with the target framework net5.0-windows10.0.19041 could not be compiled anymore.

> Error	CS1061	'TestContext' does not contain a definition for 'TestRunDirectory' and no accessible extension method 'TestRunDirectory' accepting a first argument of type 'TestContext' could be found (are you missing a using directive or an assembly reference?)

Other test projects in the same solution work fine with net5.0 or net5.0-windows.

I got also an error if I update the TestAdapter, but I will open a seperate issue for that.

## Environment
Visual Studio 16.10.0
Microsoft.NET.Test.Sdk Version="16.10.0"
MSTest.TestAdapter Version="2.2.3"
MSTest.TestFramework Version="2.2.4"

[AB#1339280](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1339280)

**Comment by Haplois** [comment]
@xantiva, can you give us a quick repro of this issue?

**Comment by xantiva** [comment]
@Haplois This is a demo for the error: https://github.com/xantiva/demo-MSTest.TestFramework-2.2.4

- 2 projects and 2 test projects
- one combination with TargetFramework: net5.0-windows which could be compiled and
- one combination with TargetFramework: net5.0-windows10.0.19041 which has the compiler error:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'TestContext' does not contain a definition for 'TestRunDirectory' and no accessible extension method 'TestRunDirectory' accepting a first argument of type 'TestContext' could be found (are you missing a using directive or an assembly reference?)	Net5-windows10Lib.Tests	C:\source\Spielwiese\demo-MSTest.TestFramework-2.2.4\DemoApp\Net5-windows10Lib.Tests\UnitTestNet5Win10.cs	14	Active
```

**Comment by mikeKuester** [comment]
@nohwnd Sorry for that question, but what does "triaged" mean?

Looks like there a more issues with the same root cause? #991 , #982

**Comment by mikeKuester** [comment]
This seems to be the root cause: https://github.com/microsoft/testfx/pull/813  as mentioned here: https://github.com/microsoft/CsWinRT/issues/1047

**Comment by jrf2** [comment]
I'm also seeing a similar problem with the net5.0-windows10.0.19041.0 dll where it is missing DeploymentDirectory from TestContext. The netstandard1.0 dll has this and if my TargetFramework is net5.0-windows instead of net5.0-windows10.0.19041.0 it uses the netstandard1.0 dll. However, we need to use net5.0-windows10.0.19041.0 or else we will be missing functions from another nuget package which has functions for a specific windows version. For now we have downgraded back to 2.2.3.

**Comment by mikeKuester** [comment]
After nearly 10 month and 4 versions - this bug is still not fixed.  :(

**Comment by Haplois** [comment]
We are sorry for the delayed fix, but one is ready now. We'll release a preview containing fix later today.
