### ISSUE TITLE
`DataRowAttribute` no longer supports `double` but does support `decimal`? Regression between v2.1.x and v2.2.x

### ISSUE THREAD

**Issue by conficient** [microsoft/testfx#857]
## Description
We use MSTest v2 in our unit tests and many libraries use the [DataRow()] attribute to pass data for test cases. I knew from past experience that you can't put `decimal` values in `DataRow` so if I need to test for a `decimal` result I put a `double` in the `DataRow` and convert in the code to a decimal value. All works fine in several projects. Example below:
```cs
[TestMethod]
[DataRow("somefile.xlsx", 1234.56)]
public void CheckFileTotals(string filename, double expected)
{
    decimal expectedTotal = Convert.ToDecimal(expected);
    // read file and check total ...
}
```

Had a colleague call me when he couldn't get the tests to run any more. Suddenly we're getting errors:
```
  Message: 
    Test method MyTestApp.CheckFileTotals threw exception: 
    System.ArgumentException: Object of type 'System.Decimal' cannot be converted to type 'System.Double'.

  Stack Trace: 
    RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
    RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
    MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
    RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    MethodBase.Invoke(Object obj, Object[] parameters)
    ThreadOperations.ExecuteWithAbortSafety(Action action)
```
Note this error is _before_ it even executes the test.

I experimented for a while and finally discovered they had updated the MSTest.Framework and MSTest.Adapter packages from v2.1.2 to v2.2.4. I downgraded the MSTest.Framework and MSTest.Adapter packages to v2.1.2 and this fixed the issue.

I also found a workaround is that the method parameter can be changed to `decimal` and it fixes the error but I am reluctant to change the code if the change is reversed in a future version.

## Steps to reproduce
I created a simple Github repo https://github.com/conficient/ConversionError to demonstrate this issue.
Identical code using v2.1.2 and v2.2.4. The v2.1.2 version works and v2.2.4 fails.

## Expected behavior
Expected that a `double` value in the `DataRow` would be acceptable as a `double` parameter.

## Actual behavior
The binding of the values from the `DataRow` to the method appears to treat any `double` as `decimal`

## Environment
Tested in Windows 10 x64 Pro Version 2004 / 19041.985

**Comment by conficient** [comment]
Ah, looks like this is a known issue? https://github.com/microsoft/testfx/issues/842

**Comment by Sanan07** [comment]
Yes, it is know, our team working on fixing it. Tracked here : #844. Closing this one.
