### ISSUE TITLE
Reason:Unable to find assembly 

### ISSUE THREAD

**Issue by aligneddev** [microsoft/testfx#863]
## Description
I have a solution with a mix of .Net Framework 3.5, 4.6.2 and 4.7.2 (it really needs to be updated to 4.8, but I don't have authorization to spend time on that right now).

I updated the MSTest.TestAdapter and MSTest.TestFramework from 1.4 to 2.2.4 and now the tests are showing in the Test Explorer, but they aren't run. I was hoping to update just enough and now I've lost a lot of time trying different things.

I see this [MSTest][Discovery][C:\chr\git\mySolution\Tests\bin\Debug\net472\MyTests.dll] Failed to discover tests from assembly C:\chr\git\mySolution\Tests\bin\Debug\net472\MyTests.dll. Reason:Unable to find assembly 'MyNet462.Data, Version=0.0.1.0, Culture=neutral, PublicKeyToken=ba37446064e06eb0'. in the Output > Tests.
(I've changed the names).

Interesting enough, the tests run in our build with 
- task: VSTest@2
  displayName: 'Run Unit Tests'
  inputs:
    testAssemblyVer2: '**\MyTests.dll'
    searchFolder: '$(Build.BinariesDirectory)'
    testFiltercriteria: 'TestCategory!=Integration'
    runOnlyImpactedTests: false
    runInParallel: true
    codeCoverageEnabled: false
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'

## Steps to reproduce
I created a new project with a mix of .Net 4.7.2 for the test project and a .Net 4.5.2 class library (MyNet452.Data.dll above it 4.6.2) but I couldn't reproduce it there. It works great.

I deleted all but a simple test from my real project and the test ran. Once I added in the tests that had usings to the dll referenced, they stopped running.

I attempted upgrading to a .Net Core csproj and target net472, but have the same problem. This is my test project .csproj that works in my test sln, but not in my real sln.
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNet.Mvc" Version="5.2.3" />
    <PackageReference Include="Microsoft.CSharp" Version="4.5.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.10.0" />
    <PackageReference Include="Moq" Version="4.16.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="2.2.4" />
    <PackageReference Include="MSTest.TestFramework" Version="2.2.4" />
    <PackageReference Include="coverlet.collector" Version="3.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Net.Http" Version="4.3.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\OtherWeb.csproj" /> <-- this one references the other one and is 4.5.2 -->
    <ProjectReference Include="..\AnotherClassLibrary.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Runtime.Caching" />
    <Reference Include="System.Web" />
  </ItemGroup>

</Project>

```
An experiment to upgrade all to .Net 4.6.2 failed as I couldn't get it to build and ran out of time.

## Expected behavior
I need to be able to run the tests in VS.

I know this is a hard one. Maybe the answer is to upgrade everything, but I'd appreciate any pointers or suggestions

Is there a way to get more logs out of MSTest of why it can't find my dll? I can't find anything searching about "Reason: Unable to find assembly". It's probably due to the MyNet452.Data.dll referencing another project or nuget package or system assembly.

## Environment
I'm in Windows 10, trying to run the tests from VS 2019 16.11.0 Preview 1.0 and VS 2019.

**Comment by aligneddev** [comment]
Here's my test solution that worked
[mixOfVersionsTest.zip](https://github.com/microsoft/testfx/files/6598908/mixOfVersionsTest.zip)

**Comment by nohwnd** [comment]
Have you tried with any of the previous versions of TestAdapter that is still 2.x.x? Is this specific to the latest release?

**Comment by aligneddev** [comment]
I have tried a few 2.x.x versions and still had the issue.

Update, I just made the project I'm referencing 4.7.2 and ran `vstest.console MyTests.dll --diag:log.txt;tracelevel=verbose` after finding https://github.com/Microsoft/vstest-docs/blob/master/docs/diagnose.md. The tests run in the console, but still not in VS.
after a lot of entries it finds the dll: TpTrace Information: 0 : 22340, 8, 2021/06/04, 09:14:02.291, 2648799427700, vstest.console, AssemblyResolver.OnResolve: Resolved assembly: MyNet452.Data, Version=0.0.1.0, Culture=neutral, PublicKeyToken=ba37446064e06eb0, from path: C:\chr\git\mysln\MyTeests\bin\Debug\net472\MyNet452.dll

**Comment by Haplois** [comment]
@aligneddev, can you enable FusionLog as shown [here][1] and run tests with diagnostics enabled; and share the logs with us? 

[1]: https://stackoverflow.com/a/1527249

**Comment by aligneddev** [comment]
you got me thinking. I went back to the original, updated to 2.0.0 and it worked. Then I updated to 2.2.4 and it doesn't run in VS.

I went back to 2.1.0 => that works
2.2.1 brought in more libraries  and only half my tests ran.
I found the breaking point!
![image](https://user-images.githubusercontent.com/1636977/120828125-c5ea6e80-c521-11eb-846e-ce334ecedcaf.png)

**Comment by Haplois** [comment]
@aligneddev, please let us know if you need any assistance.

**Comment by aligneddev** [comment]
Thanks @Haplois for checking in. I'll have to move on with 2.1.0, but I've learned some things. Hopefully we can update someday and this will all go away.

**Comment by HgDorn** [comment]
Hi,
I have the same issue with MSTest.TestAdapter 2.2.4: VS does not find all assemblies required for the Test.
With TestAdapter 2.2.3 everything works fine. I don't understand the conversation here. Is the problem fixed or is there a work around?

**Comment by Haplois** [comment]
Hi @HgDorn, could you share more information about the issue you're having? A repro project would be great. If not, please share diagnostic logs as shown here https://github.com/Microsoft/vstest-docs/blob/main/docs/diagnose.md.

**Comment by HgDorn** [comment]
> Hi @HgDorn, could you share more information about the issue you're having? A repro project would be great. If not, please share diagnostic logs as shown here https://github.com/Microsoft/vstest-docs/blob/main/docs/diagnose.md.

Yes, I think I can create a repo for the issue. But I will need several more days for it since I am currently very busy. Sorry for the delay.

**Comment by Haplois** [comment]
Thank you @HgDorn! We'll wait for your repro.
