### ISSUE TITLE
High severity vulnerabilities in the  System.Net.Http@4.3.0 (Dependency on NETStandard.Library@1.6.1)

### ISSUE THREAD

**Issue by Rashmi-nw** [microsoft/testfx#866]
## Description
> **IMPORTANT**: if the defect is reproduced only in a workflow from within the Visual Studio IDE then do not report the issue here - instead, please report it using Visual Studio's "Send Feedback" option that can be accessed from the Help menu OR using this link https://developercommunity.visualstudio.com.
>
> For a defect specific to the MSTest V2 test framework, describe the issue you've observed.

## Steps to reproduce
Create a test project using the package - `MSTest.TestAdapter@1.4.0` or `MSTest.TestAdapter@12.2.4`
Add a sample test and run `snyk test`

## Expected behavior
No high severity vulnerabilities identified. Alternatively upgrade the System.Net.Http Package?

## Actual behavior
MSTest.TestAdapter@1.4.0  has a dependency on NETStandard.Library@1.6.1 which has a dependency on System.Net.Http@4.3.0. This package has some vulnerabilities
The information can be found here : https://snyk.io/vuln/SNYK-DOTNET-SYSTEMNETHTTP-60045

## Environment
Tested from VS code/ Visual Studio. 
Test Adapter and Test framework used : 1.4.0
Same occurs even after upgrading to MSTest.TestAdapter 2.2.4 

[AB#1575879](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1575879)

**Comment by nohwnd** [comment]
We will investigate the update in the latest version of mstest.

**Comment by abatishchev** [comment]
@nohwnd any update on this, please?

**Comment by SymbioticKilla** [comment]
@nohwnd  Is there any ETA?
Related:
https://github.com/microsoft/testfx/issues/582

**Comment by Evangelink** [comment]
This will be handled by #1095

**Comment by Evangelink** [comment]
Fixed by #1163
