### ISSUE TITLE
No warning about async void tests which are not recognized by VS

### ISSUE THREAD

**Issue by arsen-ms** [microsoft/testfx#867]
## Description
VS doesn't recognize unit tests that are `async void`, which is fine, but I expect to get some warning making me aware of my mistake. I had a unit tests which didn't call any async methods inside, so initially it was void. Then I had to add an async method call with `await`, hence added the `async` keyword in the method signature, but forgot about the return type. After that I spent a couple hours trying to understand what's wrong with my unit tests or project settings. I was sure that if it were a code problem, then I would get some warning about that.

## Steps to reproduce
Create a test class with a single test method which has this signature: `public async void MyTest()`. Try running the test (doesn't matter if just individual test, or the whole test class, it's same behavior).

## Expected behavior
Source analyzer outputs a warning about the method signature making the test non-recognizable.

## Actual behavior
No warnings, and the test is not recognized. `0 tests run out of 0 total` is the output log.

## Diagnostic logs
N/A

## Environment
Was testing on Windows, in VS2019, Microsoft.VisualStudio.QualityTools.UnitTestFramework.

**Comment by nohwnd** [comment]
@arsen-ms This issue is specific to the used framework. 

It seems to be decided here, and later `null` is silently ignored. 

https://github.com/microsoft/testfx/blob/19acefa11712c387774784a79dafcf7b3dbee64c/src/Adapter/MSTest.CoreAdapter/Extensions/MethodInfoExtensions.cs#L116-L117

**Comment by Evangelink** [comment]
We know have an analyzer for this, we still need to work on producing a warning at runtime. I think this can be scheduled for 3.3 as it's not a big effort.

**Comment by Evangelink** [comment]
Runtime warning part is already handled, see
![image](https://github.com/microsoft/testfx/assets/11340282/e81cbb08-36a2-4fdb-9015-9672c18e9a0b)
