### ISSUE TITLE
System.Type not recognized anymore in DataRowAttribute

### ISSUE THREAD

**Issue by AlessandroDalMas** [microsoft/testfx#868]
## Description
After updating from 2.2.3 this type of tests don't run anymore:
```
[TestMethod]
[DataRow(typeof(bool), DisplayName = "Bool")]
public void ShouldReturnFalseIfCannotConvert(Type type)
{
    // Arrange
    var c = new ByteArrayConverter();

    // Act
    var r = c.CanConvertFrom(null, type);

    // Assert
    r.Should().BeFalse();
}
```

and this message shows on window "Output - Tests":

> ##[error]An exception occurred while invoking executor 'executor://mstestadapter/v2': Type 'System.RuntimeType' with data contract name 'RuntimeType:http://schemas.datacontract.org/2004/07/System' is not expected. Consider using a DataContractResolver if you are using DataContractSerializer or add any types not known statically to the list of known types - for example, by using the KnownTypeAttribute attribute or by adding them to the list of known types passed to the serializer.

## Steps to reproduce
VS2019 16.9.5

TargetFrameworks: net461
RuntimeIdentifiers: win
Microsoft.NET.Test.Sdk: 16.10.0
MSTest.TestAdapter: 2.2.4
MSTest.TestFramework: 2.2.4

## Expected behavior
The tests was working fine with the previous version:

Microsoft.NET.Test.Sdk: 16.9.4
MSTest.TestAdapter: 2.2.3
MSTest.TestFramework: 2.2.3

## Actual behavior
The tests output window print that error message and all tests become "not run"

## Environment
The same happens in a server build running "dotnet test"

**Comment by Sanan07** [comment]
It is known issue. Please use `2.2.5-preview-20210605-01` version of `MSTest Adapter` and `MSTest Framework`
