### ISSUE TITLE
MSTest SDK 2.2.4 breaks support for some types through the DataTypeRow attribute

### ISSUE THREAD

**Issue by K-Cully** [microsoft/testfx#869]
## Description
After upgrading the MSTest SDK version from 2.2.3 to 2.2.4, some datatypes are not supported correctly in the DataTypeRow attribute on test methods, leading to exceptions being thrown during test execution.
This repros both through dotnet test and through the VS IDE.

## Steps to reproduce
1. Create a test class using the sample project and class below.
2. run dotnet build.
3. run dotnet test.

.csproj file:

```
 <Project Sdk="Microsoft.NET.Sdk">
   <PropertyGroup>
     <TargetFramework>netcoreapp3.1</TargetFramework>
     <IsPackable>false</IsPackable>
   </PropertyGroup>
 
   <ItemGroup>
     <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.10.0" />
     <PackageReference Include="MSTest.TestAdapter" Version="2.2.4" />
     <PackageReference Include="MSTest.TestFramework" Version="2.2.4" />
     <PackageReference Include="coverlet.collector" Version="3.0.3">
       <PrivateAssets>all</PrivateAssets>
       <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
     </PackageReference>
   </ItemGroup>
 </Project>
```

Test Class:

```
 using Microsoft.VisualStudio.TestTools.UnitTesting;
 namespace TestProject1
 {
 	[TestClass]
 	public class UnitTest1
 	{
 		[DataTestMethod]
 		[DataRow(0u, false)]
 		public void TestMethod1(uint value, bool otherValue)
 		{
 			Assert.AreEqual(0u, value);
 		}
 	}
 }
```

## Expected behavior
> Test executes and passes.

## Actual behavior
>   Failed TestMethod1 (0,False) [86 ms]
  Error Message:
   Test method TestProject1.UnitTest1.TestMethod1 threw exception:
System.ArgumentException: Object of type 'System.Int32' cannot be converted to type 'System.UInt32'.
  Stack Trace:
      at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.ThreadOperations.ExecuteWithAbortSafety(Action action)

## Environment
Framework and adaptor can be seen in project file above.
Note that this also repros with net5.0 as the target framework.

DotNet Info
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.300\

Host (useful for support):
  Version: 5.0.6
  Commit:  478b2f8c0e

.NET SDKs installed:
  3.1.409 [C:\Program Files\dotnet\sdk]
  5.0.203 [C:\Program Files\dotnet\sdk]
  5.0.300 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by Haplois** [comment]
Thank you for reporting this, it's a known issue - we fixed it. See the solution [here][1].

[1]: https://github.com/microsoft/testfx/issues/844#issuecomment-855165685
