### ISSUE TITLE
Byte enums fail in DataRow with conversion exception.

### ISSUE THREAD

**Issue by Kevin-Seiden** [microsoft/testfx#870]
## Description
When using .Net 5 and the latest MSTest version, tests will fail when passing a byte enum as a DataRow parameter due to an Int32 conversion.

## Steps to reproduce
1. Create a new Unit Test project for net5.0-windows
3. Use the following code to run a test (requires UseWpf flag on):
```
using System.Windows;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace TestProject1
{
    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        [DataRow(Visibility.Visible)]
        [DataRow(Visibility.Hidden)]
        [DataRow(Visibility.Collapsed)]
        public void TestMethod1(Visibility value)
        {
            Assert.IsTrue(true);
        }
    }
}
```

## Expected behavior
The test should pass.

## Actual behavior
Test fails with the following message.

>   Message: 
    Test method TestProject1.UnitTest1.TestMethod1 threw exception: 
    System.ArgumentException: Object of type 'System.Int32' cannot be converted to type 'System.Windows.Visibility'.

  >Stack Trace: 
    RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
    RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
    MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
    RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    MethodBase.Invoke(Object obj, Object[] parameters)
    ThreadOperations.ExecuteWithAbortSafety(Action action)

## Environment
Windows 10, MSTest 2.2.4
framework and adapter: net5.0-windows, 2.2.4

**Comment by Haplois** [comment]
Thank you for reporting this, it's a known issue - we fixed it. See the solution [here][1].

[1]: https://github.com/microsoft/testfx/issues/844#issuecomment-855165685
