### ISSUE TITLE
Datarow value cannot be null

### ISSUE THREAD

**Issue by regisrc** [microsoft/testfx#872]
Hello everybody, im having a trouble using your packages, first of all let me explain what i did, i was using the 2.2.3 version for MSTestAdapter and MSTestFramework, and it was working well. The problem begins when i updated the version to 2.2.4, which broke for this error:  "... Add any types not known statically to the list of known types - for example, by using the ...", but ok i found an issue talking about it and update to 2.2.5-preview-20210531-02, but in this version i had a problem, i can't use null values in datarow.

![image](https://user-images.githubusercontent.com/47003717/121533455-ad250180-c9d6-11eb-8f47-b480cd4d398b.png)
![image](https://user-images.githubusercontent.com/47003717/121533716-ed847f80-c9d6-11eb-9935-1980037426e6.png)
![image](https://user-images.githubusercontent.com/47003717/121533650-dc3b7300-c9d6-11eb-9a90-4720cbc8208d.png)

## Expected behavior
> Can use null values in datarow (which is the behavior using the version 2.2.3)

## Actual behavior
> Errors :(

## Environment
> I'm using the version 2.2.5-preview-20210531-02 for both.

**Comment by Sanan07** [comment]
@regisrc Update to newer packages : 
`MSTest.TestAdapter v2.2.5-preview-20210605-01`
`MSTest.TestFramework v2.2.5-preview-20210605-01`

**Comment by regisrc** [comment]
It's already released? i can't download it 
![image](https://user-images.githubusercontent.com/47003717/121591589-0f4e2880-ca10-11eb-906f-d499f8986671.png)

**Comment by Haplois** [comment]
Thank you for reporting this, it's a known issue - we fixed it. See the solution [here][1]. Please clear your solution and check your NuGet sources. Packages are published at NuGet.org, and our daily feeds.

[1]: https://github.com/microsoft/testfx/issues/844#issuecomment-855165685
