### ISSUE TITLE
Version 2.2.4 cannot take double as argument in DataRow attribute

### ISSUE THREAD

**Issue by kristofferjalen** [microsoft/testfx#877]
## Description
This test passes for `MSTest.TestAdapter` and `MSTest.TestFramework` <= 2.2.3:
```
[TestMethod]
[DataRow(1.5d, "1.5")]
public void ToFormattedString(double input, string expected)
{
    var inputAsDecimal = Convert.ToDecimal(input);
    var actual = ... // some conversion
    Assert.AreEqual(expected, actual);
}
```
But when upgrading to 2.2.4 an `ArgumentException` is thrown:
```
Object of type 'System.Decimal' cannot be converted to type 'System.Double'.
```

## Steps to reproduce
`dotnet test MyProejct.Tests.csproj`

## Expected behavior
Tests should pass.

## Actual behavior
Tests are not run.

**Comment by Arjailer** [comment]
I'm getting this too, and it also does the same with floats.

DataRow uses floats:

`[DataRow(10.5f, 20.5f)]`

And the test method expects floats:

`public void SetFromGridLocation_XY_Float(float x, float y)`

But the tests fail with:

``System.ArgumentException: Object of type 'System.Decimal' cannot be converted to type 'System.Single'.``

**Comment by Haplois** [comment]
Thank you for reporting this, it's a known issue - we fixed it. See the solution [here][1].

[1]: https://github.com/microsoft/testfx/issues/844#issuecomment-855165685
