### ISSUE TITLE
TestContext.CurrentTestOutcome is always InProgress in the TestCleanup method

### ISSUE THREAD

**Issue by AbhitejJohn** [Microsoft/testfx#89]
> Copied from #Microsft/vstest/548.

## Description
In the `TestCleanup` method, the `TestContext.CurrentTestOutcome` property is always `InProgress` rather than the actual current test outcome.

Using the old test framework (bundled with VS, New > Project > Unit Test) the outcome is set correctly.

## Steps to reproduce
```cs
using Microsoft.VisualStudio.TestTools.UnitTesting;

[TestClass]
public class MyTestClass
{
	public TestContext TestContext { get; set; }

	[TestMethod]
	public void PassTest()
	{
		Assert.IsTrue(true);
	}

	[TestMethod]
	public void InconclusiveTest()
	{
		Assert.Inconclusive();
	}

	[TestMethod]
	public void FailTest()
	{
		Assert.Fail();
	}

	[TestCleanup]
	public void TestCleanup()
	{
		System.Console.WriteLine($"{TestContext.TestName}: {TestContext.CurrentTestOutcome}");
	}
}
```

## Expected behavior
`TestContext.CurrentTestOutcome` is set to the actual outcome type of the current test.

![image](https://cloud.githubusercontent.com/assets/5658207/23368375/915eae1c-fd05-11e6-8b31-ba46dc388806.png)

_Image taken when executing the code above using the old VS-bundled framework._

## Actual behavior
`TestContext.CurrentTestOutcome` is always `InProgress`

![image](https://cloud.githubusercontent.com/assets/5658207/23368211/febc6e00-fd04-11e6-9d9c-749694bafaa8.png)

_Image taken when executing the code above using the new NuGet package framework._

## Environment
&nbsp;|Version
-|-
OS|Windows 10 Enterprise build 14393
IDE|Visual Studio Enterprise 2015 Update 3
Target framework|4.5.2
`MSTest.TestAdapter`|1.1.12
`MSTest.TestFramework`|1.1.11

**Comment by hawkunsh** [comment]
I get the same in VS 2017. And possibly related:

A `TestContext.WriteLine("Some trace message");` in the test method doesn't produce any output. There's no **Output** link in the Test Explorer's right pane.

If I call any other output method, like `Console.WriteLine()`, there's a **Output** link, but the output doesn't contain the trace messages written with `TestContext.WriteLine()`.

**Comment by AbhitejJohn** [comment]
@hawkunsh: #120 is tracking the `TestContext.WriteLine` issue.
