### ISSUE TITLE
Improve Nullability Analysis for Testing Frameworks

### ISSUE THREAD

**Issue by kendrahavens** [microsoft/testfx#901]
Copied from https://github.com/dotnet/roslyn/discussions/54169

> I believe that Code such as:
> ```
> Assert.IsNotNull(x);
> Assert.AreNotEqual(x, null);
> // etc.
> ```
> Should cause nullability state to change.

## Steps to reproduce
Add "null checks" to tests

## Expected behavior
Nullability state reflects checks.

## Actual behavior
No change in nullability state.

**Comment by Haplois** [comment]
We added this support (MSTest v2) on https://github.com/microsoft/testfx/pull/744, and release it with v2.2.1.

![image](https://user-images.githubusercontent.com/433724/124444924-5fa27700-dd7f-11eb-9f73-9a08e0b4221f.png)

## Sample
![image](https://user-images.githubusercontent.com/433724/124445866-37ffde80-dd80-11eb-8540-49d27a30a854.png)
