### ISSUE TITLE
DynamicData test ignores data items when their ToString() results in the same string as other data items

### ISSUE THREAD

**Issue by cklutz** [microsoft/testfx#909]
[DynamicData] items are ignored. Best explained with an example (also see test.zip attachment for full solution):

```csharp
using System;
using System.Collections.Generic;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace test
{
    [TestClass]
    public class UnitTest1
    {
        public static IEnumerable<object[]> TestListData
        {
            get
            {
                yield return new object[] { 0, new List<int> { 1 } };
                yield return new object[] { 1, new List<int> { 2 } };
            }
        }

        [TestMethod]
        [DynamicData(nameof(TestListData))]
        public void TestList(int i, IList<int> a) => Console.WriteLine(i + ", " + a[0]);

        public static IEnumerable<object[]> TestListData2
        {
            get
            {
                yield return new object[] { new List<int> { 1 } };
                yield return new object[] { new List<int> { 2 } };
            }
        }

        [TestMethod]
        [DynamicData(nameof(TestListData2))]
        public void TestList2(IList<int> a) => Console.WriteLine(a[0]);
    }
}
```

Create a .NET 4.8 project, using MSTest.TestFramework/MSTest.TestAdapter 2.2.5, the results are as follows:

TestList:
* Discovers/creates three test cases from the `TestListData` result.
* Runs each

TestList2:
* Only creates one test case from the `TestListData2` result.
* Executes the last one (as can be seen by the output of `2`)

It looks as if in the TestList2 case only one test case is generated, because they would all result in the display(?) name "TestList2 (System.Collections.Generic.List`1[System.Int32])", whereas in the TestList case they all result in different names, because of the literals (1, 2, 3) in the test data.

Whether this guess is right or not, it still worked as expected with version 2.1.2 and below (haven't tested upwards to 2.2.5, might be an issue in an earlier version already).

[log.txt](https://github.com/microsoft/testfx-docs/files/6781869/log.txt)
[test.zip](https://github.com/microsoft/testfx-docs/files/6781897/test.zip)

**Comment by Haplois** [comment]
Thank you for the reporting this issue. In dynamic data tests, we differentiate testcases by their display name. If there is a conflict by name as you discovered, only the last discovered one is kept. This is by-design. We're working to provide an opt-out (#905) from this behavior, until that's ready you can use you workaround - or downgrade to version 2.2.3.
