### ISSUE TITLE
Dynamic Test Bugs and Enhancements

### ISSUE THREAD

**Issue by Haplois** [microsoft/testfx#910]
## Description
We have some active bugs on dynamic data tests. This issue is to track all of them in a single place.

## Tasks
 - [x] #875 
 - [x] #450
 - [x] #283
 - [x] #905 
 - [x] #464
 - [x] #997
 - [x] #906 
 - [x] #452
 - [ ] #309
 - [ ] #740 
 - [ ] #908
 - [ ] #713 
 - [ ] #246

[AB#1353432](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1353432)

**Comment by Evangelink** [comment]
Closing this issue as it's only listing a group of issues.
