### ISSUE TITLE
MSTest 2.2.5 [AssemblyInitialize] is not called in the same order as in 2.2.3 with a [DataTestMethod]

### ISSUE THREAD

**Issue by TheFireCookie** [microsoft/testfx#926]
## Description
With MSTest 2.2.3, we have some code using a [DataTestMethod] and the code feeding the dynamic data is using some objects initialized in the [AssemblyInitialize], everything was working fine. 
When upgrading to 2.2.4 or 2.2.5, the [DataTestMethod] method invocation is occuring before the [AssemblyInitialize] method.

## Steps to reproduce
Sample code here: https://github.com/TheFireCookie/MsTest225AssemblyInitializeBug

**Comment by abatishchev** [comment]
You now (can try to) opt out from the new behavior, see https://github.com/microsoft/testfx/issues/905#issuecomment-904997845.

**Comment by Haplois** [comment]
Please opt-out from the new behavior https://github.com/microsoft/testfx/issues/905#issuecomment-907775327.
