### ISSUE TITLE
Empty string is passed as null with DataRowAttribute and DynamicData

### ISSUE THREAD

**Issue by bkqc** [microsoft/testfx#938]
## Description
When in a [DataTestMethod] that receives a string parameter, if we provide String.Empty or "" data using DataRowAttribute or DynamicDataAttribute, the received parameter is always null, not an empty string.

## Steps to reproduce
Option 1
```
[DataRow(""), DataRow(null)]
[DataTestMethod]
public void ZoneComplementaireVide_IdEnveloppeNull(string value){
...
}
```

Option 2
```
[DataRow("", DisplayName ="Empty"), DataRow(null, DisplayName ="Null")]
[DataTestMethod]
public void ZoneComplementaireVide_IdEnveloppeNull(string value){
...
}
```

Option 3
```
private static IEnumerable<Object[]> EmptyOrNullStrings { get; } = new Object[][] { 
  new Object[] { string.Empty }, 
  new Object[] { null } };
[DynamicData(nameof(EmptyOrNullStrings), DynamicDataSourceType.Property)]
[DataTestMethod]
public void ZoneComplementaireVide_IdEnveloppeNull(string value){
...
}
```

## Expected behavior
First time the test runs: value == string.Empty
Second time the test runs: value == null

## Actual behavior
Options 1 and 3: The test runs only once with value == null
Option 2: Test runs twice, both times value == null

## Environment
Using Visual Studio 2019 (Version 16.4.5), the project is in .NET Framework 4.5 and the Nugets are
&lt;package id="MSTest.TestAdapter" version="2.2.5" targetFramework="net45" />
&lt;package id="MSTest.TestFramework" version="2.2.5" targetFramework="net45" />

**Comment by Haplois** [comment]
Thank you for the reporting this issue. In dynamic data tests, we differentiate testcases by their display names. If there is a conflict by name as you discovered, only the last discovered one is kept. This is by-design. We're working to provide an opt-out (#905) from this behavior, until that's ready you can use you workaround - or downgrade to version 2.2.3.
