### ISSUE TITLE
Missing strong-name and Authenticode signatures

### ISSUE THREAD

**Issue by cimryan** [microsoft/testfx#948]
The binaries produced by sdk-style project files in the repo are missing strong-name and Authenticode signatures. This prevents my organization from updating to 2.2.4 or later, since we require both kinds of signatures for regulatory compliance.

The affected binaries are:
mstest.testadapter.2.2.6\build\net5.0-windows10.0.18362.0\Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.dll
mstest.testadapter.2.2.6\build\netcoreapp1.0\Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.dll
mstest.testadapter.2.2.6\build\netstandard1.5\Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.dll
mstest.testframework.2.2.6\lib\net5.0-windows10.0.18362.0\Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions.dll

[AB#1389156](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1389156)

**Comment by Haplois** [comment]
This is fixed, and the fix will be release on 2.2.7 later today.
