### ISSUE TITLE
DataRow doesn't work with Array

### ISSUE THREAD

**Issue by 21r8390** [microsoft/testfx#977]
## Description
I have a test method like in the example, which I fill via DataRow. In this method I should test if all elements from an array or a list are added to my list.

I get a strange result. Only the first test is executed and in the UI you can see only one test. It doesn't matter what kind of collection I use. They are all different parameters, so no duplicates.

Since I have the Enterprise version, I also have Live Unit Testing, where the same problem occurs.

## Steps to reproduce
I work with a similar method. However, with this one I get the same bug:
```
        [TestMethod]
        [DataRow(new[] { 1, 2, 3, 4 })]
        [DataRow(new[] { 1, 2, 3, 4, 5, 6, 7, 8, 9 })]
        [DataRow(new[] { 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9 })]
        public void AddRangeTest(int[] addArray)
        {
            List<int> integers = new();

            integers.AddRange(addArray);

            Assert.AreEqual(addArray.Length, integers.Count);
        }
```

## Expected behavior
> I expect all my three arrays to be tested.

## Actual behavior
> As a result, only one test is displayed in the UI and only the first one is executed.

## Environment
>  - Windows 10 Build 19043.1237
>  - Visual Studio 2019 Enterprise 16.11.3 
>  - MSTest.TestFramework Version: 2.2.7 **|** MSTest.TestAdapter Version: 2.2.7 **|** Microsoft.NET.Test.Sdk Version: 16.11.0
>  - Other installed packages: [Moq](https://github.com/moq/moq4) & [Coverlet](https://github.com/coverlet-coverage/coverlet)

**Comment by Haplois** [comment]
Thank you for reporting this issue. It's caused by the changes on how we handle tests with data sources after version 2.2.3. Please update to version 2.2.6 and opt-out out of this behavior as described [here][1].

[1]: https://github.com/microsoft/testfx/issues/905#issuecomment-907775327
