### ISSUE TITLE
DynamicData: Null item does not appear in the enumeration while the test is run

### ISSUE THREAD

**Issue by m4rqs** [microsoft/testfx#984]
## Description
If the return values of dynamic method are the same except one string where there are null and empty string that differentiate the return value, dynamic method passes only value with empty string.

## Steps to reproduce
![image](https://user-images.githubusercontent.com/32226818/134529599-c2ac5d61-aa39-4126-9889-9e66b49dfa8d.png)

## Expected behavior
Every item from GetTestData is passed into Test method

## Actual behavior
First item from GetTestData (null string) is not passed into Test method

## Environment
 - Operating system: Windows 10 x64bit
 - Package version of MSTest framework and adapter: 2.2.7

## Working scenarios
![image](https://user-images.githubusercontent.com/32226818/134534592-edacffac-618f-4588-a2d4-fc1955d57b46.png)
![image](https://user-images.githubusercontent.com/32226818/134534625-78b37ee9-5636-4420-835c-02a406a3dfc8.png)

**Comment by Haplois** [comment]
Thank you for reporting this issue. It's caused by the changes on how we handle tests with data sources after version 2.2.3. Please update to version 2.2.6 and opt-out out of this behavior as described [here][1].

[1]: https://github.com/microsoft/testfx/issues/905#issuecomment-907775327

**Comment by m4rqs** [comment]
@Haplois Do I really I have to downgrade to 2.2.6?

**Comment by Haplois** [comment]
@m4rqs, there was a typo sorry. You can just opt-out to stay on the latest version.
