### ISSUE TITLE
error CS7069: Reference to type 'DispatcherQueue' claims it is defined in 'Microsoft.WinUI', but it could not be found

### ISSUE THREAD

**Issue by Zachael** [microsoft/testfx#993]
## Description
Compile error when using UITestMethodAttribute with MAUI preview 8 on VS 2022 preview 4.0

## Steps to reproduce
Create a MAUI application from the VS template, modify App.xaml.cs and compile for Windows.
```
using Microsoft.Maui;
using Microsoft.UI.Xaml;
using Microsoft.VisualStudio.TestTools.UnitTesting.AppContainer;
using System;

namespace Test.DCF_UX.MSTest.Tests.WinUI
{
    public partial class App : MauiWinUIApplication
    {
        public App()
        {
            InitializeComponent();
        }

        protected override MauiApp CreateMauiApp() => MauiProgram.CreateMauiApp();

        protected override void OnLaunched(LaunchActivatedEventArgs args)
        {
            base.OnLaunched(args);
            Microsoft.Maui.Essentials.Platform.OnLaunched(args);

            Microsoft.VisualStudio.TestPlatform.TestExecutor.UnitTestClient.CreateDefaultUI();
            UITestMethodAttribute.DispatcherQueue = MainWindow.DispatcherQueue;
            Microsoft.VisualStudio.TestPlatform.TestExecutor.UnitTestClient.Run(Environment.CommandLine);
        }
    }
}
```
## Expected behavior
Successful build. This compiled correctly in a prior preview of MAUI. It also ran the tests correctly from within VS (_Run_ worked but _Debug_ did not).

## Actual behavior
2>C:\Users\Mike\source\repos\dcf_ux_832\src\Tests\Test.DCF_UX.MSTest.Tests\Platforms\Windows\App.xaml.cs(42,35,42,50): 
error CS7069: Reference to type 'DispatcherQueue' claims it is defined in 'Microsoft.WinUI', but it could not be found

## Environment
Windows 10.0.18362.0
VS 2022 preview 4.0
MSTest.TestAdapter version 2.2.7
MSTest.TestFramework version 2.2.7
Microsoft.TestPlatform.TestHost version 16.11.0
coverlet.collector version 3.1.0
Microsoft Maui preview 8

**Comment by Zachael** [comment]
The problem also exists with testing WinUI 3. Please see the following link:

https://devblogs.microsoft.com/ifdef-windows/winui-desktop-unit-tests/

**Comment by Haplois** [comment]
Hi,

[DispatcherQueue](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.dispatching.dispatcherqueue?view=winui-3.0) is moved to `Microsoft.UI.Dispatching` namespace. You might want to check your references.
